In [ ]:
from sqlab.nb_tools import show_tables

class ColumnGetter:
    def __getitem__(self, label):
        return list(_.dict()[label])
col = ColumnGetter()

def print_assert(label):
    print(f'assert col["{label}"] == {col[label]}')

In [ ]:
%config SqlMagic.dsn_filename = "cnx.ini"
%config SqlMagic.displaycon = False
%config SqlMagic.displaylimit = 0
%reload_ext sql
%sql --section cnx
show_tables()

Connecting to 'cnx'

Table            Columns
------------------------------
ints             i, hash
sqlab_metadata   name, value
sqlab_msg        msg

# Entiers naturels
Une seule table, une seule colonne : les entiers naturels de 0 à 1000.

# Entraînement
Filtrez une table d'entiers pour la réduire aux premiers termes de suites célèbres.

## Suites numériques
En dépit de la simplicité du matériau, cette série d'exercices fait appel à un nombre surprenant de notions SQL fondamentales ou plus avancées : manipulation des nombres et des chaînes de caractères, expressions conditionnelles, jointures internes et externes, auto-jointures, sous-requêtes (corrélées ou non), conditions complexes, agrégation, regroupement, CTE (récursives ou non). Les notions de théorie des nombres mobilisées restent du niveau collège/lycée (opérateurs arithmétiques, diviseurs d'un nombre, décomposition en facteurs premiers).

### Carrés parfaits

**Exercice [002].** Un entier est un **carré parfait** si et seulement si sa racine carrée est entière.

| Exemple | Racine carrée | Propriété | Carré parfait |
|---:|:--:|:--:|:--:|
| $16$ | $4$ | entière | ✅ |
| $20$ | $$4,4721\dots$$ | non entière | ❌ |

_Tâche._ Listez par ordre croissant les carrés parfaits inférieurs ou égaux à 1000.

In [ ]:
%%sql
-- Solution recommandée. En ne gardant que les entiers dont la racine carrée a une partie fractionnaire nulle.
-- Notez l'emploi inhabituel de l'opérateur modulo.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) % 1 = 0

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. En ne gardant que les entiers dont la racine carrée est différente de sa propre partie entière.
-- Cela demande à calculer deux fois la racine carrée.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) = floor(sqrt(i))

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. En ne gardant que les entiers $a$ égaux au carré d'un entier $b$ (différent de $a$, sauf pour 0 et 1).
-- Peu performant, du fait de l'auto-jointure.
SELECT A.i
     , salt_002(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * B.i

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. Même idée, mais exprimée de façon plus procédurale, avec une requête imbriquée dans la clause `WHERE`.
-- On a également borné $b$ à $\sqrt{1000} < 32$. Attention : si vous travaillez sur une table plus grande,
-- vous devrez ajuster cette valeur.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i IN
        (SELECT i * i
         FROM ints
         WHERE i < 32 )

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Indication. Vous éliminez les carrés parfaits au lieu de les garder. Inversez votre condition.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) % 1 != 0

969 rows affected.

i,token
2,455354753305299
3,455354753305299
5,455354753305299
6,455354753305299
7,455354753305299
8,455354753305299
10,455354753305299
11,455354753305299
12,455354753305299
13,455354753305299
14,455354753305299
15,455354753305299
17,455354753305299
18,455354753305299
19,455354753305299
20,455354753305299
21,455354753305299
22,455354753305299
23,455354753305299
24,455354753305299
26,455354753305299
27,455354753305299
28,455354753305299
29,455354753305299
30,455354753305299
31,455354753305299
32,455354753305299
33,455354753305299
34,455354753305299
35,455354753305299
37,455354753305299
38,455354753305299
39,455354753305299
40,455354753305299
41,455354753305299
42,455354753305299
43,455354753305299
44,455354753305299
45,455354753305299
46,455354753305299
47,455354753305299
48,455354753305299
50,455354753305299
51,455354753305299
52,455354753305299
53,455354753305299
54,455354753305299
55,455354753305299
56,455354753305299
57,455354753305299
58,455354753305299
59,455354753305299
60,455354753305299
61,455354753305299
62,455354753305299
63,455354753305299
65,455354753305299
66,455354753305299
67,455354753305299
68,455354753305299
69,455354753305299
70,455354753305299
71,455354753305299
72,455354753305299
73,455354753305299
74,455354753305299
75,455354753305299
76,455354753305299
77,455354753305299
78,455354753305299
79,455354753305299
80,455354753305299
82,455354753305299
83,455354753305299
84,455354753305299
85,455354753305299
86,455354753305299
87,455354753305299
88,455354753305299
89,455354753305299
90,455354753305299
91,455354753305299
92,455354753305299
93,455354753305299
94,455354753305299
95,455354753305299
96,455354753305299
97,455354753305299
98,455354753305299
99,455354753305299
101,455354753305299
102,455354753305299
103,455354753305299
104,455354753305299
105,455354753305299
106,455354753305299
107,455354753305299
108,455354753305299
109,455354753305299
110,455354753305299
111,455354753305299
112,455354753305299
113,455354753305299
114,455354753305299
115,455354753305299
116,455354753305299
117,455354753305299
118,455354753305299
119,455354753305299
120,455354753305299
122,455354753305299
123,455354753305299
124,455354753305299
125,455354753305299
126,455354753305299
127,455354753305299
128,455354753305299
129,455354753305299
130,455354753305299
131,455354753305299
132,455354753305299
133,455354753305299
134,455354753305299
135,455354753305299
136,455354753305299
137,455354753305299
138,455354753305299
139,455354753305299
140,455354753305299
141,455354753305299
142,455354753305299
143,455354753305299
145,455354753305299
146,455354753305299
147,455354753305299
148,455354753305299
149,455354753305299
150,455354753305299
151,455354753305299
152,455354753305299
153,455354753305299
154,455354753305299
155,455354753305299
156,455354753305299
157,455354753305299
158,455354753305299
159,455354753305299
160,455354753305299
161,455354753305299
162,455354753305299
163,455354753305299
164,455354753305299
165,455354753305299
166,455354753305299
167,455354753305299
168,455354753305299
170,455354753305299
171,455354753305299
172,455354753305299
173,455354753305299
174,455354753305299
175,455354753305299
176,455354753305299
177,455354753305299
178,455354753305299
179,455354753305299
180,455354753305299
181,455354753305299
182,455354753305299
183,455354753305299
184,455354753305299
185,455354753305299
186,455354753305299
187,455354753305299
188,455354753305299
189,455354753305299
190,455354753305299
191,455354753305299
192,455354753305299
193,455354753305299
194,455354753305299
195,455354753305299
197,455354753305299
198,455354753305299
199,455354753305299
200,455354753305299
201,455354753305299
202,455354753305299
203,455354753305299
204,455354753305299
205,455354753305299
206,455354753305299
207,455354753305299
208,455354753305299
209,455354753305299
210,455354753305299
211,455354753305299
212,455354753305299
213,455354753305299
214,455354753305299
215,455354753305299
216,455354753305299
217,455354753305299
218,455354753305299
219,455354753305299
220,455354753305299
221,455354753305299
222,455354753305299
223,455354753305299
224,455354753305299
226,455354753305299
227,455354753305299
228,455354753305299
229,455354753305299
230,455354753305299
231,455354753305299
232,455354753305299
233,455354753305299
234,455354753305299
235,455354753305299
236,455354753305299
237,455354753305299
238,455354753305299
239,455354753305299
240,455354753305299
241,455354753305299
242,455354753305299
243,455354753305299
244,455354753305299
245,455354753305299
246,455354753305299
247,455354753305299
248,455354753305299
249,455354753305299
250,455354753305299
251,455354753305299
252,455354753305299
253,455354753305299
254,455354753305299
255,455354753305299
257,455354753305299
258,455354753305299
259,455354753305299
260,455354753305299
261,455354753305299
262,455354753305299
263,455354753305299
264,455354753305299
265,455354753305299
266,455354753305299
267,455354753305299
268,455354753305299
269,455354753305299
270,455354753305299
271,455354753305299
272,455354753305299
273,455354753305299
274,455354753305299
275,455354753305299
276,455354753305299
277,455354753305299
278,455354753305299
279,455354753305299
280,455354753305299
281,455354753305299
282,455354753305299
283,455354753305299
284,455354753305299
285,455354753305299
286,455354753305299
287,455354753305299
288,455354753305299
290,455354753305299
291,455354753305299
292,455354753305299
293,455354753305299
294,455354753305299
295,455354753305299
296,455354753305299
297,455354753305299
298,455354753305299
299,455354753305299
300,455354753305299
301,455354753305299
302,455354753305299
303,455354753305299
304,455354753305299
305,455354753305299
306,455354753305299
307,455354753305299
308,455354753305299
309,455354753305299
310,455354753305299
311,455354753305299
312,455354753305299
313,455354753305299
314,455354753305299
315,455354753305299
316,455354753305299
317,455354753305299
318,455354753305299
319,455354753305299
320,455354753305299
321,455354753305299
322,455354753305299
323,455354753305299
325,455354753305299
326,455354753305299
327,455354753305299
328,455354753305299
329,455354753305299
330,455354753305299
331,455354753305299
332,455354753305299
333,455354753305299
334,455354753305299
335,455354753305299
336,455354753305299
337,455354753305299
338,455354753305299
339,455354753305299
340,455354753305299
341,455354753305299
342,455354753305299
343,455354753305299
344,455354753305299
345,455354753305299
346,455354753305299
347,455354753305299
348,455354753305299
349,455354753305299
350,455354753305299
351,455354753305299
352,455354753305299
353,455354753305299
354,455354753305299
355,455354753305299
356,455354753305299
357,455354753305299
358,455354753305299
359,455354753305299
360,455354753305299
362,455354753305299
363,455354753305299
364,455354753305299
365,455354753305299
366,455354753305299
367,455354753305299
368,455354753305299
369,455354753305299
370,455354753305299
371,455354753305299
372,455354753305299
373,455354753305299
374,455354753305299
375,455354753305299
376,455354753305299
377,455354753305299
378,455354753305299
379,455354753305299
380,455354753305299
381,455354753305299
382,455354753305299
383,455354753305299
384,455354753305299
385,455354753305299
386,455354753305299
387,455354753305299
388,455354753305299
389,455354753305299
390,455354753305299
391,455354753305299
392,455354753305299
393,455354753305299
394,455354753305299
395,455354753305299
396,455354753305299
397,455354753305299
398,455354753305299
399,455354753305299
401,455354753305299
402,455354753305299
403,455354753305299
404,455354753305299
405,455354753305299
406,455354753305299
407,455354753305299
408,455354753305299
409,455354753305299
410,455354753305299
411,455354753305299
412,455354753305299
413,455354753305299
414,455354753305299
415,455354753305299
416,455354753305299
417,455354753305299
418,455354753305299
419,455354753305299
420,455354753305299
421,455354753305299
422,455354753305299
423,455354753305299
424,455354753305299
425,455354753305299
426,455354753305299
427,455354753305299
428,455354753305299
429,455354753305299
430,455354753305299
431,455354753305299
432,455354753305299
433,455354753305299
434,455354753305299
435,455354753305299
436,455354753305299
437,455354753305299
438,455354753305299
439,455354753305299
440,455354753305299
442,455354753305299
443,455354753305299
444,455354753305299
445,455354753305299
446,455354753305299
447,455354753305299
448,455354753305299
449,455354753305299
450,455354753305299
451,455354753305299
452,455354753305299
453,455354753305299
454,455354753305299
455,455354753305299
456,455354753305299
457,455354753305299
458,455354753305299
459,455354753305299
460,455354753305299
461,455354753305299
462,455354753305299
463,455354753305299
464,455354753305299
465,455354753305299
466,455354753305299
467,455354753305299
468,455354753305299
469,455354753305299
470,455354753305299
471,455354753305299
472,455354753305299
473,455354753305299
474,455354753305299
475,455354753305299
476,455354753305299
477,455354753305299
478,455354753305299
479,455354753305299
480,455354753305299
481,455354753305299
482,455354753305299
483,455354753305299
485,455354753305299
486,455354753305299
487,455354753305299
488,455354753305299
489,455354753305299
490,455354753305299
491,455354753305299
492,455354753305299
493,455354753305299
494,455354753305299
495,455354753305299
496,455354753305299
497,455354753305299
498,455354753305299
499,455354753305299
500,455354753305299
501,455354753305299
502,455354753305299
503,455354753305299
504,455354753305299
505,455354753305299
506,455354753305299
507,455354753305299
508,455354753305299
509,455354753305299
510,455354753305299
511,455354753305299
512,455354753305299
513,455354753305299
514,455354753305299
515,455354753305299
516,455354753305299
517,455354753305299
518,455354753305299
519,455354753305299
520,455354753305299
521,455354753305299
522,455354753305299
523,455354753305299
524,455354753305299
525,455354753305299
526,455354753305299
527,455354753305299
528,455354753305299
530,455354753305299
531,455354753305299
532,455354753305299
533,455354753305299
534,455354753305299
535,455354753305299
536,455354753305299
537,455354753305299
538,455354753305299
539,455354753305299
540,455354753305299
541,455354753305299
542,455354753305299
543,455354753305299
544,455354753305299
545,455354753305299
546,455354753305299
547,455354753305299
548,455354753305299
549,455354753305299
550,455354753305299
551,455354753305299
552,455354753305299
553,455354753305299
554,455354753305299
555,455354753305299
556,455354753305299
557,455354753305299
558,455354753305299
559,455354753305299
560,455354753305299
561,455354753305299
562,455354753305299
563,455354753305299
564,455354753305299
565,455354753305299
566,455354753305299
567,455354753305299
568,455354753305299
569,455354753305299
570,455354753305299
571,455354753305299
572,455354753305299
573,455354753305299
574,455354753305299
575,455354753305299
577,455354753305299
578,455354753305299
579,455354753305299
580,455354753305299
581,455354753305299
582,455354753305299
583,455354753305299
584,455354753305299
585,455354753305299
586,455354753305299
587,455354753305299
588,455354753305299
589,455354753305299
590,455354753305299
591,455354753305299
592,455354753305299
593,455354753305299
594,455354753305299
595,455354753305299
596,455354753305299
597,455354753305299
598,455354753305299
599,455354753305299
600,455354753305299
601,455354753305299
602,455354753305299
603,455354753305299
604,455354753305299
605,455354753305299
606,455354753305299
607,455354753305299
608,455354753305299
609,455354753305299
610,455354753305299
611,455354753305299
612,455354753305299
613,455354753305299
614,455354753305299
615,455354753305299
616,455354753305299
617,455354753305299
618,455354753305299
619,455354753305299
620,455354753305299
621,455354753305299
622,455354753305299
623,455354753305299
624,455354753305299
626,455354753305299
627,455354753305299
628,455354753305299
629,455354753305299
630,455354753305299
631,455354753305299
632,455354753305299
633,455354753305299
634,455354753305299
635,455354753305299
636,455354753305299
637,455354753305299
638,455354753305299
639,455354753305299
640,455354753305299
641,455354753305299
642,455354753305299
643,455354753305299
644,455354753305299
645,455354753305299
646,455354753305299
647,455354753305299
648,455354753305299
649,455354753305299
650,455354753305299
651,455354753305299
652,455354753305299
653,455354753305299
654,455354753305299
655,455354753305299
656,455354753305299
657,455354753305299
658,455354753305299
659,455354753305299
660,455354753305299
661,455354753305299
662,455354753305299
663,455354753305299
664,455354753305299
665,455354753305299
666,455354753305299
667,455354753305299
668,455354753305299
669,455354753305299
670,455354753305299
671,455354753305299
672,455354753305299
673,455354753305299
674,455354753305299
675,455354753305299
677,455354753305299
678,455354753305299
679,455354753305299
680,455354753305299
681,455354753305299
682,455354753305299
683,455354753305299
684,455354753305299
685,455354753305299
686,455354753305299
687,455354753305299
688,455354753305299
689,455354753305299
690,455354753305299
691,455354753305299
692,455354753305299
693,455354753305299
694,455354753305299
695,455354753305299
696,455354753305299
697,455354753305299
698,455354753305299
699,455354753305299
700,455354753305299
701,455354753305299
702,455354753305299
703,455354753305299
704,455354753305299
705,455354753305299
706,455354753305299
707,455354753305299
708,455354753305299
709,455354753305299
710,455354753305299
711,455354753305299
712,455354753305299
713,455354753305299
714,455354753305299
715,455354753305299
716,455354753305299
717,455354753305299
718,455354753305299
719,455354753305299
720,455354753305299
721,455354753305299
722,455354753305299
723,455354753305299
724,455354753305299
725,455354753305299
726,455354753305299
727,455354753305299
728,455354753305299
730,455354753305299
731,455354753305299
732,455354753305299
733,455354753305299
734,455354753305299
735,455354753305299
736,455354753305299
737,455354753305299
738,455354753305299
739,455354753305299
740,455354753305299
741,455354753305299
742,455354753305299
743,455354753305299
744,455354753305299
745,455354753305299
746,455354753305299
747,455354753305299
748,455354753305299
749,455354753305299
750,455354753305299
751,455354753305299
752,455354753305299
753,455354753305299
754,455354753305299
755,455354753305299
756,455354753305299
757,455354753305299
758,455354753305299
759,455354753305299
760,455354753305299
761,455354753305299
762,455354753305299
763,455354753305299
764,455354753305299
765,455354753305299
766,455354753305299
767,455354753305299
768,455354753305299
769,455354753305299
770,455354753305299
771,455354753305299
772,455354753305299
773,455354753305299
774,455354753305299
775,455354753305299
776,455354753305299
777,455354753305299
778,455354753305299
779,455354753305299
780,455354753305299
781,455354753305299
782,455354753305299
783,455354753305299
785,455354753305299
786,455354753305299
787,455354753305299
788,455354753305299
789,455354753305299
790,455354753305299
791,455354753305299
792,455354753305299
793,455354753305299
794,455354753305299
795,455354753305299
796,455354753305299
797,455354753305299
798,455354753305299
799,455354753305299
800,455354753305299
801,455354753305299
802,455354753305299
803,455354753305299
804,455354753305299
805,455354753305299
806,455354753305299
807,455354753305299
808,455354753305299
809,455354753305299
810,455354753305299
811,455354753305299
812,455354753305299
813,455354753305299
814,455354753305299
815,455354753305299
816,455354753305299
817,455354753305299
818,455354753305299
819,455354753305299
820,455354753305299
821,455354753305299
822,455354753305299
823,455354753305299
824,455354753305299
825,455354753305299
826,455354753305299
827,455354753305299
828,455354753305299
829,455354753305299
830,455354753305299
831,455354753305299
832,455354753305299
833,455354753305299
834,455354753305299
835,455354753305299
836,455354753305299
837,455354753305299
838,455354753305299
839,455354753305299
840,455354753305299
842,455354753305299
843,455354753305299
844,455354753305299
845,455354753305299
846,455354753305299
847,455354753305299
848,455354753305299
849,455354753305299
850,455354753305299
851,455354753305299
852,455354753305299
853,455354753305299
854,455354753305299
855,455354753305299
856,455354753305299
857,455354753305299
858,455354753305299
859,455354753305299
860,455354753305299
861,455354753305299
862,455354753305299
863,455354753305299
864,455354753305299
865,455354753305299
866,455354753305299
867,455354753305299
868,455354753305299
869,455354753305299
870,455354753305299
871,455354753305299
872,455354753305299
873,455354753305299
874,455354753305299
875,455354753305299
876,455354753305299
877,455354753305299
878,455354753305299
879,455354753305299
880,455354753305299
881,455354753305299
882,455354753305299
883,455354753305299
884,455354753305299
885,455354753305299
886,455354753305299
887,455354753305299
888,455354753305299
889,455354753305299
890,455354753305299
891,455354753305299
892,455354753305299
893,455354753305299
894,455354753305299
895,455354753305299
896,455354753305299
897,455354753305299
898,455354753305299
899,455354753305299
901,455354753305299
902,455354753305299
903,455354753305299
904,455354753305299
905,455354753305299
906,455354753305299
907,455354753305299
908,455354753305299
909,455354753305299
910,455354753305299
911,455354753305299
912,455354753305299
913,455354753305299
914,455354753305299
915,455354753305299
916,455354753305299
917,455354753305299
918,455354753305299
919,455354753305299
920,455354753305299
921,455354753305299
922,455354753305299
923,455354753305299
924,455354753305299
925,455354753305299
926,455354753305299
927,455354753305299
928,455354753305299
929,455354753305299
930,455354753305299
931,455354753305299
932,455354753305299
933,455354753305299
934,455354753305299
935,455354753305299
936,455354753305299
937,455354753305299
938,455354753305299
939,455354753305299
940,455354753305299
941,455354753305299
942,455354753305299
943,455354753305299
944,455354753305299
945,455354753305299
946,455354753305299
947,455354753305299
948,455354753305299
949,455354753305299
950,455354753305299
951,455354753305299
952,455354753305299
953,455354753305299
954,455354753305299
955,455354753305299
956,455354753305299
957,455354753305299
958,455354753305299
959,455354753305299
960,455354753305299
962,455354753305299
963,455354753305299
964,455354753305299
965,455354753305299
966,455354753305299
967,455354753305299
968,455354753305299
969,455354753305299
970,455354753305299
971,455354753305299
972,455354753305299
973,455354753305299
974,455354753305299
975,455354753305299
976,455354753305299
977,455354753305299
978,455354753305299
979,455354753305299
980,455354753305299
981,455354753305299
982,455354753305299
983,455354753305299
984,455354753305299
985,455354753305299
986,455354753305299
987,455354753305299
988,455354753305299
989,455354753305299
990,455354753305299
991,455354753305299
992,455354753305299
993,455354753305299
994,455354753305299
995,455354753305299
996,455354753305299
997,455354753305299
998,455354753305299
999,455354753305299
1000,455354753305299

### Entiers palindromiques

**Exercice [052].** Un entier est **palindromique** si sa représentation décimale se lit de la même façon de gauche à droite et de droite à gauche.

| Exemple | De droite à gauche | Palindromique |
|---:|:--:|:--:|
| $7$ | $7$ | ✅ |
| $121$ | $121$ | ✅ |
| $123$ | $$321$$ | ❌ |

_Tâche._ Listez par ordre croissant les entiers palindromiques inférieurs ou égaux à 1000.

In [ ]:
%%sql
-- Il suffit de comparer la chaîne correspondante à son inverse.
SELECT i
     , salt_052(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE cast(i AS CHAR) = reverse(cast(i AS CHAR))

109 rows affected.

i,token
0,240070160009025
1,240070160009025
2,240070160009025
3,240070160009025
4,240070160009025
5,240070160009025
6,240070160009025
7,240070160009025
8,240070160009025
9,240070160009025
11,240070160009025
22,240070160009025
33,240070160009025
44,240070160009025
55,240070160009025
66,240070160009025
77,240070160009025
88,240070160009025
99,240070160009025
101,240070160009025
111,240070160009025
121,240070160009025
131,240070160009025
141,240070160009025
151,240070160009025
161,240070160009025
171,240070160009025
181,240070160009025
191,240070160009025
202,240070160009025
212,240070160009025
222,240070160009025
232,240070160009025
242,240070160009025
252,240070160009025
262,240070160009025
272,240070160009025
282,240070160009025
292,240070160009025
303,240070160009025
313,240070160009025
323,240070160009025
333,240070160009025
343,240070160009025
353,240070160009025
363,240070160009025
373,240070160009025
383,240070160009025
393,240070160009025
404,240070160009025
414,240070160009025
424,240070160009025
434,240070160009025
444,240070160009025
454,240070160009025
464,240070160009025
474,240070160009025
484,240070160009025
494,240070160009025
505,240070160009025
515,240070160009025
525,240070160009025
535,240070160009025
545,240070160009025
555,240070160009025
565,240070160009025
575,240070160009025
585,240070160009025
595,240070160009025
606,240070160009025
616,240070160009025
626,240070160009025
636,240070160009025
646,240070160009025
656,240070160009025
666,240070160009025
676,240070160009025
686,240070160009025
696,240070160009025
707,240070160009025
717,240070160009025
727,240070160009025
737,240070160009025
747,240070160009025
757,240070160009025
767,240070160009025
777,240070160009025
787,240070160009025
797,240070160009025
808,240070160009025
818,240070160009025
828,240070160009025
838,240070160009025
848,240070160009025
858,240070160009025
868,240070160009025
878,240070160009025
888,240070160009025
898,240070160009025
909,240070160009025
919,240070160009025
929,240070160009025
939,240070160009025
949,240070160009025
959,240070160009025
969,240070160009025
979,240070160009025
989,240070160009025
999,240070160009025

In [ ]:
%%sql
-- Variante. MySQL est notoirement peu regardant sur les types. Dans la version ci-dessous, il convertit
-- implicitement l’entier `i` en chaîne de caractères pour appliquer la fonction `REVERSE`, puis reconvertit
-- le résultat en entier pour la comparaison. Cela dit, pour éviter toute ambiguïté ou comportement implicite,
-- on préférera `CAST(i AS CHAR)`, plus rigoureux et plus portable.
SELECT i
     , salt_052(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i = reverse(i)

109 rows affected.

i,token
0,240070160009025
1,240070160009025
2,240070160009025
3,240070160009025
4,240070160009025
5,240070160009025
6,240070160009025
7,240070160009025
8,240070160009025
9,240070160009025
11,240070160009025
22,240070160009025
33,240070160009025
44,240070160009025
55,240070160009025
66,240070160009025
77,240070160009025
88,240070160009025
99,240070160009025
101,240070160009025
111,240070160009025
121,240070160009025
131,240070160009025
141,240070160009025
151,240070160009025
161,240070160009025
171,240070160009025
181,240070160009025
191,240070160009025
202,240070160009025
212,240070160009025
222,240070160009025
232,240070160009025
242,240070160009025
252,240070160009025
262,240070160009025
272,240070160009025
282,240070160009025
292,240070160009025
303,240070160009025
313,240070160009025
323,240070160009025
333,240070160009025
343,240070160009025
353,240070160009025
363,240070160009025
373,240070160009025
383,240070160009025
393,240070160009025
404,240070160009025
414,240070160009025
424,240070160009025
434,240070160009025
444,240070160009025
454,240070160009025
464,240070160009025
474,240070160009025
484,240070160009025
494,240070160009025
505,240070160009025
515,240070160009025
525,240070160009025
535,240070160009025
545,240070160009025
555,240070160009025
565,240070160009025
575,240070160009025
585,240070160009025
595,240070160009025
606,240070160009025
616,240070160009025
626,240070160009025
636,240070160009025
646,240070160009025
656,240070160009025
666,240070160009025
676,240070160009025
686,240070160009025
696,240070160009025
707,240070160009025
717,240070160009025
727,240070160009025
737,240070160009025
747,240070160009025
757,240070160009025
767,240070160009025
777,240070160009025
787,240070160009025
797,240070160009025
808,240070160009025
818,240070160009025
828,240070160009025
838,240070160009025
848,240070160009025
858,240070160009025
868,240070160009025
878,240070160009025
888,240070160009025
898,240070160009025
909,240070160009025
919,240070160009025
929,240070160009025
939,240070160009025
949,240070160009025
959,240070160009025
969,240070160009025
979,240070160009025
989,240070160009025
999,240070160009025

### Nombres triangulaires

**Exercice [043].** Un entier est **triangulaire** si et seulement s'il peut s'écrire sous la forme $\frac{n (n+1)}{2}$ avec $n$ entier positif ou nul.

| Exemple | Forme cherchée | Triangulaire |
|---:|:--:|:--:|
| $15$ | $$5\times6\div2$$ | ✅ |
| $16$ | ❌ | ❌ |

_Tâche._ Listez par ordre croissant les nombres triangulaires inférieurs ou égaux à 1000.

In [ ]:
x = 45 # le dixième nombre de la colonne
# Javascript: result[9]?.i ?? 7_531_148

In [ ]:
%%sql
-- On parcourt tous les entiers $A_i$ de la liste, et on ne garde que ceux pour lesquels il existe un entier $B_i$
-- vérifiant l'équation. Comme on connaît la borne supérieure ($1000$, qui est plus petit $45\times 46\div 2=1035$), on
-- peut (facultativement) insérer la « garde » `B.i < 45`.
SELECT i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE EXISTS
        (SELECT 1
         FROM ints B
         WHERE B.i < 45
             AND A.i = B.i * (B.i + 1) / 2 )

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Variante. Avec une auto-jointure.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1) / 2
WHERE B.i < 45
ORDER BY A.i;

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Variante. Avec une sous-requête dans le `WHERE`.
SELECT i
     , salt_043({{x}} + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i IN
        (SELECT i * (i + 1) / 2
         FROM ints
         WHERE i < 45 )

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Indication. On ne cherche pas les nombres qui vérifient l'égalité $n = \frac{n(n+1)}{2}$ mais ceux qui peuvent
-- s'écrire sous la forme de sa partie droite.
SELECT i
     , salt_043(7531148 + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i = i * (i + 1) / 2

2 rows affected.

i,token
0,81063761713588
1,81063761713588

In [ ]:
x = 90

In [ ]:
%%sql
-- Indication. Vous avez oublié le numérateur de la formule.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1)
WHERE B.i < 45
ORDER BY A.i;

32 rows affected.

i,token
0,96800835160244
2,96800835160244
6,96800835160244
12,96800835160244
20,96800835160244
30,96800835160244
42,96800835160244
56,96800835160244
72,96800835160244
90,96800835160244
110,96800835160244
132,96800835160244
156,96800835160244
182,96800835160244
210,96800835160244
240,96800835160244
272,96800835160244
306,96800835160244
342,96800835160244
380,96800835160244
420,96800835160244
462,96800835160244
506,96800835160244
552,96800835160244
600,96800835160244
650,96800835160244
702,96800835160244
756,96800835160244
812,96800835160244
870,96800835160244
930,96800835160244
992,96800835160244

In [ ]:
assert col['i'][9] == x

In [ ]:
x = 162

In [ ]:
%%sql
-- Indication. Vous avez oublié le $+ 1$ dans la formule.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * B.i / 2
WHERE B.i < 45
ORDER BY A.i

23 rows affected.

i,token
0,76118056186574
2,76118056186574
8,76118056186574
18,76118056186574
32,76118056186574
50,76118056186574
72,76118056186574
98,76118056186574
128,76118056186574
162,76118056186574
200,76118056186574
242,76118056186574
288,76118056186574
338,76118056186574
392,76118056186574
450,76118056186574
512,76118056186574
578,76118056186574
648,76118056186574
722,76118056186574
800,76118056186574
882,76118056186574
968,76118056186574

In [ ]:
assert col['i'][9] == x

In [ ]:
x = 9

In [ ]:
%%sql
-- Indication. Vous ne projetez pas la colonne `i` de la bonne table.
SELECT B.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1) / 2
WHERE B.i < 45
ORDER BY A.i

45 rows affected.

i,token
0,103209978926115
1,103209978926115
2,103209978926115
3,103209978926115
4,103209978926115
5,103209978926115
6,103209978926115
7,103209978926115
8,103209978926115
9,103209978926115
10,103209978926115
11,103209978926115
12,103209978926115
13,103209978926115
14,103209978926115
15,103209978926115
16,103209978926115
17,103209978926115
18,103209978926115
19,103209978926115
20,103209978926115
21,103209978926115
22,103209978926115
23,103209978926115
24,103209978926115
25,103209978926115
26,103209978926115
27,103209978926115
28,103209978926115
29,103209978926115
30,103209978926115
31,103209978926115
32,103209978926115
33,103209978926115
34,103209978926115
35,103209978926115
36,103209978926115
37,103209978926115
38,103209978926115
39,103209978926115
40,103209978926115
41,103209978926115
42,103209978926115
43,103209978926115
44,103209978926115

In [ ]:
assert col['i'][9] == x

### FizzBuzz

**Exercice [088].** La suite **FizzBuzz** est une transformation des entiers naturels strictement positifs où :

- tout multiple de 3 est remplacé par `'Fizz'` ;
- tout multiple de 5 est remplacé par `'Buzz'` ;
- tout multiple de 15 est remplacé par `'FizzBuzz'` ;
- les autres nombres restent inchangés.

| fizzbuzz     |
|:------------:|
| `1`          |
| `2`          |
| `Fizz`     |
| `4`          |
| `Buzz`     |
| `Fizz`     |
| `7`          |
| ⋮            |
| `14`         
| `FizzBuzz` |
| `16`         
| ⋮            |


_Tâche._ Listez par ordre croissant les termes de FizzBuzz jusqu'à 1000.

_Aide._ L'opérateur `CASE` fera ici merveille sous la forme suivante :

```sql
CASE
    WHEN condition_1 THEN result_1
    WHEN condition_2 THEN result_2
    ...
    ELSE default_result
END
```

In [ ]:
x = "fizz.buzz.11.fizz.13.14.fizzbuzz.16" # la concaténation des 9e au 16e terme, séparés par des points, en minuscules.
# Javascript: (result.slice(8, 16).map(x => x?.fizzbuzz ?? '').join('.') || '').toLowerCase() || '7_531_148'

In [ ]:
%%sql
SELECT CASE
           WHEN i % 15 = 0 THEN 'FizzBuzz'
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 5 = 0 THEN 'Buzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 0

1000 rows affected.

fizzbuzz,token
1,360051049043076
2,360051049043076
Fizz,360051049043076
4,360051049043076
Buzz,360051049043076
Fizz,360051049043076
7,360051049043076
8,360051049043076
Fizz,360051049043076
Buzz,360051049043076
11,360051049043076
Fizz,360051049043076
13,360051049043076
14,360051049043076
FizzBuzz,360051049043076
16,360051049043076
17,360051049043076
Fizz,360051049043076
19,360051049043076
Buzz,360051049043076
Fizz,360051049043076
22,360051049043076
23,360051049043076
Fizz,360051049043076
Buzz,360051049043076
26,360051049043076
Fizz,360051049043076
28,360051049043076
29,360051049043076
FizzBuzz,360051049043076
31,360051049043076
32,360051049043076
Fizz,360051049043076
34,360051049043076
Buzz,360051049043076
Fizz,360051049043076
37,360051049043076
38,360051049043076
Fizz,360051049043076
Buzz,360051049043076
41,360051049043076
Fizz,360051049043076
43,360051049043076
44,360051049043076
FizzBuzz,360051049043076
46,360051049043076
47,360051049043076
Fizz,360051049043076
49,360051049043076
Buzz,360051049043076
Fizz,360051049043076
52,360051049043076
53,360051049043076
Fizz,360051049043076
Buzz,360051049043076
56,360051049043076
Fizz,360051049043076
58,360051049043076
59,360051049043076
FizzBuzz,360051049043076
61,360051049043076
62,360051049043076
Fizz,360051049043076
64,360051049043076
Buzz,360051049043076
Fizz,360051049043076
67,360051049043076
68,360051049043076
Fizz,360051049043076
Buzz,360051049043076
71,360051049043076
Fizz,360051049043076
73,360051049043076
74,360051049043076
FizzBuzz,360051049043076
76,360051049043076
77,360051049043076
Fizz,360051049043076
79,360051049043076
Buzz,360051049043076
Fizz,360051049043076
82,360051049043076
83,360051049043076
Fizz,360051049043076
Buzz,360051049043076
86,360051049043076
Fizz,360051049043076
88,360051049043076
89,360051049043076
FizzBuzz,360051049043076
91,360051049043076
92,360051049043076
Fizz,360051049043076
94,360051049043076
Buzz,360051049043076
Fizz,360051049043076
97,360051049043076
98,360051049043076
Fizz,360051049043076
Buzz,360051049043076
101,360051049043076
Fizz,360051049043076
103,360051049043076
104,360051049043076
FizzBuzz,360051049043076
106,360051049043076
107,360051049043076
Fizz,360051049043076
109,360051049043076
Buzz,360051049043076
Fizz,360051049043076
112,360051049043076
113,360051049043076
Fizz,360051049043076
Buzz,360051049043076
116,360051049043076
Fizz,360051049043076
118,360051049043076
119,360051049043076
FizzBuzz,360051049043076
121,360051049043076
122,360051049043076
Fizz,360051049043076
124,360051049043076
Buzz,360051049043076
Fizz,360051049043076
127,360051049043076
128,360051049043076
Fizz,360051049043076
Buzz,360051049043076
131,360051049043076
Fizz,360051049043076
133,360051049043076
134,360051049043076
FizzBuzz,360051049043076
136,360051049043076
137,360051049043076
Fizz,360051049043076
139,360051049043076
Buzz,360051049043076
Fizz,360051049043076
142,360051049043076
143,360051049043076
Fizz,360051049043076
Buzz,360051049043076
146,360051049043076
Fizz,360051049043076
148,360051049043076
149,360051049043076
FizzBuzz,360051049043076
151,360051049043076
152,360051049043076
Fizz,360051049043076
154,360051049043076
Buzz,360051049043076
Fizz,360051049043076
157,360051049043076
158,360051049043076
Fizz,360051049043076
Buzz,360051049043076
161,360051049043076
Fizz,360051049043076
163,360051049043076
164,360051049043076
FizzBuzz,360051049043076
166,360051049043076
167,360051049043076
Fizz,360051049043076
169,360051049043076
Buzz,360051049043076
Fizz,360051049043076
172,360051049043076
173,360051049043076
Fizz,360051049043076
Buzz,360051049043076
176,360051049043076
Fizz,360051049043076
178,360051049043076
179,360051049043076
FizzBuzz,360051049043076
181,360051049043076
182,360051049043076
Fizz,360051049043076
184,360051049043076
Buzz,360051049043076
Fizz,360051049043076
187,360051049043076
188,360051049043076
Fizz,360051049043076
Buzz,360051049043076
191,360051049043076
Fizz,360051049043076
193,360051049043076
194,360051049043076
FizzBuzz,360051049043076
196,360051049043076
197,360051049043076
Fizz,360051049043076
199,360051049043076
Buzz,360051049043076
Fizz,360051049043076
202,360051049043076
203,360051049043076
Fizz,360051049043076
Buzz,360051049043076
206,360051049043076
Fizz,360051049043076
208,360051049043076
209,360051049043076
FizzBuzz,360051049043076
211,360051049043076
212,360051049043076
Fizz,360051049043076
214,360051049043076
Buzz,360051049043076
Fizz,360051049043076
217,360051049043076
218,360051049043076
Fizz,360051049043076
Buzz,360051049043076
221,360051049043076
Fizz,360051049043076
223,360051049043076
224,360051049043076
FizzBuzz,360051049043076
226,360051049043076
227,360051049043076
Fizz,360051049043076
229,360051049043076
Buzz,360051049043076
Fizz,360051049043076
232,360051049043076
233,360051049043076
Fizz,360051049043076
Buzz,360051049043076
236,360051049043076
Fizz,360051049043076
238,360051049043076
239,360051049043076
FizzBuzz,360051049043076
241,360051049043076
242,360051049043076
Fizz,360051049043076
244,360051049043076
Buzz,360051049043076
Fizz,360051049043076
247,360051049043076
248,360051049043076
Fizz,360051049043076
Buzz,360051049043076
251,360051049043076
Fizz,360051049043076
253,360051049043076
254,360051049043076
FizzBuzz,360051049043076
256,360051049043076
257,360051049043076
Fizz,360051049043076
259,360051049043076
Buzz,360051049043076
Fizz,360051049043076
262,360051049043076
263,360051049043076
Fizz,360051049043076
Buzz,360051049043076
266,360051049043076
Fizz,360051049043076
268,360051049043076
269,360051049043076
FizzBuzz,360051049043076
271,360051049043076
272,360051049043076
Fizz,360051049043076
274,360051049043076
Buzz,360051049043076
Fizz,360051049043076
277,360051049043076
278,360051049043076
Fizz,360051049043076
Buzz,360051049043076
281,360051049043076
Fizz,360051049043076
283,360051049043076
284,360051049043076
FizzBuzz,360051049043076
286,360051049043076
287,360051049043076
Fizz,360051049043076
289,360051049043076
Buzz,360051049043076
Fizz,360051049043076
292,360051049043076
293,360051049043076
Fizz,360051049043076
Buzz,360051049043076
296,360051049043076
Fizz,360051049043076
298,360051049043076
299,360051049043076
FizzBuzz,360051049043076
301,360051049043076
302,360051049043076
Fizz,360051049043076
304,360051049043076
Buzz,360051049043076
Fizz,360051049043076
307,360051049043076
308,360051049043076
Fizz,360051049043076
Buzz,360051049043076
311,360051049043076
Fizz,360051049043076
313,360051049043076
314,360051049043076
FizzBuzz,360051049043076
316,360051049043076
317,360051049043076
Fizz,360051049043076
319,360051049043076
Buzz,360051049043076
Fizz,360051049043076
322,360051049043076
323,360051049043076
Fizz,360051049043076
Buzz,360051049043076
326,360051049043076
Fizz,360051049043076
328,360051049043076
329,360051049043076
FizzBuzz,360051049043076
331,360051049043076
332,360051049043076
Fizz,360051049043076
334,360051049043076
Buzz,360051049043076
Fizz,360051049043076
337,360051049043076
338,360051049043076
Fizz,360051049043076
Buzz,360051049043076
341,360051049043076
Fizz,360051049043076
343,360051049043076
344,360051049043076
FizzBuzz,360051049043076
346,360051049043076
347,360051049043076
Fizz,360051049043076
349,360051049043076
Buzz,360051049043076
Fizz,360051049043076
352,360051049043076
353,360051049043076
Fizz,360051049043076
Buzz,360051049043076
356,360051049043076
Fizz,360051049043076
358,360051049043076
359,360051049043076
FizzBuzz,360051049043076
361,360051049043076
362,360051049043076
Fizz,360051049043076
364,360051049043076
Buzz,360051049043076
Fizz,360051049043076
367,360051049043076
368,360051049043076
Fizz,360051049043076
Buzz,360051049043076
371,360051049043076
Fizz,360051049043076
373,360051049043076
374,360051049043076
FizzBuzz,360051049043076
376,360051049043076
377,360051049043076
Fizz,360051049043076
379,360051049043076
Buzz,360051049043076
Fizz,360051049043076
382,360051049043076
383,360051049043076
Fizz,360051049043076
Buzz,360051049043076
386,360051049043076
Fizz,360051049043076
388,360051049043076
389,360051049043076
FizzBuzz,360051049043076
391,360051049043076
392,360051049043076
Fizz,360051049043076
394,360051049043076
Buzz,360051049043076
Fizz,360051049043076
397,360051049043076
398,360051049043076
Fizz,360051049043076
Buzz,360051049043076
401,360051049043076
Fizz,360051049043076
403,360051049043076
404,360051049043076
FizzBuzz,360051049043076
406,360051049043076
407,360051049043076
Fizz,360051049043076
409,360051049043076
Buzz,360051049043076
Fizz,360051049043076
412,360051049043076
413,360051049043076
Fizz,360051049043076
Buzz,360051049043076
416,360051049043076
Fizz,360051049043076
418,360051049043076
419,360051049043076
FizzBuzz,360051049043076
421,360051049043076
422,360051049043076
Fizz,360051049043076
424,360051049043076
Buzz,360051049043076
Fizz,360051049043076
427,360051049043076
428,360051049043076
Fizz,360051049043076
Buzz,360051049043076
431,360051049043076
Fizz,360051049043076
433,360051049043076
434,360051049043076
FizzBuzz,360051049043076
436,360051049043076
437,360051049043076
Fizz,360051049043076
439,360051049043076
Buzz,360051049043076
Fizz,360051049043076
442,360051049043076
443,360051049043076
Fizz,360051049043076
Buzz,360051049043076
446,360051049043076
Fizz,360051049043076
448,360051049043076
449,360051049043076
FizzBuzz,360051049043076
451,360051049043076
452,360051049043076
Fizz,360051049043076
454,360051049043076
Buzz,360051049043076
Fizz,360051049043076
457,360051049043076
458,360051049043076
Fizz,360051049043076
Buzz,360051049043076
461,360051049043076
Fizz,360051049043076
463,360051049043076
464,360051049043076
FizzBuzz,360051049043076
466,360051049043076
467,360051049043076
Fizz,360051049043076
469,360051049043076
Buzz,360051049043076
Fizz,360051049043076
472,360051049043076
473,360051049043076
Fizz,360051049043076
Buzz,360051049043076
476,360051049043076
Fizz,360051049043076
478,360051049043076
479,360051049043076
FizzBuzz,360051049043076
481,360051049043076
482,360051049043076
Fizz,360051049043076
484,360051049043076
Buzz,360051049043076
Fizz,360051049043076
487,360051049043076
488,360051049043076
Fizz,360051049043076
Buzz,360051049043076
491,360051049043076
Fizz,360051049043076
493,360051049043076
494,360051049043076
FizzBuzz,360051049043076
496,360051049043076
497,360051049043076
Fizz,360051049043076
499,360051049043076
Buzz,360051049043076
Fizz,360051049043076
502,360051049043076
503,360051049043076
Fizz,360051049043076
Buzz,360051049043076
506,360051049043076
Fizz,360051049043076
508,360051049043076
509,360051049043076
FizzBuzz,360051049043076
511,360051049043076
512,360051049043076
Fizz,360051049043076
514,360051049043076
Buzz,360051049043076
Fizz,360051049043076
517,360051049043076
518,360051049043076
Fizz,360051049043076
Buzz,360051049043076
521,360051049043076
Fizz,360051049043076
523,360051049043076
524,360051049043076
FizzBuzz,360051049043076
526,360051049043076
527,360051049043076
Fizz,360051049043076
529,360051049043076
Buzz,360051049043076
Fizz,360051049043076
532,360051049043076
533,360051049043076
Fizz,360051049043076
Buzz,360051049043076
536,360051049043076
Fizz,360051049043076
538,360051049043076
539,360051049043076
FizzBuzz,360051049043076
541,360051049043076
542,360051049043076
Fizz,360051049043076
544,360051049043076
Buzz,360051049043076
Fizz,360051049043076
547,360051049043076
548,360051049043076
Fizz,360051049043076
Buzz,360051049043076
551,360051049043076
Fizz,360051049043076
553,360051049043076
554,360051049043076
FizzBuzz,360051049043076
556,360051049043076
557,360051049043076
Fizz,360051049043076
559,360051049043076
Buzz,360051049043076
Fizz,360051049043076
562,360051049043076
563,360051049043076
Fizz,360051049043076
Buzz,360051049043076
566,360051049043076
Fizz,360051049043076
568,360051049043076
569,360051049043076
FizzBuzz,360051049043076
571,360051049043076
572,360051049043076
Fizz,360051049043076
574,360051049043076
Buzz,360051049043076
Fizz,360051049043076
577,360051049043076
578,360051049043076
Fizz,360051049043076
Buzz,360051049043076
581,360051049043076
Fizz,360051049043076
583,360051049043076
584,360051049043076
FizzBuzz,360051049043076
586,360051049043076
587,360051049043076
Fizz,360051049043076
589,360051049043076
Buzz,360051049043076
Fizz,360051049043076
592,360051049043076
593,360051049043076
Fizz,360051049043076
Buzz,360051049043076
596,360051049043076
Fizz,360051049043076
598,360051049043076
599,360051049043076
FizzBuzz,360051049043076
601,360051049043076
602,360051049043076
Fizz,360051049043076
604,360051049043076
Buzz,360051049043076
Fizz,360051049043076
607,360051049043076
608,360051049043076
Fizz,360051049043076
Buzz,360051049043076
611,360051049043076
Fizz,360051049043076
613,360051049043076
614,360051049043076
FizzBuzz,360051049043076
616,360051049043076
617,360051049043076
Fizz,360051049043076
619,360051049043076
Buzz,360051049043076
Fizz,360051049043076
622,360051049043076
623,360051049043076
Fizz,360051049043076
Buzz,360051049043076
626,360051049043076
Fizz,360051049043076
628,360051049043076
629,360051049043076
FizzBuzz,360051049043076
631,360051049043076
632,360051049043076
Fizz,360051049043076
634,360051049043076
Buzz,360051049043076
Fizz,360051049043076
637,360051049043076
638,360051049043076
Fizz,360051049043076
Buzz,360051049043076
641,360051049043076
Fizz,360051049043076
643,360051049043076
644,360051049043076
FizzBuzz,360051049043076
646,360051049043076
647,360051049043076
Fizz,360051049043076
649,360051049043076
Buzz,360051049043076
Fizz,360051049043076
652,360051049043076
653,360051049043076
Fizz,360051049043076
Buzz,360051049043076
656,360051049043076
Fizz,360051049043076
658,360051049043076
659,360051049043076
FizzBuzz,360051049043076
661,360051049043076
662,360051049043076
Fizz,360051049043076
664,360051049043076
Buzz,360051049043076
Fizz,360051049043076
667,360051049043076
668,360051049043076
Fizz,360051049043076
Buzz,360051049043076
671,360051049043076
Fizz,360051049043076
673,360051049043076
674,360051049043076
FizzBuzz,360051049043076
676,360051049043076
677,360051049043076
Fizz,360051049043076
679,360051049043076
Buzz,360051049043076
Fizz,360051049043076
682,360051049043076
683,360051049043076
Fizz,360051049043076
Buzz,360051049043076
686,360051049043076
Fizz,360051049043076
688,360051049043076
689,360051049043076
FizzBuzz,360051049043076
691,360051049043076
692,360051049043076
Fizz,360051049043076
694,360051049043076
Buzz,360051049043076
Fizz,360051049043076
697,360051049043076
698,360051049043076
Fizz,360051049043076
Buzz,360051049043076
701,360051049043076
Fizz,360051049043076
703,360051049043076
704,360051049043076
FizzBuzz,360051049043076
706,360051049043076
707,360051049043076
Fizz,360051049043076
709,360051049043076
Buzz,360051049043076
Fizz,360051049043076
712,360051049043076
713,360051049043076
Fizz,360051049043076
Buzz,360051049043076
716,360051049043076
Fizz,360051049043076
718,360051049043076
719,360051049043076
FizzBuzz,360051049043076
721,360051049043076
722,360051049043076
Fizz,360051049043076
724,360051049043076
Buzz,360051049043076
Fizz,360051049043076
727,360051049043076
728,360051049043076
Fizz,360051049043076
Buzz,360051049043076
731,360051049043076
Fizz,360051049043076
733,360051049043076
734,360051049043076
FizzBuzz,360051049043076
736,360051049043076
737,360051049043076
Fizz,360051049043076
739,360051049043076
Buzz,360051049043076
Fizz,360051049043076
742,360051049043076
743,360051049043076
Fizz,360051049043076
Buzz,360051049043076
746,360051049043076
Fizz,360051049043076
748,360051049043076
749,360051049043076
FizzBuzz,360051049043076
751,360051049043076
752,360051049043076
Fizz,360051049043076
754,360051049043076
Buzz,360051049043076
Fizz,360051049043076
757,360051049043076
758,360051049043076
Fizz,360051049043076
Buzz,360051049043076
761,360051049043076
Fizz,360051049043076
763,360051049043076
764,360051049043076
FizzBuzz,360051049043076
766,360051049043076
767,360051049043076
Fizz,360051049043076
769,360051049043076
Buzz,360051049043076
Fizz,360051049043076
772,360051049043076
773,360051049043076
Fizz,360051049043076
Buzz,360051049043076
776,360051049043076
Fizz,360051049043076
778,360051049043076
779,360051049043076
FizzBuzz,360051049043076
781,360051049043076
782,360051049043076
Fizz,360051049043076
784,360051049043076
Buzz,360051049043076
Fizz,360051049043076
787,360051049043076
788,360051049043076
Fizz,360051049043076
Buzz,360051049043076
791,360051049043076
Fizz,360051049043076
793,360051049043076
794,360051049043076
FizzBuzz,360051049043076
796,360051049043076
797,360051049043076
Fizz,360051049043076
799,360051049043076
Buzz,360051049043076
Fizz,360051049043076
802,360051049043076
803,360051049043076
Fizz,360051049043076
Buzz,360051049043076
806,360051049043076
Fizz,360051049043076
808,360051049043076
809,360051049043076
FizzBuzz,360051049043076
811,360051049043076
812,360051049043076
Fizz,360051049043076
814,360051049043076
Buzz,360051049043076
Fizz,360051049043076
817,360051049043076
818,360051049043076
Fizz,360051049043076
Buzz,360051049043076
821,360051049043076
Fizz,360051049043076
823,360051049043076
824,360051049043076
FizzBuzz,360051049043076
826,360051049043076
827,360051049043076
Fizz,360051049043076
829,360051049043076
Buzz,360051049043076
Fizz,360051049043076
832,360051049043076
833,360051049043076
Fizz,360051049043076
Buzz,360051049043076
836,360051049043076
Fizz,360051049043076
838,360051049043076
839,360051049043076
FizzBuzz,360051049043076
841,360051049043076
842,360051049043076
Fizz,360051049043076
844,360051049043076
Buzz,360051049043076
Fizz,360051049043076
847,360051049043076
848,360051049043076
Fizz,360051049043076
Buzz,360051049043076
851,360051049043076
Fizz,360051049043076
853,360051049043076
854,360051049043076
FizzBuzz,360051049043076
856,360051049043076
857,360051049043076
Fizz,360051049043076
859,360051049043076
Buzz,360051049043076
Fizz,360051049043076
862,360051049043076
863,360051049043076
Fizz,360051049043076
Buzz,360051049043076
866,360051049043076
Fizz,360051049043076
868,360051049043076
869,360051049043076
FizzBuzz,360051049043076
871,360051049043076
872,360051049043076
Fizz,360051049043076
874,360051049043076
Buzz,360051049043076
Fizz,360051049043076
877,360051049043076
878,360051049043076
Fizz,360051049043076
Buzz,360051049043076
881,360051049043076
Fizz,360051049043076
883,360051049043076
884,360051049043076
FizzBuzz,360051049043076
886,360051049043076
887,360051049043076
Fizz,360051049043076
889,360051049043076
Buzz,360051049043076
Fizz,360051049043076
892,360051049043076
893,360051049043076
Fizz,360051049043076
Buzz,360051049043076
896,360051049043076
Fizz,360051049043076
898,360051049043076
899,360051049043076
FizzBuzz,360051049043076
901,360051049043076
902,360051049043076
Fizz,360051049043076
904,360051049043076
Buzz,360051049043076
Fizz,360051049043076
907,360051049043076
908,360051049043076
Fizz,360051049043076
Buzz,360051049043076
911,360051049043076
Fizz,360051049043076
913,360051049043076
914,360051049043076
FizzBuzz,360051049043076
916,360051049043076
917,360051049043076
Fizz,360051049043076
919,360051049043076
Buzz,360051049043076
Fizz,360051049043076
922,360051049043076
923,360051049043076
Fizz,360051049043076
Buzz,360051049043076
926,360051049043076
Fizz,360051049043076
928,360051049043076
929,360051049043076
FizzBuzz,360051049043076
931,360051049043076
932,360051049043076
Fizz,360051049043076
934,360051049043076
Buzz,360051049043076
Fizz,360051049043076
937,360051049043076
938,360051049043076
Fizz,360051049043076
Buzz,360051049043076
941,360051049043076
Fizz,360051049043076
943,360051049043076
944,360051049043076
FizzBuzz,360051049043076
946,360051049043076
947,360051049043076
Fizz,360051049043076
949,360051049043076
Buzz,360051049043076
Fizz,360051049043076
952,360051049043076
953,360051049043076
Fizz,360051049043076
Buzz,360051049043076
956,360051049043076
Fizz,360051049043076
958,360051049043076
959,360051049043076
FizzBuzz,360051049043076
961,360051049043076
962,360051049043076
Fizz,360051049043076
964,360051049043076
Buzz,360051049043076
Fizz,360051049043076

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
%%sql
-- Variante. En générant dynamiquement la chaîne.
SELECT coalesce(nullif(concat(if(i % 3 = 0, 'Fizz', ''), if(i % 5 = 0, 'Buzz', '')), ''), i) AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 0

1000 rows affected.

fizzbuzz,token
1,360051049043076
2,360051049043076
Fizz,360051049043076
4,360051049043076
Buzz,360051049043076
Fizz,360051049043076
7,360051049043076
8,360051049043076
Fizz,360051049043076
Buzz,360051049043076
11,360051049043076
Fizz,360051049043076
13,360051049043076
14,360051049043076
FizzBuzz,360051049043076
16,360051049043076
17,360051049043076
Fizz,360051049043076
19,360051049043076
Buzz,360051049043076
Fizz,360051049043076
22,360051049043076
23,360051049043076
Fizz,360051049043076
Buzz,360051049043076
26,360051049043076
Fizz,360051049043076
28,360051049043076
29,360051049043076
FizzBuzz,360051049043076
31,360051049043076
32,360051049043076
Fizz,360051049043076
34,360051049043076
Buzz,360051049043076
Fizz,360051049043076
37,360051049043076
38,360051049043076
Fizz,360051049043076
Buzz,360051049043076
41,360051049043076
Fizz,360051049043076
43,360051049043076
44,360051049043076
FizzBuzz,360051049043076
46,360051049043076
47,360051049043076
Fizz,360051049043076
49,360051049043076
Buzz,360051049043076
Fizz,360051049043076
52,360051049043076
53,360051049043076
Fizz,360051049043076
Buzz,360051049043076
56,360051049043076
Fizz,360051049043076
58,360051049043076
59,360051049043076
FizzBuzz,360051049043076
61,360051049043076
62,360051049043076
Fizz,360051049043076
64,360051049043076
Buzz,360051049043076
Fizz,360051049043076
67,360051049043076
68,360051049043076
Fizz,360051049043076
Buzz,360051049043076
71,360051049043076
Fizz,360051049043076
73,360051049043076
74,360051049043076
FizzBuzz,360051049043076
76,360051049043076
77,360051049043076
Fizz,360051049043076
79,360051049043076
Buzz,360051049043076
Fizz,360051049043076
82,360051049043076
83,360051049043076
Fizz,360051049043076
Buzz,360051049043076
86,360051049043076
Fizz,360051049043076
88,360051049043076
89,360051049043076
FizzBuzz,360051049043076
91,360051049043076
92,360051049043076
Fizz,360051049043076
94,360051049043076
Buzz,360051049043076
Fizz,360051049043076
97,360051049043076
98,360051049043076
Fizz,360051049043076
Buzz,360051049043076
101,360051049043076
Fizz,360051049043076
103,360051049043076
104,360051049043076
FizzBuzz,360051049043076
106,360051049043076
107,360051049043076
Fizz,360051049043076
109,360051049043076
Buzz,360051049043076
Fizz,360051049043076
112,360051049043076
113,360051049043076
Fizz,360051049043076
Buzz,360051049043076
116,360051049043076
Fizz,360051049043076
118,360051049043076
119,360051049043076
FizzBuzz,360051049043076
121,360051049043076
122,360051049043076
Fizz,360051049043076
124,360051049043076
Buzz,360051049043076
Fizz,360051049043076
127,360051049043076
128,360051049043076
Fizz,360051049043076
Buzz,360051049043076
131,360051049043076
Fizz,360051049043076
133,360051049043076
134,360051049043076
FizzBuzz,360051049043076
136,360051049043076
137,360051049043076
Fizz,360051049043076
139,360051049043076
Buzz,360051049043076
Fizz,360051049043076
142,360051049043076
143,360051049043076
Fizz,360051049043076
Buzz,360051049043076
146,360051049043076
Fizz,360051049043076
148,360051049043076
149,360051049043076
FizzBuzz,360051049043076
151,360051049043076
152,360051049043076
Fizz,360051049043076
154,360051049043076
Buzz,360051049043076
Fizz,360051049043076
157,360051049043076
158,360051049043076
Fizz,360051049043076
Buzz,360051049043076
161,360051049043076
Fizz,360051049043076
163,360051049043076
164,360051049043076
FizzBuzz,360051049043076
166,360051049043076
167,360051049043076
Fizz,360051049043076
169,360051049043076
Buzz,360051049043076
Fizz,360051049043076
172,360051049043076
173,360051049043076
Fizz,360051049043076
Buzz,360051049043076
176,360051049043076
Fizz,360051049043076
178,360051049043076
179,360051049043076
FizzBuzz,360051049043076
181,360051049043076
182,360051049043076
Fizz,360051049043076
184,360051049043076
Buzz,360051049043076
Fizz,360051049043076
187,360051049043076
188,360051049043076
Fizz,360051049043076
Buzz,360051049043076
191,360051049043076
Fizz,360051049043076
193,360051049043076
194,360051049043076
FizzBuzz,360051049043076
196,360051049043076
197,360051049043076
Fizz,360051049043076
199,360051049043076
Buzz,360051049043076
Fizz,360051049043076
202,360051049043076
203,360051049043076
Fizz,360051049043076
Buzz,360051049043076
206,360051049043076
Fizz,360051049043076
208,360051049043076
209,360051049043076
FizzBuzz,360051049043076
211,360051049043076
212,360051049043076
Fizz,360051049043076
214,360051049043076
Buzz,360051049043076
Fizz,360051049043076
217,360051049043076
218,360051049043076
Fizz,360051049043076
Buzz,360051049043076
221,360051049043076
Fizz,360051049043076
223,360051049043076
224,360051049043076
FizzBuzz,360051049043076
226,360051049043076
227,360051049043076
Fizz,360051049043076
229,360051049043076
Buzz,360051049043076
Fizz,360051049043076
232,360051049043076
233,360051049043076
Fizz,360051049043076
Buzz,360051049043076
236,360051049043076
Fizz,360051049043076
238,360051049043076
239,360051049043076
FizzBuzz,360051049043076
241,360051049043076
242,360051049043076
Fizz,360051049043076
244,360051049043076
Buzz,360051049043076
Fizz,360051049043076
247,360051049043076
248,360051049043076
Fizz,360051049043076
Buzz,360051049043076
251,360051049043076
Fizz,360051049043076
253,360051049043076
254,360051049043076
FizzBuzz,360051049043076
256,360051049043076
257,360051049043076
Fizz,360051049043076
259,360051049043076
Buzz,360051049043076
Fizz,360051049043076
262,360051049043076
263,360051049043076
Fizz,360051049043076
Buzz,360051049043076
266,360051049043076
Fizz,360051049043076
268,360051049043076
269,360051049043076
FizzBuzz,360051049043076
271,360051049043076
272,360051049043076
Fizz,360051049043076
274,360051049043076
Buzz,360051049043076
Fizz,360051049043076
277,360051049043076
278,360051049043076
Fizz,360051049043076
Buzz,360051049043076
281,360051049043076
Fizz,360051049043076
283,360051049043076
284,360051049043076
FizzBuzz,360051049043076
286,360051049043076
287,360051049043076
Fizz,360051049043076
289,360051049043076
Buzz,360051049043076
Fizz,360051049043076
292,360051049043076
293,360051049043076
Fizz,360051049043076
Buzz,360051049043076
296,360051049043076
Fizz,360051049043076
298,360051049043076
299,360051049043076
FizzBuzz,360051049043076
301,360051049043076
302,360051049043076
Fizz,360051049043076
304,360051049043076
Buzz,360051049043076
Fizz,360051049043076
307,360051049043076
308,360051049043076
Fizz,360051049043076
Buzz,360051049043076
311,360051049043076
Fizz,360051049043076
313,360051049043076
314,360051049043076
FizzBuzz,360051049043076
316,360051049043076
317,360051049043076
Fizz,360051049043076
319,360051049043076
Buzz,360051049043076
Fizz,360051049043076
322,360051049043076
323,360051049043076
Fizz,360051049043076
Buzz,360051049043076
326,360051049043076
Fizz,360051049043076
328,360051049043076
329,360051049043076
FizzBuzz,360051049043076
331,360051049043076
332,360051049043076
Fizz,360051049043076
334,360051049043076
Buzz,360051049043076
Fizz,360051049043076
337,360051049043076
338,360051049043076
Fizz,360051049043076
Buzz,360051049043076
341,360051049043076
Fizz,360051049043076
343,360051049043076
344,360051049043076
FizzBuzz,360051049043076
346,360051049043076
347,360051049043076
Fizz,360051049043076
349,360051049043076
Buzz,360051049043076
Fizz,360051049043076
352,360051049043076
353,360051049043076
Fizz,360051049043076
Buzz,360051049043076
356,360051049043076
Fizz,360051049043076
358,360051049043076
359,360051049043076
FizzBuzz,360051049043076
361,360051049043076
362,360051049043076
Fizz,360051049043076
364,360051049043076
Buzz,360051049043076
Fizz,360051049043076
367,360051049043076
368,360051049043076
Fizz,360051049043076
Buzz,360051049043076
371,360051049043076
Fizz,360051049043076
373,360051049043076
374,360051049043076
FizzBuzz,360051049043076
376,360051049043076
377,360051049043076
Fizz,360051049043076
379,360051049043076
Buzz,360051049043076
Fizz,360051049043076
382,360051049043076
383,360051049043076
Fizz,360051049043076
Buzz,360051049043076
386,360051049043076
Fizz,360051049043076
388,360051049043076
389,360051049043076
FizzBuzz,360051049043076
391,360051049043076
392,360051049043076
Fizz,360051049043076
394,360051049043076
Buzz,360051049043076
Fizz,360051049043076
397,360051049043076
398,360051049043076
Fizz,360051049043076
Buzz,360051049043076
401,360051049043076
Fizz,360051049043076
403,360051049043076
404,360051049043076
FizzBuzz,360051049043076
406,360051049043076
407,360051049043076
Fizz,360051049043076
409,360051049043076
Buzz,360051049043076
Fizz,360051049043076
412,360051049043076
413,360051049043076
Fizz,360051049043076
Buzz,360051049043076
416,360051049043076
Fizz,360051049043076
418,360051049043076
419,360051049043076
FizzBuzz,360051049043076
421,360051049043076
422,360051049043076
Fizz,360051049043076
424,360051049043076
Buzz,360051049043076
Fizz,360051049043076
427,360051049043076
428,360051049043076
Fizz,360051049043076
Buzz,360051049043076
431,360051049043076
Fizz,360051049043076
433,360051049043076
434,360051049043076
FizzBuzz,360051049043076
436,360051049043076
437,360051049043076
Fizz,360051049043076
439,360051049043076
Buzz,360051049043076
Fizz,360051049043076
442,360051049043076
443,360051049043076
Fizz,360051049043076
Buzz,360051049043076
446,360051049043076
Fizz,360051049043076
448,360051049043076
449,360051049043076
FizzBuzz,360051049043076
451,360051049043076
452,360051049043076
Fizz,360051049043076
454,360051049043076
Buzz,360051049043076
Fizz,360051049043076
457,360051049043076
458,360051049043076
Fizz,360051049043076
Buzz,360051049043076
461,360051049043076
Fizz,360051049043076
463,360051049043076
464,360051049043076
FizzBuzz,360051049043076
466,360051049043076
467,360051049043076
Fizz,360051049043076
469,360051049043076
Buzz,360051049043076
Fizz,360051049043076
472,360051049043076
473,360051049043076
Fizz,360051049043076
Buzz,360051049043076
476,360051049043076
Fizz,360051049043076
478,360051049043076
479,360051049043076
FizzBuzz,360051049043076
481,360051049043076
482,360051049043076
Fizz,360051049043076
484,360051049043076
Buzz,360051049043076
Fizz,360051049043076
487,360051049043076
488,360051049043076
Fizz,360051049043076
Buzz,360051049043076
491,360051049043076
Fizz,360051049043076
493,360051049043076
494,360051049043076
FizzBuzz,360051049043076
496,360051049043076
497,360051049043076
Fizz,360051049043076
499,360051049043076
Buzz,360051049043076
Fizz,360051049043076
502,360051049043076
503,360051049043076
Fizz,360051049043076
Buzz,360051049043076
506,360051049043076
Fizz,360051049043076
508,360051049043076
509,360051049043076
FizzBuzz,360051049043076
511,360051049043076
512,360051049043076
Fizz,360051049043076
514,360051049043076
Buzz,360051049043076
Fizz,360051049043076
517,360051049043076
518,360051049043076
Fizz,360051049043076
Buzz,360051049043076
521,360051049043076
Fizz,360051049043076
523,360051049043076
524,360051049043076
FizzBuzz,360051049043076
526,360051049043076
527,360051049043076
Fizz,360051049043076
529,360051049043076
Buzz,360051049043076
Fizz,360051049043076
532,360051049043076
533,360051049043076
Fizz,360051049043076
Buzz,360051049043076
536,360051049043076
Fizz,360051049043076
538,360051049043076
539,360051049043076
FizzBuzz,360051049043076
541,360051049043076
542,360051049043076
Fizz,360051049043076
544,360051049043076
Buzz,360051049043076
Fizz,360051049043076
547,360051049043076
548,360051049043076
Fizz,360051049043076
Buzz,360051049043076
551,360051049043076
Fizz,360051049043076
553,360051049043076
554,360051049043076
FizzBuzz,360051049043076
556,360051049043076
557,360051049043076
Fizz,360051049043076
559,360051049043076
Buzz,360051049043076
Fizz,360051049043076
562,360051049043076
563,360051049043076
Fizz,360051049043076
Buzz,360051049043076
566,360051049043076
Fizz,360051049043076
568,360051049043076
569,360051049043076
FizzBuzz,360051049043076
571,360051049043076
572,360051049043076
Fizz,360051049043076
574,360051049043076
Buzz,360051049043076
Fizz,360051049043076
577,360051049043076
578,360051049043076
Fizz,360051049043076
Buzz,360051049043076
581,360051049043076
Fizz,360051049043076
583,360051049043076
584,360051049043076
FizzBuzz,360051049043076
586,360051049043076
587,360051049043076
Fizz,360051049043076
589,360051049043076
Buzz,360051049043076
Fizz,360051049043076
592,360051049043076
593,360051049043076
Fizz,360051049043076
Buzz,360051049043076
596,360051049043076
Fizz,360051049043076
598,360051049043076
599,360051049043076
FizzBuzz,360051049043076
601,360051049043076
602,360051049043076
Fizz,360051049043076
604,360051049043076
Buzz,360051049043076
Fizz,360051049043076
607,360051049043076
608,360051049043076
Fizz,360051049043076
Buzz,360051049043076
611,360051049043076
Fizz,360051049043076
613,360051049043076
614,360051049043076
FizzBuzz,360051049043076
616,360051049043076
617,360051049043076
Fizz,360051049043076
619,360051049043076
Buzz,360051049043076
Fizz,360051049043076
622,360051049043076
623,360051049043076
Fizz,360051049043076
Buzz,360051049043076
626,360051049043076
Fizz,360051049043076
628,360051049043076
629,360051049043076
FizzBuzz,360051049043076
631,360051049043076
632,360051049043076
Fizz,360051049043076
634,360051049043076
Buzz,360051049043076
Fizz,360051049043076
637,360051049043076
638,360051049043076
Fizz,360051049043076
Buzz,360051049043076
641,360051049043076
Fizz,360051049043076
643,360051049043076
644,360051049043076
FizzBuzz,360051049043076
646,360051049043076
647,360051049043076
Fizz,360051049043076
649,360051049043076
Buzz,360051049043076
Fizz,360051049043076
652,360051049043076
653,360051049043076
Fizz,360051049043076
Buzz,360051049043076
656,360051049043076
Fizz,360051049043076
658,360051049043076
659,360051049043076
FizzBuzz,360051049043076
661,360051049043076
662,360051049043076
Fizz,360051049043076
664,360051049043076
Buzz,360051049043076
Fizz,360051049043076
667,360051049043076
668,360051049043076
Fizz,360051049043076
Buzz,360051049043076
671,360051049043076
Fizz,360051049043076
673,360051049043076
674,360051049043076
FizzBuzz,360051049043076
676,360051049043076
677,360051049043076
Fizz,360051049043076
679,360051049043076
Buzz,360051049043076
Fizz,360051049043076
682,360051049043076
683,360051049043076
Fizz,360051049043076
Buzz,360051049043076
686,360051049043076
Fizz,360051049043076
688,360051049043076
689,360051049043076
FizzBuzz,360051049043076
691,360051049043076
692,360051049043076
Fizz,360051049043076
694,360051049043076
Buzz,360051049043076
Fizz,360051049043076
697,360051049043076
698,360051049043076
Fizz,360051049043076
Buzz,360051049043076
701,360051049043076
Fizz,360051049043076
703,360051049043076
704,360051049043076
FizzBuzz,360051049043076
706,360051049043076
707,360051049043076
Fizz,360051049043076
709,360051049043076
Buzz,360051049043076
Fizz,360051049043076
712,360051049043076
713,360051049043076
Fizz,360051049043076
Buzz,360051049043076
716,360051049043076
Fizz,360051049043076
718,360051049043076
719,360051049043076
FizzBuzz,360051049043076
721,360051049043076
722,360051049043076
Fizz,360051049043076
724,360051049043076
Buzz,360051049043076
Fizz,360051049043076
727,360051049043076
728,360051049043076
Fizz,360051049043076
Buzz,360051049043076
731,360051049043076
Fizz,360051049043076
733,360051049043076
734,360051049043076
FizzBuzz,360051049043076
736,360051049043076
737,360051049043076
Fizz,360051049043076
739,360051049043076
Buzz,360051049043076
Fizz,360051049043076
742,360051049043076
743,360051049043076
Fizz,360051049043076
Buzz,360051049043076
746,360051049043076
Fizz,360051049043076
748,360051049043076
749,360051049043076
FizzBuzz,360051049043076
751,360051049043076
752,360051049043076
Fizz,360051049043076
754,360051049043076
Buzz,360051049043076
Fizz,360051049043076
757,360051049043076
758,360051049043076
Fizz,360051049043076
Buzz,360051049043076
761,360051049043076
Fizz,360051049043076
763,360051049043076
764,360051049043076
FizzBuzz,360051049043076
766,360051049043076
767,360051049043076
Fizz,360051049043076
769,360051049043076
Buzz,360051049043076
Fizz,360051049043076
772,360051049043076
773,360051049043076
Fizz,360051049043076
Buzz,360051049043076
776,360051049043076
Fizz,360051049043076
778,360051049043076
779,360051049043076
FizzBuzz,360051049043076
781,360051049043076
782,360051049043076
Fizz,360051049043076
784,360051049043076
Buzz,360051049043076
Fizz,360051049043076
787,360051049043076
788,360051049043076
Fizz,360051049043076
Buzz,360051049043076
791,360051049043076
Fizz,360051049043076
793,360051049043076
794,360051049043076
FizzBuzz,360051049043076
796,360051049043076
797,360051049043076
Fizz,360051049043076
799,360051049043076
Buzz,360051049043076
Fizz,360051049043076
802,360051049043076
803,360051049043076
Fizz,360051049043076
Buzz,360051049043076
806,360051049043076
Fizz,360051049043076
808,360051049043076
809,360051049043076
FizzBuzz,360051049043076
811,360051049043076
812,360051049043076
Fizz,360051049043076
814,360051049043076
Buzz,360051049043076
Fizz,360051049043076
817,360051049043076
818,360051049043076
Fizz,360051049043076
Buzz,360051049043076
821,360051049043076
Fizz,360051049043076
823,360051049043076
824,360051049043076
FizzBuzz,360051049043076
826,360051049043076
827,360051049043076
Fizz,360051049043076
829,360051049043076
Buzz,360051049043076
Fizz,360051049043076
832,360051049043076
833,360051049043076
Fizz,360051049043076
Buzz,360051049043076
836,360051049043076
Fizz,360051049043076
838,360051049043076
839,360051049043076
FizzBuzz,360051049043076
841,360051049043076
842,360051049043076
Fizz,360051049043076
844,360051049043076
Buzz,360051049043076
Fizz,360051049043076
847,360051049043076
848,360051049043076
Fizz,360051049043076
Buzz,360051049043076
851,360051049043076
Fizz,360051049043076
853,360051049043076
854,360051049043076
FizzBuzz,360051049043076
856,360051049043076
857,360051049043076
Fizz,360051049043076
859,360051049043076
Buzz,360051049043076
Fizz,360051049043076
862,360051049043076
863,360051049043076
Fizz,360051049043076
Buzz,360051049043076
866,360051049043076
Fizz,360051049043076
868,360051049043076
869,360051049043076
FizzBuzz,360051049043076
871,360051049043076
872,360051049043076
Fizz,360051049043076
874,360051049043076
Buzz,360051049043076
Fizz,360051049043076
877,360051049043076
878,360051049043076
Fizz,360051049043076
Buzz,360051049043076
881,360051049043076
Fizz,360051049043076
883,360051049043076
884,360051049043076
FizzBuzz,360051049043076
886,360051049043076
887,360051049043076
Fizz,360051049043076
889,360051049043076
Buzz,360051049043076
Fizz,360051049043076
892,360051049043076
893,360051049043076
Fizz,360051049043076
Buzz,360051049043076
896,360051049043076
Fizz,360051049043076
898,360051049043076
899,360051049043076
FizzBuzz,360051049043076
901,360051049043076
902,360051049043076
Fizz,360051049043076
904,360051049043076
Buzz,360051049043076
Fizz,360051049043076
907,360051049043076
908,360051049043076
Fizz,360051049043076
Buzz,360051049043076
911,360051049043076
Fizz,360051049043076
913,360051049043076
914,360051049043076
FizzBuzz,360051049043076
916,360051049043076
917,360051049043076
Fizz,360051049043076
919,360051049043076
Buzz,360051049043076
Fizz,360051049043076
922,360051049043076
923,360051049043076
Fizz,360051049043076
Buzz,360051049043076
926,360051049043076
Fizz,360051049043076
928,360051049043076
929,360051049043076
FizzBuzz,360051049043076
931,360051049043076
932,360051049043076
Fizz,360051049043076
934,360051049043076
Buzz,360051049043076
Fizz,360051049043076
937,360051049043076
938,360051049043076
Fizz,360051049043076
Buzz,360051049043076
941,360051049043076
Fizz,360051049043076
943,360051049043076
944,360051049043076
FizzBuzz,360051049043076
946,360051049043076
947,360051049043076
Fizz,360051049043076
949,360051049043076
Buzz,360051049043076
Fizz,360051049043076
952,360051049043076
953,360051049043076
Fizz,360051049043076
Buzz,360051049043076
956,360051049043076
Fizz,360051049043076
958,360051049043076
959,360051049043076
FizzBuzz,360051049043076
961,360051049043076
962,360051049043076
Fizz,360051049043076
964,360051049043076
Buzz,360051049043076
Fizz,360051049043076

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = '8.fizz.buzz.11.fizz.13.14.fizzbuzz'

In [ ]:
%%sql
-- Indication. La véritable suite FizzBuzz™️ commence à 1.
SELECT CASE
           WHEN i % 15 = 0 THEN 'FizzBuzz'
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 5 = 0 THEN 'Buzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints

1001 rows affected.

fizzbuzz,token
FizzBuzz,360247014033845
1,360247014033845
2,360247014033845
Fizz,360247014033845
4,360247014033845
Buzz,360247014033845
Fizz,360247014033845
7,360247014033845
8,360247014033845
Fizz,360247014033845
Buzz,360247014033845
11,360247014033845
Fizz,360247014033845
13,360247014033845
14,360247014033845
FizzBuzz,360247014033845
16,360247014033845
17,360247014033845
Fizz,360247014033845
19,360247014033845
Buzz,360247014033845
Fizz,360247014033845
22,360247014033845
23,360247014033845
Fizz,360247014033845
Buzz,360247014033845
26,360247014033845
Fizz,360247014033845
28,360247014033845
29,360247014033845
FizzBuzz,360247014033845
31,360247014033845
32,360247014033845
Fizz,360247014033845
34,360247014033845
Buzz,360247014033845
Fizz,360247014033845
37,360247014033845
38,360247014033845
Fizz,360247014033845
Buzz,360247014033845
41,360247014033845
Fizz,360247014033845
43,360247014033845
44,360247014033845
FizzBuzz,360247014033845
46,360247014033845
47,360247014033845
Fizz,360247014033845
49,360247014033845
Buzz,360247014033845
Fizz,360247014033845
52,360247014033845
53,360247014033845
Fizz,360247014033845
Buzz,360247014033845
56,360247014033845
Fizz,360247014033845
58,360247014033845
59,360247014033845
FizzBuzz,360247014033845
61,360247014033845
62,360247014033845
Fizz,360247014033845
64,360247014033845
Buzz,360247014033845
Fizz,360247014033845
67,360247014033845
68,360247014033845
Fizz,360247014033845
Buzz,360247014033845
71,360247014033845
Fizz,360247014033845
73,360247014033845
74,360247014033845
FizzBuzz,360247014033845
76,360247014033845
77,360247014033845
Fizz,360247014033845
79,360247014033845
Buzz,360247014033845
Fizz,360247014033845
82,360247014033845
83,360247014033845
Fizz,360247014033845
Buzz,360247014033845
86,360247014033845
Fizz,360247014033845
88,360247014033845
89,360247014033845
FizzBuzz,360247014033845
91,360247014033845
92,360247014033845
Fizz,360247014033845
94,360247014033845
Buzz,360247014033845
Fizz,360247014033845
97,360247014033845
98,360247014033845
Fizz,360247014033845
Buzz,360247014033845
101,360247014033845
Fizz,360247014033845
103,360247014033845
104,360247014033845
FizzBuzz,360247014033845
106,360247014033845
107,360247014033845
Fizz,360247014033845
109,360247014033845
Buzz,360247014033845
Fizz,360247014033845
112,360247014033845
113,360247014033845
Fizz,360247014033845
Buzz,360247014033845
116,360247014033845
Fizz,360247014033845
118,360247014033845
119,360247014033845
FizzBuzz,360247014033845
121,360247014033845
122,360247014033845
Fizz,360247014033845
124,360247014033845
Buzz,360247014033845
Fizz,360247014033845
127,360247014033845
128,360247014033845
Fizz,360247014033845
Buzz,360247014033845
131,360247014033845
Fizz,360247014033845
133,360247014033845
134,360247014033845
FizzBuzz,360247014033845
136,360247014033845
137,360247014033845
Fizz,360247014033845
139,360247014033845
Buzz,360247014033845
Fizz,360247014033845
142,360247014033845
143,360247014033845
Fizz,360247014033845
Buzz,360247014033845
146,360247014033845
Fizz,360247014033845
148,360247014033845
149,360247014033845
FizzBuzz,360247014033845
151,360247014033845
152,360247014033845
Fizz,360247014033845
154,360247014033845
Buzz,360247014033845
Fizz,360247014033845
157,360247014033845
158,360247014033845
Fizz,360247014033845
Buzz,360247014033845
161,360247014033845
Fizz,360247014033845
163,360247014033845
164,360247014033845
FizzBuzz,360247014033845
166,360247014033845
167,360247014033845
Fizz,360247014033845
169,360247014033845
Buzz,360247014033845
Fizz,360247014033845
172,360247014033845
173,360247014033845
Fizz,360247014033845
Buzz,360247014033845
176,360247014033845
Fizz,360247014033845
178,360247014033845
179,360247014033845
FizzBuzz,360247014033845
181,360247014033845
182,360247014033845
Fizz,360247014033845
184,360247014033845
Buzz,360247014033845
Fizz,360247014033845
187,360247014033845
188,360247014033845
Fizz,360247014033845
Buzz,360247014033845
191,360247014033845
Fizz,360247014033845
193,360247014033845
194,360247014033845
FizzBuzz,360247014033845
196,360247014033845
197,360247014033845
Fizz,360247014033845
199,360247014033845
Buzz,360247014033845
Fizz,360247014033845
202,360247014033845
203,360247014033845
Fizz,360247014033845
Buzz,360247014033845
206,360247014033845
Fizz,360247014033845
208,360247014033845
209,360247014033845
FizzBuzz,360247014033845
211,360247014033845
212,360247014033845
Fizz,360247014033845
214,360247014033845
Buzz,360247014033845
Fizz,360247014033845
217,360247014033845
218,360247014033845
Fizz,360247014033845
Buzz,360247014033845
221,360247014033845
Fizz,360247014033845
223,360247014033845
224,360247014033845
FizzBuzz,360247014033845
226,360247014033845
227,360247014033845
Fizz,360247014033845
229,360247014033845
Buzz,360247014033845
Fizz,360247014033845
232,360247014033845
233,360247014033845
Fizz,360247014033845
Buzz,360247014033845
236,360247014033845
Fizz,360247014033845
238,360247014033845
239,360247014033845
FizzBuzz,360247014033845
241,360247014033845
242,360247014033845
Fizz,360247014033845
244,360247014033845
Buzz,360247014033845
Fizz,360247014033845
247,360247014033845
248,360247014033845
Fizz,360247014033845
Buzz,360247014033845
251,360247014033845
Fizz,360247014033845
253,360247014033845
254,360247014033845
FizzBuzz,360247014033845
256,360247014033845
257,360247014033845
Fizz,360247014033845
259,360247014033845
Buzz,360247014033845
Fizz,360247014033845
262,360247014033845
263,360247014033845
Fizz,360247014033845
Buzz,360247014033845
266,360247014033845
Fizz,360247014033845
268,360247014033845
269,360247014033845
FizzBuzz,360247014033845
271,360247014033845
272,360247014033845
Fizz,360247014033845
274,360247014033845
Buzz,360247014033845
Fizz,360247014033845
277,360247014033845
278,360247014033845
Fizz,360247014033845
Buzz,360247014033845
281,360247014033845
Fizz,360247014033845
283,360247014033845
284,360247014033845
FizzBuzz,360247014033845
286,360247014033845
287,360247014033845
Fizz,360247014033845
289,360247014033845
Buzz,360247014033845
Fizz,360247014033845
292,360247014033845
293,360247014033845
Fizz,360247014033845
Buzz,360247014033845
296,360247014033845
Fizz,360247014033845
298,360247014033845
299,360247014033845
FizzBuzz,360247014033845
301,360247014033845
302,360247014033845
Fizz,360247014033845
304,360247014033845
Buzz,360247014033845
Fizz,360247014033845
307,360247014033845
308,360247014033845
Fizz,360247014033845
Buzz,360247014033845
311,360247014033845
Fizz,360247014033845
313,360247014033845
314,360247014033845
FizzBuzz,360247014033845
316,360247014033845
317,360247014033845
Fizz,360247014033845
319,360247014033845
Buzz,360247014033845
Fizz,360247014033845
322,360247014033845
323,360247014033845
Fizz,360247014033845
Buzz,360247014033845
326,360247014033845
Fizz,360247014033845
328,360247014033845
329,360247014033845
FizzBuzz,360247014033845
331,360247014033845
332,360247014033845
Fizz,360247014033845
334,360247014033845
Buzz,360247014033845
Fizz,360247014033845
337,360247014033845
338,360247014033845
Fizz,360247014033845
Buzz,360247014033845
341,360247014033845
Fizz,360247014033845
343,360247014033845
344,360247014033845
FizzBuzz,360247014033845
346,360247014033845
347,360247014033845
Fizz,360247014033845
349,360247014033845
Buzz,360247014033845
Fizz,360247014033845
352,360247014033845
353,360247014033845
Fizz,360247014033845
Buzz,360247014033845
356,360247014033845
Fizz,360247014033845
358,360247014033845
359,360247014033845
FizzBuzz,360247014033845
361,360247014033845
362,360247014033845
Fizz,360247014033845
364,360247014033845
Buzz,360247014033845
Fizz,360247014033845
367,360247014033845
368,360247014033845
Fizz,360247014033845
Buzz,360247014033845
371,360247014033845
Fizz,360247014033845
373,360247014033845
374,360247014033845
FizzBuzz,360247014033845
376,360247014033845
377,360247014033845
Fizz,360247014033845
379,360247014033845
Buzz,360247014033845
Fizz,360247014033845
382,360247014033845
383,360247014033845
Fizz,360247014033845
Buzz,360247014033845
386,360247014033845
Fizz,360247014033845
388,360247014033845
389,360247014033845
FizzBuzz,360247014033845
391,360247014033845
392,360247014033845
Fizz,360247014033845
394,360247014033845
Buzz,360247014033845
Fizz,360247014033845
397,360247014033845
398,360247014033845
Fizz,360247014033845
Buzz,360247014033845
401,360247014033845
Fizz,360247014033845
403,360247014033845
404,360247014033845
FizzBuzz,360247014033845
406,360247014033845
407,360247014033845
Fizz,360247014033845
409,360247014033845
Buzz,360247014033845
Fizz,360247014033845
412,360247014033845
413,360247014033845
Fizz,360247014033845
Buzz,360247014033845
416,360247014033845
Fizz,360247014033845
418,360247014033845
419,360247014033845
FizzBuzz,360247014033845
421,360247014033845
422,360247014033845
Fizz,360247014033845
424,360247014033845
Buzz,360247014033845
Fizz,360247014033845
427,360247014033845
428,360247014033845
Fizz,360247014033845
Buzz,360247014033845
431,360247014033845
Fizz,360247014033845
433,360247014033845
434,360247014033845
FizzBuzz,360247014033845
436,360247014033845
437,360247014033845
Fizz,360247014033845
439,360247014033845
Buzz,360247014033845
Fizz,360247014033845
442,360247014033845
443,360247014033845
Fizz,360247014033845
Buzz,360247014033845
446,360247014033845
Fizz,360247014033845
448,360247014033845
449,360247014033845
FizzBuzz,360247014033845
451,360247014033845
452,360247014033845
Fizz,360247014033845
454,360247014033845
Buzz,360247014033845
Fizz,360247014033845
457,360247014033845
458,360247014033845
Fizz,360247014033845
Buzz,360247014033845
461,360247014033845
Fizz,360247014033845
463,360247014033845
464,360247014033845
FizzBuzz,360247014033845
466,360247014033845
467,360247014033845
Fizz,360247014033845
469,360247014033845
Buzz,360247014033845
Fizz,360247014033845
472,360247014033845
473,360247014033845
Fizz,360247014033845
Buzz,360247014033845
476,360247014033845
Fizz,360247014033845
478,360247014033845
479,360247014033845
FizzBuzz,360247014033845
481,360247014033845
482,360247014033845
Fizz,360247014033845
484,360247014033845
Buzz,360247014033845
Fizz,360247014033845
487,360247014033845
488,360247014033845
Fizz,360247014033845
Buzz,360247014033845
491,360247014033845
Fizz,360247014033845
493,360247014033845
494,360247014033845
FizzBuzz,360247014033845
496,360247014033845
497,360247014033845
Fizz,360247014033845
499,360247014033845
Buzz,360247014033845
Fizz,360247014033845
502,360247014033845
503,360247014033845
Fizz,360247014033845
Buzz,360247014033845
506,360247014033845
Fizz,360247014033845
508,360247014033845
509,360247014033845
FizzBuzz,360247014033845
511,360247014033845
512,360247014033845
Fizz,360247014033845
514,360247014033845
Buzz,360247014033845
Fizz,360247014033845
517,360247014033845
518,360247014033845
Fizz,360247014033845
Buzz,360247014033845
521,360247014033845
Fizz,360247014033845
523,360247014033845
524,360247014033845
FizzBuzz,360247014033845
526,360247014033845
527,360247014033845
Fizz,360247014033845
529,360247014033845
Buzz,360247014033845
Fizz,360247014033845
532,360247014033845
533,360247014033845
Fizz,360247014033845
Buzz,360247014033845
536,360247014033845
Fizz,360247014033845
538,360247014033845
539,360247014033845
FizzBuzz,360247014033845
541,360247014033845
542,360247014033845
Fizz,360247014033845
544,360247014033845
Buzz,360247014033845
Fizz,360247014033845
547,360247014033845
548,360247014033845
Fizz,360247014033845
Buzz,360247014033845
551,360247014033845
Fizz,360247014033845
553,360247014033845
554,360247014033845
FizzBuzz,360247014033845
556,360247014033845
557,360247014033845
Fizz,360247014033845
559,360247014033845
Buzz,360247014033845
Fizz,360247014033845
562,360247014033845
563,360247014033845
Fizz,360247014033845
Buzz,360247014033845
566,360247014033845
Fizz,360247014033845
568,360247014033845
569,360247014033845
FizzBuzz,360247014033845
571,360247014033845
572,360247014033845
Fizz,360247014033845
574,360247014033845
Buzz,360247014033845
Fizz,360247014033845
577,360247014033845
578,360247014033845
Fizz,360247014033845
Buzz,360247014033845
581,360247014033845
Fizz,360247014033845
583,360247014033845
584,360247014033845
FizzBuzz,360247014033845
586,360247014033845
587,360247014033845
Fizz,360247014033845
589,360247014033845
Buzz,360247014033845
Fizz,360247014033845
592,360247014033845
593,360247014033845
Fizz,360247014033845
Buzz,360247014033845
596,360247014033845
Fizz,360247014033845
598,360247014033845
599,360247014033845
FizzBuzz,360247014033845
601,360247014033845
602,360247014033845
Fizz,360247014033845
604,360247014033845
Buzz,360247014033845
Fizz,360247014033845
607,360247014033845
608,360247014033845
Fizz,360247014033845
Buzz,360247014033845
611,360247014033845
Fizz,360247014033845
613,360247014033845
614,360247014033845
FizzBuzz,360247014033845
616,360247014033845
617,360247014033845
Fizz,360247014033845
619,360247014033845
Buzz,360247014033845
Fizz,360247014033845
622,360247014033845
623,360247014033845
Fizz,360247014033845
Buzz,360247014033845
626,360247014033845
Fizz,360247014033845
628,360247014033845
629,360247014033845
FizzBuzz,360247014033845
631,360247014033845
632,360247014033845
Fizz,360247014033845
634,360247014033845
Buzz,360247014033845
Fizz,360247014033845
637,360247014033845
638,360247014033845
Fizz,360247014033845
Buzz,360247014033845
641,360247014033845
Fizz,360247014033845
643,360247014033845
644,360247014033845
FizzBuzz,360247014033845
646,360247014033845
647,360247014033845
Fizz,360247014033845
649,360247014033845
Buzz,360247014033845
Fizz,360247014033845
652,360247014033845
653,360247014033845
Fizz,360247014033845
Buzz,360247014033845
656,360247014033845
Fizz,360247014033845
658,360247014033845
659,360247014033845
FizzBuzz,360247014033845
661,360247014033845
662,360247014033845
Fizz,360247014033845
664,360247014033845
Buzz,360247014033845
Fizz,360247014033845
667,360247014033845
668,360247014033845
Fizz,360247014033845
Buzz,360247014033845
671,360247014033845
Fizz,360247014033845
673,360247014033845
674,360247014033845
FizzBuzz,360247014033845
676,360247014033845
677,360247014033845
Fizz,360247014033845
679,360247014033845
Buzz,360247014033845
Fizz,360247014033845
682,360247014033845
683,360247014033845
Fizz,360247014033845
Buzz,360247014033845
686,360247014033845
Fizz,360247014033845
688,360247014033845
689,360247014033845
FizzBuzz,360247014033845
691,360247014033845
692,360247014033845
Fizz,360247014033845
694,360247014033845
Buzz,360247014033845
Fizz,360247014033845
697,360247014033845
698,360247014033845
Fizz,360247014033845
Buzz,360247014033845
701,360247014033845
Fizz,360247014033845
703,360247014033845
704,360247014033845
FizzBuzz,360247014033845
706,360247014033845
707,360247014033845
Fizz,360247014033845
709,360247014033845
Buzz,360247014033845
Fizz,360247014033845
712,360247014033845
713,360247014033845
Fizz,360247014033845
Buzz,360247014033845
716,360247014033845
Fizz,360247014033845
718,360247014033845
719,360247014033845
FizzBuzz,360247014033845
721,360247014033845
722,360247014033845
Fizz,360247014033845
724,360247014033845
Buzz,360247014033845
Fizz,360247014033845
727,360247014033845
728,360247014033845
Fizz,360247014033845
Buzz,360247014033845
731,360247014033845
Fizz,360247014033845
733,360247014033845
734,360247014033845
FizzBuzz,360247014033845
736,360247014033845
737,360247014033845
Fizz,360247014033845
739,360247014033845
Buzz,360247014033845
Fizz,360247014033845
742,360247014033845
743,360247014033845
Fizz,360247014033845
Buzz,360247014033845
746,360247014033845
Fizz,360247014033845
748,360247014033845
749,360247014033845
FizzBuzz,360247014033845
751,360247014033845
752,360247014033845
Fizz,360247014033845
754,360247014033845
Buzz,360247014033845
Fizz,360247014033845
757,360247014033845
758,360247014033845
Fizz,360247014033845
Buzz,360247014033845
761,360247014033845
Fizz,360247014033845
763,360247014033845
764,360247014033845
FizzBuzz,360247014033845
766,360247014033845
767,360247014033845
Fizz,360247014033845
769,360247014033845
Buzz,360247014033845
Fizz,360247014033845
772,360247014033845
773,360247014033845
Fizz,360247014033845
Buzz,360247014033845
776,360247014033845
Fizz,360247014033845
778,360247014033845
779,360247014033845
FizzBuzz,360247014033845
781,360247014033845
782,360247014033845
Fizz,360247014033845
784,360247014033845
Buzz,360247014033845
Fizz,360247014033845
787,360247014033845
788,360247014033845
Fizz,360247014033845
Buzz,360247014033845
791,360247014033845
Fizz,360247014033845
793,360247014033845
794,360247014033845
FizzBuzz,360247014033845
796,360247014033845
797,360247014033845
Fizz,360247014033845
799,360247014033845
Buzz,360247014033845
Fizz,360247014033845
802,360247014033845
803,360247014033845
Fizz,360247014033845
Buzz,360247014033845
806,360247014033845
Fizz,360247014033845
808,360247014033845
809,360247014033845
FizzBuzz,360247014033845
811,360247014033845
812,360247014033845
Fizz,360247014033845
814,360247014033845
Buzz,360247014033845
Fizz,360247014033845
817,360247014033845
818,360247014033845
Fizz,360247014033845
Buzz,360247014033845
821,360247014033845
Fizz,360247014033845
823,360247014033845
824,360247014033845
FizzBuzz,360247014033845
826,360247014033845
827,360247014033845
Fizz,360247014033845
829,360247014033845
Buzz,360247014033845
Fizz,360247014033845
832,360247014033845
833,360247014033845
Fizz,360247014033845
Buzz,360247014033845
836,360247014033845
Fizz,360247014033845
838,360247014033845
839,360247014033845
FizzBuzz,360247014033845
841,360247014033845
842,360247014033845
Fizz,360247014033845
844,360247014033845
Buzz,360247014033845
Fizz,360247014033845
847,360247014033845
848,360247014033845
Fizz,360247014033845
Buzz,360247014033845
851,360247014033845
Fizz,360247014033845
853,360247014033845
854,360247014033845
FizzBuzz,360247014033845
856,360247014033845
857,360247014033845
Fizz,360247014033845
859,360247014033845
Buzz,360247014033845
Fizz,360247014033845
862,360247014033845
863,360247014033845
Fizz,360247014033845
Buzz,360247014033845
866,360247014033845
Fizz,360247014033845
868,360247014033845
869,360247014033845
FizzBuzz,360247014033845
871,360247014033845
872,360247014033845
Fizz,360247014033845
874,360247014033845
Buzz,360247014033845
Fizz,360247014033845
877,360247014033845
878,360247014033845
Fizz,360247014033845
Buzz,360247014033845
881,360247014033845
Fizz,360247014033845
883,360247014033845
884,360247014033845
FizzBuzz,360247014033845
886,360247014033845
887,360247014033845
Fizz,360247014033845
889,360247014033845
Buzz,360247014033845
Fizz,360247014033845
892,360247014033845
893,360247014033845
Fizz,360247014033845
Buzz,360247014033845
896,360247014033845
Fizz,360247014033845
898,360247014033845
899,360247014033845
FizzBuzz,360247014033845
901,360247014033845
902,360247014033845
Fizz,360247014033845
904,360247014033845
Buzz,360247014033845
Fizz,360247014033845
907,360247014033845
908,360247014033845
Fizz,360247014033845
Buzz,360247014033845
911,360247014033845
Fizz,360247014033845
913,360247014033845
914,360247014033845
FizzBuzz,360247014033845
916,360247014033845
917,360247014033845
Fizz,360247014033845
919,360247014033845
Buzz,360247014033845
Fizz,360247014033845
922,360247014033845
923,360247014033845
Fizz,360247014033845
Buzz,360247014033845
926,360247014033845
Fizz,360247014033845
928,360247014033845
929,360247014033845
FizzBuzz,360247014033845
931,360247014033845
932,360247014033845
Fizz,360247014033845
934,360247014033845
Buzz,360247014033845
Fizz,360247014033845
937,360247014033845
938,360247014033845
Fizz,360247014033845
Buzz,360247014033845
941,360247014033845
Fizz,360247014033845
943,360247014033845
944,360247014033845
FizzBuzz,360247014033845
946,360247014033845
947,360247014033845
Fizz,360247014033845
949,360247014033845
Buzz,360247014033845
Fizz,360247014033845
952,360247014033845
953,360247014033845
Fizz,360247014033845
Buzz,360247014033845
956,360247014033845
Fizz,360247014033845
958,360247014033845
959,360247014033845
FizzBuzz,360247014033845
961,360247014033845
962,360247014033845
Fizz,360247014033845
964,360247014033845
Buzz,360247014033845

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = 'buzz.11.fizz.13.14.fizzbuzz.16.17'

In [ ]:
%%sql
-- Indication. La véritable suite FizzBuzz™️ commence à 1.
SELECT CASE
           WHEN i % 15 = 0 THEN 'FizzBuzz'
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 5 = 0 THEN 'Buzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 1

999 rows affected.

fizzbuzz,token
2,359749191076977
Fizz,359749191076977
4,359749191076977
Buzz,359749191076977
Fizz,359749191076977
7,359749191076977
8,359749191076977
Fizz,359749191076977
Buzz,359749191076977
11,359749191076977
Fizz,359749191076977
13,359749191076977
14,359749191076977
FizzBuzz,359749191076977
16,359749191076977
17,359749191076977
Fizz,359749191076977
19,359749191076977
Buzz,359749191076977
Fizz,359749191076977
22,359749191076977
23,359749191076977
Fizz,359749191076977
Buzz,359749191076977
26,359749191076977
Fizz,359749191076977
28,359749191076977
29,359749191076977
FizzBuzz,359749191076977
31,359749191076977
32,359749191076977
Fizz,359749191076977
34,359749191076977
Buzz,359749191076977
Fizz,359749191076977
37,359749191076977
38,359749191076977
Fizz,359749191076977
Buzz,359749191076977
41,359749191076977
Fizz,359749191076977
43,359749191076977
44,359749191076977
FizzBuzz,359749191076977
46,359749191076977
47,359749191076977
Fizz,359749191076977
49,359749191076977
Buzz,359749191076977
Fizz,359749191076977
52,359749191076977
53,359749191076977
Fizz,359749191076977
Buzz,359749191076977
56,359749191076977
Fizz,359749191076977
58,359749191076977
59,359749191076977
FizzBuzz,359749191076977
61,359749191076977
62,359749191076977
Fizz,359749191076977
64,359749191076977
Buzz,359749191076977
Fizz,359749191076977
67,359749191076977
68,359749191076977
Fizz,359749191076977
Buzz,359749191076977
71,359749191076977
Fizz,359749191076977
73,359749191076977
74,359749191076977
FizzBuzz,359749191076977
76,359749191076977
77,359749191076977
Fizz,359749191076977
79,359749191076977
Buzz,359749191076977
Fizz,359749191076977
82,359749191076977
83,359749191076977
Fizz,359749191076977
Buzz,359749191076977
86,359749191076977
Fizz,359749191076977
88,359749191076977
89,359749191076977
FizzBuzz,359749191076977
91,359749191076977
92,359749191076977
Fizz,359749191076977
94,359749191076977
Buzz,359749191076977
Fizz,359749191076977
97,359749191076977
98,359749191076977
Fizz,359749191076977
Buzz,359749191076977
101,359749191076977
Fizz,359749191076977
103,359749191076977
104,359749191076977
FizzBuzz,359749191076977
106,359749191076977
107,359749191076977
Fizz,359749191076977
109,359749191076977
Buzz,359749191076977
Fizz,359749191076977
112,359749191076977
113,359749191076977
Fizz,359749191076977
Buzz,359749191076977
116,359749191076977
Fizz,359749191076977
118,359749191076977
119,359749191076977
FizzBuzz,359749191076977
121,359749191076977
122,359749191076977
Fizz,359749191076977
124,359749191076977
Buzz,359749191076977
Fizz,359749191076977
127,359749191076977
128,359749191076977
Fizz,359749191076977
Buzz,359749191076977
131,359749191076977
Fizz,359749191076977
133,359749191076977
134,359749191076977
FizzBuzz,359749191076977
136,359749191076977
137,359749191076977
Fizz,359749191076977
139,359749191076977
Buzz,359749191076977
Fizz,359749191076977
142,359749191076977
143,359749191076977
Fizz,359749191076977
Buzz,359749191076977
146,359749191076977
Fizz,359749191076977
148,359749191076977
149,359749191076977
FizzBuzz,359749191076977
151,359749191076977
152,359749191076977
Fizz,359749191076977
154,359749191076977
Buzz,359749191076977
Fizz,359749191076977
157,359749191076977
158,359749191076977
Fizz,359749191076977
Buzz,359749191076977
161,359749191076977
Fizz,359749191076977
163,359749191076977
164,359749191076977
FizzBuzz,359749191076977
166,359749191076977
167,359749191076977
Fizz,359749191076977
169,359749191076977
Buzz,359749191076977
Fizz,359749191076977
172,359749191076977
173,359749191076977
Fizz,359749191076977
Buzz,359749191076977
176,359749191076977
Fizz,359749191076977
178,359749191076977
179,359749191076977
FizzBuzz,359749191076977
181,359749191076977
182,359749191076977
Fizz,359749191076977
184,359749191076977
Buzz,359749191076977
Fizz,359749191076977
187,359749191076977
188,359749191076977
Fizz,359749191076977
Buzz,359749191076977
191,359749191076977
Fizz,359749191076977
193,359749191076977
194,359749191076977
FizzBuzz,359749191076977
196,359749191076977
197,359749191076977
Fizz,359749191076977
199,359749191076977
Buzz,359749191076977
Fizz,359749191076977
202,359749191076977
203,359749191076977
Fizz,359749191076977
Buzz,359749191076977
206,359749191076977
Fizz,359749191076977
208,359749191076977
209,359749191076977
FizzBuzz,359749191076977
211,359749191076977
212,359749191076977
Fizz,359749191076977
214,359749191076977
Buzz,359749191076977
Fizz,359749191076977
217,359749191076977
218,359749191076977
Fizz,359749191076977
Buzz,359749191076977
221,359749191076977
Fizz,359749191076977
223,359749191076977
224,359749191076977
FizzBuzz,359749191076977
226,359749191076977
227,359749191076977
Fizz,359749191076977
229,359749191076977
Buzz,359749191076977
Fizz,359749191076977
232,359749191076977
233,359749191076977
Fizz,359749191076977
Buzz,359749191076977
236,359749191076977
Fizz,359749191076977
238,359749191076977
239,359749191076977
FizzBuzz,359749191076977
241,359749191076977
242,359749191076977
Fizz,359749191076977
244,359749191076977
Buzz,359749191076977
Fizz,359749191076977
247,359749191076977
248,359749191076977
Fizz,359749191076977
Buzz,359749191076977
251,359749191076977
Fizz,359749191076977
253,359749191076977
254,359749191076977
FizzBuzz,359749191076977
256,359749191076977
257,359749191076977
Fizz,359749191076977
259,359749191076977
Buzz,359749191076977
Fizz,359749191076977
262,359749191076977
263,359749191076977
Fizz,359749191076977
Buzz,359749191076977
266,359749191076977
Fizz,359749191076977
268,359749191076977
269,359749191076977
FizzBuzz,359749191076977
271,359749191076977
272,359749191076977
Fizz,359749191076977
274,359749191076977
Buzz,359749191076977
Fizz,359749191076977
277,359749191076977
278,359749191076977
Fizz,359749191076977
Buzz,359749191076977
281,359749191076977
Fizz,359749191076977
283,359749191076977
284,359749191076977
FizzBuzz,359749191076977
286,359749191076977
287,359749191076977
Fizz,359749191076977
289,359749191076977
Buzz,359749191076977
Fizz,359749191076977
292,359749191076977
293,359749191076977
Fizz,359749191076977
Buzz,359749191076977
296,359749191076977
Fizz,359749191076977
298,359749191076977
299,359749191076977
FizzBuzz,359749191076977
301,359749191076977
302,359749191076977
Fizz,359749191076977
304,359749191076977
Buzz,359749191076977
Fizz,359749191076977
307,359749191076977
308,359749191076977
Fizz,359749191076977
Buzz,359749191076977
311,359749191076977
Fizz,359749191076977
313,359749191076977
314,359749191076977
FizzBuzz,359749191076977
316,359749191076977
317,359749191076977
Fizz,359749191076977
319,359749191076977
Buzz,359749191076977
Fizz,359749191076977
322,359749191076977
323,359749191076977
Fizz,359749191076977
Buzz,359749191076977
326,359749191076977
Fizz,359749191076977
328,359749191076977
329,359749191076977
FizzBuzz,359749191076977
331,359749191076977
332,359749191076977
Fizz,359749191076977
334,359749191076977
Buzz,359749191076977
Fizz,359749191076977
337,359749191076977
338,359749191076977
Fizz,359749191076977
Buzz,359749191076977
341,359749191076977
Fizz,359749191076977
343,359749191076977
344,359749191076977
FizzBuzz,359749191076977
346,359749191076977
347,359749191076977
Fizz,359749191076977
349,359749191076977
Buzz,359749191076977
Fizz,359749191076977
352,359749191076977
353,359749191076977
Fizz,359749191076977
Buzz,359749191076977
356,359749191076977
Fizz,359749191076977
358,359749191076977
359,359749191076977
FizzBuzz,359749191076977
361,359749191076977
362,359749191076977
Fizz,359749191076977
364,359749191076977
Buzz,359749191076977
Fizz,359749191076977
367,359749191076977
368,359749191076977
Fizz,359749191076977
Buzz,359749191076977
371,359749191076977
Fizz,359749191076977
373,359749191076977
374,359749191076977
FizzBuzz,359749191076977
376,359749191076977
377,359749191076977
Fizz,359749191076977
379,359749191076977
Buzz,359749191076977
Fizz,359749191076977
382,359749191076977
383,359749191076977
Fizz,359749191076977
Buzz,359749191076977
386,359749191076977
Fizz,359749191076977
388,359749191076977
389,359749191076977
FizzBuzz,359749191076977
391,359749191076977
392,359749191076977
Fizz,359749191076977
394,359749191076977
Buzz,359749191076977
Fizz,359749191076977
397,359749191076977
398,359749191076977
Fizz,359749191076977
Buzz,359749191076977
401,359749191076977
Fizz,359749191076977
403,359749191076977
404,359749191076977
FizzBuzz,359749191076977
406,359749191076977
407,359749191076977
Fizz,359749191076977
409,359749191076977
Buzz,359749191076977
Fizz,359749191076977
412,359749191076977
413,359749191076977
Fizz,359749191076977
Buzz,359749191076977
416,359749191076977
Fizz,359749191076977
418,359749191076977
419,359749191076977
FizzBuzz,359749191076977
421,359749191076977
422,359749191076977
Fizz,359749191076977
424,359749191076977
Buzz,359749191076977
Fizz,359749191076977
427,359749191076977
428,359749191076977
Fizz,359749191076977
Buzz,359749191076977
431,359749191076977
Fizz,359749191076977
433,359749191076977
434,359749191076977
FizzBuzz,359749191076977
436,359749191076977
437,359749191076977
Fizz,359749191076977
439,359749191076977
Buzz,359749191076977
Fizz,359749191076977
442,359749191076977
443,359749191076977
Fizz,359749191076977
Buzz,359749191076977
446,359749191076977
Fizz,359749191076977
448,359749191076977
449,359749191076977
FizzBuzz,359749191076977
451,359749191076977
452,359749191076977
Fizz,359749191076977
454,359749191076977
Buzz,359749191076977
Fizz,359749191076977
457,359749191076977
458,359749191076977
Fizz,359749191076977
Buzz,359749191076977
461,359749191076977
Fizz,359749191076977
463,359749191076977
464,359749191076977
FizzBuzz,359749191076977
466,359749191076977
467,359749191076977
Fizz,359749191076977
469,359749191076977
Buzz,359749191076977
Fizz,359749191076977
472,359749191076977
473,359749191076977
Fizz,359749191076977
Buzz,359749191076977
476,359749191076977
Fizz,359749191076977
478,359749191076977
479,359749191076977
FizzBuzz,359749191076977
481,359749191076977
482,359749191076977
Fizz,359749191076977
484,359749191076977
Buzz,359749191076977
Fizz,359749191076977
487,359749191076977
488,359749191076977
Fizz,359749191076977
Buzz,359749191076977
491,359749191076977
Fizz,359749191076977
493,359749191076977
494,359749191076977
FizzBuzz,359749191076977
496,359749191076977
497,359749191076977
Fizz,359749191076977
499,359749191076977
Buzz,359749191076977
Fizz,359749191076977
502,359749191076977
503,359749191076977
Fizz,359749191076977
Buzz,359749191076977
506,359749191076977
Fizz,359749191076977
508,359749191076977
509,359749191076977
FizzBuzz,359749191076977
511,359749191076977
512,359749191076977
Fizz,359749191076977
514,359749191076977
Buzz,359749191076977
Fizz,359749191076977
517,359749191076977
518,359749191076977
Fizz,359749191076977
Buzz,359749191076977
521,359749191076977
Fizz,359749191076977
523,359749191076977
524,359749191076977
FizzBuzz,359749191076977
526,359749191076977
527,359749191076977
Fizz,359749191076977
529,359749191076977
Buzz,359749191076977
Fizz,359749191076977
532,359749191076977
533,359749191076977
Fizz,359749191076977
Buzz,359749191076977
536,359749191076977
Fizz,359749191076977
538,359749191076977
539,359749191076977
FizzBuzz,359749191076977
541,359749191076977
542,359749191076977
Fizz,359749191076977
544,359749191076977
Buzz,359749191076977
Fizz,359749191076977
547,359749191076977
548,359749191076977
Fizz,359749191076977
Buzz,359749191076977
551,359749191076977
Fizz,359749191076977
553,359749191076977
554,359749191076977
FizzBuzz,359749191076977
556,359749191076977
557,359749191076977
Fizz,359749191076977
559,359749191076977
Buzz,359749191076977
Fizz,359749191076977
562,359749191076977
563,359749191076977
Fizz,359749191076977
Buzz,359749191076977
566,359749191076977
Fizz,359749191076977
568,359749191076977
569,359749191076977
FizzBuzz,359749191076977
571,359749191076977
572,359749191076977
Fizz,359749191076977
574,359749191076977
Buzz,359749191076977
Fizz,359749191076977
577,359749191076977
578,359749191076977
Fizz,359749191076977
Buzz,359749191076977
581,359749191076977
Fizz,359749191076977
583,359749191076977
584,359749191076977
FizzBuzz,359749191076977
586,359749191076977
587,359749191076977
Fizz,359749191076977
589,359749191076977
Buzz,359749191076977
Fizz,359749191076977
592,359749191076977
593,359749191076977
Fizz,359749191076977
Buzz,359749191076977
596,359749191076977
Fizz,359749191076977
598,359749191076977
599,359749191076977
FizzBuzz,359749191076977
601,359749191076977
602,359749191076977
Fizz,359749191076977
604,359749191076977
Buzz,359749191076977
Fizz,359749191076977
607,359749191076977
608,359749191076977
Fizz,359749191076977
Buzz,359749191076977
611,359749191076977
Fizz,359749191076977
613,359749191076977
614,359749191076977
FizzBuzz,359749191076977
616,359749191076977
617,359749191076977
Fizz,359749191076977
619,359749191076977
Buzz,359749191076977
Fizz,359749191076977
622,359749191076977
623,359749191076977
Fizz,359749191076977
Buzz,359749191076977
626,359749191076977
Fizz,359749191076977
628,359749191076977
629,359749191076977
FizzBuzz,359749191076977
631,359749191076977
632,359749191076977
Fizz,359749191076977
634,359749191076977
Buzz,359749191076977
Fizz,359749191076977
637,359749191076977
638,359749191076977
Fizz,359749191076977
Buzz,359749191076977
641,359749191076977
Fizz,359749191076977
643,359749191076977
644,359749191076977
FizzBuzz,359749191076977
646,359749191076977
647,359749191076977
Fizz,359749191076977
649,359749191076977
Buzz,359749191076977
Fizz,359749191076977
652,359749191076977
653,359749191076977
Fizz,359749191076977
Buzz,359749191076977
656,359749191076977
Fizz,359749191076977
658,359749191076977
659,359749191076977
FizzBuzz,359749191076977
661,359749191076977
662,359749191076977
Fizz,359749191076977
664,359749191076977
Buzz,359749191076977
Fizz,359749191076977
667,359749191076977
668,359749191076977
Fizz,359749191076977
Buzz,359749191076977
671,359749191076977
Fizz,359749191076977
673,359749191076977
674,359749191076977
FizzBuzz,359749191076977
676,359749191076977
677,359749191076977
Fizz,359749191076977
679,359749191076977
Buzz,359749191076977
Fizz,359749191076977
682,359749191076977
683,359749191076977
Fizz,359749191076977
Buzz,359749191076977
686,359749191076977
Fizz,359749191076977
688,359749191076977
689,359749191076977
FizzBuzz,359749191076977
691,359749191076977
692,359749191076977
Fizz,359749191076977
694,359749191076977
Buzz,359749191076977
Fizz,359749191076977
697,359749191076977
698,359749191076977
Fizz,359749191076977
Buzz,359749191076977
701,359749191076977
Fizz,359749191076977
703,359749191076977
704,359749191076977
FizzBuzz,359749191076977
706,359749191076977
707,359749191076977
Fizz,359749191076977
709,359749191076977
Buzz,359749191076977
Fizz,359749191076977
712,359749191076977
713,359749191076977
Fizz,359749191076977
Buzz,359749191076977
716,359749191076977
Fizz,359749191076977
718,359749191076977
719,359749191076977
FizzBuzz,359749191076977
721,359749191076977
722,359749191076977
Fizz,359749191076977
724,359749191076977
Buzz,359749191076977
Fizz,359749191076977
727,359749191076977
728,359749191076977
Fizz,359749191076977
Buzz,359749191076977
731,359749191076977
Fizz,359749191076977
733,359749191076977
734,359749191076977
FizzBuzz,359749191076977
736,359749191076977
737,359749191076977
Fizz,359749191076977
739,359749191076977
Buzz,359749191076977
Fizz,359749191076977
742,359749191076977
743,359749191076977
Fizz,359749191076977
Buzz,359749191076977
746,359749191076977
Fizz,359749191076977
748,359749191076977
749,359749191076977
FizzBuzz,359749191076977
751,359749191076977
752,359749191076977
Fizz,359749191076977
754,359749191076977
Buzz,359749191076977
Fizz,359749191076977
757,359749191076977
758,359749191076977
Fizz,359749191076977
Buzz,359749191076977
761,359749191076977
Fizz,359749191076977
763,359749191076977
764,359749191076977
FizzBuzz,359749191076977
766,359749191076977
767,359749191076977
Fizz,359749191076977
769,359749191076977
Buzz,359749191076977
Fizz,359749191076977
772,359749191076977
773,359749191076977
Fizz,359749191076977
Buzz,359749191076977
776,359749191076977
Fizz,359749191076977
778,359749191076977
779,359749191076977
FizzBuzz,359749191076977
781,359749191076977
782,359749191076977
Fizz,359749191076977
784,359749191076977
Buzz,359749191076977
Fizz,359749191076977
787,359749191076977
788,359749191076977
Fizz,359749191076977
Buzz,359749191076977
791,359749191076977
Fizz,359749191076977
793,359749191076977
794,359749191076977
FizzBuzz,359749191076977
796,359749191076977
797,359749191076977
Fizz,359749191076977
799,359749191076977
Buzz,359749191076977
Fizz,359749191076977
802,359749191076977
803,359749191076977
Fizz,359749191076977
Buzz,359749191076977
806,359749191076977
Fizz,359749191076977
808,359749191076977
809,359749191076977
FizzBuzz,359749191076977
811,359749191076977
812,359749191076977
Fizz,359749191076977
814,359749191076977
Buzz,359749191076977
Fizz,359749191076977
817,359749191076977
818,359749191076977
Fizz,359749191076977
Buzz,359749191076977
821,359749191076977
Fizz,359749191076977
823,359749191076977
824,359749191076977
FizzBuzz,359749191076977
826,359749191076977
827,359749191076977
Fizz,359749191076977
829,359749191076977
Buzz,359749191076977
Fizz,359749191076977
832,359749191076977
833,359749191076977
Fizz,359749191076977
Buzz,359749191076977
836,359749191076977
Fizz,359749191076977
838,359749191076977
839,359749191076977
FizzBuzz,359749191076977
841,359749191076977
842,359749191076977
Fizz,359749191076977
844,359749191076977
Buzz,359749191076977
Fizz,359749191076977
847,359749191076977
848,359749191076977
Fizz,359749191076977
Buzz,359749191076977
851,359749191076977
Fizz,359749191076977
853,359749191076977
854,359749191076977
FizzBuzz,359749191076977
856,359749191076977
857,359749191076977
Fizz,359749191076977
859,359749191076977
Buzz,359749191076977
Fizz,359749191076977
862,359749191076977
863,359749191076977
Fizz,359749191076977
Buzz,359749191076977
866,359749191076977
Fizz,359749191076977
868,359749191076977
869,359749191076977
FizzBuzz,359749191076977
871,359749191076977
872,359749191076977
Fizz,359749191076977
874,359749191076977
Buzz,359749191076977
Fizz,359749191076977
877,359749191076977
878,359749191076977
Fizz,359749191076977
Buzz,359749191076977
881,359749191076977
Fizz,359749191076977
883,359749191076977
884,359749191076977
FizzBuzz,359749191076977
886,359749191076977
887,359749191076977
Fizz,359749191076977
889,359749191076977
Buzz,359749191076977
Fizz,359749191076977
892,359749191076977
893,359749191076977
Fizz,359749191076977
Buzz,359749191076977
896,359749191076977
Fizz,359749191076977
898,359749191076977
899,359749191076977
FizzBuzz,359749191076977
901,359749191076977
902,359749191076977
Fizz,359749191076977
904,359749191076977
Buzz,359749191076977
Fizz,359749191076977
907,359749191076977
908,359749191076977
Fizz,359749191076977
Buzz,359749191076977
911,359749191076977
Fizz,359749191076977
913,359749191076977
914,359749191076977
FizzBuzz,359749191076977
916,359749191076977
917,359749191076977
Fizz,359749191076977
919,359749191076977
Buzz,359749191076977
Fizz,359749191076977
922,359749191076977
923,359749191076977
Fizz,359749191076977
Buzz,359749191076977
926,359749191076977
Fizz,359749191076977
928,359749191076977
929,359749191076977
FizzBuzz,359749191076977
931,359749191076977
932,359749191076977
Fizz,359749191076977
934,359749191076977
Buzz,359749191076977
Fizz,359749191076977
937,359749191076977
938,359749191076977
Fizz,359749191076977
Buzz,359749191076977
941,359749191076977
Fizz,359749191076977
943,359749191076977
944,359749191076977
FizzBuzz,359749191076977
946,359749191076977
947,359749191076977
Fizz,359749191076977
949,359749191076977
Buzz,359749191076977
Fizz,359749191076977
952,359749191076977
953,359749191076977
Fizz,359749191076977
Buzz,359749191076977
956,359749191076977
Fizz,359749191076977
958,359749191076977
959,359749191076977
FizzBuzz,359749191076977
961,359749191076977
962,359749191076977
Fizz,359749191076977
964,359749191076977
Buzz,359749191076977
Fizz,359749191076977
967,359749191076977

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = "fizz.buzz.11.fizz.13.14.fizz.16"

In [ ]:
%%sql
-- Indication. Avez-vous pensé au fait qu'un nombre divisible par 15 l'est également par 4 et 5 ?
SELECT CASE
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 5 = 0 THEN 'Buzz'
           WHEN i % 15 = 0 THEN 'FizzBuzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 0
LIMIT 20

20 rows affected.

fizzbuzz,token
1,360186567754554
2,360186567754554
Fizz,360186567754554
4,360186567754554
Buzz,360186567754554
Fizz,360186567754554
7,360186567754554
8,360186567754554
Fizz,360186567754554
Buzz,360186567754554
11,360186567754554
Fizz,360186567754554
13,360186567754554
14,360186567754554
Fizz,360186567754554
16,360186567754554
17,360186567754554
Fizz,360186567754554
19,360186567754554
Buzz,360186567754554

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = "fizz.buzz.11.fizz.13.14.buzz.16"

In [ ]:
%%sql
-- Indication. Avez-vous pensé au fait qu'un nombre divisible par 15 l'est également par 4 et 5 ?
SELECT CASE
           WHEN i % 5 = 0 THEN 'Buzz'
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 15 = 0 THEN 'FizzBuzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 0
LIMIT 20

20 rows affected.

fizzbuzz,token
1,359943398969027
2,359943398969027
Fizz,359943398969027
4,359943398969027
Buzz,359943398969027
Fizz,359943398969027
7,359943398969027
8,359943398969027
Fizz,359943398969027
Buzz,359943398969027
11,359943398969027
Fizz,359943398969027
13,359943398969027
14,359943398969027
Buzz,359943398969027
16,359943398969027
17,359943398969027
Fizz,359943398969027
19,359943398969027
Buzz,359943398969027

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = "fizz.buzz.11.fizz.13.14.fizzbuzz.16"

In [ ]:
%%sql
-- Indication. Votre suite comporte un terme de trop.
SELECT CASE
           WHEN (i + 1) % 15 = 0 THEN 'FizzBuzz'
           WHEN (i + 1) % 3 = 0 THEN 'Fizz'
           WHEN (i + 1) % 5 = 0 THEN 'Buzz'
           ELSE (i + 1)
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints

1001 rows affected.

fizzbuzz,token
1,359642314904307
2,359642314904307
Fizz,359642314904307
4,359642314904307
Buzz,359642314904307
Fizz,359642314904307
7,359642314904307
8,359642314904307
Fizz,359642314904307
Buzz,359642314904307
11,359642314904307
Fizz,359642314904307
13,359642314904307
14,359642314904307
FizzBuzz,359642314904307
16,359642314904307
17,359642314904307
Fizz,359642314904307
19,359642314904307
Buzz,359642314904307
Fizz,359642314904307
22,359642314904307
23,359642314904307
Fizz,359642314904307
Buzz,359642314904307
26,359642314904307
Fizz,359642314904307
28,359642314904307
29,359642314904307
FizzBuzz,359642314904307
31,359642314904307
32,359642314904307
Fizz,359642314904307
34,359642314904307
Buzz,359642314904307
Fizz,359642314904307
37,359642314904307
38,359642314904307
Fizz,359642314904307
Buzz,359642314904307
41,359642314904307
Fizz,359642314904307
43,359642314904307
44,359642314904307
FizzBuzz,359642314904307
46,359642314904307
47,359642314904307
Fizz,359642314904307
49,359642314904307
Buzz,359642314904307
Fizz,359642314904307
52,359642314904307
53,359642314904307
Fizz,359642314904307
Buzz,359642314904307
56,359642314904307
Fizz,359642314904307
58,359642314904307
59,359642314904307
FizzBuzz,359642314904307
61,359642314904307
62,359642314904307
Fizz,359642314904307
64,359642314904307
Buzz,359642314904307
Fizz,359642314904307
67,359642314904307
68,359642314904307
Fizz,359642314904307
Buzz,359642314904307
71,359642314904307
Fizz,359642314904307
73,359642314904307
74,359642314904307
FizzBuzz,359642314904307
76,359642314904307
77,359642314904307
Fizz,359642314904307
79,359642314904307
Buzz,359642314904307
Fizz,359642314904307
82,359642314904307
83,359642314904307
Fizz,359642314904307
Buzz,359642314904307
86,359642314904307
Fizz,359642314904307
88,359642314904307
89,359642314904307
FizzBuzz,359642314904307
91,359642314904307
92,359642314904307
Fizz,359642314904307
94,359642314904307
Buzz,359642314904307
Fizz,359642314904307
97,359642314904307
98,359642314904307
Fizz,359642314904307
Buzz,359642314904307
101,359642314904307
Fizz,359642314904307
103,359642314904307
104,359642314904307
FizzBuzz,359642314904307
106,359642314904307
107,359642314904307
Fizz,359642314904307
109,359642314904307
Buzz,359642314904307
Fizz,359642314904307
112,359642314904307
113,359642314904307
Fizz,359642314904307
Buzz,359642314904307
116,359642314904307
Fizz,359642314904307
118,359642314904307
119,359642314904307
FizzBuzz,359642314904307
121,359642314904307
122,359642314904307
Fizz,359642314904307
124,359642314904307
Buzz,359642314904307
Fizz,359642314904307
127,359642314904307
128,359642314904307
Fizz,359642314904307
Buzz,359642314904307
131,359642314904307
Fizz,359642314904307
133,359642314904307
134,359642314904307
FizzBuzz,359642314904307
136,359642314904307
137,359642314904307
Fizz,359642314904307
139,359642314904307
Buzz,359642314904307
Fizz,359642314904307
142,359642314904307
143,359642314904307
Fizz,359642314904307
Buzz,359642314904307
146,359642314904307
Fizz,359642314904307
148,359642314904307
149,359642314904307
FizzBuzz,359642314904307
151,359642314904307
152,359642314904307
Fizz,359642314904307
154,359642314904307
Buzz,359642314904307
Fizz,359642314904307
157,359642314904307
158,359642314904307
Fizz,359642314904307
Buzz,359642314904307
161,359642314904307
Fizz,359642314904307
163,359642314904307
164,359642314904307
FizzBuzz,359642314904307
166,359642314904307
167,359642314904307
Fizz,359642314904307
169,359642314904307
Buzz,359642314904307
Fizz,359642314904307
172,359642314904307
173,359642314904307
Fizz,359642314904307
Buzz,359642314904307
176,359642314904307
Fizz,359642314904307
178,359642314904307
179,359642314904307
FizzBuzz,359642314904307
181,359642314904307
182,359642314904307
Fizz,359642314904307
184,359642314904307
Buzz,359642314904307
Fizz,359642314904307
187,359642314904307
188,359642314904307
Fizz,359642314904307
Buzz,359642314904307
191,359642314904307
Fizz,359642314904307
193,359642314904307
194,359642314904307
FizzBuzz,359642314904307
196,359642314904307
197,359642314904307
Fizz,359642314904307
199,359642314904307
Buzz,359642314904307
Fizz,359642314904307
202,359642314904307
203,359642314904307
Fizz,359642314904307
Buzz,359642314904307
206,359642314904307
Fizz,359642314904307
208,359642314904307
209,359642314904307
FizzBuzz,359642314904307
211,359642314904307
212,359642314904307
Fizz,359642314904307
214,359642314904307
Buzz,359642314904307
Fizz,359642314904307
217,359642314904307
218,359642314904307
Fizz,359642314904307
Buzz,359642314904307
221,359642314904307
Fizz,359642314904307
223,359642314904307
224,359642314904307
FizzBuzz,359642314904307
226,359642314904307
227,359642314904307
Fizz,359642314904307
229,359642314904307
Buzz,359642314904307
Fizz,359642314904307
232,359642314904307
233,359642314904307
Fizz,359642314904307
Buzz,359642314904307
236,359642314904307
Fizz,359642314904307
238,359642314904307
239,359642314904307
FizzBuzz,359642314904307
241,359642314904307
242,359642314904307
Fizz,359642314904307
244,359642314904307
Buzz,359642314904307
Fizz,359642314904307
247,359642314904307
248,359642314904307
Fizz,359642314904307
Buzz,359642314904307
251,359642314904307
Fizz,359642314904307
253,359642314904307
254,359642314904307
FizzBuzz,359642314904307
256,359642314904307
257,359642314904307
Fizz,359642314904307
259,359642314904307
Buzz,359642314904307
Fizz,359642314904307
262,359642314904307
263,359642314904307
Fizz,359642314904307
Buzz,359642314904307
266,359642314904307
Fizz,359642314904307
268,359642314904307
269,359642314904307
FizzBuzz,359642314904307
271,359642314904307
272,359642314904307
Fizz,359642314904307
274,359642314904307
Buzz,359642314904307
Fizz,359642314904307
277,359642314904307
278,359642314904307
Fizz,359642314904307
Buzz,359642314904307
281,359642314904307
Fizz,359642314904307
283,359642314904307
284,359642314904307
FizzBuzz,359642314904307
286,359642314904307
287,359642314904307
Fizz,359642314904307
289,359642314904307
Buzz,359642314904307
Fizz,359642314904307
292,359642314904307
293,359642314904307
Fizz,359642314904307
Buzz,359642314904307
296,359642314904307
Fizz,359642314904307
298,359642314904307
299,359642314904307
FizzBuzz,359642314904307
301,359642314904307
302,359642314904307
Fizz,359642314904307
304,359642314904307
Buzz,359642314904307
Fizz,359642314904307
307,359642314904307
308,359642314904307
Fizz,359642314904307
Buzz,359642314904307
311,359642314904307
Fizz,359642314904307
313,359642314904307
314,359642314904307
FizzBuzz,359642314904307
316,359642314904307
317,359642314904307
Fizz,359642314904307
319,359642314904307
Buzz,359642314904307
Fizz,359642314904307
322,359642314904307
323,359642314904307
Fizz,359642314904307
Buzz,359642314904307
326,359642314904307
Fizz,359642314904307
328,359642314904307
329,359642314904307
FizzBuzz,359642314904307
331,359642314904307
332,359642314904307
Fizz,359642314904307
334,359642314904307
Buzz,359642314904307
Fizz,359642314904307
337,359642314904307
338,359642314904307
Fizz,359642314904307
Buzz,359642314904307
341,359642314904307
Fizz,359642314904307
343,359642314904307
344,359642314904307
FizzBuzz,359642314904307
346,359642314904307
347,359642314904307
Fizz,359642314904307
349,359642314904307
Buzz,359642314904307
Fizz,359642314904307
352,359642314904307
353,359642314904307
Fizz,359642314904307
Buzz,359642314904307
356,359642314904307
Fizz,359642314904307
358,359642314904307
359,359642314904307
FizzBuzz,359642314904307
361,359642314904307
362,359642314904307
Fizz,359642314904307
364,359642314904307
Buzz,359642314904307
Fizz,359642314904307
367,359642314904307
368,359642314904307
Fizz,359642314904307
Buzz,359642314904307
371,359642314904307
Fizz,359642314904307
373,359642314904307
374,359642314904307
FizzBuzz,359642314904307
376,359642314904307
377,359642314904307
Fizz,359642314904307
379,359642314904307
Buzz,359642314904307
Fizz,359642314904307
382,359642314904307
383,359642314904307
Fizz,359642314904307
Buzz,359642314904307
386,359642314904307
Fizz,359642314904307
388,359642314904307
389,359642314904307
FizzBuzz,359642314904307
391,359642314904307
392,359642314904307
Fizz,359642314904307
394,359642314904307
Buzz,359642314904307
Fizz,359642314904307
397,359642314904307
398,359642314904307
Fizz,359642314904307
Buzz,359642314904307
401,359642314904307
Fizz,359642314904307
403,359642314904307
404,359642314904307
FizzBuzz,359642314904307
406,359642314904307
407,359642314904307
Fizz,359642314904307
409,359642314904307
Buzz,359642314904307
Fizz,359642314904307
412,359642314904307
413,359642314904307
Fizz,359642314904307
Buzz,359642314904307
416,359642314904307
Fizz,359642314904307
418,359642314904307
419,359642314904307
FizzBuzz,359642314904307
421,359642314904307
422,359642314904307
Fizz,359642314904307
424,359642314904307
Buzz,359642314904307
Fizz,359642314904307
427,359642314904307
428,359642314904307
Fizz,359642314904307
Buzz,359642314904307
431,359642314904307
Fizz,359642314904307
433,359642314904307
434,359642314904307
FizzBuzz,359642314904307
436,359642314904307
437,359642314904307
Fizz,359642314904307
439,359642314904307
Buzz,359642314904307
Fizz,359642314904307
442,359642314904307
443,359642314904307
Fizz,359642314904307
Buzz,359642314904307
446,359642314904307
Fizz,359642314904307
448,359642314904307
449,359642314904307
FizzBuzz,359642314904307
451,359642314904307
452,359642314904307
Fizz,359642314904307
454,359642314904307
Buzz,359642314904307
Fizz,359642314904307
457,359642314904307
458,359642314904307
Fizz,359642314904307
Buzz,359642314904307
461,359642314904307
Fizz,359642314904307
463,359642314904307
464,359642314904307
FizzBuzz,359642314904307
466,359642314904307
467,359642314904307
Fizz,359642314904307
469,359642314904307
Buzz,359642314904307
Fizz,359642314904307
472,359642314904307
473,359642314904307
Fizz,359642314904307
Buzz,359642314904307
476,359642314904307
Fizz,359642314904307
478,359642314904307
479,359642314904307
FizzBuzz,359642314904307
481,359642314904307
482,359642314904307
Fizz,359642314904307
484,359642314904307
Buzz,359642314904307
Fizz,359642314904307
487,359642314904307
488,359642314904307
Fizz,359642314904307
Buzz,359642314904307
491,359642314904307
Fizz,359642314904307
493,359642314904307
494,359642314904307
FizzBuzz,359642314904307
496,359642314904307
497,359642314904307
Fizz,359642314904307
499,359642314904307
Buzz,359642314904307
Fizz,359642314904307
502,359642314904307
503,359642314904307
Fizz,359642314904307
Buzz,359642314904307
506,359642314904307
Fizz,359642314904307
508,359642314904307
509,359642314904307
FizzBuzz,359642314904307
511,359642314904307
512,359642314904307
Fizz,359642314904307
514,359642314904307
Buzz,359642314904307
Fizz,359642314904307
517,359642314904307
518,359642314904307
Fizz,359642314904307
Buzz,359642314904307
521,359642314904307
Fizz,359642314904307
523,359642314904307
524,359642314904307
FizzBuzz,359642314904307
526,359642314904307
527,359642314904307
Fizz,359642314904307
529,359642314904307
Buzz,359642314904307
Fizz,359642314904307
532,359642314904307
533,359642314904307
Fizz,359642314904307
Buzz,359642314904307
536,359642314904307
Fizz,359642314904307
538,359642314904307
539,359642314904307
FizzBuzz,359642314904307
541,359642314904307
542,359642314904307
Fizz,359642314904307
544,359642314904307
Buzz,359642314904307
Fizz,359642314904307
547,359642314904307
548,359642314904307
Fizz,359642314904307
Buzz,359642314904307
551,359642314904307
Fizz,359642314904307
553,359642314904307
554,359642314904307
FizzBuzz,359642314904307
556,359642314904307
557,359642314904307
Fizz,359642314904307
559,359642314904307
Buzz,359642314904307
Fizz,359642314904307
562,359642314904307
563,359642314904307
Fizz,359642314904307
Buzz,359642314904307
566,359642314904307
Fizz,359642314904307
568,359642314904307
569,359642314904307
FizzBuzz,359642314904307
571,359642314904307
572,359642314904307
Fizz,359642314904307
574,359642314904307
Buzz,359642314904307
Fizz,359642314904307
577,359642314904307
578,359642314904307
Fizz,359642314904307
Buzz,359642314904307
581,359642314904307
Fizz,359642314904307
583,359642314904307
584,359642314904307
FizzBuzz,359642314904307
586,359642314904307
587,359642314904307
Fizz,359642314904307
589,359642314904307
Buzz,359642314904307
Fizz,359642314904307
592,359642314904307
593,359642314904307
Fizz,359642314904307
Buzz,359642314904307
596,359642314904307
Fizz,359642314904307
598,359642314904307
599,359642314904307
FizzBuzz,359642314904307
601,359642314904307
602,359642314904307
Fizz,359642314904307
604,359642314904307
Buzz,359642314904307
Fizz,359642314904307
607,359642314904307
608,359642314904307
Fizz,359642314904307
Buzz,359642314904307
611,359642314904307
Fizz,359642314904307
613,359642314904307
614,359642314904307
FizzBuzz,359642314904307
616,359642314904307
617,359642314904307
Fizz,359642314904307
619,359642314904307
Buzz,359642314904307
Fizz,359642314904307
622,359642314904307
623,359642314904307
Fizz,359642314904307
Buzz,359642314904307
626,359642314904307
Fizz,359642314904307
628,359642314904307
629,359642314904307
FizzBuzz,359642314904307
631,359642314904307
632,359642314904307
Fizz,359642314904307
634,359642314904307
Buzz,359642314904307
Fizz,359642314904307
637,359642314904307
638,359642314904307
Fizz,359642314904307
Buzz,359642314904307
641,359642314904307
Fizz,359642314904307
643,359642314904307
644,359642314904307
FizzBuzz,359642314904307
646,359642314904307
647,359642314904307
Fizz,359642314904307
649,359642314904307
Buzz,359642314904307
Fizz,359642314904307
652,359642314904307
653,359642314904307
Fizz,359642314904307
Buzz,359642314904307
656,359642314904307
Fizz,359642314904307
658,359642314904307
659,359642314904307
FizzBuzz,359642314904307
661,359642314904307
662,359642314904307
Fizz,359642314904307
664,359642314904307
Buzz,359642314904307
Fizz,359642314904307
667,359642314904307
668,359642314904307
Fizz,359642314904307
Buzz,359642314904307
671,359642314904307
Fizz,359642314904307
673,359642314904307
674,359642314904307
FizzBuzz,359642314904307
676,359642314904307
677,359642314904307
Fizz,359642314904307
679,359642314904307
Buzz,359642314904307
Fizz,359642314904307
682,359642314904307
683,359642314904307
Fizz,359642314904307
Buzz,359642314904307
686,359642314904307
Fizz,359642314904307
688,359642314904307
689,359642314904307
FizzBuzz,359642314904307
691,359642314904307
692,359642314904307
Fizz,359642314904307
694,359642314904307
Buzz,359642314904307
Fizz,359642314904307
697,359642314904307
698,359642314904307
Fizz,359642314904307
Buzz,359642314904307
701,359642314904307
Fizz,359642314904307
703,359642314904307
704,359642314904307
FizzBuzz,359642314904307
706,359642314904307
707,359642314904307
Fizz,359642314904307
709,359642314904307
Buzz,359642314904307
Fizz,359642314904307
712,359642314904307
713,359642314904307
Fizz,359642314904307
Buzz,359642314904307
716,359642314904307
Fizz,359642314904307
718,359642314904307
719,359642314904307
FizzBuzz,359642314904307
721,359642314904307
722,359642314904307
Fizz,359642314904307
724,359642314904307
Buzz,359642314904307
Fizz,359642314904307
727,359642314904307
728,359642314904307
Fizz,359642314904307
Buzz,359642314904307
731,359642314904307
Fizz,359642314904307
733,359642314904307
734,359642314904307
FizzBuzz,359642314904307
736,359642314904307
737,359642314904307
Fizz,359642314904307
739,359642314904307
Buzz,359642314904307
Fizz,359642314904307
742,359642314904307
743,359642314904307
Fizz,359642314904307
Buzz,359642314904307
746,359642314904307
Fizz,359642314904307
748,359642314904307
749,359642314904307
FizzBuzz,359642314904307
751,359642314904307
752,359642314904307
Fizz,359642314904307
754,359642314904307
Buzz,359642314904307
Fizz,359642314904307
757,359642314904307
758,359642314904307
Fizz,359642314904307
Buzz,359642314904307
761,359642314904307
Fizz,359642314904307
763,359642314904307
764,359642314904307
FizzBuzz,359642314904307
766,359642314904307
767,359642314904307
Fizz,359642314904307
769,359642314904307
Buzz,359642314904307
Fizz,359642314904307
772,359642314904307
773,359642314904307
Fizz,359642314904307
Buzz,359642314904307
776,359642314904307
Fizz,359642314904307
778,359642314904307
779,359642314904307
FizzBuzz,359642314904307
781,359642314904307
782,359642314904307
Fizz,359642314904307
784,359642314904307
Buzz,359642314904307
Fizz,359642314904307
787,359642314904307
788,359642314904307
Fizz,359642314904307
Buzz,359642314904307
791,359642314904307
Fizz,359642314904307
793,359642314904307
794,359642314904307
FizzBuzz,359642314904307
796,359642314904307
797,359642314904307
Fizz,359642314904307
799,359642314904307
Buzz,359642314904307
Fizz,359642314904307
802,359642314904307
803,359642314904307
Fizz,359642314904307
Buzz,359642314904307
806,359642314904307
Fizz,359642314904307
808,359642314904307
809,359642314904307
FizzBuzz,359642314904307
811,359642314904307
812,359642314904307
Fizz,359642314904307
814,359642314904307
Buzz,359642314904307
Fizz,359642314904307
817,359642314904307
818,359642314904307
Fizz,359642314904307
Buzz,359642314904307
821,359642314904307
Fizz,359642314904307
823,359642314904307
824,359642314904307
FizzBuzz,359642314904307
826,359642314904307
827,359642314904307
Fizz,359642314904307
829,359642314904307
Buzz,359642314904307
Fizz,359642314904307
832,359642314904307
833,359642314904307
Fizz,359642314904307
Buzz,359642314904307
836,359642314904307
Fizz,359642314904307
838,359642314904307
839,359642314904307
FizzBuzz,359642314904307
841,359642314904307
842,359642314904307
Fizz,359642314904307
844,359642314904307
Buzz,359642314904307
Fizz,359642314904307
847,359642314904307
848,359642314904307
Fizz,359642314904307
Buzz,359642314904307
851,359642314904307
Fizz,359642314904307
853,359642314904307
854,359642314904307
FizzBuzz,359642314904307
856,359642314904307
857,359642314904307
Fizz,359642314904307
859,359642314904307
Buzz,359642314904307
Fizz,359642314904307
862,359642314904307
863,359642314904307
Fizz,359642314904307
Buzz,359642314904307
866,359642314904307
Fizz,359642314904307
868,359642314904307
869,359642314904307
FizzBuzz,359642314904307
871,359642314904307
872,359642314904307
Fizz,359642314904307
874,359642314904307
Buzz,359642314904307
Fizz,359642314904307
877,359642314904307
878,359642314904307
Fizz,359642314904307
Buzz,359642314904307
881,359642314904307
Fizz,359642314904307
883,359642314904307
884,359642314904307
FizzBuzz,359642314904307
886,359642314904307
887,359642314904307
Fizz,359642314904307
889,359642314904307
Buzz,359642314904307
Fizz,359642314904307
892,359642314904307
893,359642314904307
Fizz,359642314904307
Buzz,359642314904307
896,359642314904307
Fizz,359642314904307
898,359642314904307
899,359642314904307
FizzBuzz,359642314904307
901,359642314904307
902,359642314904307
Fizz,359642314904307
904,359642314904307
Buzz,359642314904307
Fizz,359642314904307
907,359642314904307
908,359642314904307
Fizz,359642314904307
Buzz,359642314904307
911,359642314904307
Fizz,359642314904307
913,359642314904307
914,359642314904307
FizzBuzz,359642314904307
916,359642314904307
917,359642314904307
Fizz,359642314904307
919,359642314904307
Buzz,359642314904307
Fizz,359642314904307
922,359642314904307
923,359642314904307
Fizz,359642314904307
Buzz,359642314904307
926,359642314904307
Fizz,359642314904307
928,359642314904307
929,359642314904307
FizzBuzz,359642314904307
931,359642314904307
932,359642314904307
Fizz,359642314904307
934,359642314904307
Buzz,359642314904307
Fizz,359642314904307
937,359642314904307
938,359642314904307
Fizz,359642314904307
Buzz,359642314904307
941,359642314904307
Fizz,359642314904307
943,359642314904307
944,359642314904307
FizzBuzz,359642314904307
946,359642314904307
947,359642314904307
Fizz,359642314904307
949,359642314904307
Buzz,359642314904307
Fizz,359642314904307
952,359642314904307
953,359642314904307
Fizz,359642314904307
Buzz,359642314904307
956,359642314904307
Fizz,359642314904307
958,359642314904307
959,359642314904307
FizzBuzz,359642314904307
961,359642314904307
962,359642314904307
Fizz,359642314904307
964,359642314904307
Buzz,359642314904307
Fizz,359642314904307

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = "fizz.buzz.11.fizz.13.14.fizzbuzz.16"

In [ ]:
%%sql
-- Indication. Vous pouvez éviter d'incrémenter chaque `i` : laissez tomber le premier `i` au lieu du dernier.
SELECT CASE
           WHEN (i + 1) % 15 = 0 THEN 'FizzBuzz'
           WHEN (i + 1) % 3 = 0 THEN 'Fizz'
           WHEN (i + 1) % 5 = 0 THEN 'Buzz'
           ELSE (i + 1)
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i < 1000

1000 rows affected.

fizzbuzz,token
1,359813838431707
2,359813838431707
Fizz,359813838431707
4,359813838431707
Buzz,359813838431707
Fizz,359813838431707
7,359813838431707
8,359813838431707
Fizz,359813838431707
Buzz,359813838431707
11,359813838431707
Fizz,359813838431707
13,359813838431707
14,359813838431707
FizzBuzz,359813838431707
16,359813838431707
17,359813838431707
Fizz,359813838431707
19,359813838431707
Buzz,359813838431707
Fizz,359813838431707
22,359813838431707
23,359813838431707
Fizz,359813838431707
Buzz,359813838431707
26,359813838431707
Fizz,359813838431707
28,359813838431707
29,359813838431707
FizzBuzz,359813838431707
31,359813838431707
32,359813838431707
Fizz,359813838431707
34,359813838431707
Buzz,359813838431707
Fizz,359813838431707
37,359813838431707
38,359813838431707
Fizz,359813838431707
Buzz,359813838431707
41,359813838431707
Fizz,359813838431707
43,359813838431707
44,359813838431707
FizzBuzz,359813838431707
46,359813838431707
47,359813838431707
Fizz,359813838431707
49,359813838431707
Buzz,359813838431707
Fizz,359813838431707
52,359813838431707
53,359813838431707
Fizz,359813838431707
Buzz,359813838431707
56,359813838431707
Fizz,359813838431707
58,359813838431707
59,359813838431707
FizzBuzz,359813838431707
61,359813838431707
62,359813838431707
Fizz,359813838431707
64,359813838431707
Buzz,359813838431707
Fizz,359813838431707
67,359813838431707
68,359813838431707
Fizz,359813838431707
Buzz,359813838431707
71,359813838431707
Fizz,359813838431707
73,359813838431707
74,359813838431707
FizzBuzz,359813838431707
76,359813838431707
77,359813838431707
Fizz,359813838431707
79,359813838431707
Buzz,359813838431707
Fizz,359813838431707
82,359813838431707
83,359813838431707
Fizz,359813838431707
Buzz,359813838431707
86,359813838431707
Fizz,359813838431707
88,359813838431707
89,359813838431707
FizzBuzz,359813838431707
91,359813838431707
92,359813838431707
Fizz,359813838431707
94,359813838431707
Buzz,359813838431707
Fizz,359813838431707
97,359813838431707
98,359813838431707
Fizz,359813838431707
Buzz,359813838431707
101,359813838431707
Fizz,359813838431707
103,359813838431707
104,359813838431707
FizzBuzz,359813838431707
106,359813838431707
107,359813838431707
Fizz,359813838431707
109,359813838431707
Buzz,359813838431707
Fizz,359813838431707
112,359813838431707
113,359813838431707
Fizz,359813838431707
Buzz,359813838431707
116,359813838431707
Fizz,359813838431707
118,359813838431707
119,359813838431707
FizzBuzz,359813838431707
121,359813838431707
122,359813838431707
Fizz,359813838431707
124,359813838431707
Buzz,359813838431707
Fizz,359813838431707
127,359813838431707
128,359813838431707
Fizz,359813838431707
Buzz,359813838431707
131,359813838431707
Fizz,359813838431707
133,359813838431707
134,359813838431707
FizzBuzz,359813838431707
136,359813838431707
137,359813838431707
Fizz,359813838431707
139,359813838431707
Buzz,359813838431707
Fizz,359813838431707
142,359813838431707
143,359813838431707
Fizz,359813838431707
Buzz,359813838431707
146,359813838431707
Fizz,359813838431707
148,359813838431707
149,359813838431707
FizzBuzz,359813838431707
151,359813838431707
152,359813838431707
Fizz,359813838431707
154,359813838431707
Buzz,359813838431707
Fizz,359813838431707
157,359813838431707
158,359813838431707
Fizz,359813838431707
Buzz,359813838431707
161,359813838431707
Fizz,359813838431707
163,359813838431707
164,359813838431707
FizzBuzz,359813838431707
166,359813838431707
167,359813838431707
Fizz,359813838431707
169,359813838431707
Buzz,359813838431707
Fizz,359813838431707
172,359813838431707
173,359813838431707
Fizz,359813838431707
Buzz,359813838431707
176,359813838431707
Fizz,359813838431707
178,359813838431707
179,359813838431707
FizzBuzz,359813838431707
181,359813838431707
182,359813838431707
Fizz,359813838431707
184,359813838431707
Buzz,359813838431707
Fizz,359813838431707
187,359813838431707
188,359813838431707
Fizz,359813838431707
Buzz,359813838431707
191,359813838431707
Fizz,359813838431707
193,359813838431707
194,359813838431707
FizzBuzz,359813838431707
196,359813838431707
197,359813838431707
Fizz,359813838431707
199,359813838431707
Buzz,359813838431707
Fizz,359813838431707
202,359813838431707
203,359813838431707
Fizz,359813838431707
Buzz,359813838431707
206,359813838431707
Fizz,359813838431707
208,359813838431707
209,359813838431707
FizzBuzz,359813838431707
211,359813838431707
212,359813838431707
Fizz,359813838431707
214,359813838431707
Buzz,359813838431707
Fizz,359813838431707
217,359813838431707
218,359813838431707
Fizz,359813838431707
Buzz,359813838431707
221,359813838431707
Fizz,359813838431707
223,359813838431707
224,359813838431707
FizzBuzz,359813838431707
226,359813838431707
227,359813838431707
Fizz,359813838431707
229,359813838431707
Buzz,359813838431707
Fizz,359813838431707
232,359813838431707
233,359813838431707
Fizz,359813838431707
Buzz,359813838431707
236,359813838431707
Fizz,359813838431707
238,359813838431707
239,359813838431707
FizzBuzz,359813838431707
241,359813838431707
242,359813838431707
Fizz,359813838431707
244,359813838431707
Buzz,359813838431707
Fizz,359813838431707
247,359813838431707
248,359813838431707
Fizz,359813838431707
Buzz,359813838431707
251,359813838431707
Fizz,359813838431707
253,359813838431707
254,359813838431707
FizzBuzz,359813838431707
256,359813838431707
257,359813838431707
Fizz,359813838431707
259,359813838431707
Buzz,359813838431707
Fizz,359813838431707
262,359813838431707
263,359813838431707
Fizz,359813838431707
Buzz,359813838431707
266,359813838431707
Fizz,359813838431707
268,359813838431707
269,359813838431707
FizzBuzz,359813838431707
271,359813838431707
272,359813838431707
Fizz,359813838431707
274,359813838431707
Buzz,359813838431707
Fizz,359813838431707
277,359813838431707
278,359813838431707
Fizz,359813838431707
Buzz,359813838431707
281,359813838431707
Fizz,359813838431707
283,359813838431707
284,359813838431707
FizzBuzz,359813838431707
286,359813838431707
287,359813838431707
Fizz,359813838431707
289,359813838431707
Buzz,359813838431707
Fizz,359813838431707
292,359813838431707
293,359813838431707
Fizz,359813838431707
Buzz,359813838431707
296,359813838431707
Fizz,359813838431707
298,359813838431707
299,359813838431707
FizzBuzz,359813838431707
301,359813838431707
302,359813838431707
Fizz,359813838431707
304,359813838431707
Buzz,359813838431707
Fizz,359813838431707
307,359813838431707
308,359813838431707
Fizz,359813838431707
Buzz,359813838431707
311,359813838431707
Fizz,359813838431707
313,359813838431707
314,359813838431707
FizzBuzz,359813838431707
316,359813838431707
317,359813838431707
Fizz,359813838431707
319,359813838431707
Buzz,359813838431707
Fizz,359813838431707
322,359813838431707
323,359813838431707
Fizz,359813838431707
Buzz,359813838431707
326,359813838431707
Fizz,359813838431707
328,359813838431707
329,359813838431707
FizzBuzz,359813838431707
331,359813838431707
332,359813838431707
Fizz,359813838431707
334,359813838431707
Buzz,359813838431707
Fizz,359813838431707
337,359813838431707
338,359813838431707
Fizz,359813838431707
Buzz,359813838431707
341,359813838431707
Fizz,359813838431707
343,359813838431707
344,359813838431707
FizzBuzz,359813838431707
346,359813838431707
347,359813838431707
Fizz,359813838431707
349,359813838431707
Buzz,359813838431707
Fizz,359813838431707
352,359813838431707
353,359813838431707
Fizz,359813838431707
Buzz,359813838431707
356,359813838431707
Fizz,359813838431707
358,359813838431707
359,359813838431707
FizzBuzz,359813838431707
361,359813838431707
362,359813838431707
Fizz,359813838431707
364,359813838431707
Buzz,359813838431707
Fizz,359813838431707
367,359813838431707
368,359813838431707
Fizz,359813838431707
Buzz,359813838431707
371,359813838431707
Fizz,359813838431707
373,359813838431707
374,359813838431707
FizzBuzz,359813838431707
376,359813838431707
377,359813838431707
Fizz,359813838431707
379,359813838431707
Buzz,359813838431707
Fizz,359813838431707
382,359813838431707
383,359813838431707
Fizz,359813838431707
Buzz,359813838431707
386,359813838431707
Fizz,359813838431707
388,359813838431707
389,359813838431707
FizzBuzz,359813838431707
391,359813838431707
392,359813838431707
Fizz,359813838431707
394,359813838431707
Buzz,359813838431707
Fizz,359813838431707
397,359813838431707
398,359813838431707
Fizz,359813838431707
Buzz,359813838431707
401,359813838431707
Fizz,359813838431707
403,359813838431707
404,359813838431707
FizzBuzz,359813838431707
406,359813838431707
407,359813838431707
Fizz,359813838431707
409,359813838431707
Buzz,359813838431707
Fizz,359813838431707
412,359813838431707
413,359813838431707
Fizz,359813838431707
Buzz,359813838431707
416,359813838431707
Fizz,359813838431707
418,359813838431707
419,359813838431707
FizzBuzz,359813838431707
421,359813838431707
422,359813838431707
Fizz,359813838431707
424,359813838431707
Buzz,359813838431707
Fizz,359813838431707
427,359813838431707
428,359813838431707
Fizz,359813838431707
Buzz,359813838431707
431,359813838431707
Fizz,359813838431707
433,359813838431707
434,359813838431707
FizzBuzz,359813838431707
436,359813838431707
437,359813838431707
Fizz,359813838431707
439,359813838431707
Buzz,359813838431707
Fizz,359813838431707
442,359813838431707
443,359813838431707
Fizz,359813838431707
Buzz,359813838431707
446,359813838431707
Fizz,359813838431707
448,359813838431707
449,359813838431707
FizzBuzz,359813838431707
451,359813838431707
452,359813838431707
Fizz,359813838431707
454,359813838431707
Buzz,359813838431707
Fizz,359813838431707
457,359813838431707
458,359813838431707
Fizz,359813838431707
Buzz,359813838431707
461,359813838431707
Fizz,359813838431707
463,359813838431707
464,359813838431707
FizzBuzz,359813838431707
466,359813838431707
467,359813838431707
Fizz,359813838431707
469,359813838431707
Buzz,359813838431707
Fizz,359813838431707
472,359813838431707
473,359813838431707
Fizz,359813838431707
Buzz,359813838431707
476,359813838431707
Fizz,359813838431707
478,359813838431707
479,359813838431707
FizzBuzz,359813838431707
481,359813838431707
482,359813838431707
Fizz,359813838431707
484,359813838431707
Buzz,359813838431707
Fizz,359813838431707
487,359813838431707
488,359813838431707
Fizz,359813838431707
Buzz,359813838431707
491,359813838431707
Fizz,359813838431707
493,359813838431707
494,359813838431707
FizzBuzz,359813838431707
496,359813838431707
497,359813838431707
Fizz,359813838431707
499,359813838431707
Buzz,359813838431707
Fizz,359813838431707
502,359813838431707
503,359813838431707
Fizz,359813838431707
Buzz,359813838431707
506,359813838431707
Fizz,359813838431707
508,359813838431707
509,359813838431707
FizzBuzz,359813838431707
511,359813838431707
512,359813838431707
Fizz,359813838431707
514,359813838431707
Buzz,359813838431707
Fizz,359813838431707
517,359813838431707
518,359813838431707
Fizz,359813838431707
Buzz,359813838431707
521,359813838431707
Fizz,359813838431707
523,359813838431707
524,359813838431707
FizzBuzz,359813838431707
526,359813838431707
527,359813838431707
Fizz,359813838431707
529,359813838431707
Buzz,359813838431707
Fizz,359813838431707
532,359813838431707
533,359813838431707
Fizz,359813838431707
Buzz,359813838431707
536,359813838431707
Fizz,359813838431707
538,359813838431707
539,359813838431707
FizzBuzz,359813838431707
541,359813838431707
542,359813838431707
Fizz,359813838431707
544,359813838431707
Buzz,359813838431707
Fizz,359813838431707
547,359813838431707
548,359813838431707
Fizz,359813838431707
Buzz,359813838431707
551,359813838431707
Fizz,359813838431707
553,359813838431707
554,359813838431707
FizzBuzz,359813838431707
556,359813838431707
557,359813838431707
Fizz,359813838431707
559,359813838431707
Buzz,359813838431707
Fizz,359813838431707
562,359813838431707
563,359813838431707
Fizz,359813838431707
Buzz,359813838431707
566,359813838431707
Fizz,359813838431707
568,359813838431707
569,359813838431707
FizzBuzz,359813838431707
571,359813838431707
572,359813838431707
Fizz,359813838431707
574,359813838431707
Buzz,359813838431707
Fizz,359813838431707
577,359813838431707
578,359813838431707
Fizz,359813838431707
Buzz,359813838431707
581,359813838431707
Fizz,359813838431707
583,359813838431707
584,359813838431707
FizzBuzz,359813838431707
586,359813838431707
587,359813838431707
Fizz,359813838431707
589,359813838431707
Buzz,359813838431707
Fizz,359813838431707
592,359813838431707
593,359813838431707
Fizz,359813838431707
Buzz,359813838431707
596,359813838431707
Fizz,359813838431707
598,359813838431707
599,359813838431707
FizzBuzz,359813838431707
601,359813838431707
602,359813838431707
Fizz,359813838431707
604,359813838431707
Buzz,359813838431707
Fizz,359813838431707
607,359813838431707
608,359813838431707
Fizz,359813838431707
Buzz,359813838431707
611,359813838431707
Fizz,359813838431707
613,359813838431707
614,359813838431707
FizzBuzz,359813838431707
616,359813838431707
617,359813838431707
Fizz,359813838431707
619,359813838431707
Buzz,359813838431707
Fizz,359813838431707
622,359813838431707
623,359813838431707
Fizz,359813838431707
Buzz,359813838431707
626,359813838431707
Fizz,359813838431707
628,359813838431707
629,359813838431707
FizzBuzz,359813838431707
631,359813838431707
632,359813838431707
Fizz,359813838431707
634,359813838431707
Buzz,359813838431707
Fizz,359813838431707
637,359813838431707
638,359813838431707
Fizz,359813838431707
Buzz,359813838431707
641,359813838431707
Fizz,359813838431707
643,359813838431707
644,359813838431707
FizzBuzz,359813838431707
646,359813838431707
647,359813838431707
Fizz,359813838431707
649,359813838431707
Buzz,359813838431707
Fizz,359813838431707
652,359813838431707
653,359813838431707
Fizz,359813838431707
Buzz,359813838431707
656,359813838431707
Fizz,359813838431707
658,359813838431707
659,359813838431707
FizzBuzz,359813838431707
661,359813838431707
662,359813838431707
Fizz,359813838431707
664,359813838431707
Buzz,359813838431707
Fizz,359813838431707
667,359813838431707
668,359813838431707
Fizz,359813838431707
Buzz,359813838431707
671,359813838431707
Fizz,359813838431707
673,359813838431707
674,359813838431707
FizzBuzz,359813838431707
676,359813838431707
677,359813838431707
Fizz,359813838431707
679,359813838431707
Buzz,359813838431707
Fizz,359813838431707
682,359813838431707
683,359813838431707
Fizz,359813838431707
Buzz,359813838431707
686,359813838431707
Fizz,359813838431707
688,359813838431707
689,359813838431707
FizzBuzz,359813838431707
691,359813838431707
692,359813838431707
Fizz,359813838431707
694,359813838431707
Buzz,359813838431707
Fizz,359813838431707
697,359813838431707
698,359813838431707
Fizz,359813838431707
Buzz,359813838431707
701,359813838431707
Fizz,359813838431707
703,359813838431707
704,359813838431707
FizzBuzz,359813838431707
706,359813838431707
707,359813838431707
Fizz,359813838431707
709,359813838431707
Buzz,359813838431707
Fizz,359813838431707
712,359813838431707
713,359813838431707
Fizz,359813838431707
Buzz,359813838431707
716,359813838431707
Fizz,359813838431707
718,359813838431707
719,359813838431707
FizzBuzz,359813838431707
721,359813838431707
722,359813838431707
Fizz,359813838431707
724,359813838431707
Buzz,359813838431707
Fizz,359813838431707
727,359813838431707
728,359813838431707
Fizz,359813838431707
Buzz,359813838431707
731,359813838431707
Fizz,359813838431707
733,359813838431707
734,359813838431707
FizzBuzz,359813838431707
736,359813838431707
737,359813838431707
Fizz,359813838431707
739,359813838431707
Buzz,359813838431707
Fizz,359813838431707
742,359813838431707
743,359813838431707
Fizz,359813838431707
Buzz,359813838431707
746,359813838431707
Fizz,359813838431707
748,359813838431707
749,359813838431707
FizzBuzz,359813838431707
751,359813838431707
752,359813838431707
Fizz,359813838431707
754,359813838431707
Buzz,359813838431707
Fizz,359813838431707
757,359813838431707
758,359813838431707
Fizz,359813838431707
Buzz,359813838431707
761,359813838431707
Fizz,359813838431707
763,359813838431707
764,359813838431707
FizzBuzz,359813838431707
766,359813838431707
767,359813838431707
Fizz,359813838431707
769,359813838431707
Buzz,359813838431707
Fizz,359813838431707
772,359813838431707
773,359813838431707
Fizz,359813838431707
Buzz,359813838431707
776,359813838431707
Fizz,359813838431707
778,359813838431707
779,359813838431707
FizzBuzz,359813838431707
781,359813838431707
782,359813838431707
Fizz,359813838431707
784,359813838431707
Buzz,359813838431707
Fizz,359813838431707
787,359813838431707
788,359813838431707
Fizz,359813838431707
Buzz,359813838431707
791,359813838431707
Fizz,359813838431707
793,359813838431707
794,359813838431707
FizzBuzz,359813838431707
796,359813838431707
797,359813838431707
Fizz,359813838431707
799,359813838431707
Buzz,359813838431707
Fizz,359813838431707
802,359813838431707
803,359813838431707
Fizz,359813838431707
Buzz,359813838431707
806,359813838431707
Fizz,359813838431707
808,359813838431707
809,359813838431707
FizzBuzz,359813838431707
811,359813838431707
812,359813838431707
Fizz,359813838431707
814,359813838431707
Buzz,359813838431707
Fizz,359813838431707
817,359813838431707
818,359813838431707
Fizz,359813838431707
Buzz,359813838431707
821,359813838431707
Fizz,359813838431707
823,359813838431707
824,359813838431707
FizzBuzz,359813838431707
826,359813838431707
827,359813838431707
Fizz,359813838431707
829,359813838431707
Buzz,359813838431707
Fizz,359813838431707
832,359813838431707
833,359813838431707
Fizz,359813838431707
Buzz,359813838431707
836,359813838431707
Fizz,359813838431707
838,359813838431707
839,359813838431707
FizzBuzz,359813838431707
841,359813838431707
842,359813838431707
Fizz,359813838431707
844,359813838431707
Buzz,359813838431707
Fizz,359813838431707
847,359813838431707
848,359813838431707
Fizz,359813838431707
Buzz,359813838431707
851,359813838431707
Fizz,359813838431707
853,359813838431707
854,359813838431707
FizzBuzz,359813838431707
856,359813838431707
857,359813838431707
Fizz,359813838431707
859,359813838431707
Buzz,359813838431707
Fizz,359813838431707
862,359813838431707
863,359813838431707
Fizz,359813838431707
Buzz,359813838431707
866,359813838431707
Fizz,359813838431707
868,359813838431707
869,359813838431707
FizzBuzz,359813838431707
871,359813838431707
872,359813838431707
Fizz,359813838431707
874,359813838431707
Buzz,359813838431707
Fizz,359813838431707
877,359813838431707
878,359813838431707
Fizz,359813838431707
Buzz,359813838431707
881,359813838431707
Fizz,359813838431707
883,359813838431707
884,359813838431707
FizzBuzz,359813838431707
886,359813838431707
887,359813838431707
Fizz,359813838431707
889,359813838431707
Buzz,359813838431707
Fizz,359813838431707
892,359813838431707
893,359813838431707
Fizz,359813838431707
Buzz,359813838431707
896,359813838431707
Fizz,359813838431707
898,359813838431707
899,359813838431707
FizzBuzz,359813838431707
901,359813838431707
902,359813838431707
Fizz,359813838431707
904,359813838431707
Buzz,359813838431707
Fizz,359813838431707
907,359813838431707
908,359813838431707
Fizz,359813838431707
Buzz,359813838431707
911,359813838431707
Fizz,359813838431707
913,359813838431707
914,359813838431707
FizzBuzz,359813838431707
916,359813838431707
917,359813838431707
Fizz,359813838431707
919,359813838431707
Buzz,359813838431707
Fizz,359813838431707
922,359813838431707
923,359813838431707
Fizz,359813838431707
Buzz,359813838431707
926,359813838431707
Fizz,359813838431707
928,359813838431707
929,359813838431707
FizzBuzz,359813838431707
931,359813838431707
932,359813838431707
Fizz,359813838431707
934,359813838431707
Buzz,359813838431707
Fizz,359813838431707
937,359813838431707
938,359813838431707
Fizz,359813838431707
Buzz,359813838431707
941,359813838431707
Fizz,359813838431707
943,359813838431707
944,359813838431707
FizzBuzz,359813838431707
946,359813838431707
947,359813838431707
Fizz,359813838431707
949,359813838431707
Buzz,359813838431707
Fizz,359813838431707
952,359813838431707
953,359813838431707
Fizz,359813838431707
Buzz,359813838431707
956,359813838431707
Fizz,359813838431707
958,359813838431707
959,359813838431707
FizzBuzz,359813838431707
961,359813838431707
962,359813838431707
Fizz,359813838431707
964,359813838431707
Buzz,359813838431707
Fizz,359813838431707

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

In [ ]:
x = "fizz.buzz.11.fizz.13.14.fizz buzz.16"

In [ ]:
%%sql
-- Indication. N'insérez pas d'espace dans `'FizzBuzz'`.
SELECT CASE
           WHEN i % 15 = 0 THEN 'Fizz Buzz'
           WHEN i % 3 = 0 THEN 'Fizz'
           WHEN i % 5 = 0 THEN 'Buzz'
           ELSE i
       END AS fizzbuzz
     , salt_088(string_hash('{{x}}') + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i > 0

1000 rows affected.

fizzbuzz,token
1,359590657654446
2,359590657654446
Fizz,359590657654446
4,359590657654446
Buzz,359590657654446
Fizz,359590657654446
7,359590657654446
8,359590657654446
Fizz,359590657654446
Buzz,359590657654446
11,359590657654446
Fizz,359590657654446
13,359590657654446
14,359590657654446
Fizz Buzz,359590657654446
16,359590657654446
17,359590657654446
Fizz,359590657654446
19,359590657654446
Buzz,359590657654446
Fizz,359590657654446
22,359590657654446
23,359590657654446
Fizz,359590657654446
Buzz,359590657654446
26,359590657654446
Fizz,359590657654446
28,359590657654446
29,359590657654446
Fizz Buzz,359590657654446
31,359590657654446
32,359590657654446
Fizz,359590657654446
34,359590657654446
Buzz,359590657654446
Fizz,359590657654446
37,359590657654446
38,359590657654446
Fizz,359590657654446
Buzz,359590657654446
41,359590657654446
Fizz,359590657654446
43,359590657654446
44,359590657654446
Fizz Buzz,359590657654446
46,359590657654446
47,359590657654446
Fizz,359590657654446
49,359590657654446
Buzz,359590657654446
Fizz,359590657654446
52,359590657654446
53,359590657654446
Fizz,359590657654446
Buzz,359590657654446
56,359590657654446
Fizz,359590657654446
58,359590657654446
59,359590657654446
Fizz Buzz,359590657654446
61,359590657654446
62,359590657654446
Fizz,359590657654446
64,359590657654446
Buzz,359590657654446
Fizz,359590657654446
67,359590657654446
68,359590657654446
Fizz,359590657654446
Buzz,359590657654446
71,359590657654446
Fizz,359590657654446
73,359590657654446
74,359590657654446
Fizz Buzz,359590657654446
76,359590657654446
77,359590657654446
Fizz,359590657654446
79,359590657654446
Buzz,359590657654446
Fizz,359590657654446
82,359590657654446
83,359590657654446
Fizz,359590657654446
Buzz,359590657654446
86,359590657654446
Fizz,359590657654446
88,359590657654446
89,359590657654446
Fizz Buzz,359590657654446
91,359590657654446
92,359590657654446
Fizz,359590657654446
94,359590657654446
Buzz,359590657654446
Fizz,359590657654446
97,359590657654446
98,359590657654446
Fizz,359590657654446
Buzz,359590657654446
101,359590657654446
Fizz,359590657654446
103,359590657654446
104,359590657654446
Fizz Buzz,359590657654446
106,359590657654446
107,359590657654446
Fizz,359590657654446
109,359590657654446
Buzz,359590657654446
Fizz,359590657654446
112,359590657654446
113,359590657654446
Fizz,359590657654446
Buzz,359590657654446
116,359590657654446
Fizz,359590657654446
118,359590657654446
119,359590657654446
Fizz Buzz,359590657654446
121,359590657654446
122,359590657654446
Fizz,359590657654446
124,359590657654446
Buzz,359590657654446
Fizz,359590657654446
127,359590657654446
128,359590657654446
Fizz,359590657654446
Buzz,359590657654446
131,359590657654446
Fizz,359590657654446
133,359590657654446
134,359590657654446
Fizz Buzz,359590657654446
136,359590657654446
137,359590657654446
Fizz,359590657654446
139,359590657654446
Buzz,359590657654446
Fizz,359590657654446
142,359590657654446
143,359590657654446
Fizz,359590657654446
Buzz,359590657654446
146,359590657654446
Fizz,359590657654446
148,359590657654446
149,359590657654446
Fizz Buzz,359590657654446
151,359590657654446
152,359590657654446
Fizz,359590657654446
154,359590657654446
Buzz,359590657654446
Fizz,359590657654446
157,359590657654446
158,359590657654446
Fizz,359590657654446
Buzz,359590657654446
161,359590657654446
Fizz,359590657654446
163,359590657654446
164,359590657654446
Fizz Buzz,359590657654446
166,359590657654446
167,359590657654446
Fizz,359590657654446
169,359590657654446
Buzz,359590657654446
Fizz,359590657654446
172,359590657654446
173,359590657654446
Fizz,359590657654446
Buzz,359590657654446
176,359590657654446
Fizz,359590657654446
178,359590657654446
179,359590657654446
Fizz Buzz,359590657654446
181,359590657654446
182,359590657654446
Fizz,359590657654446
184,359590657654446
Buzz,359590657654446
Fizz,359590657654446
187,359590657654446
188,359590657654446
Fizz,359590657654446
Buzz,359590657654446
191,359590657654446
Fizz,359590657654446
193,359590657654446
194,359590657654446
Fizz Buzz,359590657654446
196,359590657654446
197,359590657654446
Fizz,359590657654446
199,359590657654446
Buzz,359590657654446
Fizz,359590657654446
202,359590657654446
203,359590657654446
Fizz,359590657654446
Buzz,359590657654446
206,359590657654446
Fizz,359590657654446
208,359590657654446
209,359590657654446
Fizz Buzz,359590657654446
211,359590657654446
212,359590657654446
Fizz,359590657654446
214,359590657654446
Buzz,359590657654446
Fizz,359590657654446
217,359590657654446
218,359590657654446
Fizz,359590657654446
Buzz,359590657654446
221,359590657654446
Fizz,359590657654446
223,359590657654446
224,359590657654446
Fizz Buzz,359590657654446
226,359590657654446
227,359590657654446
Fizz,359590657654446
229,359590657654446
Buzz,359590657654446
Fizz,359590657654446
232,359590657654446
233,359590657654446
Fizz,359590657654446
Buzz,359590657654446
236,359590657654446
Fizz,359590657654446
238,359590657654446
239,359590657654446
Fizz Buzz,359590657654446
241,359590657654446
242,359590657654446
Fizz,359590657654446
244,359590657654446
Buzz,359590657654446
Fizz,359590657654446
247,359590657654446
248,359590657654446
Fizz,359590657654446
Buzz,359590657654446
251,359590657654446
Fizz,359590657654446
253,359590657654446
254,359590657654446
Fizz Buzz,359590657654446
256,359590657654446
257,359590657654446
Fizz,359590657654446
259,359590657654446
Buzz,359590657654446
Fizz,359590657654446
262,359590657654446
263,359590657654446
Fizz,359590657654446
Buzz,359590657654446
266,359590657654446
Fizz,359590657654446
268,359590657654446
269,359590657654446
Fizz Buzz,359590657654446
271,359590657654446
272,359590657654446
Fizz,359590657654446
274,359590657654446
Buzz,359590657654446
Fizz,359590657654446
277,359590657654446
278,359590657654446
Fizz,359590657654446
Buzz,359590657654446
281,359590657654446
Fizz,359590657654446
283,359590657654446
284,359590657654446
Fizz Buzz,359590657654446
286,359590657654446
287,359590657654446
Fizz,359590657654446
289,359590657654446
Buzz,359590657654446
Fizz,359590657654446
292,359590657654446
293,359590657654446
Fizz,359590657654446
Buzz,359590657654446
296,359590657654446
Fizz,359590657654446
298,359590657654446
299,359590657654446
Fizz Buzz,359590657654446
301,359590657654446
302,359590657654446
Fizz,359590657654446
304,359590657654446
Buzz,359590657654446
Fizz,359590657654446
307,359590657654446
308,359590657654446
Fizz,359590657654446
Buzz,359590657654446
311,359590657654446
Fizz,359590657654446
313,359590657654446
314,359590657654446
Fizz Buzz,359590657654446
316,359590657654446
317,359590657654446
Fizz,359590657654446
319,359590657654446
Buzz,359590657654446
Fizz,359590657654446
322,359590657654446
323,359590657654446
Fizz,359590657654446
Buzz,359590657654446
326,359590657654446
Fizz,359590657654446
328,359590657654446
329,359590657654446
Fizz Buzz,359590657654446
331,359590657654446
332,359590657654446
Fizz,359590657654446
334,359590657654446
Buzz,359590657654446
Fizz,359590657654446
337,359590657654446
338,359590657654446
Fizz,359590657654446
Buzz,359590657654446
341,359590657654446
Fizz,359590657654446
343,359590657654446
344,359590657654446
Fizz Buzz,359590657654446
346,359590657654446
347,359590657654446
Fizz,359590657654446
349,359590657654446
Buzz,359590657654446
Fizz,359590657654446
352,359590657654446
353,359590657654446
Fizz,359590657654446
Buzz,359590657654446
356,359590657654446
Fizz,359590657654446
358,359590657654446
359,359590657654446
Fizz Buzz,359590657654446
361,359590657654446
362,359590657654446
Fizz,359590657654446
364,359590657654446
Buzz,359590657654446
Fizz,359590657654446
367,359590657654446
368,359590657654446
Fizz,359590657654446
Buzz,359590657654446
371,359590657654446
Fizz,359590657654446
373,359590657654446
374,359590657654446
Fizz Buzz,359590657654446
376,359590657654446
377,359590657654446
Fizz,359590657654446
379,359590657654446
Buzz,359590657654446
Fizz,359590657654446
382,359590657654446
383,359590657654446
Fizz,359590657654446
Buzz,359590657654446
386,359590657654446
Fizz,359590657654446
388,359590657654446
389,359590657654446
Fizz Buzz,359590657654446
391,359590657654446
392,359590657654446
Fizz,359590657654446
394,359590657654446
Buzz,359590657654446
Fizz,359590657654446
397,359590657654446
398,359590657654446
Fizz,359590657654446
Buzz,359590657654446
401,359590657654446
Fizz,359590657654446
403,359590657654446
404,359590657654446
Fizz Buzz,359590657654446
406,359590657654446
407,359590657654446
Fizz,359590657654446
409,359590657654446
Buzz,359590657654446
Fizz,359590657654446
412,359590657654446
413,359590657654446
Fizz,359590657654446
Buzz,359590657654446
416,359590657654446
Fizz,359590657654446
418,359590657654446
419,359590657654446
Fizz Buzz,359590657654446
421,359590657654446
422,359590657654446
Fizz,359590657654446
424,359590657654446
Buzz,359590657654446
Fizz,359590657654446
427,359590657654446
428,359590657654446
Fizz,359590657654446
Buzz,359590657654446
431,359590657654446
Fizz,359590657654446
433,359590657654446
434,359590657654446
Fizz Buzz,359590657654446
436,359590657654446
437,359590657654446
Fizz,359590657654446
439,359590657654446
Buzz,359590657654446
Fizz,359590657654446
442,359590657654446
443,359590657654446
Fizz,359590657654446
Buzz,359590657654446
446,359590657654446
Fizz,359590657654446
448,359590657654446
449,359590657654446
Fizz Buzz,359590657654446
451,359590657654446
452,359590657654446
Fizz,359590657654446
454,359590657654446
Buzz,359590657654446
Fizz,359590657654446
457,359590657654446
458,359590657654446
Fizz,359590657654446
Buzz,359590657654446
461,359590657654446
Fizz,359590657654446
463,359590657654446
464,359590657654446
Fizz Buzz,359590657654446
466,359590657654446
467,359590657654446
Fizz,359590657654446
469,359590657654446
Buzz,359590657654446
Fizz,359590657654446
472,359590657654446
473,359590657654446
Fizz,359590657654446
Buzz,359590657654446
476,359590657654446
Fizz,359590657654446
478,359590657654446
479,359590657654446
Fizz Buzz,359590657654446
481,359590657654446
482,359590657654446
Fizz,359590657654446
484,359590657654446
Buzz,359590657654446
Fizz,359590657654446
487,359590657654446
488,359590657654446
Fizz,359590657654446
Buzz,359590657654446
491,359590657654446
Fizz,359590657654446
493,359590657654446
494,359590657654446
Fizz Buzz,359590657654446
496,359590657654446
497,359590657654446
Fizz,359590657654446
499,359590657654446
Buzz,359590657654446
Fizz,359590657654446
502,359590657654446
503,359590657654446
Fizz,359590657654446
Buzz,359590657654446
506,359590657654446
Fizz,359590657654446
508,359590657654446
509,359590657654446
Fizz Buzz,359590657654446
511,359590657654446
512,359590657654446
Fizz,359590657654446
514,359590657654446
Buzz,359590657654446
Fizz,359590657654446
517,359590657654446
518,359590657654446
Fizz,359590657654446
Buzz,359590657654446
521,359590657654446
Fizz,359590657654446
523,359590657654446
524,359590657654446
Fizz Buzz,359590657654446
526,359590657654446
527,359590657654446
Fizz,359590657654446
529,359590657654446
Buzz,359590657654446
Fizz,359590657654446
532,359590657654446
533,359590657654446
Fizz,359590657654446
Buzz,359590657654446
536,359590657654446
Fizz,359590657654446
538,359590657654446
539,359590657654446
Fizz Buzz,359590657654446
541,359590657654446
542,359590657654446
Fizz,359590657654446
544,359590657654446
Buzz,359590657654446
Fizz,359590657654446
547,359590657654446
548,359590657654446
Fizz,359590657654446
Buzz,359590657654446
551,359590657654446
Fizz,359590657654446
553,359590657654446
554,359590657654446
Fizz Buzz,359590657654446
556,359590657654446
557,359590657654446
Fizz,359590657654446
559,359590657654446
Buzz,359590657654446
Fizz,359590657654446
562,359590657654446
563,359590657654446
Fizz,359590657654446
Buzz,359590657654446
566,359590657654446
Fizz,359590657654446
568,359590657654446
569,359590657654446
Fizz Buzz,359590657654446
571,359590657654446
572,359590657654446
Fizz,359590657654446
574,359590657654446
Buzz,359590657654446
Fizz,359590657654446
577,359590657654446
578,359590657654446
Fizz,359590657654446
Buzz,359590657654446
581,359590657654446
Fizz,359590657654446
583,359590657654446
584,359590657654446
Fizz Buzz,359590657654446
586,359590657654446
587,359590657654446
Fizz,359590657654446
589,359590657654446
Buzz,359590657654446
Fizz,359590657654446
592,359590657654446
593,359590657654446
Fizz,359590657654446
Buzz,359590657654446
596,359590657654446
Fizz,359590657654446
598,359590657654446
599,359590657654446
Fizz Buzz,359590657654446
601,359590657654446
602,359590657654446
Fizz,359590657654446
604,359590657654446
Buzz,359590657654446
Fizz,359590657654446
607,359590657654446
608,359590657654446
Fizz,359590657654446
Buzz,359590657654446
611,359590657654446
Fizz,359590657654446
613,359590657654446
614,359590657654446
Fizz Buzz,359590657654446
616,359590657654446
617,359590657654446
Fizz,359590657654446
619,359590657654446
Buzz,359590657654446
Fizz,359590657654446
622,359590657654446
623,359590657654446
Fizz,359590657654446
Buzz,359590657654446
626,359590657654446
Fizz,359590657654446
628,359590657654446
629,359590657654446
Fizz Buzz,359590657654446
631,359590657654446
632,359590657654446
Fizz,359590657654446
634,359590657654446
Buzz,359590657654446
Fizz,359590657654446
637,359590657654446
638,359590657654446
Fizz,359590657654446
Buzz,359590657654446
641,359590657654446
Fizz,359590657654446
643,359590657654446
644,359590657654446
Fizz Buzz,359590657654446
646,359590657654446
647,359590657654446
Fizz,359590657654446
649,359590657654446
Buzz,359590657654446
Fizz,359590657654446
652,359590657654446
653,359590657654446
Fizz,359590657654446
Buzz,359590657654446
656,359590657654446
Fizz,359590657654446
658,359590657654446
659,359590657654446
Fizz Buzz,359590657654446
661,359590657654446
662,359590657654446
Fizz,359590657654446
664,359590657654446
Buzz,359590657654446
Fizz,359590657654446
667,359590657654446
668,359590657654446
Fizz,359590657654446
Buzz,359590657654446
671,359590657654446
Fizz,359590657654446
673,359590657654446
674,359590657654446
Fizz Buzz,359590657654446
676,359590657654446
677,359590657654446
Fizz,359590657654446
679,359590657654446
Buzz,359590657654446
Fizz,359590657654446
682,359590657654446
683,359590657654446
Fizz,359590657654446
Buzz,359590657654446
686,359590657654446
Fizz,359590657654446
688,359590657654446
689,359590657654446
Fizz Buzz,359590657654446
691,359590657654446
692,359590657654446
Fizz,359590657654446
694,359590657654446
Buzz,359590657654446
Fizz,359590657654446
697,359590657654446
698,359590657654446
Fizz,359590657654446
Buzz,359590657654446
701,359590657654446
Fizz,359590657654446
703,359590657654446
704,359590657654446
Fizz Buzz,359590657654446
706,359590657654446
707,359590657654446
Fizz,359590657654446
709,359590657654446
Buzz,359590657654446
Fizz,359590657654446
712,359590657654446
713,359590657654446
Fizz,359590657654446
Buzz,359590657654446
716,359590657654446
Fizz,359590657654446
718,359590657654446
719,359590657654446
Fizz Buzz,359590657654446
721,359590657654446
722,359590657654446
Fizz,359590657654446
724,359590657654446
Buzz,359590657654446
Fizz,359590657654446
727,359590657654446
728,359590657654446
Fizz,359590657654446
Buzz,359590657654446
731,359590657654446
Fizz,359590657654446
733,359590657654446
734,359590657654446
Fizz Buzz,359590657654446
736,359590657654446
737,359590657654446
Fizz,359590657654446
739,359590657654446
Buzz,359590657654446
Fizz,359590657654446
742,359590657654446
743,359590657654446
Fizz,359590657654446
Buzz,359590657654446
746,359590657654446
Fizz,359590657654446
748,359590657654446
749,359590657654446
Fizz Buzz,359590657654446
751,359590657654446
752,359590657654446
Fizz,359590657654446
754,359590657654446
Buzz,359590657654446
Fizz,359590657654446
757,359590657654446
758,359590657654446
Fizz,359590657654446
Buzz,359590657654446
761,359590657654446
Fizz,359590657654446
763,359590657654446
764,359590657654446
Fizz Buzz,359590657654446
766,359590657654446
767,359590657654446
Fizz,359590657654446
769,359590657654446
Buzz,359590657654446
Fizz,359590657654446
772,359590657654446
773,359590657654446
Fizz,359590657654446
Buzz,359590657654446
776,359590657654446
Fizz,359590657654446
778,359590657654446
779,359590657654446
Fizz Buzz,359590657654446
781,359590657654446
782,359590657654446
Fizz,359590657654446
784,359590657654446
Buzz,359590657654446
Fizz,359590657654446
787,359590657654446
788,359590657654446
Fizz,359590657654446
Buzz,359590657654446
791,359590657654446
Fizz,359590657654446
793,359590657654446
794,359590657654446
Fizz Buzz,359590657654446
796,359590657654446
797,359590657654446
Fizz,359590657654446
799,359590657654446
Buzz,359590657654446
Fizz,359590657654446
802,359590657654446
803,359590657654446
Fizz,359590657654446
Buzz,359590657654446
806,359590657654446
Fizz,359590657654446
808,359590657654446
809,359590657654446
Fizz Buzz,359590657654446
811,359590657654446
812,359590657654446
Fizz,359590657654446
814,359590657654446
Buzz,359590657654446
Fizz,359590657654446
817,359590657654446
818,359590657654446
Fizz,359590657654446
Buzz,359590657654446
821,359590657654446
Fizz,359590657654446
823,359590657654446
824,359590657654446
Fizz Buzz,359590657654446
826,359590657654446
827,359590657654446
Fizz,359590657654446
829,359590657654446
Buzz,359590657654446
Fizz,359590657654446
832,359590657654446
833,359590657654446
Fizz,359590657654446
Buzz,359590657654446
836,359590657654446
Fizz,359590657654446
838,359590657654446
839,359590657654446
Fizz Buzz,359590657654446
841,359590657654446
842,359590657654446
Fizz,359590657654446
844,359590657654446
Buzz,359590657654446
Fizz,359590657654446
847,359590657654446
848,359590657654446
Fizz,359590657654446
Buzz,359590657654446
851,359590657654446
Fizz,359590657654446
853,359590657654446
854,359590657654446
Fizz Buzz,359590657654446
856,359590657654446
857,359590657654446
Fizz,359590657654446
859,359590657654446
Buzz,359590657654446
Fizz,359590657654446
862,359590657654446
863,359590657654446
Fizz,359590657654446
Buzz,359590657654446
866,359590657654446
Fizz,359590657654446
868,359590657654446
869,359590657654446
Fizz Buzz,359590657654446
871,359590657654446
872,359590657654446
Fizz,359590657654446
874,359590657654446
Buzz,359590657654446
Fizz,359590657654446
877,359590657654446
878,359590657654446
Fizz,359590657654446
Buzz,359590657654446
881,359590657654446
Fizz,359590657654446
883,359590657654446
884,359590657654446
Fizz Buzz,359590657654446
886,359590657654446
887,359590657654446
Fizz,359590657654446
889,359590657654446
Buzz,359590657654446
Fizz,359590657654446
892,359590657654446
893,359590657654446
Fizz,359590657654446
Buzz,359590657654446
896,359590657654446
Fizz,359590657654446
898,359590657654446
899,359590657654446
Fizz Buzz,359590657654446
901,359590657654446
902,359590657654446
Fizz,359590657654446
904,359590657654446
Buzz,359590657654446
Fizz,359590657654446
907,359590657654446
908,359590657654446
Fizz,359590657654446
Buzz,359590657654446
911,359590657654446
Fizz,359590657654446
913,359590657654446
914,359590657654446
Fizz Buzz,359590657654446
916,359590657654446
917,359590657654446
Fizz,359590657654446
919,359590657654446
Buzz,359590657654446
Fizz,359590657654446
922,359590657654446
923,359590657654446
Fizz,359590657654446
Buzz,359590657654446
926,359590657654446
Fizz,359590657654446
928,359590657654446
929,359590657654446
Fizz Buzz,359590657654446
931,359590657654446
932,359590657654446
Fizz,359590657654446
934,359590657654446
Buzz,359590657654446
Fizz,359590657654446
937,359590657654446
938,359590657654446
Fizz,359590657654446
Buzz,359590657654446
941,359590657654446
Fizz,359590657654446
943,359590657654446
944,359590657654446
Fizz Buzz,359590657654446
946,359590657654446
947,359590657654446
Fizz,359590657654446
949,359590657654446
Buzz,359590657654446
Fizz,359590657654446
952,359590657654446
953,359590657654446
Fizz,359590657654446
Buzz,359590657654446
956,359590657654446
Fizz,359590657654446
958,359590657654446
959,359590657654446
Fizz Buzz,359590657654446
961,359590657654446
962,359590657654446
Fizz,359590657654446

In [ ]:
assert '.'.join(col['fizzbuzz'][8:16]).lower() == x

### Entiers automorphes

**Exercice [010].** Un entier $n$ est **automorphe** si son carré se termine par $n$ (en écriture décimale).

| Exemple | Carré | Automorphe |
|---:|:--:|:--:|
| $5$ | $25$ | ✅
| $25$ | $625$ | ✅ |
| $7$ | $49$ | ❌ |

_Tâche._ Listez par ordre croissant les entiers automorphes inférieurs ou égaux à 1000.

In [ ]:
%%sql
-- Avec la fonction de concaténation et l'opérateur `LIKE`.
SELECT i
     , salt_010(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE cast(i * i AS CHAR) LIKE concat('%', cast(i AS CHAR))

8 rows affected.

i,token
0,155147806452639
1,155147806452639
5,155147806452639
6,155147806452639
25,155147806452639
76,155147806452639
376,155147806452639
625,155147806452639

In [ ]:
%%sql
-- Variante. En extrayant le bon nombre de caractères à droite et en comparant. L'observation de l'exercice sur
-- les palindromes reste valable ici : MySQL pourrait se passer des opérations de conversion explicite, ce qui
-- rendrait certainement l'expression plus lisible.
SELECT i
     , salt_010(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE right(cast(i * i AS CHAR), length(cast(i AS CHAR))) = cast(i AS CHAR)

8 rows affected.

i,token
0,155147806452639
1,155147806452639
5,155147806452639
6,155147806452639
25,155147806452639
76,155147806452639
376,155147806452639
625,155147806452639

### Nombres bicarrés

**Exercice [032].** Un entier $c$ est **bicarré** si et seulement s'il peut s'écrire sous la forme $a^2+b^2$ avec $a$ et $b$ entiers.

| Exemple | Forme cherchée | Bicarré |
|---:|:--:|:--:|
| $17$ | $$1^2+4^2$$ | ✅ |
| $15$ | aucune | ❌ |

_Tâche._ Listez par ordre croissant les entiers bicarrés inférieurs ou égaux à 1000.

_Contrainte._ Faites un produit cartésien de trois tables.

<figure>
  <img src="https://raw.githubusercontent.com/laowantong/sqlab_ints/refs/heads/main/assets/nombre-bigarré.png"/>
  <figcaption>Entier bicarré et bigarré.</figcaption>
</figure>

In [ ]:
x = 8 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT DISTINCT C.i
              , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints C
JOIN ints A ON A.i * A.i <= C.i
JOIN ints B ON A.i * A.i + B.i * B.i = C.i
ORDER BY 1

331 rows affected.

i,token
0,1230160502988882
1,1230160502988882
2,1230160502988882
4,1230160502988882
5,1230160502988882
8,1230160502988882
9,1230160502988882
10,1230160502988882
13,1230160502988882
16,1230160502988882
17,1230160502988882
18,1230160502988882
20,1230160502988882
25,1230160502988882
26,1230160502988882
29,1230160502988882
32,1230160502988882
34,1230160502988882
36,1230160502988882
37,1230160502988882
40,1230160502988882
41,1230160502988882
45,1230160502988882
49,1230160502988882
50,1230160502988882
52,1230160502988882
53,1230160502988882
58,1230160502988882
61,1230160502988882
64,1230160502988882
65,1230160502988882
68,1230160502988882
72,1230160502988882
73,1230160502988882
74,1230160502988882
80,1230160502988882
81,1230160502988882
82,1230160502988882
85,1230160502988882
89,1230160502988882
90,1230160502988882
97,1230160502988882
98,1230160502988882
100,1230160502988882
101,1230160502988882
104,1230160502988882
106,1230160502988882
109,1230160502988882
113,1230160502988882
116,1230160502988882
117,1230160502988882
121,1230160502988882
122,1230160502988882
125,1230160502988882
128,1230160502988882
130,1230160502988882
136,1230160502988882
137,1230160502988882
144,1230160502988882
145,1230160502988882
146,1230160502988882
148,1230160502988882
149,1230160502988882
153,1230160502988882
157,1230160502988882
160,1230160502988882
162,1230160502988882
164,1230160502988882
169,1230160502988882
170,1230160502988882
173,1230160502988882
178,1230160502988882
180,1230160502988882
181,1230160502988882
185,1230160502988882
193,1230160502988882
194,1230160502988882
196,1230160502988882
197,1230160502988882
200,1230160502988882
202,1230160502988882
205,1230160502988882
208,1230160502988882
212,1230160502988882
218,1230160502988882
221,1230160502988882
225,1230160502988882
226,1230160502988882
229,1230160502988882
232,1230160502988882
233,1230160502988882
234,1230160502988882
241,1230160502988882
242,1230160502988882
244,1230160502988882
245,1230160502988882
250,1230160502988882
256,1230160502988882
257,1230160502988882
260,1230160502988882
261,1230160502988882
265,1230160502988882
269,1230160502988882
272,1230160502988882
274,1230160502988882
277,1230160502988882
281,1230160502988882
288,1230160502988882
289,1230160502988882
290,1230160502988882
292,1230160502988882
293,1230160502988882
296,1230160502988882
298,1230160502988882
305,1230160502988882
306,1230160502988882
313,1230160502988882
314,1230160502988882
317,1230160502988882
320,1230160502988882
324,1230160502988882
325,1230160502988882
328,1230160502988882
333,1230160502988882
337,1230160502988882
338,1230160502988882
340,1230160502988882
346,1230160502988882
349,1230160502988882
353,1230160502988882
356,1230160502988882
360,1230160502988882
361,1230160502988882
362,1230160502988882
365,1230160502988882
369,1230160502988882
370,1230160502988882
373,1230160502988882
377,1230160502988882
386,1230160502988882
388,1230160502988882
389,1230160502988882
392,1230160502988882
394,1230160502988882
397,1230160502988882
400,1230160502988882
401,1230160502988882
404,1230160502988882
405,1230160502988882
409,1230160502988882
410,1230160502988882
416,1230160502988882
421,1230160502988882
424,1230160502988882
425,1230160502988882
433,1230160502988882
436,1230160502988882
441,1230160502988882
442,1230160502988882
445,1230160502988882
449,1230160502988882
450,1230160502988882
452,1230160502988882
457,1230160502988882
458,1230160502988882
461,1230160502988882
464,1230160502988882
466,1230160502988882
468,1230160502988882
477,1230160502988882
481,1230160502988882
482,1230160502988882
484,1230160502988882
485,1230160502988882
488,1230160502988882
490,1230160502988882
493,1230160502988882
500,1230160502988882
505,1230160502988882
509,1230160502988882
512,1230160502988882
514,1230160502988882
520,1230160502988882
521,1230160502988882
522,1230160502988882
529,1230160502988882
530,1230160502988882
533,1230160502988882
538,1230160502988882
541,1230160502988882
544,1230160502988882
545,1230160502988882
548,1230160502988882
549,1230160502988882
554,1230160502988882
557,1230160502988882
562,1230160502988882
565,1230160502988882
569,1230160502988882
576,1230160502988882
577,1230160502988882
578,1230160502988882
580,1230160502988882
584,1230160502988882
585,1230160502988882
586,1230160502988882
592,1230160502988882
593,1230160502988882
596,1230160502988882
601,1230160502988882
605,1230160502988882
610,1230160502988882
612,1230160502988882
613,1230160502988882
617,1230160502988882
625,1230160502988882
626,1230160502988882
628,1230160502988882
629,1230160502988882
634,1230160502988882
637,1230160502988882
640,1230160502988882
641,1230160502988882
648,1230160502988882
650,1230160502988882
653,1230160502988882
656,1230160502988882
657,1230160502988882
661,1230160502988882
666,1230160502988882
673,1230160502988882
674,1230160502988882
676,1230160502988882
677,1230160502988882
680,1230160502988882
685,1230160502988882
689,1230160502988882
692,1230160502988882
697,1230160502988882
698,1230160502988882
701,1230160502988882
706,1230160502988882
709,1230160502988882
712,1230160502988882
720,1230160502988882
722,1230160502988882
724,1230160502988882
725,1230160502988882
729,1230160502988882
730,1230160502988882
733,1230160502988882
738,1230160502988882
740,1230160502988882
745,1230160502988882
746,1230160502988882
754,1230160502988882
757,1230160502988882
761,1230160502988882
765,1230160502988882
769,1230160502988882
772,1230160502988882
773,1230160502988882
776,1230160502988882
778,1230160502988882
784,1230160502988882
785,1230160502988882
788,1230160502988882
793,1230160502988882
794,1230160502988882
797,1230160502988882
800,1230160502988882
801,1230160502988882
802,1230160502988882
808,1230160502988882
809,1230160502988882
810,1230160502988882
818,1230160502988882
820,1230160502988882
821,1230160502988882
829,1230160502988882
832,1230160502988882
833,1230160502988882
841,1230160502988882
842,1230160502988882
845,1230160502988882
848,1230160502988882
850,1230160502988882
853,1230160502988882
857,1230160502988882
865,1230160502988882
866,1230160502988882
872,1230160502988882
873,1230160502988882
877,1230160502988882
881,1230160502988882
882,1230160502988882
884,1230160502988882
890,1230160502988882
898,1230160502988882
900,1230160502988882
901,1230160502988882
904,1230160502988882
905,1230160502988882
909,1230160502988882
914,1230160502988882
916,1230160502988882
922,1230160502988882
925,1230160502988882
928,1230160502988882
929,1230160502988882
932,1230160502988882
936,1230160502988882
937,1230160502988882
941,1230160502988882
949,1230160502988882
953,1230160502988882
954,1230160502988882
961,1230160502988882
962,1230160502988882
964,1230160502988882
965,1230160502988882
968,1230160502988882
970,1230160502988882
976,1230160502988882
977,1230160502988882
980,1230160502988882
981,1230160502988882
985,1230160502988882
986,1230160502988882
997,1230160502988882
1000,1230160502988882

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 4

In [ ]:
%%sql
-- Indication. Supprimez les doublons.
SELECT A.i
     , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i * B.i <= A.i
JOIN ints C ON C.i * C.i <= A.i
WHERE B.i * B.i + C.i * C.i = A.i
ORDER BY 1

819 rows affected.

i,token
0,1230160502988894
1,1230160502988894
1,1230160502988894
2,1230160502988894
4,1230160502988894
4,1230160502988894
5,1230160502988894
5,1230160502988894
8,1230160502988894
9,1230160502988894
9,1230160502988894
10,1230160502988894
10,1230160502988894
13,1230160502988894
13,1230160502988894
16,1230160502988894
16,1230160502988894
17,1230160502988894
17,1230160502988894
18,1230160502988894
20,1230160502988894
20,1230160502988894
25,1230160502988894
25,1230160502988894
25,1230160502988894
25,1230160502988894
26,1230160502988894
26,1230160502988894
29,1230160502988894
29,1230160502988894
32,1230160502988894
34,1230160502988894
34,1230160502988894
36,1230160502988894
36,1230160502988894
37,1230160502988894
37,1230160502988894
40,1230160502988894
40,1230160502988894
41,1230160502988894
41,1230160502988894
45,1230160502988894
45,1230160502988894
49,1230160502988894
49,1230160502988894
50,1230160502988894
50,1230160502988894
50,1230160502988894
52,1230160502988894
52,1230160502988894
53,1230160502988894
53,1230160502988894
58,1230160502988894
58,1230160502988894
61,1230160502988894
61,1230160502988894
64,1230160502988894
64,1230160502988894
65,1230160502988894
65,1230160502988894
65,1230160502988894
65,1230160502988894
68,1230160502988894
68,1230160502988894
72,1230160502988894
73,1230160502988894
73,1230160502988894
74,1230160502988894
74,1230160502988894
80,1230160502988894
80,1230160502988894
81,1230160502988894
81,1230160502988894
82,1230160502988894
82,1230160502988894
85,1230160502988894
85,1230160502988894
85,1230160502988894
85,1230160502988894
89,1230160502988894
89,1230160502988894
90,1230160502988894
90,1230160502988894
97,1230160502988894
97,1230160502988894
98,1230160502988894
100,1230160502988894
100,1230160502988894
100,1230160502988894
100,1230160502988894
101,1230160502988894
101,1230160502988894
104,1230160502988894
104,1230160502988894
106,1230160502988894
106,1230160502988894
109,1230160502988894
109,1230160502988894
113,1230160502988894
113,1230160502988894
116,1230160502988894
116,1230160502988894
117,1230160502988894
117,1230160502988894
121,1230160502988894
121,1230160502988894
122,1230160502988894
122,1230160502988894
125,1230160502988894
125,1230160502988894
125,1230160502988894
125,1230160502988894
128,1230160502988894
130,1230160502988894
130,1230160502988894
130,1230160502988894
130,1230160502988894
136,1230160502988894
136,1230160502988894
137,1230160502988894
137,1230160502988894
144,1230160502988894
144,1230160502988894
145,1230160502988894
145,1230160502988894
145,1230160502988894
145,1230160502988894
146,1230160502988894
146,1230160502988894
148,1230160502988894
148,1230160502988894
149,1230160502988894
149,1230160502988894
153,1230160502988894
153,1230160502988894
157,1230160502988894
157,1230160502988894
160,1230160502988894
160,1230160502988894
162,1230160502988894
164,1230160502988894
164,1230160502988894
169,1230160502988894
169,1230160502988894
169,1230160502988894
169,1230160502988894
170,1230160502988894
170,1230160502988894
170,1230160502988894
170,1230160502988894
173,1230160502988894
173,1230160502988894
178,1230160502988894
178,1230160502988894
180,1230160502988894
180,1230160502988894
181,1230160502988894
181,1230160502988894
185,1230160502988894
185,1230160502988894
185,1230160502988894
185,1230160502988894
193,1230160502988894
193,1230160502988894
194,1230160502988894
194,1230160502988894
196,1230160502988894
196,1230160502988894
197,1230160502988894
197,1230160502988894
200,1230160502988894
200,1230160502988894
200,1230160502988894
202,1230160502988894
202,1230160502988894
205,1230160502988894
205,1230160502988894
205,1230160502988894
205,1230160502988894
208,1230160502988894
208,1230160502988894
212,1230160502988894
212,1230160502988894
218,1230160502988894
218,1230160502988894
221,1230160502988894
221,1230160502988894
221,1230160502988894
221,1230160502988894
225,1230160502988894
225,1230160502988894
225,1230160502988894
225,1230160502988894
226,1230160502988894
226,1230160502988894
229,1230160502988894
229,1230160502988894
232,1230160502988894
232,1230160502988894
233,1230160502988894
233,1230160502988894
234,1230160502988894
234,1230160502988894
241,1230160502988894
241,1230160502988894
242,1230160502988894
244,1230160502988894
244,1230160502988894
245,1230160502988894
245,1230160502988894
250,1230160502988894
250,1230160502988894
250,1230160502988894
250,1230160502988894
256,1230160502988894
256,1230160502988894
257,1230160502988894
257,1230160502988894
260,1230160502988894
260,1230160502988894
260,1230160502988894
260,1230160502988894
261,1230160502988894
261,1230160502988894
265,1230160502988894
265,1230160502988894
265,1230160502988894
265,1230160502988894
269,1230160502988894
269,1230160502988894
272,1230160502988894
272,1230160502988894
274,1230160502988894
274,1230160502988894
277,1230160502988894
277,1230160502988894
281,1230160502988894
281,1230160502988894
288,1230160502988894
289,1230160502988894
289,1230160502988894
289,1230160502988894
289,1230160502988894
290,1230160502988894
290,1230160502988894
290,1230160502988894
290,1230160502988894
292,1230160502988894
292,1230160502988894
293,1230160502988894
293,1230160502988894
296,1230160502988894
296,1230160502988894
298,1230160502988894
298,1230160502988894
305,1230160502988894
305,1230160502988894
305,1230160502988894
305,1230160502988894
306,1230160502988894
306,1230160502988894
313,1230160502988894
313,1230160502988894
314,1230160502988894
314,1230160502988894
317,1230160502988894
317,1230160502988894
320,1230160502988894
320,1230160502988894
324,1230160502988894
324,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
328,1230160502988894
328,1230160502988894
333,1230160502988894
333,1230160502988894
337,1230160502988894
337,1230160502988894
338,1230160502988894
338,1230160502988894
338,1230160502988894
340,1230160502988894
340,1230160502988894
340,1230160502988894
340,1230160502988894
346,1230160502988894
346,1230160502988894
349,1230160502988894
349,1230160502988894
353,1230160502988894
353,1230160502988894
356,1230160502988894
356,1230160502988894
360,1230160502988894
360,1230160502988894
361,1230160502988894
361,1230160502988894
362,1230160502988894
362,1230160502988894
365,1230160502988894
365,1230160502988894
365,1230160502988894
365,1230160502988894
369,1230160502988894
369,1230160502988894
370,1230160502988894
370,1230160502988894
370,1230160502988894
370,1230160502988894
373,1230160502988894
373,1230160502988894
377,1230160502988894
377,1230160502988894
377,1230160502988894
377,1230160502988894
386,1230160502988894
386,1230160502988894
388,1230160502988894
388,1230160502988894
389,1230160502988894
389,1230160502988894
392,1230160502988894
394,1230160502988894
394,1230160502988894
397,1230160502988894
397,1230160502988894
400,1230160502988894
400,1230160502988894
400,1230160502988894
400,1230160502988894
401,1230160502988894
401,1230160502988894
404,1230160502988894
404,1230160502988894
405,1230160502988894
405,1230160502988894
409,1230160502988894
409,1230160502988894
410,1230160502988894
410,1230160502988894
410,1230160502988894
410,1230160502988894
416,1230160502988894
416,1230160502988894
421,1230160502988894
421,1230160502988894
424,1230160502988894
424,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
433,1230160502988894
433,1230160502988894
436,1230160502988894
436,1230160502988894
441,1230160502988894
441,1230160502988894
442,1230160502988894
442,1230160502988894
442,1230160502988894
442,1230160502988894
445,1230160502988894
445,1230160502988894
445,1230160502988894
445,1230160502988894
449,1230160502988894
449,1230160502988894
450,1230160502988894
450,1230160502988894
450,1230160502988894
452,1230160502988894
452,1230160502988894
457,1230160502988894
457,1230160502988894
458,1230160502988894
458,1230160502988894
461,1230160502988894
461,1230160502988894
464,1230160502988894
464,1230160502988894
466,1230160502988894
466,1230160502988894
468,1230160502988894
468,1230160502988894
477,1230160502988894
477,1230160502988894
481,1230160502988894
481,1230160502988894
481,1230160502988894
481,1230160502988894
482,1230160502988894
482,1230160502988894
484,1230160502988894
484,1230160502988894
485,1230160502988894
485,1230160502988894
485,1230160502988894
485,1230160502988894
488,1230160502988894
488,1230160502988894
490,1230160502988894
490,1230160502988894
493,1230160502988894
493,1230160502988894
493,1230160502988894
493,1230160502988894
500,1230160502988894
500,1230160502988894
500,1230160502988894
500,1230160502988894
505,1230160502988894
505,1230160502988894
505,1230160502988894
505,1230160502988894
509,1230160502988894
509,1230160502988894
512,1230160502988894
514,1230160502988894
514,1230160502988894
520,1230160502988894
520,1230160502988894
520,1230160502988894
520,1230160502988894
521,1230160502988894
521,1230160502988894
522,1230160502988894
522,1230160502988894
529,1230160502988894
529,1230160502988894
530,1230160502988894
530,1230160502988894
530,1230160502988894
530,1230160502988894
533,1230160502988894
533,1230160502988894
533,1230160502988894
533,1230160502988894
538,1230160502988894
538,1230160502988894
541,1230160502988894
541,1230160502988894
544,1230160502988894
544,1230160502988894
545,1230160502988894
545,1230160502988894
545,1230160502988894
545,1230160502988894
548,1230160502988894
548,1230160502988894
549,1230160502988894
549,1230160502988894
554,1230160502988894
554,1230160502988894
557,1230160502988894
557,1230160502988894
562,1230160502988894
562,1230160502988894
565,1230160502988894
565,1230160502988894
565,1230160502988894
565,1230160502988894
569,1230160502988894
569,1230160502988894
576,1230160502988894
576,1230160502988894
577,1230160502988894
577,1230160502988894
578,1230160502988894
578,1230160502988894
578,1230160502988894
580,1230160502988894
580,1230160502988894
580,1230160502988894
580,1230160502988894
584,1230160502988894
584,1230160502988894
585,1230160502988894
585,1230160502988894
585,1230160502988894
585,1230160502988894
586,1230160502988894
586,1230160502988894
592,1230160502988894
592,1230160502988894
593,1230160502988894
593,1230160502988894
596,1230160502988894
596,1230160502988894
601,1230160502988894
601,1230160502988894
605,1230160502988894
605,1230160502988894
610,1230160502988894
610,1230160502988894
610,1230160502988894
610,1230160502988894
612,1230160502988894
612,1230160502988894
613,1230160502988894
613,1230160502988894
617,1230160502988894
617,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
626,1230160502988894
626,1230160502988894
628,1230160502988894
628,1230160502988894
629,1230160502988894
629,1230160502988894
629,1230160502988894
629,1230160502988894
634,1230160502988894
634,1230160502988894
637,1230160502988894
637,1230160502988894
640,1230160502988894
640,1230160502988894
641,1230160502988894
641,1230160502988894
648,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
653,1230160502988894
653,1230160502988894
656,1230160502988894
656,1230160502988894
657,1230160502988894
657,1230160502988894
661,1230160502988894
661,1230160502988894
666,1230160502988894
666,1230160502988894
673,1230160502988894
673,1230160502988894
674,1230160502988894
674,1230160502988894
676,1230160502988894
676,1230160502988894
676,1230160502988894
676,1230160502988894
677,1230160502988894
677,1230160502988894
680,1230160502988894
680,1230160502988894
680,1230160502988894
680,1230160502988894
685,1230160502988894
685,1230160502988894
685,1230160502988894
685,1230160502988894
689,1230160502988894
689,1230160502988894
689,1230160502988894
689,1230160502988894
692,1230160502988894
692,1230160502988894
697,1230160502988894
697,1230160502988894
697,1230160502988894
697,1230160502988894
698,1230160502988894
698,1230160502988894
701,1230160502988894
701,1230160502988894
706,1230160502988894
706,1230160502988894
709,1230160502988894
709,1230160502988894
712,1230160502988894
712,1230160502988894
720,1230160502988894
720,1230160502988894
722,1230160502988894
724,1230160502988894
724,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
729,1230160502988894
729,1230160502988894
730,1230160502988894
730,1230160502988894
730,1230160502988894
730,1230160502988894
733,1230160502988894
733,1230160502988894
738,1230160502988894
738,1230160502988894
740,1230160502988894
740,1230160502988894
740,1230160502988894
740,1230160502988894
745,1230160502988894
745,1230160502988894
745,1230160502988894
745,1230160502988894
746,1230160502988894
746,1230160502988894
754,1230160502988894
754,1230160502988894
754,1230160502988894
754,1230160502988894
757,1230160502988894
757,1230160502988894
761,1230160502988894
761,1230160502988894
765,1230160502988894
765,1230160502988894
765,1230160502988894
765,1230160502988894
769,1230160502988894
769,1230160502988894
772,1230160502988894
772,1230160502988894
773,1230160502988894
773,1230160502988894
776,1230160502988894
776,1230160502988894
778,1230160502988894
778,1230160502988894
784,1230160502988894
784,1230160502988894
785,1230160502988894
785,1230160502988894
785,1230160502988894
785,1230160502988894
788,1230160502988894
788,1230160502988894
793,1230160502988894
793,1230160502988894
793,1230160502988894
793,1230160502988894
794,1230160502988894
794,1230160502988894
797,1230160502988894
797,1230160502988894
800,1230160502988894
800,1230160502988894
800,1230160502988894
801,1230160502988894
801,1230160502988894
802,1230160502988894
802,1230160502988894
808,1230160502988894
808,1230160502988894
809,1230160502988894
809,1230160502988894
810,1230160502988894
810,1230160502988894
818,1230160502988894
818,1230160502988894
820,1230160502988894
820,1230160502988894
820,1230160502988894
820,1230160502988894
821,1230160502988894
821,1230160502988894
829,1230160502988894
829,1230160502988894
832,1230160502988894
832,1230160502988894
833,1230160502988894
833,1230160502988894
841,1230160502988894
841,1230160502988894
841,1230160502988894
841,1230160502988894
842,1230160502988894
842,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
848,1230160502988894
848,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
853,1230160502988894
853,1230160502988894
857,1230160502988894
857,1230160502988894
865,1230160502988894
865,1230160502988894
865,1230160502988894
865,1230160502988894
866,1230160502988894
866,1230160502988894
872,1230160502988894
872,1230160502988894
873,1230160502988894
873,1230160502988894
877,1230160502988894
877,1230160502988894
881,1230160502988894
881,1230160502988894
882,1230160502988894
884,1230160502988894
884,1230160502988894
884,1230160502988894
884,1230160502988894
890,1230160502988894
890,1230160502988894
890,1230160502988894
890,1230160502988894
898,1230160502988894
898,1230160502988894
900,1230160502988894
900,1230160502988894
900,1230160502988894
900,1230160502988894
901,1230160502988894
901,1230160502988894
901,1230160502988894
901,1230160502988894
904,1230160502988894
904,1230160502988894
905,1230160502988894
905,1230160502988894
905,1230160502988894
905,1230160502988894
909,1230160502988894
909,1230160502988894
914,1230160502988894
914,1230160502988894
916,1230160502988894
916,1230160502988894
922,1230160502988894
922,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
928,1230160502988894
928,1230160502988894
929,1230160502988894
929,1230160502988894
932,1230160502988894
932,1230160502988894
936,1230160502988894
936,1230160502988894
937,1230160502988894
937,1230160502988894
941,1230160502988894
941,1230160502988894
949,1230160502988894
949,1230160502988894
949,1230160502988894
949,1230160502988894
953,1230160502988894
953,1230160502988894
954,1230160502988894
954,1230160502988894
961,1230160502988894
961,1230160502988894
962,1230160502988894
962,1230160502988894
962,1230160502988894
962,1230160502988894
964,1230160502988894
964,1230160502988894
965,1230160502988894
965,1230160502988894
965,1230160502988894
965,1230160502988894
968,1230160502988894
970,1230160502988894
970,1230160502988894
970,1230160502988894
970,1230160502988894
976,1230160502988894
976,1230160502988894
977,1230160502988894
977,1230160502988894
980,1230160502988894
980,1230160502988894
981,1230160502988894
981,1230160502988894
985,1230160502988894
985,1230160502988894
985,1230160502988894
985,1230160502988894
986,1230160502988894
986,1230160502988894
986,1230160502988894
986,1230160502988894
997,1230160502988894
997,1230160502988894
1000,1230160502988894
1000,1230160502988894
1000,1230160502988894
1000,1230160502988894

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 676

In [ ]:
%%sql
-- Indication. Triez ces nombres par ordre croissant.
SELECT DISTINCT A.i
              , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i * B.i <= A.i
JOIN ints C ON C.i * C.i <= A.i
WHERE B.i * B.i + C.i * C.i = A.i

331 rows affected.

i,token
961,1230160502992190
900,1230160502992190
841,1230160502992190
784,1230160502992190
729,1230160502992190
676,1230160502992190
625,1230160502992190
576,1230160502992190
529,1230160502992190
484,1230160502992190
441,1230160502992190
400,1230160502992190
361,1230160502992190
324,1230160502992190
289,1230160502992190
256,1230160502992190
225,1230160502992190
196,1230160502992190
169,1230160502992190
144,1230160502992190
121,1230160502992190
100,1230160502992190
81,1230160502992190
64,1230160502992190
49,1230160502992190
36,1230160502992190
25,1230160502992190
16,1230160502992190
9,1230160502992190
4,1230160502992190
1,1230160502992190
0,1230160502992190
962,1230160502992190
901,1230160502992190
842,1230160502992190
785,1230160502992190
730,1230160502992190
677,1230160502992190
626,1230160502992190
577,1230160502992190
530,1230160502992190
485,1230160502992190
442,1230160502992190
401,1230160502992190
362,1230160502992190
325,1230160502992190
290,1230160502992190
257,1230160502992190
226,1230160502992190
197,1230160502992190
170,1230160502992190
145,1230160502992190
122,1230160502992190
101,1230160502992190
82,1230160502992190
65,1230160502992190
50,1230160502992190
37,1230160502992190
26,1230160502992190
17,1230160502992190
10,1230160502992190
5,1230160502992190
2,1230160502992190
965,1230160502992190
904,1230160502992190
845,1230160502992190
788,1230160502992190
733,1230160502992190
680,1230160502992190
629,1230160502992190
580,1230160502992190
533,1230160502992190
488,1230160502992190
445,1230160502992190
404,1230160502992190
365,1230160502992190
328,1230160502992190
293,1230160502992190
260,1230160502992190
229,1230160502992190
200,1230160502992190
173,1230160502992190
148,1230160502992190
125,1230160502992190
104,1230160502992190
85,1230160502992190
68,1230160502992190
53,1230160502992190
40,1230160502992190
29,1230160502992190
20,1230160502992190
13,1230160502992190
8,1230160502992190
970,1230160502992190
909,1230160502992190
850,1230160502992190
793,1230160502992190
738,1230160502992190
685,1230160502992190
634,1230160502992190
585,1230160502992190
538,1230160502992190
493,1230160502992190
450,1230160502992190
409,1230160502992190
370,1230160502992190
333,1230160502992190
298,1230160502992190
265,1230160502992190
234,1230160502992190
205,1230160502992190
178,1230160502992190
153,1230160502992190
130,1230160502992190
109,1230160502992190
90,1230160502992190
73,1230160502992190
58,1230160502992190
45,1230160502992190
34,1230160502992190
18,1230160502992190
977,1230160502992190
916,1230160502992190
857,1230160502992190
800,1230160502992190
745,1230160502992190
692,1230160502992190
641,1230160502992190
592,1230160502992190
545,1230160502992190
500,1230160502992190
457,1230160502992190
416,1230160502992190
377,1230160502992190
340,1230160502992190
305,1230160502992190
272,1230160502992190
241,1230160502992190
212,1230160502992190
185,1230160502992190
160,1230160502992190
137,1230160502992190
116,1230160502992190
97,1230160502992190
80,1230160502992190
52,1230160502992190
41,1230160502992190
32,1230160502992190
986,1230160502992190
925,1230160502992190
866,1230160502992190
809,1230160502992190
754,1230160502992190
701,1230160502992190
650,1230160502992190
601,1230160502992190
554,1230160502992190
509,1230160502992190
466,1230160502992190
425,1230160502992190
386,1230160502992190
349,1230160502992190
314,1230160502992190
281,1230160502992190
250,1230160502992190
221,1230160502992190
194,1230160502992190
146,1230160502992190
106,1230160502992190
89,1230160502992190
74,1230160502992190
61,1230160502992190
997,1230160502992190
936,1230160502992190
877,1230160502992190
820,1230160502992190
765,1230160502992190
712,1230160502992190
661,1230160502992190
612,1230160502992190
565,1230160502992190
520,1230160502992190
477,1230160502992190
436,1230160502992190
397,1230160502992190
360,1230160502992190
292,1230160502992190
261,1230160502992190
232,1230160502992190
180,1230160502992190
157,1230160502992190
136,1230160502992190
117,1230160502992190
72,1230160502992190
949,1230160502992190
890,1230160502992190
833,1230160502992190
778,1230160502992190
725,1230160502992190
674,1230160502992190
578,1230160502992190
490,1230160502992190
449,1230160502992190
410,1230160502992190
373,1230160502992190
338,1230160502992190
274,1230160502992190
245,1230160502992190
218,1230160502992190
193,1230160502992190
149,1230160502992190
113,1230160502992190
98,1230160502992190
964,1230160502992190
905,1230160502992190
848,1230160502992190
740,1230160502992190
689,1230160502992190
640,1230160502992190
593,1230160502992190
548,1230160502992190
505,1230160502992190
464,1230160502992190
388,1230160502992190
353,1230160502992190
320,1230160502992190
233,1230160502992190
208,1230160502992190
164,1230160502992190
128,1230160502992190
981,1230160502992190
922,1230160502992190
865,1230160502992190
810,1230160502992190
757,1230160502992190
706,1230160502992190
657,1230160502992190
610,1230160502992190
522,1230160502992190
481,1230160502992190
405,1230160502992190
337,1230160502992190
306,1230160502992190
277,1230160502992190
202,1230160502992190
181,1230160502992190
162,1230160502992190
1000,1230160502992190
941,1230160502992190
884,1230160502992190
829,1230160502992190
776,1230160502992190
584,1230160502992190
541,1230160502992190
461,1230160502992190
424,1230160502992190
389,1230160502992190
356,1230160502992190
296,1230160502992190
269,1230160502992190
244,1230160502992190
797,1230160502992190
746,1230160502992190
697,1230160502992190
605,1230160502992190
562,1230160502992190
521,1230160502992190
482,1230160502992190
346,1230160502992190
317,1230160502992190
242,1230160502992190
985,1230160502992190
928,1230160502992190
873,1230160502992190
769,1230160502992190
720,1230160502992190
673,1230160502992190
628,1230160502992190
544,1230160502992190
468,1230160502992190
433,1230160502992190
369,1230160502992190
313,1230160502992190
288,1230160502992190
953,1230160502992190
898,1230160502992190
794,1230160502992190
698,1230160502992190
653,1230160502992190
569,1230160502992190
458,1230160502992190
394,1230160502992190
980,1230160502992190
872,1230160502992190
821,1230160502992190
772,1230160502992190
637,1230160502992190
596,1230160502992190
557,1230160502992190
452,1230160502992190
421,1230160502992190
392,1230160502992190
954,1230160502992190
801,1230160502992190
709,1230160502992190
666,1230160502992190
586,1230160502992190
549,1230160502992190
514,1230160502992190
932,1230160502992190
881,1230160502992190
832,1230160502992190
656,1230160502992190
617,1230160502992190
512,1230160502992190
914,1230160502992190
818,1230160502992190
773,1230160502992190
613,1230160502992190
853,1230160502992190
808,1230160502992190
724,1230160502992190
648,1230160502992190
937,1230160502992190
802,1230160502992190
761,1230160502992190
722,1230160502992190
976,1230160502992190
929,1230160502992190
882,1230160502992190
968,1230160502992190

In [ ]:
assert col['i'][5] == x

**Exercice [033].** Un entier $c$ est **bicarré** si et seulement s'il peut s'écrire sous la forme $a^2+b^2$ avec $a$ et $b$ entiers.

| Exemple | Forme cherchée | Bicarré |
|---:|:--:|:--:|
| $17$ | $$1^2+4^2$$ | ✅ |
| $15$ | aucune | ❌ |

_Tâche._ Listez par ordre croissant les entiers bicarrés inférieurs ou égaux à 1000.

_Contrainte._ Faites un produit cartésien de deux tables seulement.

<figure>
  <img src="https://raw.githubusercontent.com/laowantong/sqlab_ints/refs/heads/main/assets/nombre-non-bigarré.png"/>
  <figcaption>Entier non bicarré ni bigarré.</figcaption>
</figure>

In [ ]:
x = 8 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
-- On fait deux « boucles », l'une sur $a$, l'autre sur $b$.
-- Plutôt que de « parcourir » tous les $c$ possibles, et éliminer ceux qui ne valent pas $a^2 + b^2$,
-- on calcule directement $c = a^2 + b^2$, et on vérifie que cette somme est bien dans la table donnée
-- (pour plus de généralité, on aurait pu écrire `A.i * A.i + B.i * B.i IN (SELECT i FROM ints)`).
-- La deuxième condition du `ON` évite les doublons par symétrie (p. ex., (3, 4) et (4, 3)).
SELECT DISTINCT A.i * A.i + B.i * B.i AS i
              , salt_033({{x}} + sum(nn(A.hash) + nn(B.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i * A.i + B.i * B.i <= 1000
AND A.i <= B.i
ORDER BY 1

331 rows affected.

i,token
0,298774613720463
1,298774613720463
2,298774613720463
4,298774613720463
5,298774613720463
8,298774613720463
9,298774613720463
10,298774613720463
13,298774613720463
16,298774613720463
17,298774613720463
18,298774613720463
20,298774613720463
25,298774613720463
26,298774613720463
29,298774613720463
32,298774613720463
34,298774613720463
36,298774613720463
37,298774613720463
40,298774613720463
41,298774613720463
45,298774613720463
49,298774613720463
50,298774613720463
52,298774613720463
53,298774613720463
58,298774613720463
61,298774613720463
64,298774613720463
65,298774613720463
68,298774613720463
72,298774613720463
73,298774613720463
74,298774613720463
80,298774613720463
81,298774613720463
82,298774613720463
85,298774613720463
89,298774613720463
90,298774613720463
97,298774613720463
98,298774613720463
100,298774613720463
101,298774613720463
104,298774613720463
106,298774613720463
109,298774613720463
113,298774613720463
116,298774613720463
117,298774613720463
121,298774613720463
122,298774613720463
125,298774613720463
128,298774613720463
130,298774613720463
136,298774613720463
137,298774613720463
144,298774613720463
145,298774613720463
146,298774613720463
148,298774613720463
149,298774613720463
153,298774613720463
157,298774613720463
160,298774613720463
162,298774613720463
164,298774613720463
169,298774613720463
170,298774613720463
173,298774613720463
178,298774613720463
180,298774613720463
181,298774613720463
185,298774613720463
193,298774613720463
194,298774613720463
196,298774613720463
197,298774613720463
200,298774613720463
202,298774613720463
205,298774613720463
208,298774613720463
212,298774613720463
218,298774613720463
221,298774613720463
225,298774613720463
226,298774613720463
229,298774613720463
232,298774613720463
233,298774613720463
234,298774613720463
241,298774613720463
242,298774613720463
244,298774613720463
245,298774613720463
250,298774613720463
256,298774613720463
257,298774613720463
260,298774613720463
261,298774613720463
265,298774613720463
269,298774613720463
272,298774613720463
274,298774613720463
277,298774613720463
281,298774613720463
288,298774613720463
289,298774613720463
290,298774613720463
292,298774613720463
293,298774613720463
296,298774613720463
298,298774613720463
305,298774613720463
306,298774613720463
313,298774613720463
314,298774613720463
317,298774613720463
320,298774613720463
324,298774613720463
325,298774613720463
328,298774613720463
333,298774613720463
337,298774613720463
338,298774613720463
340,298774613720463
346,298774613720463
349,298774613720463
353,298774613720463
356,298774613720463
360,298774613720463
361,298774613720463
362,298774613720463
365,298774613720463
369,298774613720463
370,298774613720463
373,298774613720463
377,298774613720463
386,298774613720463
388,298774613720463
389,298774613720463
392,298774613720463
394,298774613720463
397,298774613720463
400,298774613720463
401,298774613720463
404,298774613720463
405,298774613720463
409,298774613720463
410,298774613720463
416,298774613720463
421,298774613720463
424,298774613720463
425,298774613720463
433,298774613720463
436,298774613720463
441,298774613720463
442,298774613720463
445,298774613720463
449,298774613720463
450,298774613720463
452,298774613720463
457,298774613720463
458,298774613720463
461,298774613720463
464,298774613720463
466,298774613720463
468,298774613720463
477,298774613720463
481,298774613720463
482,298774613720463
484,298774613720463
485,298774613720463
488,298774613720463
490,298774613720463
493,298774613720463
500,298774613720463
505,298774613720463
509,298774613720463
512,298774613720463
514,298774613720463
520,298774613720463
521,298774613720463
522,298774613720463
529,298774613720463
530,298774613720463
533,298774613720463
538,298774613720463
541,298774613720463
544,298774613720463
545,298774613720463
548,298774613720463
549,298774613720463
554,298774613720463
557,298774613720463
562,298774613720463
565,298774613720463
569,298774613720463
576,298774613720463
577,298774613720463
578,298774613720463
580,298774613720463
584,298774613720463
585,298774613720463
586,298774613720463
592,298774613720463
593,298774613720463
596,298774613720463
601,298774613720463
605,298774613720463
610,298774613720463
612,298774613720463
613,298774613720463
617,298774613720463
625,298774613720463
626,298774613720463
628,298774613720463
629,298774613720463
634,298774613720463
637,298774613720463
640,298774613720463
641,298774613720463
648,298774613720463
650,298774613720463
653,298774613720463
656,298774613720463
657,298774613720463
661,298774613720463
666,298774613720463
673,298774613720463
674,298774613720463
676,298774613720463
677,298774613720463
680,298774613720463
685,298774613720463
689,298774613720463
692,298774613720463
697,298774613720463
698,298774613720463
701,298774613720463
706,298774613720463
709,298774613720463
712,298774613720463
720,298774613720463
722,298774613720463
724,298774613720463
725,298774613720463
729,298774613720463
730,298774613720463
733,298774613720463
738,298774613720463
740,298774613720463
745,298774613720463
746,298774613720463
754,298774613720463
757,298774613720463
761,298774613720463
765,298774613720463
769,298774613720463
772,298774613720463
773,298774613720463
776,298774613720463
778,298774613720463
784,298774613720463
785,298774613720463
788,298774613720463
793,298774613720463
794,298774613720463
797,298774613720463
800,298774613720463
801,298774613720463
802,298774613720463
808,298774613720463
809,298774613720463
810,298774613720463
818,298774613720463
820,298774613720463
821,298774613720463
829,298774613720463
832,298774613720463
833,298774613720463
841,298774613720463
842,298774613720463
845,298774613720463
848,298774613720463
850,298774613720463
853,298774613720463
857,298774613720463
865,298774613720463
866,298774613720463
872,298774613720463
873,298774613720463
877,298774613720463
881,298774613720463
882,298774613720463
884,298774613720463
890,298774613720463
898,298774613720463
900,298774613720463
901,298774613720463
904,298774613720463
905,298774613720463
909,298774613720463
914,298774613720463
916,298774613720463
922,298774613720463
925,298774613720463
928,298774613720463
929,298774613720463
932,298774613720463
936,298774613720463
937,298774613720463
941,298774613720463
949,298774613720463
953,298774613720463
954,298774613720463
961,298774613720463
962,298774613720463
964,298774613720463
965,298774613720463
968,298774613720463
970,298774613720463
976,298774613720463
977,298774613720463
980,298774613720463
981,298774613720463
985,298774613720463
986,298774613720463
997,298774613720463
1000,298774613720463

In [ ]:
assert col['i'][5] == x

### Nombres premiers

**Exercice [081].** Un entier est **premier** si et seulement s'il a exactement deux diviseurs entiers (1 et lui-même).

| Exemple | Diviseurs | Propriété | Premier |
|---:|:--:|:--:|:--:|
| $13$ | $${1, 13}$$ | exactement deux diviseurs | ✅ |
| $12$ | $${1, 2, 3, 4, 6, 12}$$ | plus de deux diviseurs | ❌ |
| $1$ | $${1}$$ | moins de deux diviseurs | ❌ |

_Tâche._ Listez par ordre croissant les nombres premiers inférieurs ou égaux à 1000.

_Contrainte._ N'utilisez pas de regroupement.

In [ ]:
%%sql
SELECT i
     , salt_081(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE NOT EXISTS
        (SELECT 1
         FROM ints B
         WHERE B.i BETWEEN 2 AND sqrt(A.i)
             AND A.i % B.i = 0 )
    AND i > 1

168 rows affected.

i,token
2,253352561534995
3,253352561534995
5,253352561534995
7,253352561534995
11,253352561534995
13,253352561534995
17,253352561534995
19,253352561534995
23,253352561534995
29,253352561534995
31,253352561534995
37,253352561534995
41,253352561534995
43,253352561534995
47,253352561534995
53,253352561534995
59,253352561534995
61,253352561534995
67,253352561534995
71,253352561534995
73,253352561534995
79,253352561534995
83,253352561534995
89,253352561534995
97,253352561534995
101,253352561534995
103,253352561534995
107,253352561534995
109,253352561534995
113,253352561534995
127,253352561534995
131,253352561534995
137,253352561534995
139,253352561534995
149,253352561534995
151,253352561534995
157,253352561534995
163,253352561534995
167,253352561534995
173,253352561534995
179,253352561534995
181,253352561534995
191,253352561534995
193,253352561534995
197,253352561534995
199,253352561534995
211,253352561534995
223,253352561534995
227,253352561534995
229,253352561534995
233,253352561534995
239,253352561534995
241,253352561534995
251,253352561534995
257,253352561534995
263,253352561534995
269,253352561534995
271,253352561534995
277,253352561534995
281,253352561534995
283,253352561534995
293,253352561534995
307,253352561534995
311,253352561534995
313,253352561534995
317,253352561534995
331,253352561534995
337,253352561534995
347,253352561534995
349,253352561534995
353,253352561534995
359,253352561534995
367,253352561534995
373,253352561534995
379,253352561534995
383,253352561534995
389,253352561534995
397,253352561534995
401,253352561534995
409,253352561534995
419,253352561534995
421,253352561534995
431,253352561534995
433,253352561534995
439,253352561534995
443,253352561534995
449,253352561534995
457,253352561534995
461,253352561534995
463,253352561534995
467,253352561534995
479,253352561534995
487,253352561534995
491,253352561534995
499,253352561534995
503,253352561534995
509,253352561534995
521,253352561534995
523,253352561534995
541,253352561534995
547,253352561534995
557,253352561534995
563,253352561534995
569,253352561534995
571,253352561534995
577,253352561534995
587,253352561534995
593,253352561534995
599,253352561534995
601,253352561534995
607,253352561534995
613,253352561534995
617,253352561534995
619,253352561534995
631,253352561534995
641,253352561534995
643,253352561534995
647,253352561534995
653,253352561534995
659,253352561534995
661,253352561534995
673,253352561534995
677,253352561534995
683,253352561534995
691,253352561534995
701,253352561534995
709,253352561534995
719,253352561534995
727,253352561534995
733,253352561534995
739,253352561534995
743,253352561534995
751,253352561534995
757,253352561534995
761,253352561534995
769,253352561534995
773,253352561534995
787,253352561534995
797,253352561534995
809,253352561534995
811,253352561534995
821,253352561534995
823,253352561534995
827,253352561534995
829,253352561534995
839,253352561534995
853,253352561534995
857,253352561534995
859,253352561534995
863,253352561534995
877,253352561534995
881,253352561534995
883,253352561534995
887,253352561534995
907,253352561534995
911,253352561534995
919,253352561534995
929,253352561534995
937,253352561534995
941,253352561534995
947,253352561534995
953,253352561534995
967,253352561534995
971,253352561534995
977,253352561534995
983,253352561534995
991,253352561534995
997,253352561534995

In [ ]:
%%sql
-- Variante. Avec une requête imbriquée dans le WHERE.
SELECT A.i
     , salt_081(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE A.i > 1
    AND A.i NOT IN
        (SELECT A2.i
         FROM ints A2
         JOIN ints B ON B.i BETWEEN 2 AND sqrt(A2.i)
         AND A2.i % B.i = 0)

168 rows affected.

i,token
2,253352561534995
3,253352561534995
5,253352561534995
7,253352561534995
11,253352561534995
13,253352561534995
17,253352561534995
19,253352561534995
23,253352561534995
29,253352561534995
31,253352561534995
37,253352561534995
41,253352561534995
43,253352561534995
47,253352561534995
53,253352561534995
59,253352561534995
61,253352561534995
67,253352561534995
71,253352561534995
73,253352561534995
79,253352561534995
83,253352561534995
89,253352561534995
97,253352561534995
101,253352561534995
103,253352561534995
107,253352561534995
109,253352561534995
113,253352561534995
127,253352561534995
131,253352561534995
137,253352561534995
139,253352561534995
149,253352561534995
151,253352561534995
157,253352561534995
163,253352561534995
167,253352561534995
173,253352561534995
179,253352561534995
181,253352561534995
191,253352561534995
193,253352561534995
197,253352561534995
199,253352561534995
211,253352561534995
223,253352561534995
227,253352561534995
229,253352561534995
233,253352561534995
239,253352561534995
241,253352561534995
251,253352561534995
257,253352561534995
263,253352561534995
269,253352561534995
271,253352561534995
277,253352561534995
281,253352561534995
283,253352561534995
293,253352561534995
307,253352561534995
311,253352561534995
313,253352561534995
317,253352561534995
331,253352561534995
337,253352561534995
347,253352561534995
349,253352561534995
353,253352561534995
359,253352561534995
367,253352561534995
373,253352561534995
379,253352561534995
383,253352561534995
389,253352561534995
397,253352561534995
401,253352561534995
409,253352561534995
419,253352561534995
421,253352561534995
431,253352561534995
433,253352561534995
439,253352561534995
443,253352561534995
449,253352561534995
457,253352561534995
461,253352561534995
463,253352561534995
467,253352561534995
479,253352561534995
487,253352561534995
491,253352561534995
499,253352561534995
503,253352561534995
509,253352561534995
521,253352561534995
523,253352561534995
541,253352561534995
547,253352561534995
557,253352561534995
563,253352561534995
569,253352561534995
571,253352561534995
577,253352561534995
587,253352561534995
593,253352561534995
599,253352561534995
601,253352561534995
607,253352561534995
613,253352561534995
617,253352561534995
619,253352561534995
631,253352561534995
641,253352561534995
643,253352561534995
647,253352561534995
653,253352561534995
659,253352561534995
661,253352561534995
673,253352561534995
677,253352561534995
683,253352561534995
691,253352561534995
701,253352561534995
709,253352561534995
719,253352561534995
727,253352561534995
733,253352561534995
739,253352561534995
743,253352561534995
751,253352561534995
757,253352561534995
761,253352561534995
769,253352561534995
773,253352561534995
787,253352561534995
797,253352561534995
809,253352561534995
811,253352561534995
821,253352561534995
823,253352561534995
827,253352561534995
829,253352561534995
839,253352561534995
853,253352561534995
857,253352561534995
859,253352561534995
863,253352561534995
877,253352561534995
881,253352561534995
883,253352561534995
887,253352561534995
907,253352561534995
911,253352561534995
919,253352561534995
929,253352561534995
937,253352561534995
941,253352561534995
947,253352561534995
953,253352561534995
967,253352561534995
971,253352561534995
977,253352561534995
983,253352561534995
991,253352561534995
997,253352561534995

**Exercice [082].** Un entier est **premier** si et seulement s'il a exactement deux diviseurs entiers (1 et lui-même).

| Exemple | Diviseurs | Propriété | Premier |
|---:|:--:|:--:|:--:|
| $13$ | $${1, 13}$$ | exactement deux diviseurs | ✅ |
| $12$ | $${1, 2, 3, 4, 6, 12}$$ | plus de deux diviseurs | ❌ |
| $1$ | $${1}$$ | moins de deux diviseurs | ❌ |

_Tâche._ Listez par ordre croissant les nombres premiers inférieurs ou égaux à 1000.

_Contrainte._ Utilisez un regroupement.

In [ ]:
%%sql
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
WHERE A.i > 1
GROUP BY A.i
HAVING count(B.i) = 0

168 rows affected.

i,token
2,156364735562291
3,156364735562291
5,156364735562291
7,156364735562291
11,156364735562291
13,156364735562291
17,156364735562291
19,156364735562291
23,156364735562291
29,156364735562291
31,156364735562291
37,156364735562291
41,156364735562291
43,156364735562291
47,156364735562291
53,156364735562291
59,156364735562291
61,156364735562291
67,156364735562291
71,156364735562291
73,156364735562291
79,156364735562291
83,156364735562291
89,156364735562291
97,156364735562291
101,156364735562291
103,156364735562291
107,156364735562291
109,156364735562291
113,156364735562291
127,156364735562291
131,156364735562291
137,156364735562291
139,156364735562291
149,156364735562291
151,156364735562291
157,156364735562291
163,156364735562291
167,156364735562291
173,156364735562291
179,156364735562291
181,156364735562291
191,156364735562291
193,156364735562291
197,156364735562291
199,156364735562291
211,156364735562291
223,156364735562291
227,156364735562291
229,156364735562291
233,156364735562291
239,156364735562291
241,156364735562291
251,156364735562291
257,156364735562291
263,156364735562291
269,156364735562291
271,156364735562291
277,156364735562291
281,156364735562291
283,156364735562291
293,156364735562291
307,156364735562291
311,156364735562291
313,156364735562291
317,156364735562291
331,156364735562291
337,156364735562291
347,156364735562291
349,156364735562291
353,156364735562291
359,156364735562291
367,156364735562291
373,156364735562291
379,156364735562291
383,156364735562291
389,156364735562291
397,156364735562291
401,156364735562291
409,156364735562291
419,156364735562291
421,156364735562291
431,156364735562291
433,156364735562291
439,156364735562291
443,156364735562291
449,156364735562291
457,156364735562291
461,156364735562291
463,156364735562291
467,156364735562291
479,156364735562291
487,156364735562291
491,156364735562291
499,156364735562291
503,156364735562291
509,156364735562291
521,156364735562291
523,156364735562291
541,156364735562291
547,156364735562291
557,156364735562291
563,156364735562291
569,156364735562291
571,156364735562291
577,156364735562291
587,156364735562291
593,156364735562291
599,156364735562291
601,156364735562291
607,156364735562291
613,156364735562291
617,156364735562291
619,156364735562291
631,156364735562291
641,156364735562291
643,156364735562291
647,156364735562291
653,156364735562291
659,156364735562291
661,156364735562291
673,156364735562291
677,156364735562291
683,156364735562291
691,156364735562291
701,156364735562291
709,156364735562291
719,156364735562291
727,156364735562291
733,156364735562291
739,156364735562291
743,156364735562291
751,156364735562291
757,156364735562291
761,156364735562291
769,156364735562291
773,156364735562291
787,156364735562291
797,156364735562291
809,156364735562291
811,156364735562291
821,156364735562291
823,156364735562291
827,156364735562291
829,156364735562291
839,156364735562291
853,156364735562291
857,156364735562291
859,156364735562291
863,156364735562291
877,156364735562291
881,156364735562291
883,156364735562291
887,156364735562291
907,156364735562291
911,156364735562291
919,156364735562291
929,156364735562291
937,156364735562291
941,156364735562291
947,156364735562291
953,156364735562291
967,156364735562291
971,156364735562291
977,156364735562291
983,156364735562291
991,156364735562291
997,156364735562291

In [ ]:
%%sql
-- Indication. 0 et 1 ne sont pas premiers.
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
GROUP BY A.i
HAVING count(B.i) = 0

170 rows affected.

i,token
0,156596690231090
1,156596690231090
2,156596690231090
3,156596690231090
5,156596690231090
7,156596690231090
11,156596690231090
13,156596690231090
17,156596690231090
19,156596690231090
23,156596690231090
29,156596690231090
31,156596690231090
37,156596690231090
41,156596690231090
43,156596690231090
47,156596690231090
53,156596690231090
59,156596690231090
61,156596690231090
67,156596690231090
71,156596690231090
73,156596690231090
79,156596690231090
83,156596690231090
89,156596690231090
97,156596690231090
101,156596690231090
103,156596690231090
107,156596690231090
109,156596690231090
113,156596690231090
127,156596690231090
131,156596690231090
137,156596690231090
139,156596690231090
149,156596690231090
151,156596690231090
157,156596690231090
163,156596690231090
167,156596690231090
173,156596690231090
179,156596690231090
181,156596690231090
191,156596690231090
193,156596690231090
197,156596690231090
199,156596690231090
211,156596690231090
223,156596690231090
227,156596690231090
229,156596690231090
233,156596690231090
239,156596690231090
241,156596690231090
251,156596690231090
257,156596690231090
263,156596690231090
269,156596690231090
271,156596690231090
277,156596690231090
281,156596690231090
283,156596690231090
293,156596690231090
307,156596690231090
311,156596690231090
313,156596690231090
317,156596690231090
331,156596690231090
337,156596690231090
347,156596690231090
349,156596690231090
353,156596690231090
359,156596690231090
367,156596690231090
373,156596690231090
379,156596690231090
383,156596690231090
389,156596690231090
397,156596690231090
401,156596690231090
409,156596690231090
419,156596690231090
421,156596690231090
431,156596690231090
433,156596690231090
439,156596690231090
443,156596690231090
449,156596690231090
457,156596690231090
461,156596690231090
463,156596690231090
467,156596690231090
479,156596690231090
487,156596690231090
491,156596690231090
499,156596690231090
503,156596690231090
509,156596690231090
521,156596690231090
523,156596690231090
541,156596690231090
547,156596690231090
557,156596690231090
563,156596690231090
569,156596690231090
571,156596690231090
577,156596690231090
587,156596690231090
593,156596690231090
599,156596690231090
601,156596690231090
607,156596690231090
613,156596690231090
617,156596690231090
619,156596690231090
631,156596690231090
641,156596690231090
643,156596690231090
647,156596690231090
653,156596690231090
659,156596690231090
661,156596690231090
673,156596690231090
677,156596690231090
683,156596690231090
691,156596690231090
701,156596690231090
709,156596690231090
719,156596690231090
727,156596690231090
733,156596690231090
739,156596690231090
743,156596690231090
751,156596690231090
757,156596690231090
761,156596690231090
769,156596690231090
773,156596690231090
787,156596690231090
797,156596690231090
809,156596690231090
811,156596690231090
821,156596690231090
823,156596690231090
827,156596690231090
829,156596690231090
839,156596690231090
853,156596690231090
857,156596690231090
859,156596690231090
863,156596690231090
877,156596690231090
881,156596690231090
883,156596690231090
887,156596690231090
907,156596690231090
911,156596690231090
919,156596690231090
929,156596690231090
937,156596690231090
941,156596690231090
947,156596690231090
953,156596690231090
967,156596690231090
971,156596690231090
977,156596690231090
983,156596690231090
991,156596690231090
997,156596690231090

In [ ]:
%%sql
-- Indication. 1 n'est pas premier.
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
WHERE A.i != 0
GROUP BY A.i
HAVING count(B.i) = 0

169 rows affected.

i,token
1,156189361184507
2,156189361184507
3,156189361184507
5,156189361184507
7,156189361184507
11,156189361184507
13,156189361184507
17,156189361184507
19,156189361184507
23,156189361184507
29,156189361184507
31,156189361184507
37,156189361184507
41,156189361184507
43,156189361184507
47,156189361184507
53,156189361184507
59,156189361184507
61,156189361184507
67,156189361184507
71,156189361184507
73,156189361184507
79,156189361184507
83,156189361184507
89,156189361184507
97,156189361184507
101,156189361184507
103,156189361184507
107,156189361184507
109,156189361184507
113,156189361184507
127,156189361184507
131,156189361184507
137,156189361184507
139,156189361184507
149,156189361184507
151,156189361184507
157,156189361184507
163,156189361184507
167,156189361184507
173,156189361184507
179,156189361184507
181,156189361184507
191,156189361184507
193,156189361184507
197,156189361184507
199,156189361184507
211,156189361184507
223,156189361184507
227,156189361184507
229,156189361184507
233,156189361184507
239,156189361184507
241,156189361184507
251,156189361184507
257,156189361184507
263,156189361184507
269,156189361184507
271,156189361184507
277,156189361184507
281,156189361184507
283,156189361184507
293,156189361184507
307,156189361184507
311,156189361184507
313,156189361184507
317,156189361184507
331,156189361184507
337,156189361184507
347,156189361184507
349,156189361184507
353,156189361184507
359,156189361184507
367,156189361184507
373,156189361184507
379,156189361184507
383,156189361184507
389,156189361184507
397,156189361184507
401,156189361184507
409,156189361184507
419,156189361184507
421,156189361184507
431,156189361184507
433,156189361184507
439,156189361184507
443,156189361184507
449,156189361184507
457,156189361184507
461,156189361184507
463,156189361184507
467,156189361184507
479,156189361184507
487,156189361184507
491,156189361184507
499,156189361184507
503,156189361184507
509,156189361184507
521,156189361184507
523,156189361184507
541,156189361184507
547,156189361184507
557,156189361184507
563,156189361184507
569,156189361184507
571,156189361184507
577,156189361184507
587,156189361184507
593,156189361184507
599,156189361184507
601,156189361184507
607,156189361184507
613,156189361184507
617,156189361184507
619,156189361184507
631,156189361184507
641,156189361184507
643,156189361184507
647,156189361184507
653,156189361184507
659,156189361184507
661,156189361184507
673,156189361184507
677,156189361184507
683,156189361184507
691,156189361184507
701,156189361184507
709,156189361184507
719,156189361184507
727,156189361184507
733,156189361184507
739,156189361184507
743,156189361184507
751,156189361184507
757,156189361184507
761,156189361184507
769,156189361184507
773,156189361184507
787,156189361184507
797,156189361184507
809,156189361184507
811,156189361184507
821,156189361184507
823,156189361184507
827,156189361184507
829,156189361184507
839,156189361184507
853,156189361184507
857,156189361184507
859,156189361184507
863,156189361184507
877,156189361184507
881,156189361184507
883,156189361184507
887,156189361184507
907,156189361184507
911,156189361184507
919,156189361184507
929,156189361184507
937,156189361184507
941,156189361184507
947,156189361184507
953,156189361184507
967,156189361184507
971,156189361184507
977,156189361184507
983,156189361184507
991,156189361184507
997,156189361184507

**Exercice [062].** Un entier est **composite** si et seulement s'il a plus de deux diviseurs entiers (1 et lui-même).

| i | Diviseurs |
|---:|:--|
|4 | 1 2 4 |
|6 | 1 2 6 |
|8 | 1 2 8 |
|9 | 1 3 9 |
|10 | 1 2 10 |
|12 | 1 2 3 12 |

_Tâche._ Listez par ordre croissant les nombres composites inférieurs ou égaux à 1000 avec la liste de leurs diviseurs séparés un espace comme dans la table ci-dessus.

_Aide._ Une simple variation du calcul des nombres premiers pour découvrir la fonction d'agrégation [`group_concat()`](https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html#function_group-concat).

In [ ]:
x = '1 2 3 4 24' # la 14e liste de diviseurs, séparés par un espace
# Javascript: result[13]?.divisors ?? 7_531_148

In [ ]:
%%sql
SELECT A.i
     , group_concat(B.i
                    ORDER BY B.i ASC SEPARATOR ' ') AS divisors
     , salt_062(string_hash('{{x}}') + bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i % B.i = 0
WHERE B.i = A.i
    OR B.i BETWEEN 1 AND sqrt(A.i)
GROUP BY A.i
HAVING count(B.i) > 2

831 rows affected.

i,divisors,token
4,1 2 4,92857264956831
6,1 2 6,92857264956831
8,1 2 8,92857264956831
9,1 3 9,92857264956831
10,1 2 10,92857264956831
12,1 2 3 12,92857264956831
14,1 2 14,92857264956831
15,1 3 15,92857264956831
16,1 2 4 16,92857264956831
18,1 2 3 18,92857264956831
20,1 2 4 20,92857264956831
21,1 3 21,92857264956831
22,1 2 22,92857264956831
24,1 2 3 4 24,92857264956831
25,1 5 25,92857264956831
26,1 2 26,92857264956831
27,1 3 27,92857264956831
28,1 2 4 28,92857264956831
30,1 2 3 5 30,92857264956831
32,1 2 4 32,92857264956831
33,1 3 33,92857264956831
34,1 2 34,92857264956831
35,1 5 35,92857264956831
36,1 2 3 4 6 36,92857264956831
38,1 2 38,92857264956831
39,1 3 39,92857264956831
40,1 2 4 5 40,92857264956831
42,1 2 3 6 42,92857264956831
44,1 2 4 44,92857264956831
45,1 3 5 45,92857264956831
46,1 2 46,92857264956831
48,1 2 3 4 6 48,92857264956831
49,1 7 49,92857264956831
50,1 2 5 50,92857264956831
51,1 3 51,92857264956831
52,1 2 4 52,92857264956831
54,1 2 3 6 54,92857264956831
55,1 5 55,92857264956831
56,1 2 4 7 56,92857264956831
57,1 3 57,92857264956831
58,1 2 58,92857264956831
60,1 2 3 4 5 6 60,92857264956831
62,1 2 62,92857264956831
63,1 3 7 63,92857264956831
64,1 2 4 8 64,92857264956831
65,1 5 65,92857264956831
66,1 2 3 6 66,92857264956831
68,1 2 4 68,92857264956831
69,1 3 69,92857264956831
70,1 2 5 7 70,92857264956831
72,1 2 3 4 6 8 72,92857264956831
74,1 2 74,92857264956831
75,1 3 5 75,92857264956831
76,1 2 4 76,92857264956831
77,1 7 77,92857264956831
78,1 2 3 6 78,92857264956831
80,1 2 4 5 8 80,92857264956831
81,1 3 9 81,92857264956831
82,1 2 82,92857264956831
84,1 2 3 4 6 7 84,92857264956831
85,1 5 85,92857264956831
86,1 2 86,92857264956831
87,1 3 87,92857264956831
88,1 2 4 8 88,92857264956831
90,1 2 3 5 6 9 90,92857264956831
91,1 7 91,92857264956831
92,1 2 4 92,92857264956831
93,1 3 93,92857264956831
94,1 2 94,92857264956831
95,1 5 95,92857264956831
96,1 2 3 4 6 8 96,92857264956831
98,1 2 7 98,92857264956831
99,1 3 9 99,92857264956831
100,1 2 4 5 10 100,92857264956831
102,1 2 3 6 102,92857264956831
104,1 2 4 8 104,92857264956831
105,1 3 5 7 105,92857264956831
106,1 2 106,92857264956831
108,1 2 3 4 6 9 108,92857264956831
110,1 2 5 10 110,92857264956831
111,1 3 111,92857264956831
112,1 2 4 7 8 112,92857264956831
114,1 2 3 6 114,92857264956831
115,1 5 115,92857264956831
116,1 2 4 116,92857264956831
117,1 3 9 117,92857264956831
118,1 2 118,92857264956831
119,1 7 119,92857264956831
120,1 2 3 4 5 6 8 10 120,92857264956831
121,1 11 121,92857264956831
122,1 2 122,92857264956831
123,1 3 123,92857264956831
124,1 2 4 124,92857264956831
125,1 5 125,92857264956831
126,1 2 3 6 7 9 126,92857264956831
128,1 2 4 8 128,92857264956831
129,1 3 129,92857264956831
130,1 2 5 10 130,92857264956831
132,1 2 3 4 6 11 132,92857264956831
133,1 7 133,92857264956831
134,1 2 134,92857264956831
135,1 3 5 9 135,92857264956831
136,1 2 4 8 136,92857264956831
138,1 2 3 6 138,92857264956831
140,1 2 4 5 7 10 140,92857264956831
141,1 3 141,92857264956831
142,1 2 142,92857264956831
143,1 11 143,92857264956831
144,1 2 3 4 6 8 9 12 144,92857264956831
145,1 5 145,92857264956831
146,1 2 146,92857264956831
147,1 3 7 147,92857264956831
148,1 2 4 148,92857264956831
150,1 2 3 5 6 10 150,92857264956831
152,1 2 4 8 152,92857264956831
153,1 3 9 153,92857264956831
154,1 2 7 11 154,92857264956831
155,1 5 155,92857264956831
156,1 2 3 4 6 12 156,92857264956831
158,1 2 158,92857264956831
159,1 3 159,92857264956831
160,1 2 4 5 8 10 160,92857264956831
161,1 7 161,92857264956831
162,1 2 3 6 9 162,92857264956831
164,1 2 4 164,92857264956831
165,1 3 5 11 165,92857264956831
166,1 2 166,92857264956831
168,1 2 3 4 6 7 8 12 168,92857264956831
169,1 13 169,92857264956831
170,1 2 5 10 170,92857264956831
171,1 3 9 171,92857264956831
172,1 2 4 172,92857264956831
174,1 2 3 6 174,92857264956831
175,1 5 7 175,92857264956831
176,1 2 4 8 11 176,92857264956831
177,1 3 177,92857264956831
178,1 2 178,92857264956831
180,1 2 3 4 5 6 9 10 12 180,92857264956831
182,1 2 7 13 182,92857264956831
183,1 3 183,92857264956831
184,1 2 4 8 184,92857264956831
185,1 5 185,92857264956831
186,1 2 3 6 186,92857264956831
187,1 11 187,92857264956831
188,1 2 4 188,92857264956831
189,1 3 7 9 189,92857264956831
190,1 2 5 10 190,92857264956831
192,1 2 3 4 6 8 12 192,92857264956831
194,1 2 194,92857264956831
195,1 3 5 13 195,92857264956831
196,1 2 4 7 14 196,92857264956831
198,1 2 3 6 9 11 198,92857264956831
200,1 2 4 5 8 10 200,92857264956831
201,1 3 201,92857264956831
202,1 2 202,92857264956831
203,1 7 203,92857264956831
204,1 2 3 4 6 12 204,92857264956831
205,1 5 205,92857264956831
206,1 2 206,92857264956831
207,1 3 9 207,92857264956831
208,1 2 4 8 13 208,92857264956831
209,1 11 209,92857264956831
210,1 2 3 5 6 7 10 14 210,92857264956831
212,1 2 4 212,92857264956831
213,1 3 213,92857264956831
214,1 2 214,92857264956831
215,1 5 215,92857264956831
216,1 2 3 4 6 8 9 12 216,92857264956831
217,1 7 217,92857264956831
218,1 2 218,92857264956831
219,1 3 219,92857264956831
220,1 2 4 5 10 11 220,92857264956831
221,1 13 221,92857264956831
222,1 2 3 6 222,92857264956831
224,1 2 4 7 8 14 224,92857264956831
225,1 3 5 9 15 225,92857264956831
226,1 2 226,92857264956831
228,1 2 3 4 6 12 228,92857264956831
230,1 2 5 10 230,92857264956831
231,1 3 7 11 231,92857264956831
232,1 2 4 8 232,92857264956831
234,1 2 3 6 9 13 234,92857264956831
235,1 5 235,92857264956831
236,1 2 4 236,92857264956831
237,1 3 237,92857264956831
238,1 2 7 14 238,92857264956831
240,1 2 3 4 5 6 8 10 12 15 240,92857264956831
242,1 2 11 242,92857264956831
243,1 3 9 243,92857264956831
244,1 2 4 244,92857264956831
245,1 5 7 245,92857264956831
246,1 2 3 6 246,92857264956831
247,1 13 247,92857264956831
248,1 2 4 8 248,92857264956831
249,1 3 249,92857264956831
250,1 2 5 10 250,92857264956831
252,1 2 3 4 6 7 9 12 14 252,92857264956831
253,1 11 253,92857264956831
254,1 2 254,92857264956831
255,1 3 5 15 255,92857264956831
256,1 2 4 8 16 256,92857264956831
258,1 2 3 6 258,92857264956831
259,1 7 259,92857264956831
260,1 2 4 5 10 13 260,92857264956831
261,1 3 9 261,92857264956831
262,1 2 262,92857264956831
264,1 2 3 4 6 8 11 12 264,92857264956831
265,1 5 265,92857264956831
266,1 2 7 14 266,92857264956831
267,1 3 267,92857264956831
268,1 2 4 268,92857264956831
270,1 2 3 5 6 9 10 15 270,92857264956831
272,1 2 4 8 16 272,92857264956831
273,1 3 7 13 273,92857264956831
274,1 2 274,92857264956831
275,1 5 11 275,92857264956831
276,1 2 3 4 6 12 276,92857264956831
278,1 2 278,92857264956831
279,1 3 9 279,92857264956831
280,1 2 4 5 7 8 10 14 280,92857264956831
282,1 2 3 6 282,92857264956831
284,1 2 4 284,92857264956831
285,1 3 5 15 285,92857264956831
286,1 2 11 13 286,92857264956831
287,1 7 287,92857264956831
288,1 2 3 4 6 8 9 12 16 288,92857264956831
289,1 17 289,92857264956831
290,1 2 5 10 290,92857264956831
291,1 3 291,92857264956831
292,1 2 4 292,92857264956831
294,1 2 3 6 7 14 294,92857264956831
295,1 5 295,92857264956831
296,1 2 4 8 296,92857264956831
297,1 3 9 11 297,92857264956831
298,1 2 298,92857264956831
299,1 13 299,92857264956831
300,1 2 3 4 5 6 10 12 15 300,92857264956831
301,1 7 301,92857264956831
302,1 2 302,92857264956831
303,1 3 303,92857264956831
304,1 2 4 8 16 304,92857264956831
305,1 5 305,92857264956831
306,1 2 3 6 9 17 306,92857264956831
308,1 2 4 7 11 14 308,92857264956831
309,1 3 309,92857264956831
310,1 2 5 10 310,92857264956831
312,1 2 3 4 6 8 12 13 312,92857264956831
314,1 2 314,92857264956831
315,1 3 5 7 9 15 315,92857264956831
316,1 2 4 316,92857264956831
318,1 2 3 6 318,92857264956831
319,1 11 319,92857264956831
320,1 2 4 5 8 10 16 320,92857264956831
321,1 3 321,92857264956831
322,1 2 7 14 322,92857264956831
323,1 17 323,92857264956831
324,1 2 3 4 6 9 12 18 324,92857264956831
325,1 5 13 325,92857264956831
326,1 2 326,92857264956831
327,1 3 327,92857264956831
328,1 2 4 8 328,92857264956831
329,1 7 329,92857264956831
330,1 2 3 5 6 10 11 15 330,92857264956831
332,1 2 4 332,92857264956831
333,1 3 9 333,92857264956831
334,1 2 334,92857264956831
335,1 5 335,92857264956831
336,1 2 3 4 6 7 8 12 14 16 336,92857264956831
338,1 2 13 338,92857264956831
339,1 3 339,92857264956831
340,1 2 4 5 10 17 340,92857264956831
341,1 11 341,92857264956831
342,1 2 3 6 9 18 342,92857264956831
343,1 7 343,92857264956831
344,1 2 4 8 344,92857264956831
345,1 3 5 15 345,92857264956831
346,1 2 346,92857264956831
348,1 2 3 4 6 12 348,92857264956831
350,1 2 5 7 10 14 350,92857264956831
351,1 3 9 13 351,92857264956831
352,1 2 4 8 11 16 352,92857264956831
354,1 2 3 6 354,92857264956831
355,1 5 355,92857264956831
356,1 2 4 356,92857264956831
357,1 3 7 17 357,92857264956831
358,1 2 358,92857264956831
360,1 2 3 4 5 6 8 9 10 12 15 18 360,92857264956831
361,1 19 361,92857264956831
362,1 2 362,92857264956831
363,1 3 11 363,92857264956831
364,1 2 4 7 13 14 364,92857264956831
365,1 5 365,92857264956831
366,1 2 3 6 366,92857264956831
368,1 2 4 8 16 368,92857264956831
369,1 3 9 369,92857264956831
370,1 2 5 10 370,92857264956831
371,1 7 371,92857264956831
372,1 2 3 4 6 12 372,92857264956831
374,1 2 11 17 374,92857264956831
375,1 3 5 15 375,92857264956831
376,1 2 4 8 376,92857264956831
377,1 13 377,92857264956831
378,1 2 3 6 7 9 14 18 378,92857264956831
380,1 2 4 5 10 19 380,92857264956831
381,1 3 381,92857264956831
382,1 2 382,92857264956831
384,1 2 3 4 6 8 12 16 384,92857264956831
385,1 5 7 11 385,92857264956831
386,1 2 386,92857264956831
387,1 3 9 387,92857264956831
388,1 2 4 388,92857264956831
390,1 2 3 5 6 10 13 15 390,92857264956831
391,1 17 391,92857264956831
392,1 2 4 7 8 14 392,92857264956831
393,1 3 393,92857264956831
394,1 2 394,92857264956831
395,1 5 395,92857264956831
396,1 2 3 4 6 9 11 12 18 396,92857264956831
398,1 2 398,92857264956831
399,1 3 7 19 399,92857264956831
400,1 2 4 5 8 10 16 20 400,92857264956831
402,1 2 3 6 402,92857264956831
403,1 13 403,92857264956831
404,1 2 4 404,92857264956831
405,1 3 5 9 15 405,92857264956831
406,1 2 7 14 406,92857264956831
407,1 11 407,92857264956831
408,1 2 3 4 6 8 12 17 408,92857264956831
410,1 2 5 10 410,92857264956831
411,1 3 411,92857264956831
412,1 2 4 412,92857264956831
413,1 7 413,92857264956831
414,1 2 3 6 9 18 414,92857264956831
415,1 5 415,92857264956831
416,1 2 4 8 13 16 416,92857264956831
417,1 3 417,92857264956831
418,1 2 11 19 418,92857264956831
420,1 2 3 4 5 6 7 10 12 14 15 20 420,92857264956831
422,1 2 422,92857264956831
423,1 3 9 423,92857264956831
424,1 2 4 8 424,92857264956831
425,1 5 17 425,92857264956831
426,1 2 3 6 426,92857264956831
427,1 7 427,92857264956831
428,1 2 4 428,92857264956831
429,1 3 11 13 429,92857264956831
430,1 2 5 10 430,92857264956831
432,1 2 3 4 6 8 9 12 16 18 432,92857264956831
434,1 2 7 14 434,92857264956831
435,1 3 5 15 435,92857264956831
436,1 2 4 436,92857264956831
437,1 19 437,92857264956831
438,1 2 3 6 438,92857264956831
440,1 2 4 5 8 10 11 20 440,92857264956831
441,1 3 7 9 21 441,92857264956831
442,1 2 13 17 442,92857264956831
444,1 2 3 4 6 12 444,92857264956831
445,1 5 445,92857264956831
446,1 2 446,92857264956831
447,1 3 447,92857264956831
448,1 2 4 7 8 14 16 448,92857264956831
450,1 2 3 5 6 9 10 15 18 450,92857264956831
451,1 11 451,92857264956831
452,1 2 4 452,92857264956831
453,1 3 453,92857264956831
454,1 2 454,92857264956831
455,1 5 7 13 455,92857264956831
456,1 2 3 4 6 8 12 19 456,92857264956831
458,1 2 458,92857264956831
459,1 3 9 17 459,92857264956831
460,1 2 4 5 10 20 460,92857264956831
462,1 2 3 6 7 11 14 21 462,92857264956831
464,1 2 4 8 16 464,92857264956831
465,1 3 5 15 465,92857264956831
466,1 2 466,92857264956831
468,1 2 3 4 6 9 12 13 18 468,92857264956831
469,1 7 469,92857264956831
470,1 2 5 10 470,92857264956831
471,1 3 471,92857264956831
472,1 2 4 8 472,92857264956831
473,1 11 473,92857264956831
474,1 2 3 6 474,92857264956831
475,1 5 19 475,92857264956831
476,1 2 4 7 14 17 476,92857264956831
477,1 3 9 477,92857264956831
478,1 2 478,92857264956831
480,1 2 3 4 5 6 8 10 12 15 16 20 480,92857264956831
481,1 13 481,92857264956831
482,1 2 482,92857264956831
483,1 3 7 21 483,92857264956831
484,1 2 4 11 22 484,92857264956831
485,1 5 485,92857264956831
486,1 2 3 6 9 18 486,92857264956831
488,1 2 4 8 488,92857264956831
489,1 3 489,92857264956831
490,1 2 5 7 10 14 490,92857264956831
492,1 2 3 4 6 12 492,92857264956831
493,1 17 493,92857264956831
494,1 2 13 19 494,92857264956831
495,1 3 5 9 11 15 495,92857264956831
496,1 2 4 8 16 496,92857264956831
497,1 7 497,92857264956831
498,1 2 3 6 498,92857264956831
500,1 2 4 5 10 20 500,92857264956831
501,1 3 501,92857264956831
502,1 2 502,92857264956831
504,1 2 3 4 6 7 8 9 12 14 18 21 504,92857264956831
505,1 5 505,92857264956831
506,1 2 11 22 506,92857264956831
507,1 3 13 507,92857264956831
508,1 2 4 508,92857264956831
510,1 2 3 5 6 10 15 17 510,92857264956831
511,1 7 511,92857264956831
512,1 2 4 8 16 512,92857264956831
513,1 3 9 19 513,92857264956831
514,1 2 514,92857264956831
515,1 5 515,92857264956831
516,1 2 3 4 6 12 516,92857264956831
517,1 11 517,92857264956831
518,1 2 7 14 518,92857264956831
519,1 3 519,92857264956831
520,1 2 4 5 8 10 13 20 520,92857264956831
522,1 2 3 6 9 18 522,92857264956831
524,1 2 4 524,92857264956831
525,1 3 5 7 15 21 525,92857264956831
526,1 2 526,92857264956831
527,1 17 527,92857264956831
528,1 2 3 4 6 8 11 12 16 22 528,92857264956831
529,1 23 529,92857264956831
530,1 2 5 10 530,92857264956831
531,1 3 9 531,92857264956831
532,1 2 4 7 14 19 532,92857264956831
533,1 13 533,92857264956831
534,1 2 3 6 534,92857264956831
535,1 5 535,92857264956831
536,1 2 4 8 536,92857264956831
537,1 3 537,92857264956831
538,1 2 538,92857264956831
539,1 7 11 539,92857264956831
540,1 2 3 4 5 6 9 10 12 15 18 20 540,92857264956831
542,1 2 542,92857264956831
543,1 3 543,92857264956831
544,1 2 4 8 16 17 544,92857264956831
545,1 5 545,92857264956831
546,1 2 3 6 7 13 14 21 546,92857264956831
548,1 2 4 548,92857264956831
549,1 3 9 549,92857264956831
550,1 2 5 10 11 22 550,92857264956831
551,1 19 551,92857264956831
552,1 2 3 4 6 8 12 23 552,92857264956831
553,1 7 553,92857264956831
554,1 2 554,92857264956831
555,1 3 5 15 555,92857264956831
556,1 2 4 556,92857264956831
558,1 2 3 6 9 18 558,92857264956831
559,1 13 559,92857264956831
560,1 2 4 5 7 8 10 14 16 20 560,92857264956831
561,1 3 11 17 561,92857264956831
562,1 2 562,92857264956831
564,1 2 3 4 6 12 564,92857264956831
565,1 5 565,92857264956831
566,1 2 566,92857264956831
567,1 3 7 9 21 567,92857264956831
568,1 2 4 8 568,92857264956831
570,1 2 3 5 6 10 15 19 570,92857264956831
572,1 2 4 11 13 22 572,92857264956831
573,1 3 573,92857264956831
574,1 2 7 14 574,92857264956831
575,1 5 23 575,92857264956831
576,1 2 3 4 6 8 9 12 16 18 24 576,92857264956831
578,1 2 17 578,92857264956831
579,1 3 579,92857264956831
580,1 2 4 5 10 20 580,92857264956831
581,1 7 581,92857264956831
582,1 2 3 6 582,92857264956831
583,1 11 583,92857264956831
584,1 2 4 8 584,92857264956831
585,1 3 5 9 13 15 585,92857264956831
586,1 2 586,92857264956831
588,1 2 3 4 6 7 12 14 21 588,92857264956831
589,1 19 589,92857264956831
590,1 2 5 10 590,92857264956831
591,1 3 591,92857264956831
592,1 2 4 8 16 592,92857264956831
594,1 2 3 6 9 11 18 22 594,92857264956831
595,1 5 7 17 595,92857264956831
596,1 2 4 596,92857264956831
597,1 3 597,92857264956831
598,1 2 13 23 598,92857264956831
600,1 2 3 4 5 6 8 10 12 15 20 24 600,92857264956831
602,1 2 7 14 602,92857264956831
603,1 3 9 603,92857264956831
604,1 2 4 604,92857264956831
605,1 5 11 605,92857264956831
606,1 2 3 6 606,92857264956831
608,1 2 4 8 16 19 608,92857264956831
609,1 3 7 21 609,92857264956831
610,1 2 5 10 610,92857264956831
611,1 13 611,92857264956831
612,1 2 3 4 6 9 12 17 18 612,92857264956831
614,1 2 614,92857264956831
615,1 3 5 15 615,92857264956831
616,1 2 4 7 8 11 14 22 616,92857264956831
618,1 2 3 6 618,92857264956831
620,1 2 4 5 10 20 620,92857264956831
621,1 3 9 23 621,92857264956831
622,1 2 622,92857264956831
623,1 7 623,92857264956831
624,1 2 3 4 6 8 12 13 16 24 624,92857264956831
625,1 5 25 625,92857264956831
626,1 2 626,92857264956831
627,1 3 11 19 627,92857264956831
628,1 2 4 628,92857264956831
629,1 17 629,92857264956831
630,1 2 3 5 6 7 9 10 14 15 18 21 630,92857264956831
632,1 2 4 8 632,92857264956831
633,1 3 633,92857264956831
634,1 2 634,92857264956831
635,1 5 635,92857264956831
636,1 2 3 4 6 12 636,92857264956831
637,1 7 13 637,92857264956831
638,1 2 11 22 638,92857264956831
639,1 3 9 639,92857264956831
640,1 2 4 5 8 10 16 20 640,92857264956831
642,1 2 3 6 642,92857264956831
644,1 2 4 7 14 23 644,92857264956831
645,1 3 5 15 645,92857264956831
646,1 2 17 19 646,92857264956831
648,1 2 3 4 6 8 9 12 18 24 648,92857264956831
649,1 11 649,92857264956831
650,1 2 5 10 13 25 650,92857264956831
651,1 3 7 21 651,92857264956831
652,1 2 4 652,92857264956831
654,1 2 3 6 654,92857264956831
655,1 5 655,92857264956831
656,1 2 4 8 16 656,92857264956831
657,1 3 9 657,92857264956831
658,1 2 7 14 658,92857264956831
660,1 2 3 4 5 6 10 11 12 15 20 22 660,92857264956831
662,1 2 662,92857264956831
663,1 3 13 17 663,92857264956831
664,1 2 4 8 664,92857264956831
665,1 5 7 19 665,92857264956831
666,1 2 3 6 9 18 666,92857264956831
667,1 23 667,92857264956831
668,1 2 4 668,92857264956831
669,1 3 669,92857264956831
670,1 2 5 10 670,92857264956831
671,1 11 671,92857264956831
672,1 2 3 4 6 7 8 12 14 16 21 24 672,92857264956831
674,1 2 674,92857264956831
675,1 3 5 9 15 25 675,92857264956831
676,1 2 4 13 26 676,92857264956831
678,1 2 3 6 678,92857264956831
679,1 7 679,92857264956831
680,1 2 4 5 8 10 17 20 680,92857264956831
681,1 3 681,92857264956831
682,1 2 11 22 682,92857264956831
684,1 2 3 4 6 9 12 18 19 684,92857264956831
685,1 5 685,92857264956831
686,1 2 7 14 686,92857264956831
687,1 3 687,92857264956831
688,1 2 4 8 16 688,92857264956831
689,1 13 689,92857264956831
690,1 2 3 5 6 10 15 23 690,92857264956831
692,1 2 4 692,92857264956831
693,1 3 7 9 11 21 693,92857264956831
694,1 2 694,92857264956831
695,1 5 695,92857264956831
696,1 2 3 4 6 8 12 24 696,92857264956831
697,1 17 697,92857264956831
698,1 2 698,92857264956831
699,1 3 699,92857264956831
700,1 2 4 5 7 10 14 20 25 700,92857264956831
702,1 2 3 6 9 13 18 26 702,92857264956831
703,1 19 703,92857264956831
704,1 2 4 8 11 16 22 704,92857264956831
705,1 3 5 15 705,92857264956831
706,1 2 706,92857264956831
707,1 7 707,92857264956831
708,1 2 3 4 6 12 708,92857264956831
710,1 2 5 10 710,92857264956831
711,1 3 9 711,92857264956831
712,1 2 4 8 712,92857264956831
713,1 23 713,92857264956831
714,1 2 3 6 7 14 17 21 714,92857264956831
715,1 5 11 13 715,92857264956831
716,1 2 4 716,92857264956831
717,1 3 717,92857264956831
718,1 2 718,92857264956831
720,1 2 3 4 5 6 8 9 10 12 15 16 18 20 24 720,92857264956831
721,1 7 721,92857264956831
722,1 2 19 722,92857264956831
723,1 3 723,92857264956831
724,1 2 4 724,92857264956831
725,1 5 25 725,92857264956831
726,1 2 3 6 11 22 726,92857264956831
728,1 2 4 7 8 13 14 26 728,92857264956831
729,1 3 9 27 729,92857264956831
730,1 2 5 10 730,92857264956831
731,1 17 731,92857264956831
732,1 2 3 4 6 12 732,92857264956831
734,1 2 734,92857264956831
735,1 3 5 7 15 21 735,92857264956831
736,1 2 4 8 16 23 736,92857264956831
737,1 11 737,92857264956831
738,1 2 3 6 9 18 738,92857264956831
740,1 2 4 5 10 20 740,92857264956831
741,1 3 13 19 741,92857264956831
742,1 2 7 14 742,92857264956831
744,1 2 3 4 6 8 12 24 744,92857264956831
745,1 5 745,92857264956831
746,1 2 746,92857264956831
747,1 3 9 747,92857264956831
748,1 2 4 11 17 22 748,92857264956831
749,1 7 749,92857264956831
750,1 2 3 5 6 10 15 25 750,92857264956831
752,1 2 4 8 16 752,92857264956831
753,1 3 753,92857264956831
754,1 2 13 26 754,92857264956831
755,1 5 755,92857264956831
756,1 2 3 4 6 7 9 12 14 18 21 27 756,92857264956831
758,1 2 758,92857264956831
759,1 3 11 23 759,92857264956831
760,1 2 4 5 8 10 19 20 760,92857264956831
762,1 2 3 6 762,92857264956831
763,1 7 763,92857264956831
764,1 2 4 764,92857264956831
765,1 3 5 9 15 17 765,92857264956831
766,1 2 766,92857264956831
767,1 13 767,92857264956831
768,1 2 3 4 6 8 12 16 24 768,92857264956831
770,1 2 5 7 10 11 14 22 770,92857264956831
771,1 3 771,92857264956831
772,1 2 4 772,92857264956831

In [ ]:
assert col['divisors'][13] == x

### Nombres abondants

**Exercice [023].** Un entier $n$ est **abondant** si et seulement s'il est inférieur à la somme de ses diviseurs stricts (_i.e._, distincts de $n$).

| Exemple | Diviseurs stricts | Propriété | Abondant |
|---:|:--:|:--:|:--:|
| $12$ | $${1, 2, 3, 4, 6}$$ | $$12 < 1+2+3+4+6 = 16$$ | ✅ |
| $16$ | $${1, 2, 4, 8}$$ | $$16 \geq 1+2+4+8 = 15$$ | ❌ |

_Tâche._ Listez par ordre croissant les nombres abondants inférieurs ou égaux à 1000.

_Contrainte._ Utilisez une auto-jointure et un regroupement.

In [ ]:
x = 36 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i < A.i
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

246 rows affected.

i,token
12,5591408610389
18,5591408610389
20,5591408610389
24,5591408610389
30,5591408610389
36,5591408610389
40,5591408610389
42,5591408610389
48,5591408610389
54,5591408610389
56,5591408610389
60,5591408610389
66,5591408610389
70,5591408610389
72,5591408610389
78,5591408610389
80,5591408610389
84,5591408610389
88,5591408610389
90,5591408610389
96,5591408610389
100,5591408610389
102,5591408610389
104,5591408610389
108,5591408610389
112,5591408610389
114,5591408610389
120,5591408610389
126,5591408610389
132,5591408610389
138,5591408610389
140,5591408610389
144,5591408610389
150,5591408610389
156,5591408610389
160,5591408610389
162,5591408610389
168,5591408610389
174,5591408610389
176,5591408610389
180,5591408610389
186,5591408610389
192,5591408610389
196,5591408610389
198,5591408610389
200,5591408610389
204,5591408610389
208,5591408610389
210,5591408610389
216,5591408610389
220,5591408610389
222,5591408610389
224,5591408610389
228,5591408610389
234,5591408610389
240,5591408610389
246,5591408610389
252,5591408610389
258,5591408610389
260,5591408610389
264,5591408610389
270,5591408610389
272,5591408610389
276,5591408610389
280,5591408610389
282,5591408610389
288,5591408610389
294,5591408610389
300,5591408610389
304,5591408610389
306,5591408610389
308,5591408610389
312,5591408610389
318,5591408610389
320,5591408610389
324,5591408610389
330,5591408610389
336,5591408610389
340,5591408610389
342,5591408610389
348,5591408610389
350,5591408610389
352,5591408610389
354,5591408610389
360,5591408610389
364,5591408610389
366,5591408610389
368,5591408610389
372,5591408610389
378,5591408610389
380,5591408610389
384,5591408610389
390,5591408610389
392,5591408610389
396,5591408610389
400,5591408610389
402,5591408610389
408,5591408610389
414,5591408610389
416,5591408610389
420,5591408610389
426,5591408610389
432,5591408610389
438,5591408610389
440,5591408610389
444,5591408610389
448,5591408610389
450,5591408610389
456,5591408610389
460,5591408610389
462,5591408610389
464,5591408610389
468,5591408610389
474,5591408610389
476,5591408610389
480,5591408610389
486,5591408610389
490,5591408610389
492,5591408610389
498,5591408610389
500,5591408610389
504,5591408610389
510,5591408610389
516,5591408610389
520,5591408610389
522,5591408610389
528,5591408610389
532,5591408610389
534,5591408610389
540,5591408610389
544,5591408610389
546,5591408610389
550,5591408610389
552,5591408610389
558,5591408610389
560,5591408610389
564,5591408610389
570,5591408610389
572,5591408610389
576,5591408610389
580,5591408610389
582,5591408610389
588,5591408610389
594,5591408610389
600,5591408610389
606,5591408610389
608,5591408610389
612,5591408610389
616,5591408610389
618,5591408610389
620,5591408610389
624,5591408610389
630,5591408610389
636,5591408610389
640,5591408610389
642,5591408610389
644,5591408610389
648,5591408610389
650,5591408610389
654,5591408610389
660,5591408610389
666,5591408610389
672,5591408610389
678,5591408610389
680,5591408610389
684,5591408610389
690,5591408610389
696,5591408610389
700,5591408610389
702,5591408610389
704,5591408610389
708,5591408610389
714,5591408610389
720,5591408610389
726,5591408610389
728,5591408610389
732,5591408610389
736,5591408610389
738,5591408610389
740,5591408610389
744,5591408610389
748,5591408610389
750,5591408610389
756,5591408610389
760,5591408610389
762,5591408610389
768,5591408610389
770,5591408610389
774,5591408610389
780,5591408610389
784,5591408610389
786,5591408610389
792,5591408610389
798,5591408610389
800,5591408610389
804,5591408610389
810,5591408610389
812,5591408610389
816,5591408610389
820,5591408610389
822,5591408610389
828,5591408610389
832,5591408610389
834,5591408610389
836,5591408610389
840,5591408610389
846,5591408610389
852,5591408610389
858,5591408610389
860,5591408610389
864,5591408610389
868,5591408610389
870,5591408610389
876,5591408610389
880,5591408610389
882,5591408610389
888,5591408610389
894,5591408610389
896,5591408610389
900,5591408610389
906,5591408610389
910,5591408610389
912,5591408610389
918,5591408610389
920,5591408610389
924,5591408610389
928,5591408610389
930,5591408610389
936,5591408610389
940,5591408610389
942,5591408610389
945,5591408610389
948,5591408610389
952,5591408610389
954,5591408610389
960,5591408610389
966,5591408610389
968,5591408610389
972,5591408610389
978,5591408610389
980,5591408610389
984,5591408610389
990,5591408610389
992,5591408610389
996,5591408610389
1000,5591408610389

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 36

In [ ]:
%%sql
-- Indication. Sommez tous les diviseurs inférieurs à $n$, y compris 1. Le résultat est le même pour les nombres
-- de notre table, mais on peut prouver mathématiquement que cette condition supplémentaire est inutile dans le
-- cas général.
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i < A.i
AND B.i > 1
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

246 rows affected.

i,token
12,62621691563930
18,62621691563930
20,62621691563930
24,62621691563930
30,62621691563930
36,62621691563930
40,62621691563930
42,62621691563930
48,62621691563930
54,62621691563930
56,62621691563930
60,62621691563930
66,62621691563930
70,62621691563930
72,62621691563930
78,62621691563930
80,62621691563930
84,62621691563930
88,62621691563930
90,62621691563930
96,62621691563930
100,62621691563930
102,62621691563930
104,62621691563930
108,62621691563930
112,62621691563930
114,62621691563930
120,62621691563930
126,62621691563930
132,62621691563930
138,62621691563930
140,62621691563930
144,62621691563930
150,62621691563930
156,62621691563930
160,62621691563930
162,62621691563930
168,62621691563930
174,62621691563930
176,62621691563930
180,62621691563930
186,62621691563930
192,62621691563930
196,62621691563930
198,62621691563930
200,62621691563930
204,62621691563930
208,62621691563930
210,62621691563930
216,62621691563930
220,62621691563930
222,62621691563930
224,62621691563930
228,62621691563930
234,62621691563930
240,62621691563930
246,62621691563930
252,62621691563930
258,62621691563930
260,62621691563930
264,62621691563930
270,62621691563930
272,62621691563930
276,62621691563930
280,62621691563930
282,62621691563930
288,62621691563930
294,62621691563930
300,62621691563930
304,62621691563930
306,62621691563930
308,62621691563930
312,62621691563930
318,62621691563930
320,62621691563930
324,62621691563930
330,62621691563930
336,62621691563930
340,62621691563930
342,62621691563930
348,62621691563930
350,62621691563930
352,62621691563930
354,62621691563930
360,62621691563930
364,62621691563930
366,62621691563930
368,62621691563930
372,62621691563930
378,62621691563930
380,62621691563930
384,62621691563930
390,62621691563930
392,62621691563930
396,62621691563930
400,62621691563930
402,62621691563930
408,62621691563930
414,62621691563930
416,62621691563930
420,62621691563930
426,62621691563930
432,62621691563930
438,62621691563930
440,62621691563930
444,62621691563930
448,62621691563930
450,62621691563930
456,62621691563930
460,62621691563930
462,62621691563930
464,62621691563930
468,62621691563930
474,62621691563930
476,62621691563930
480,62621691563930
486,62621691563930
490,62621691563930
492,62621691563930
498,62621691563930
500,62621691563930
504,62621691563930
510,62621691563930
516,62621691563930
520,62621691563930
522,62621691563930
528,62621691563930
532,62621691563930
534,62621691563930
540,62621691563930
544,62621691563930
546,62621691563930
550,62621691563930
552,62621691563930
558,62621691563930
560,62621691563930
564,62621691563930
570,62621691563930
572,62621691563930
576,62621691563930
580,62621691563930
582,62621691563930
588,62621691563930
594,62621691563930
600,62621691563930
606,62621691563930
608,62621691563930
612,62621691563930
616,62621691563930
618,62621691563930
620,62621691563930
624,62621691563930
630,62621691563930
636,62621691563930
640,62621691563930
642,62621691563930
644,62621691563930
648,62621691563930
650,62621691563930
654,62621691563930
660,62621691563930
666,62621691563930
672,62621691563930
678,62621691563930
680,62621691563930
684,62621691563930
690,62621691563930
696,62621691563930
700,62621691563930
702,62621691563930
704,62621691563930
708,62621691563930
714,62621691563930
720,62621691563930
726,62621691563930
728,62621691563930
732,62621691563930
736,62621691563930
738,62621691563930
740,62621691563930
744,62621691563930
748,62621691563930
750,62621691563930
756,62621691563930
760,62621691563930
762,62621691563930
768,62621691563930
770,62621691563930
774,62621691563930
780,62621691563930
784,62621691563930
786,62621691563930
792,62621691563930
798,62621691563930
800,62621691563930
804,62621691563930
810,62621691563930
812,62621691563930
816,62621691563930
820,62621691563930
822,62621691563930
828,62621691563930
832,62621691563930
834,62621691563930
836,62621691563930
840,62621691563930
846,62621691563930
852,62621691563930
858,62621691563930
860,62621691563930
864,62621691563930
868,62621691563930
870,62621691563930
876,62621691563930
880,62621691563930
882,62621691563930
888,62621691563930
894,62621691563930
896,62621691563930
900,62621691563930
906,62621691563930
910,62621691563930
912,62621691563930
918,62621691563930
920,62621691563930
924,62621691563930
928,62621691563930
930,62621691563930
936,62621691563930
940,62621691563930
942,62621691563930
945,62621691563930
948,62621691563930
952,62621691563930
954,62621691563930
960,62621691563930
966,62621691563930
968,62621691563930
972,62621691563930
978,62621691563930
980,62621691563930
984,62621691563930
990,62621691563930
992,62621691563930
996,62621691563930
1000,62621691563930

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 7

In [ ]:
%%sql
-- Indication. $n$ n'est pas un diviseur strict de lui-même.
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i <= A.i
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

999 rows affected.

i,token
2,14110344140782
3,14110344140782
4,14110344140782
5,14110344140782
6,14110344140782
7,14110344140782
8,14110344140782
9,14110344140782
10,14110344140782
11,14110344140782
12,14110344140782
13,14110344140782
14,14110344140782
15,14110344140782
16,14110344140782
17,14110344140782
18,14110344140782
19,14110344140782
20,14110344140782
21,14110344140782
22,14110344140782
23,14110344140782
24,14110344140782
25,14110344140782
26,14110344140782
27,14110344140782
28,14110344140782
29,14110344140782
30,14110344140782
31,14110344140782
32,14110344140782
33,14110344140782
34,14110344140782
35,14110344140782
36,14110344140782
37,14110344140782
38,14110344140782
39,14110344140782
40,14110344140782
41,14110344140782
42,14110344140782
43,14110344140782
44,14110344140782
45,14110344140782
46,14110344140782
47,14110344140782
48,14110344140782
49,14110344140782
50,14110344140782
51,14110344140782
52,14110344140782
53,14110344140782
54,14110344140782
55,14110344140782
56,14110344140782
57,14110344140782
58,14110344140782
59,14110344140782
60,14110344140782
61,14110344140782
62,14110344140782
63,14110344140782
64,14110344140782
65,14110344140782
66,14110344140782
67,14110344140782
68,14110344140782
69,14110344140782
70,14110344140782
71,14110344140782
72,14110344140782
73,14110344140782
74,14110344140782
75,14110344140782
76,14110344140782
77,14110344140782
78,14110344140782
79,14110344140782
80,14110344140782
81,14110344140782
82,14110344140782
83,14110344140782
84,14110344140782
85,14110344140782
86,14110344140782
87,14110344140782
88,14110344140782
89,14110344140782
90,14110344140782
91,14110344140782
92,14110344140782
93,14110344140782
94,14110344140782
95,14110344140782
96,14110344140782
97,14110344140782
98,14110344140782
99,14110344140782
100,14110344140782
101,14110344140782
102,14110344140782
103,14110344140782
104,14110344140782
105,14110344140782
106,14110344140782
107,14110344140782
108,14110344140782
109,14110344140782
110,14110344140782
111,14110344140782
112,14110344140782
113,14110344140782
114,14110344140782
115,14110344140782
116,14110344140782
117,14110344140782
118,14110344140782
119,14110344140782
120,14110344140782
121,14110344140782
122,14110344140782
123,14110344140782
124,14110344140782
125,14110344140782
126,14110344140782
127,14110344140782
128,14110344140782
129,14110344140782
130,14110344140782
131,14110344140782
132,14110344140782
133,14110344140782
134,14110344140782
135,14110344140782
136,14110344140782
137,14110344140782
138,14110344140782
139,14110344140782
140,14110344140782
141,14110344140782
142,14110344140782
143,14110344140782
144,14110344140782
145,14110344140782
146,14110344140782
147,14110344140782
148,14110344140782
149,14110344140782
150,14110344140782
151,14110344140782
152,14110344140782
153,14110344140782
154,14110344140782
155,14110344140782
156,14110344140782
157,14110344140782
158,14110344140782
159,14110344140782
160,14110344140782
161,14110344140782
162,14110344140782
163,14110344140782
164,14110344140782
165,14110344140782
166,14110344140782
167,14110344140782
168,14110344140782
169,14110344140782
170,14110344140782
171,14110344140782
172,14110344140782
173,14110344140782
174,14110344140782
175,14110344140782
176,14110344140782
177,14110344140782
178,14110344140782
179,14110344140782
180,14110344140782
181,14110344140782
182,14110344140782
183,14110344140782
184,14110344140782
185,14110344140782
186,14110344140782
187,14110344140782
188,14110344140782
189,14110344140782
190,14110344140782
191,14110344140782
192,14110344140782
193,14110344140782
194,14110344140782
195,14110344140782
196,14110344140782
197,14110344140782
198,14110344140782
199,14110344140782
200,14110344140782
201,14110344140782
202,14110344140782
203,14110344140782
204,14110344140782
205,14110344140782
206,14110344140782
207,14110344140782
208,14110344140782
209,14110344140782
210,14110344140782
211,14110344140782
212,14110344140782
213,14110344140782
214,14110344140782
215,14110344140782
216,14110344140782
217,14110344140782
218,14110344140782
219,14110344140782
220,14110344140782
221,14110344140782
222,14110344140782
223,14110344140782
224,14110344140782
225,14110344140782
226,14110344140782
227,14110344140782
228,14110344140782
229,14110344140782
230,14110344140782
231,14110344140782
232,14110344140782
233,14110344140782
234,14110344140782
235,14110344140782
236,14110344140782
237,14110344140782
238,14110344140782
239,14110344140782
240,14110344140782
241,14110344140782
242,14110344140782
243,14110344140782
244,14110344140782
245,14110344140782
246,14110344140782
247,14110344140782
248,14110344140782
249,14110344140782
250,14110344140782
251,14110344140782
252,14110344140782
253,14110344140782
254,14110344140782
255,14110344140782
256,14110344140782
257,14110344140782
258,14110344140782
259,14110344140782
260,14110344140782
261,14110344140782
262,14110344140782
263,14110344140782
264,14110344140782
265,14110344140782
266,14110344140782
267,14110344140782
268,14110344140782
269,14110344140782
270,14110344140782
271,14110344140782
272,14110344140782
273,14110344140782
274,14110344140782
275,14110344140782
276,14110344140782
277,14110344140782
278,14110344140782
279,14110344140782
280,14110344140782
281,14110344140782
282,14110344140782
283,14110344140782
284,14110344140782
285,14110344140782
286,14110344140782
287,14110344140782
288,14110344140782
289,14110344140782
290,14110344140782
291,14110344140782
292,14110344140782
293,14110344140782
294,14110344140782
295,14110344140782
296,14110344140782
297,14110344140782
298,14110344140782
299,14110344140782
300,14110344140782
301,14110344140782
302,14110344140782
303,14110344140782
304,14110344140782
305,14110344140782
306,14110344140782
307,14110344140782
308,14110344140782
309,14110344140782
310,14110344140782
311,14110344140782
312,14110344140782
313,14110344140782
314,14110344140782
315,14110344140782
316,14110344140782
317,14110344140782
318,14110344140782
319,14110344140782
320,14110344140782
321,14110344140782
322,14110344140782
323,14110344140782
324,14110344140782
325,14110344140782
326,14110344140782
327,14110344140782
328,14110344140782
329,14110344140782
330,14110344140782
331,14110344140782
332,14110344140782
333,14110344140782
334,14110344140782
335,14110344140782
336,14110344140782
337,14110344140782
338,14110344140782
339,14110344140782
340,14110344140782
341,14110344140782
342,14110344140782
343,14110344140782
344,14110344140782
345,14110344140782
346,14110344140782
347,14110344140782
348,14110344140782
349,14110344140782
350,14110344140782
351,14110344140782
352,14110344140782
353,14110344140782
354,14110344140782
355,14110344140782
356,14110344140782
357,14110344140782
358,14110344140782
359,14110344140782
360,14110344140782
361,14110344140782
362,14110344140782
363,14110344140782
364,14110344140782
365,14110344140782
366,14110344140782
367,14110344140782
368,14110344140782
369,14110344140782
370,14110344140782
371,14110344140782
372,14110344140782
373,14110344140782
374,14110344140782
375,14110344140782
376,14110344140782
377,14110344140782
378,14110344140782
379,14110344140782
380,14110344140782
381,14110344140782
382,14110344140782
383,14110344140782
384,14110344140782
385,14110344140782
386,14110344140782
387,14110344140782
388,14110344140782
389,14110344140782
390,14110344140782
391,14110344140782
392,14110344140782
393,14110344140782
394,14110344140782
395,14110344140782
396,14110344140782
397,14110344140782
398,14110344140782
399,14110344140782
400,14110344140782
401,14110344140782
402,14110344140782
403,14110344140782
404,14110344140782
405,14110344140782
406,14110344140782
407,14110344140782
408,14110344140782
409,14110344140782
410,14110344140782
411,14110344140782
412,14110344140782
413,14110344140782
414,14110344140782
415,14110344140782
416,14110344140782
417,14110344140782
418,14110344140782
419,14110344140782
420,14110344140782
421,14110344140782
422,14110344140782
423,14110344140782
424,14110344140782
425,14110344140782
426,14110344140782
427,14110344140782
428,14110344140782
429,14110344140782
430,14110344140782
431,14110344140782
432,14110344140782
433,14110344140782
434,14110344140782
435,14110344140782
436,14110344140782
437,14110344140782
438,14110344140782
439,14110344140782
440,14110344140782
441,14110344140782
442,14110344140782
443,14110344140782
444,14110344140782
445,14110344140782
446,14110344140782
447,14110344140782
448,14110344140782
449,14110344140782
450,14110344140782
451,14110344140782
452,14110344140782
453,14110344140782
454,14110344140782
455,14110344140782
456,14110344140782
457,14110344140782
458,14110344140782
459,14110344140782
460,14110344140782
461,14110344140782
462,14110344140782
463,14110344140782
464,14110344140782
465,14110344140782
466,14110344140782
467,14110344140782
468,14110344140782
469,14110344140782
470,14110344140782
471,14110344140782
472,14110344140782
473,14110344140782
474,14110344140782
475,14110344140782
476,14110344140782
477,14110344140782
478,14110344140782
479,14110344140782
480,14110344140782
481,14110344140782
482,14110344140782
483,14110344140782
484,14110344140782
485,14110344140782
486,14110344140782
487,14110344140782
488,14110344140782
489,14110344140782
490,14110344140782
491,14110344140782
492,14110344140782
493,14110344140782
494,14110344140782
495,14110344140782
496,14110344140782
497,14110344140782
498,14110344140782
499,14110344140782
500,14110344140782
501,14110344140782
502,14110344140782
503,14110344140782
504,14110344140782
505,14110344140782
506,14110344140782
507,14110344140782
508,14110344140782
509,14110344140782
510,14110344140782
511,14110344140782
512,14110344140782
513,14110344140782
514,14110344140782
515,14110344140782
516,14110344140782
517,14110344140782
518,14110344140782
519,14110344140782
520,14110344140782
521,14110344140782
522,14110344140782
523,14110344140782
524,14110344140782
525,14110344140782
526,14110344140782
527,14110344140782
528,14110344140782
529,14110344140782
530,14110344140782
531,14110344140782
532,14110344140782
533,14110344140782
534,14110344140782
535,14110344140782
536,14110344140782
537,14110344140782
538,14110344140782
539,14110344140782
540,14110344140782
541,14110344140782
542,14110344140782
543,14110344140782
544,14110344140782
545,14110344140782
546,14110344140782
547,14110344140782
548,14110344140782
549,14110344140782
550,14110344140782
551,14110344140782
552,14110344140782
553,14110344140782
554,14110344140782
555,14110344140782
556,14110344140782
557,14110344140782
558,14110344140782
559,14110344140782
560,14110344140782
561,14110344140782
562,14110344140782
563,14110344140782
564,14110344140782
565,14110344140782
566,14110344140782
567,14110344140782
568,14110344140782
569,14110344140782
570,14110344140782
571,14110344140782
572,14110344140782
573,14110344140782
574,14110344140782
575,14110344140782
576,14110344140782
577,14110344140782
578,14110344140782
579,14110344140782
580,14110344140782
581,14110344140782
582,14110344140782
583,14110344140782
584,14110344140782
585,14110344140782
586,14110344140782
587,14110344140782
588,14110344140782
589,14110344140782
590,14110344140782
591,14110344140782
592,14110344140782
593,14110344140782
594,14110344140782
595,14110344140782
596,14110344140782
597,14110344140782
598,14110344140782
599,14110344140782
600,14110344140782
601,14110344140782
602,14110344140782
603,14110344140782
604,14110344140782
605,14110344140782
606,14110344140782
607,14110344140782
608,14110344140782
609,14110344140782
610,14110344140782
611,14110344140782
612,14110344140782
613,14110344140782
614,14110344140782
615,14110344140782
616,14110344140782
617,14110344140782
618,14110344140782
619,14110344140782
620,14110344140782
621,14110344140782
622,14110344140782
623,14110344140782
624,14110344140782
625,14110344140782
626,14110344140782
627,14110344140782
628,14110344140782
629,14110344140782
630,14110344140782
631,14110344140782
632,14110344140782
633,14110344140782
634,14110344140782
635,14110344140782
636,14110344140782
637,14110344140782
638,14110344140782
639,14110344140782
640,14110344140782
641,14110344140782
642,14110344140782
643,14110344140782
644,14110344140782
645,14110344140782
646,14110344140782
647,14110344140782
648,14110344140782
649,14110344140782
650,14110344140782
651,14110344140782
652,14110344140782
653,14110344140782
654,14110344140782
655,14110344140782
656,14110344140782
657,14110344140782
658,14110344140782
659,14110344140782
660,14110344140782
661,14110344140782
662,14110344140782
663,14110344140782
664,14110344140782
665,14110344140782
666,14110344140782
667,14110344140782
668,14110344140782
669,14110344140782
670,14110344140782
671,14110344140782
672,14110344140782
673,14110344140782
674,14110344140782
675,14110344140782
676,14110344140782
677,14110344140782
678,14110344140782
679,14110344140782
680,14110344140782
681,14110344140782
682,14110344140782
683,14110344140782
684,14110344140782
685,14110344140782
686,14110344140782
687,14110344140782
688,14110344140782
689,14110344140782
690,14110344140782
691,14110344140782
692,14110344140782
693,14110344140782
694,14110344140782
695,14110344140782
696,14110344140782
697,14110344140782
698,14110344140782
699,14110344140782
700,14110344140782
701,14110344140782
702,14110344140782
703,14110344140782
704,14110344140782
705,14110344140782
706,14110344140782
707,14110344140782
708,14110344140782
709,14110344140782
710,14110344140782
711,14110344140782
712,14110344140782
713,14110344140782
714,14110344140782
715,14110344140782
716,14110344140782
717,14110344140782
718,14110344140782
719,14110344140782
720,14110344140782
721,14110344140782
722,14110344140782
723,14110344140782
724,14110344140782
725,14110344140782
726,14110344140782
727,14110344140782
728,14110344140782
729,14110344140782
730,14110344140782
731,14110344140782
732,14110344140782
733,14110344140782
734,14110344140782
735,14110344140782
736,14110344140782
737,14110344140782
738,14110344140782
739,14110344140782
740,14110344140782
741,14110344140782
742,14110344140782
743,14110344140782
744,14110344140782
745,14110344140782
746,14110344140782
747,14110344140782
748,14110344140782
749,14110344140782
750,14110344140782
751,14110344140782
752,14110344140782
753,14110344140782
754,14110344140782
755,14110344140782
756,14110344140782
757,14110344140782
758,14110344140782
759,14110344140782
760,14110344140782
761,14110344140782
762,14110344140782
763,14110344140782
764,14110344140782
765,14110344140782
766,14110344140782
767,14110344140782
768,14110344140782
769,14110344140782
770,14110344140782
771,14110344140782
772,14110344140782
773,14110344140782
774,14110344140782
775,14110344140782
776,14110344140782
777,14110344140782
778,14110344140782
779,14110344140782
780,14110344140782
781,14110344140782
782,14110344140782
783,14110344140782
784,14110344140782
785,14110344140782
786,14110344140782
787,14110344140782
788,14110344140782
789,14110344140782
790,14110344140782
791,14110344140782
792,14110344140782
793,14110344140782
794,14110344140782
795,14110344140782
796,14110344140782
797,14110344140782
798,14110344140782
799,14110344140782
800,14110344140782
801,14110344140782
802,14110344140782
803,14110344140782
804,14110344140782
805,14110344140782
806,14110344140782
807,14110344140782
808,14110344140782
809,14110344140782
810,14110344140782
811,14110344140782
812,14110344140782
813,14110344140782
814,14110344140782
815,14110344140782
816,14110344140782
817,14110344140782
818,14110344140782
819,14110344140782
820,14110344140782
821,14110344140782
822,14110344140782
823,14110344140782
824,14110344140782
825,14110344140782
826,14110344140782
827,14110344140782
828,14110344140782
829,14110344140782
830,14110344140782
831,14110344140782
832,14110344140782
833,14110344140782
834,14110344140782
835,14110344140782
836,14110344140782
837,14110344140782
838,14110344140782
839,14110344140782
840,14110344140782
841,14110344140782
842,14110344140782
843,14110344140782
844,14110344140782
845,14110344140782
846,14110344140782
847,14110344140782
848,14110344140782
849,14110344140782
850,14110344140782
851,14110344140782
852,14110344140782
853,14110344140782
854,14110344140782
855,14110344140782
856,14110344140782
857,14110344140782
858,14110344140782
859,14110344140782
860,14110344140782
861,14110344140782
862,14110344140782
863,14110344140782
864,14110344140782
865,14110344140782
866,14110344140782
867,14110344140782
868,14110344140782
869,14110344140782
870,14110344140782
871,14110344140782
872,14110344140782
873,14110344140782
874,14110344140782
875,14110344140782
876,14110344140782
877,14110344140782
878,14110344140782
879,14110344140782
880,14110344140782
881,14110344140782
882,14110344140782
883,14110344140782
884,14110344140782
885,14110344140782
886,14110344140782
887,14110344140782
888,14110344140782
889,14110344140782
890,14110344140782
891,14110344140782
892,14110344140782
893,14110344140782
894,14110344140782
895,14110344140782
896,14110344140782
897,14110344140782
898,14110344140782
899,14110344140782
900,14110344140782
901,14110344140782
902,14110344140782
903,14110344140782
904,14110344140782
905,14110344140782
906,14110344140782
907,14110344140782
908,14110344140782
909,14110344140782
910,14110344140782
911,14110344140782
912,14110344140782
913,14110344140782
914,14110344140782
915,14110344140782
916,14110344140782
917,14110344140782
918,14110344140782
919,14110344140782
920,14110344140782
921,14110344140782
922,14110344140782
923,14110344140782
924,14110344140782
925,14110344140782
926,14110344140782
927,14110344140782
928,14110344140782
929,14110344140782
930,14110344140782
931,14110344140782
932,14110344140782
933,14110344140782
934,14110344140782
935,14110344140782
936,14110344140782
937,14110344140782
938,14110344140782
939,14110344140782
940,14110344140782
941,14110344140782
942,14110344140782
943,14110344140782
944,14110344140782
945,14110344140782
946,14110344140782
947,14110344140782
948,14110344140782
949,14110344140782
950,14110344140782
951,14110344140782
952,14110344140782
953,14110344140782
954,14110344140782
955,14110344140782
956,14110344140782
957,14110344140782
958,14110344140782
959,14110344140782
960,14110344140782
961,14110344140782
962,14110344140782
963,14110344140782
964,14110344140782
965,14110344140782
966,14110344140782
967,14110344140782
968,14110344140782
969,14110344140782
970,14110344140782
971,14110344140782
972,14110344140782
973,14110344140782
974,14110344140782
975,14110344140782
976,14110344140782
977,14110344140782
978,14110344140782
979,14110344140782
980,14110344140782
981,14110344140782
982,14110344140782
983,14110344140782
984,14110344140782
985,14110344140782
986,14110344140782
987,14110344140782
988,14110344140782
989,14110344140782
990,14110344140782
991,14110344140782
992,14110344140782
993,14110344140782
994,14110344140782
995,14110344140782
996,14110344140782
997,14110344140782
998,14110344140782
999,14110344140782
1000,14110344140782

In [ ]:
assert col['i'][5] == x

**Exercice [024].** Un entier $n$ est **abondant** si et seulement s'il est inférieur à la somme de ses diviseurs stricts (_i.e._, distincts de $n$).

| Exemple | Diviseurs stricts | Propriété | Abondant |
|---:|:--:|:--:|:--:|
| $12$ | $${1, 2, 3, 4, 6}$$ | $$12 < 1+2+3+4+6 = 16$$ | ✅ |
| $16$ | $${1, 2, 4, 8}$$ | $$16 \geq 1+2+4+8 = 15$$ | ❌ |

_Tâche._ Listez par ordre croissant les nombres abondants inférieurs ou égaux à 1000.

_Contrainte._ Utilisez une sous-requête corrélée, et pas de regroupement.

In [ ]:
x = 36 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT A.i
     , salt_024({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE A.i <
        (SELECT sum(B.i)
         FROM ints B
         WHERE B.i < A.i
             AND A.i % B.i = 0 )
ORDER BY 1

246 rows affected.

i,token
12,248960157567190
18,248960157567190
20,248960157567190
24,248960157567190
30,248960157567190
36,248960157567190
40,248960157567190
42,248960157567190
48,248960157567190
54,248960157567190
56,248960157567190
60,248960157567190
66,248960157567190
70,248960157567190
72,248960157567190
78,248960157567190
80,248960157567190
84,248960157567190
88,248960157567190
90,248960157567190
96,248960157567190
100,248960157567190
102,248960157567190
104,248960157567190
108,248960157567190
112,248960157567190
114,248960157567190
120,248960157567190
126,248960157567190
132,248960157567190
138,248960157567190
140,248960157567190
144,248960157567190
150,248960157567190
156,248960157567190
160,248960157567190
162,248960157567190
168,248960157567190
174,248960157567190
176,248960157567190
180,248960157567190
186,248960157567190
192,248960157567190
196,248960157567190
198,248960157567190
200,248960157567190
204,248960157567190
208,248960157567190
210,248960157567190
216,248960157567190
220,248960157567190
222,248960157567190
224,248960157567190
228,248960157567190
234,248960157567190
240,248960157567190
246,248960157567190
252,248960157567190
258,248960157567190
260,248960157567190
264,248960157567190
270,248960157567190
272,248960157567190
276,248960157567190
280,248960157567190
282,248960157567190
288,248960157567190
294,248960157567190
300,248960157567190
304,248960157567190
306,248960157567190
308,248960157567190
312,248960157567190
318,248960157567190
320,248960157567190
324,248960157567190
330,248960157567190
336,248960157567190
340,248960157567190
342,248960157567190
348,248960157567190
350,248960157567190
352,248960157567190
354,248960157567190
360,248960157567190
364,248960157567190
366,248960157567190
368,248960157567190
372,248960157567190
378,248960157567190
380,248960157567190
384,248960157567190
390,248960157567190
392,248960157567190
396,248960157567190
400,248960157567190
402,248960157567190
408,248960157567190
414,248960157567190
416,248960157567190
420,248960157567190
426,248960157567190
432,248960157567190
438,248960157567190
440,248960157567190
444,248960157567190
448,248960157567190
450,248960157567190
456,248960157567190
460,248960157567190
462,248960157567190
464,248960157567190
468,248960157567190
474,248960157567190
476,248960157567190
480,248960157567190
486,248960157567190
490,248960157567190
492,248960157567190
498,248960157567190
500,248960157567190
504,248960157567190
510,248960157567190
516,248960157567190
520,248960157567190
522,248960157567190
528,248960157567190
532,248960157567190
534,248960157567190
540,248960157567190
544,248960157567190
546,248960157567190
550,248960157567190
552,248960157567190
558,248960157567190
560,248960157567190
564,248960157567190
570,248960157567190
572,248960157567190
576,248960157567190
580,248960157567190
582,248960157567190
588,248960157567190
594,248960157567190
600,248960157567190
606,248960157567190
608,248960157567190
612,248960157567190
616,248960157567190
618,248960157567190
620,248960157567190
624,248960157567190
630,248960157567190
636,248960157567190
640,248960157567190
642,248960157567190
644,248960157567190
648,248960157567190
650,248960157567190
654,248960157567190
660,248960157567190
666,248960157567190
672,248960157567190
678,248960157567190
680,248960157567190
684,248960157567190
690,248960157567190
696,248960157567190
700,248960157567190
702,248960157567190
704,248960157567190
708,248960157567190
714,248960157567190
720,248960157567190
726,248960157567190
728,248960157567190
732,248960157567190
736,248960157567190
738,248960157567190
740,248960157567190
744,248960157567190
748,248960157567190
750,248960157567190
756,248960157567190
760,248960157567190
762,248960157567190
768,248960157567190
770,248960157567190
774,248960157567190
780,248960157567190
784,248960157567190
786,248960157567190
792,248960157567190
798,248960157567190
800,248960157567190
804,248960157567190
810,248960157567190
812,248960157567190
816,248960157567190
820,248960157567190
822,248960157567190
828,248960157567190
832,248960157567190
834,248960157567190
836,248960157567190
840,248960157567190
846,248960157567190
852,248960157567190
858,248960157567190
860,248960157567190
864,248960157567190
868,248960157567190
870,248960157567190
876,248960157567190
880,248960157567190
882,248960157567190
888,248960157567190
894,248960157567190
896,248960157567190
900,248960157567190
906,248960157567190
910,248960157567190
912,248960157567190
918,248960157567190
920,248960157567190
924,248960157567190
928,248960157567190
930,248960157567190
936,248960157567190
940,248960157567190
942,248960157567190
945,248960157567190
948,248960157567190
952,248960157567190
954,248960157567190
960,248960157567190
966,248960157567190
968,248960157567190
972,248960157567190
978,248960157567190
980,248960157567190
984,248960157567190
990,248960157567190
992,248960157567190
996,248960157567190
1000,248960157567190

In [ ]:
assert col['i'][5] == x

### Entiers sans facteurs carrés

**Exercice [037].** Un entier est **sans facteur carré** si et seulement si aucun des nombres de sa décomposition en facteurs premiers n'apparaît plus d'une fois.

| Exemple | Décomposition | Propriété | Sans facteur carré |
|---:|:--:|:--:|:--:|
| $30$ | $$2 \times 3 \times 5$$ | aucun facteur dupliqué | ✅ |
| $12$ | $$2 \times 2 \times 3$$ | $2$ apparaît plus d'une fois | ❌ |

_Tâche._ Listez par ordre croissant les entiers sans facteurs carrés inférieurs ou égaux à 1000.

In [ ]:
%%sql
WITH squares AS
    (SELECT DISTINCT B.i * B.i AS N2
                   , hash
     FROM ints B
     WHERE B.i * B.i <= 1000
         AND B.i > 1 )
SELECT A.i
     , salt_037(bit_xor(sum(nn(A.hash) + nn(S.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN squares S ON A.i % S.n2 = 0
GROUP BY A.i
HAVING count(S.n2) = 0

608 rows affected.

i,token
1,183542481619562
2,183542481619562
3,183542481619562
5,183542481619562
6,183542481619562
7,183542481619562
10,183542481619562
11,183542481619562
13,183542481619562
14,183542481619562
15,183542481619562
17,183542481619562
19,183542481619562
21,183542481619562
22,183542481619562
23,183542481619562
26,183542481619562
29,183542481619562
30,183542481619562
31,183542481619562
33,183542481619562
34,183542481619562
35,183542481619562
37,183542481619562
38,183542481619562
39,183542481619562
41,183542481619562
42,183542481619562
43,183542481619562
46,183542481619562
47,183542481619562
51,183542481619562
53,183542481619562
55,183542481619562
57,183542481619562
58,183542481619562
59,183542481619562
61,183542481619562
62,183542481619562
65,183542481619562
66,183542481619562
67,183542481619562
69,183542481619562
70,183542481619562
71,183542481619562
73,183542481619562
74,183542481619562
77,183542481619562
78,183542481619562
79,183542481619562
82,183542481619562
83,183542481619562
85,183542481619562
86,183542481619562
87,183542481619562
89,183542481619562
91,183542481619562
93,183542481619562
94,183542481619562
95,183542481619562
97,183542481619562
101,183542481619562
102,183542481619562
103,183542481619562
105,183542481619562
106,183542481619562
107,183542481619562
109,183542481619562
110,183542481619562
111,183542481619562
113,183542481619562
114,183542481619562
115,183542481619562
118,183542481619562
119,183542481619562
122,183542481619562
123,183542481619562
127,183542481619562
129,183542481619562
130,183542481619562
131,183542481619562
133,183542481619562
134,183542481619562
137,183542481619562
138,183542481619562
139,183542481619562
141,183542481619562
142,183542481619562
143,183542481619562
145,183542481619562
146,183542481619562
149,183542481619562
151,183542481619562
154,183542481619562
155,183542481619562
157,183542481619562
158,183542481619562
159,183542481619562
161,183542481619562
163,183542481619562
165,183542481619562
166,183542481619562
167,183542481619562
170,183542481619562
173,183542481619562
174,183542481619562
177,183542481619562
178,183542481619562
179,183542481619562
181,183542481619562
182,183542481619562
183,183542481619562
185,183542481619562
186,183542481619562
187,183542481619562
190,183542481619562
191,183542481619562
193,183542481619562
194,183542481619562
195,183542481619562
197,183542481619562
199,183542481619562
201,183542481619562
202,183542481619562
203,183542481619562
205,183542481619562
206,183542481619562
209,183542481619562
210,183542481619562
211,183542481619562
213,183542481619562
214,183542481619562
215,183542481619562
217,183542481619562
218,183542481619562
219,183542481619562
221,183542481619562
222,183542481619562
223,183542481619562
226,183542481619562
227,183542481619562
229,183542481619562
230,183542481619562
231,183542481619562
233,183542481619562
235,183542481619562
237,183542481619562
238,183542481619562
239,183542481619562
241,183542481619562
246,183542481619562
247,183542481619562
249,183542481619562
251,183542481619562
253,183542481619562
254,183542481619562
255,183542481619562
257,183542481619562
258,183542481619562
259,183542481619562
262,183542481619562
263,183542481619562
265,183542481619562
266,183542481619562
267,183542481619562
269,183542481619562
271,183542481619562
273,183542481619562
274,183542481619562
277,183542481619562
278,183542481619562
281,183542481619562
282,183542481619562
283,183542481619562
285,183542481619562
286,183542481619562
287,183542481619562
290,183542481619562
291,183542481619562
293,183542481619562
295,183542481619562
298,183542481619562
299,183542481619562
301,183542481619562
302,183542481619562
303,183542481619562
305,183542481619562
307,183542481619562
309,183542481619562
310,183542481619562
311,183542481619562
313,183542481619562
314,183542481619562
317,183542481619562
318,183542481619562
319,183542481619562
321,183542481619562
322,183542481619562
323,183542481619562
326,183542481619562
327,183542481619562
329,183542481619562
330,183542481619562
331,183542481619562
334,183542481619562
335,183542481619562
337,183542481619562
339,183542481619562
341,183542481619562
345,183542481619562
346,183542481619562
347,183542481619562
349,183542481619562
353,183542481619562
354,183542481619562
355,183542481619562
357,183542481619562
358,183542481619562
359,183542481619562
362,183542481619562
365,183542481619562
366,183542481619562
367,183542481619562
370,183542481619562
371,183542481619562
373,183542481619562
374,183542481619562
377,183542481619562
379,183542481619562
381,183542481619562
382,183542481619562
383,183542481619562
385,183542481619562
386,183542481619562
389,183542481619562
390,183542481619562
391,183542481619562
393,183542481619562
394,183542481619562
395,183542481619562
397,183542481619562
398,183542481619562
399,183542481619562
401,183542481619562
402,183542481619562
403,183542481619562
406,183542481619562
407,183542481619562
409,183542481619562
410,183542481619562
411,183542481619562
413,183542481619562
415,183542481619562
417,183542481619562
418,183542481619562
419,183542481619562
421,183542481619562
422,183542481619562
426,183542481619562
427,183542481619562
429,183542481619562
430,183542481619562
431,183542481619562
433,183542481619562
434,183542481619562
435,183542481619562
437,183542481619562
438,183542481619562
439,183542481619562
442,183542481619562
443,183542481619562
445,183542481619562
446,183542481619562
447,183542481619562
449,183542481619562
451,183542481619562
453,183542481619562
454,183542481619562
455,183542481619562
457,183542481619562
458,183542481619562
461,183542481619562
462,183542481619562
463,183542481619562
465,183542481619562
466,183542481619562
467,183542481619562
469,183542481619562
470,183542481619562
471,183542481619562
473,183542481619562
474,183542481619562
478,183542481619562
479,183542481619562
481,183542481619562
482,183542481619562
483,183542481619562
485,183542481619562
487,183542481619562
489,183542481619562
491,183542481619562
493,183542481619562
494,183542481619562
497,183542481619562
498,183542481619562
499,183542481619562
501,183542481619562
502,183542481619562
503,183542481619562
505,183542481619562
506,183542481619562
509,183542481619562
510,183542481619562
511,183542481619562
514,183542481619562
515,183542481619562
517,183542481619562
518,183542481619562
519,183542481619562
521,183542481619562
523,183542481619562
526,183542481619562
527,183542481619562
530,183542481619562
533,183542481619562
534,183542481619562
535,183542481619562
537,183542481619562
538,183542481619562
541,183542481619562
542,183542481619562
543,183542481619562
545,183542481619562
546,183542481619562
547,183542481619562
551,183542481619562
553,183542481619562
554,183542481619562
555,183542481619562
557,183542481619562
559,183542481619562
561,183542481619562
562,183542481619562
563,183542481619562
565,183542481619562
566,183542481619562
569,183542481619562
570,183542481619562
571,183542481619562
573,183542481619562
574,183542481619562
577,183542481619562
579,183542481619562
581,183542481619562
582,183542481619562
583,183542481619562
586,183542481619562
587,183542481619562
589,183542481619562
590,183542481619562
591,183542481619562
593,183542481619562
595,183542481619562
597,183542481619562
598,183542481619562
599,183542481619562
601,183542481619562
602,183542481619562
606,183542481619562
607,183542481619562
609,183542481619562
610,183542481619562
611,183542481619562
613,183542481619562
614,183542481619562
615,183542481619562
617,183542481619562
618,183542481619562
619,183542481619562
622,183542481619562
623,183542481619562
626,183542481619562
627,183542481619562
629,183542481619562
631,183542481619562
633,183542481619562
634,183542481619562
635,183542481619562
638,183542481619562
641,183542481619562
642,183542481619562
643,183542481619562
645,183542481619562
646,183542481619562
647,183542481619562
649,183542481619562
651,183542481619562
653,183542481619562
654,183542481619562
655,183542481619562
658,183542481619562
659,183542481619562
661,183542481619562
662,183542481619562
663,183542481619562
665,183542481619562
667,183542481619562
669,183542481619562
670,183542481619562
671,183542481619562
673,183542481619562
674,183542481619562
677,183542481619562
678,183542481619562
679,183542481619562
681,183542481619562
682,183542481619562
683,183542481619562
685,183542481619562
687,183542481619562
689,183542481619562
690,183542481619562
691,183542481619562
694,183542481619562
695,183542481619562
697,183542481619562
698,183542481619562
699,183542481619562
701,183542481619562
703,183542481619562
705,183542481619562
706,183542481619562
707,183542481619562
709,183542481619562
710,183542481619562
713,183542481619562
714,183542481619562
715,183542481619562
717,183542481619562
718,183542481619562
719,183542481619562
721,183542481619562
723,183542481619562
727,183542481619562
730,183542481619562
731,183542481619562
733,183542481619562
734,183542481619562
737,183542481619562
739,183542481619562
741,183542481619562
742,183542481619562
743,183542481619562
745,183542481619562
746,183542481619562
749,183542481619562
751,183542481619562
753,183542481619562
754,183542481619562
755,183542481619562
757,183542481619562
758,183542481619562
759,183542481619562
761,183542481619562
762,183542481619562
763,183542481619562
766,183542481619562
767,183542481619562
769,183542481619562
770,183542481619562
771,183542481619562
773,183542481619562
777,183542481619562
778,183542481619562
779,183542481619562
781,183542481619562
782,183542481619562
785,183542481619562
786,183542481619562
787,183542481619562
789,183542481619562
790,183542481619562
791,183542481619562
793,183542481619562
794,183542481619562
795,183542481619562
797,183542481619562
798,183542481619562
799,183542481619562
802,183542481619562
803,183542481619562
805,183542481619562
806,183542481619562
807,183542481619562
809,183542481619562
811,183542481619562
813,183542481619562
814,183542481619562
815,183542481619562
817,183542481619562
818,183542481619562
821,183542481619562
822,183542481619562
823,183542481619562
826,183542481619562
827,183542481619562
829,183542481619562
830,183542481619562
831,183542481619562
834,183542481619562
835,183542481619562
838,183542481619562
839,183542481619562
842,183542481619562
843,183542481619562
849,183542481619562
851,183542481619562
853,183542481619562
854,183542481619562
857,183542481619562
858,183542481619562
859,183542481619562
861,183542481619562
862,183542481619562
863,183542481619562
865,183542481619562
866,183542481619562
869,183542481619562
870,183542481619562
871,183542481619562
874,183542481619562
877,183542481619562
878,183542481619562
879,183542481619562
881,183542481619562
883,183542481619562
885,183542481619562
886,183542481619562
887,183542481619562
889,183542481619562
890,183542481619562
893,183542481619562
894,183542481619562
895,183542481619562
897,183542481619562
898,183542481619562
899,183542481619562
901,183542481619562
902,183542481619562
903,183542481619562
905,183542481619562
906,183542481619562
907,183542481619562
910,183542481619562
911,183542481619562
913,183542481619562
914,183542481619562
915,183542481619562
917,183542481619562
919,183542481619562
921,183542481619562
922,183542481619562
923,183542481619562
926,183542481619562
929,183542481619562
930,183542481619562
933,183542481619562
934,183542481619562
935,183542481619562
937,183542481619562
938,183542481619562
939,183542481619562
941,183542481619562
942,183542481619562
943,183542481619562
946,183542481619562
947,183542481619562
949,183542481619562
951,183542481619562
953,183542481619562
955,183542481619562
957,183542481619562
958,183542481619562
959,183542481619562
962,183542481619562
965,183542481619562
966,183542481619562
967,183542481619562
969,183542481619562
970,183542481619562
971,183542481619562
973,183542481619562
974,183542481619562
977,183542481619562
978,183542481619562
979,183542481619562
982,183542481619562
983,183542481619562
985,183542481619562
986,183542481619562
987,183542481619562
989,183542481619562
991,183542481619562
993,183542481619562
994,183542481619562
995,183542481619562
997,183542481619562
998,183542481619562

### Nombres de Kaprekar

**Exercice [009].** Un entier $n$ est un **nombre de Kaprekar** si et seulement si son carré peut être séparé en une partie gauche et une partie droite dont la somme vaut $n$. La partie gauche peut être vide. La partie droite ne peut être vide ou nulle.

| Exemple | Carré | Découpage       | Somme | Kaprekar                 |
|--------:|------:|----------------:|------:|:-------------------------|
| 1       | 1     | `"" + "1"`      | 1     | ✅ (NB : partie gauche vide)  |
| 5       | 25    | `"" + "25"` <br> `"2" + "5"`    | 25 <br> 7 | ❌                       |
| 9       | 81    | `"8" + "1"`     | 9     | ✅                       |
| 45      | 2025  | `"20" + "25"`   | 45    | ✅                       |
| 10      | 100   | `"10" + "0"`    | 10    | ❌ (partie droite nulle) |
| 99      | 9801  | `"98" + "01"`   | 99    | ✅                       |

_Tâche._ Listez par ordre croissant les nombres de Kaprekar inférieurs ou égaux à 1000.

_Aide._ Utilisez les fonctions `left(str, len)` et `right(str, len)`.

**Annotation.**
On parcourt tous les entiers $A_i$ candidats, en excluant immédiatement les multiples de $10$
(`i % 10 != 0`).

Pour chaque $A_i$, on vérifie si c'est un nombre de Kaprekar via la sous-requête `EXISTS` :

- On prend le même entier $A_i$ sous l'alias $B_i$.
- On parcourt toutes les positions de coupe jusque avant le dernier caractère de $B_i^2$.
- On découpe $B_i^2$ et on somme les parties.
- On s'assure que cette somme est égale à $A_i$.

In [ ]:
%%sql
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS A
WHERE i % 10 != 0
    AND EXISTS
        (SELECT 1
         FROM ints AS cut
         JOIN ints AS B ON cut.i < length(B.i * B.i)
         WHERE A.i = B.i
             AND A.i = left(B.i * B.i, cut.i) + right(B.i * B.i, length(B.i * B.i) - cut.i) )

8 rows affected.

i,token
1,253600606633879
9,253600606633879
45,253600606633879
55,253600606633879
99,253600606633879
297,253600606633879
703,253600606633879
999,253600606633879

In [ ]:
%%sql
-- Variante. Avec une CTE qui précalcule les carrés une fois pour toutes.
WITH squares AS
    (SELECT i
          , i * i AS I2
     FROM ints)
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS A
WHERE i % 10 != 0
    AND EXISTS
        (SELECT 1
         FROM ints AS cut
         JOIN squares ON cut.i < length(I2)
         WHERE A.i = squares.i
             AND A.i = left(I2, cut.i) + right(I2, length(I2) - cut.i) )

8 rows affected.

i,token
1,253600606633879
9,253600606633879
45,253600606633879
55,253600606633879
99,253600606633879
297,253600606633879
703,253600606633879
999,253600606633879

In [ ]:
%%sql
-- Indication. Vérifiez les positions de coupe.
WITH squares AS
    (SELECT i
          , i * i AS I2
     FROM ints)
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS A
WHERE i % 10 != 0
    AND EXISTS
        (SELECT 1
         FROM ints AS cut
         JOIN squares ON cut.i < length(I2)
         WHERE A.i = squares.i
             AND A.i = left(I2, cut.i - 1) + right(I2, length(I2) - cut.i + 1) )

7 rows affected.

i,token
1,253974688626775
45,253974688626775
55,253974688626775
99,253974688626775
297,253974688626775
703,253974688626775
999,253974688626775

In [ ]:
%%sql
-- Indication. La partie gauche peut avoir comme longueur 1.
WITH squares AS
    (SELECT i
          , i * i AS I2
     FROM ints)
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS A
WHERE i % 10 != 0
    AND EXISTS
        (SELECT 1
         FROM ints AS cut
         JOIN squares ON cut.i < length(I2) - 1
         WHERE A.i = squares.i
             AND A.i = left(I2, cut.i) + right(I2, length(I2) - cut.i) )

6 rows affected.

i,token
45,254220120595727
55,254220120595727
99,254220120595727
297,254220120595727
703,254220120595727
999,254220120595727

In [ ]:
%%sql
-- Indication. Une suite de zéros n'est pas autorisée pour la partie droite.
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS base
WHERE EXISTS
        (SELECT 1
         FROM
             (SELECT base.i
                   , cast(left(sq, cut.i) AS UNSIGNED) AS left_part
                   , cast(right(sq, length(sq) - cut.i) AS UNSIGNED) AS right_part
              FROM
                  (SELECT i
                        , cast(i * i AS CHAR) AS sq
                   FROM ints) AS base
              JOIN ints AS cut ON cut.i BETWEEN 1 AND length(base.sq) - 1) AS parts
         WHERE parts.left_part + parts.right_part = parts.i
             AND parts.i = base.i )

10 rows affected.

i,token
9,253352804744747
10,253352804744747
45,253352804744747
55,253352804744747
99,253352804744747
100,253352804744747
297,253352804744747
703,253352804744747
999,253352804744747
1000,253352804744747

In [ ]:
%%sql
-- Indication. Le premier nombre de Kaprekar est 1.
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS base
WHERE i % 10 != 0
    AND EXISTS
        (SELECT 1
         FROM
             (SELECT base.i
                   , cast(left(sq, cut.i) AS UNSIGNED) AS left_part
                   , cast(right(sq, length(sq) - cut.i) AS UNSIGNED) AS right_part
              FROM
                  (SELECT i
                        , cast(i * i AS CHAR) AS sq
                   FROM ints) AS base
              JOIN ints AS cut ON cut.i BETWEEN 1 AND length(base.sq) - 1) AS parts
         WHERE parts.left_part + parts.right_part = parts.i
             AND parts.i = base.i )

7 rows affected.

i,token
9,253843891117135
45,253843891117135
55,253843891117135
99,253843891117135
297,253843891117135
703,253843891117135
999,253843891117135

In [ ]:
%%sql
-- Indication. Une suite de zéros n'est pas autorisée pour la partie droite.
SELECT i
     , salt_009(sum(nn(hash)) OVER ()) AS token
FROM ints AS base
WHERE i = 1
    OR EXISTS
        (SELECT 1
         FROM
             (SELECT base.i
                   , cast(left(sq, cut.i) AS UNSIGNED) AS left_part
                   , cast(right(sq, length(sq) - cut.i) AS UNSIGNED) AS right_part
              FROM
                  (SELECT i
                        , cast(i * i AS CHAR) AS sq
                   FROM ints) AS base
              JOIN ints AS cut ON cut.i BETWEEN 1 AND length(base.sq) - 1) AS parts
         WHERE parts.left_part + parts.right_part = parts.i
             AND parts.i = base.i )

11 rows affected.

i,token
1,253109520226675
9,253109520226675
10,253109520226675
45,253109520226675
55,253109520226675
99,253109520226675
100,253109520226675
297,253109520226675
703,253109520226675
999,253109520226675
1000,253109520226675

### Suite de Fibonacci

**Exercice [019].** La **suite de Fibonacci** commence par 0 et 1, puis chaque autre terme est la somme des deux termes précédents :

| Terme | Explication |
|-------:|:-------|
| $0$      | (donné) |
| $1$      | (donné) |
| $1$      | $$0 + 1 = 1$$ |
| $2$      | $$1 + 1 = 2$$ |
| $3$      | $$1 + 2 = 3$$ |
| $5$      | $$2 + 3 = 5$$ |
| $8$      | $$3 + 5 = 8$$ |
| $13$     | $$5 + 8 = 13$$ |
|  ⋮  |   |

_Tâche._ Listez par ordre croissant tous les nombres de Fibonacci inférieurs ou égaux à 1000.

_Aide._ Utilisez une CTE (_Common Table Expression_) récursive.

_Contrainte._ Pour que SQLab puisse valider votre requête, vous devrez impérativement l'insérer dans la structure de filtrage suivante :

```sql
WITH RECURSIVE fib (
        /* en-tête de votre CTE */
    )
    AS (
        /* corps de votre CTE */
    )
SELECT i
FROM ints
WHERE i IN (SELECT i from fib)
```

In [ ]:
%%sql
WITH RECURSIVE fib(i, J) AS
    (SELECT 1 AS i
          , 1 AS J

     UNION ALL

     SELECT J AS i
                    , i + J AS J
     FROM fib
     WHERE J <= 1000 )
SELECT i
     , salt_019(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i IN
        (SELECT i
         FROM fib)

15 rows affected.

i,token
1,142617064293148
2,142617064293148
3,142617064293148
5,142617064293148
8,142617064293148
13,142617064293148
21,142617064293148
34,142617064293148
55,142617064293148
89,142617064293148
144,142617064293148
233,142617064293148
377,142617064293148
610,142617064293148
987,142617064293148

### Nombres de Harshad

**Exercice [039].** Un entier est un **nombre de Harshad** si et seulement s'il est divisible par la somme de ses chiffres (en écriture décimale).

| Exemple | Chiffres | Somme | Propriété | Harshad |
|---:|:--:|:--:|:--:|:--:|
| $42$ | $${4, 2}$$ | $6$ | divisible | ✅ |
| $11$ | $${1, 1}$$ | $2$ | non divisible | ❌ |

_Tâche._ Listez par ordre croissant les nombres de Harshad inférieurs ou égaux à 1000.

_Contrainte._ Utilisez une CTE récursive.

In [ ]:
%%sql
WITH RECURSIVE digits(i, Q, R, hash) AS
    (SELECT i
          , i MOD 10
                , i DIV 10
                , hash
     FROM ints

     UNION ALL

     SELECT i
                    , R MOD 10
                          , R DIV 10
                          , hash
     FROM digits
     WHERE R > 0 )
SELECT i
--   , group_concat(q SEPARATOR ' ') as digits
     , salt_039(bit_xor(sum(nn(hash))) OVER ()) AS token
FROM digits
GROUP BY i
HAVING i % sum(q) = 0

213 rows affected.

i,token
1,227239899382463
2,227239899382463
3,227239899382463
4,227239899382463
5,227239899382463
6,227239899382463
7,227239899382463
8,227239899382463
9,227239899382463
10,227239899382463
12,227239899382463
18,227239899382463
20,227239899382463
21,227239899382463
24,227239899382463
27,227239899382463
30,227239899382463
36,227239899382463
40,227239899382463
42,227239899382463
45,227239899382463
48,227239899382463
50,227239899382463
54,227239899382463
60,227239899382463
63,227239899382463
70,227239899382463
72,227239899382463
80,227239899382463
81,227239899382463
84,227239899382463
90,227239899382463
100,227239899382463
102,227239899382463
108,227239899382463
110,227239899382463
111,227239899382463
112,227239899382463
114,227239899382463
117,227239899382463
120,227239899382463
126,227239899382463
132,227239899382463
133,227239899382463
135,227239899382463
140,227239899382463
144,227239899382463
150,227239899382463
152,227239899382463
153,227239899382463
156,227239899382463
162,227239899382463
171,227239899382463
180,227239899382463
190,227239899382463
192,227239899382463
195,227239899382463
198,227239899382463
200,227239899382463
201,227239899382463
204,227239899382463
207,227239899382463
209,227239899382463
210,227239899382463
216,227239899382463
220,227239899382463
222,227239899382463
224,227239899382463
225,227239899382463
228,227239899382463
230,227239899382463
234,227239899382463
240,227239899382463
243,227239899382463
247,227239899382463
252,227239899382463
261,227239899382463
264,227239899382463
266,227239899382463
270,227239899382463
280,227239899382463
285,227239899382463
288,227239899382463
300,227239899382463
306,227239899382463
308,227239899382463
312,227239899382463
315,227239899382463
320,227239899382463
322,227239899382463
324,227239899382463
330,227239899382463
333,227239899382463
336,227239899382463
342,227239899382463
351,227239899382463
360,227239899382463
364,227239899382463
370,227239899382463
372,227239899382463
375,227239899382463
378,227239899382463
392,227239899382463
396,227239899382463
399,227239899382463
400,227239899382463
402,227239899382463
405,227239899382463
407,227239899382463
408,227239899382463
410,227239899382463
414,227239899382463
420,227239899382463
423,227239899382463
432,227239899382463
440,227239899382463
441,227239899382463
444,227239899382463
448,227239899382463
450,227239899382463
460,227239899382463
465,227239899382463
468,227239899382463
476,227239899382463
480,227239899382463
481,227239899382463
486,227239899382463
500,227239899382463
504,227239899382463
506,227239899382463
510,227239899382463
511,227239899382463
512,227239899382463
513,227239899382463
516,227239899382463
518,227239899382463
522,227239899382463
531,227239899382463
540,227239899382463
550,227239899382463
552,227239899382463
555,227239899382463
558,227239899382463
576,227239899382463
588,227239899382463
592,227239899382463
594,227239899382463
600,227239899382463
603,227239899382463
605,227239899382463
612,227239899382463
621,227239899382463
624,227239899382463
629,227239899382463
630,227239899382463
640,227239899382463
644,227239899382463
645,227239899382463
648,227239899382463
660,227239899382463
666,227239899382463
684,227239899382463
690,227239899382463
700,227239899382463
702,227239899382463
704,227239899382463
711,227239899382463
715,227239899382463
720,227239899382463
730,227239899382463
732,227239899382463
735,227239899382463
736,227239899382463
738,227239899382463
756,227239899382463
770,227239899382463
774,227239899382463
777,227239899382463
780,227239899382463
782,227239899382463
792,227239899382463
800,227239899382463
801,227239899382463
803,227239899382463
804,227239899382463
810,227239899382463
820,227239899382463
825,227239899382463
828,227239899382463
832,227239899382463
840,227239899382463
846,227239899382463
864,227239899382463
870,227239899382463
874,227239899382463
880,227239899382463
882,227239899382463
888,227239899382463
900,227239899382463
902,227239899382463
910,227239899382463
912,227239899382463
915,227239899382463
918,227239899382463
935,227239899382463
936,227239899382463
954,227239899382463
960,227239899382463
966,227239899382463
972,227239899382463
990,227239899382463
999,227239899382463
1000,227239899382463

In [ ]:
raise EOFError

EOFError:

In [ ]:
from markdown2 import Markdown
md = Markdown(extras=["fenced-code-blocks", "latex", "tables"])

In [ ]:
md.convert(text)