In [ ]:
from sqlab.nb_tools import show_tables

class ColumnGetter:
    def __getitem__(self, label):
        return list(_.dict()[label])
col = ColumnGetter()

def print_assert(label):
    print(f'assert col["{label}"] == {col[label]}')

In [ ]:
%config SqlMagic.dsn_filename = "cnx.ini"
%config SqlMagic.displaycon = False
%config SqlMagic.displaylimit = 0
%reload_ext sql
%sql --section cnx
show_tables()

Connecting to 'cnx'

Table            Columns
------------------------------
ints             i, hash
sqlab_metadata   name, value
sqlab_msg        msg

# Entiers naturels
Une seule table, une seule colonne : les entiers naturels de 0 à 1000.

# Entraînement
Filtrez la table des 1001 premiers entiers naturels pour la réduire aux éléments de suites numériques plus ou moins connues.

## Suites numériques
Dans tous les énoncés, <i>i</i> dénote un entier positif ou nul.

### Carrés parfaits

**Exercice [002].** Un entier est un **carré parfait** si et seulement si sa racine carrée est entière.

| Exemple | Racine carrée | Propriété | Carré parfait |
|---:|:--:|:--:|:--:|
| $16$ | $4$ | entier | oui |
| $20$ | $$4,4721\dots$$ | non entier | non |

_Tâche._ Listez par ordre croissant les carrés parfaits inférieurs ou égaux à 1000.

In [ ]:
%%sql
-- Solution recommandée. En ne gardant que les entiers dont la racine carrée a une partie fractionnaire nulle.
-- Notez l'emploi inhabituel de l'opérateur modulo.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) % 1 = 0

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. En ne gardant que les entiers dont la racine carrée est différente de sa propre partie entière.
-- Cela demande à calculer deux fois la racine carrée.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) = floor(sqrt(i))

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. En ne gardant que les entiers $a$ égaux au carré d'un entier $b$ (différent de $a$, sauf pour 0 et 1).
-- Peu performant, du fait de l'auto-jointure.
SELECT A.i
     , salt_002(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i * B.i = A.i

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Variante. Même idée, mais exprimée de façon plus procédurale, avec une requête imbriquée dans la clause `WHERE`.
-- On a également borné $b$ à $\sqrt{1000} < 32$. Attention : si vous travaillez sur une table plus grande,
-- vous devrez ajuster cette valeur.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i IN
        (SELECT i * i
         FROM ints
         WHERE i < 32 )

32 rows affected.

i,token
0,125856070581408
1,125856070581408
4,125856070581408
9,125856070581408
16,125856070581408
25,125856070581408
36,125856070581408
49,125856070581408
64,125856070581408
81,125856070581408
100,125856070581408
121,125856070581408
144,125856070581408
169,125856070581408
196,125856070581408
225,125856070581408
256,125856070581408
289,125856070581408
324,125856070581408
361,125856070581408
400,125856070581408
441,125856070581408
484,125856070581408
529,125856070581408
576,125856070581408
625,125856070581408
676,125856070581408
729,125856070581408
784,125856070581408
841,125856070581408
900,125856070581408
961,125856070581408

In [ ]:
%%sql
-- Indication. Vous éliminez les carrés parfaits au lieu de les garder. Inversez votre condition.
SELECT i
     , salt_002(sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE sqrt(i) % 1 != 0

969 rows affected.

i,token
2,455354753305299
3,455354753305299
5,455354753305299
6,455354753305299
7,455354753305299
8,455354753305299
10,455354753305299
11,455354753305299
12,455354753305299
13,455354753305299
14,455354753305299
15,455354753305299
17,455354753305299
18,455354753305299
19,455354753305299
20,455354753305299
21,455354753305299
22,455354753305299
23,455354753305299
24,455354753305299
26,455354753305299
27,455354753305299
28,455354753305299
29,455354753305299
30,455354753305299
31,455354753305299
32,455354753305299
33,455354753305299
34,455354753305299
35,455354753305299
37,455354753305299
38,455354753305299
39,455354753305299
40,455354753305299
41,455354753305299
42,455354753305299
43,455354753305299
44,455354753305299
45,455354753305299
46,455354753305299
47,455354753305299
48,455354753305299
50,455354753305299
51,455354753305299
52,455354753305299
53,455354753305299
54,455354753305299
55,455354753305299
56,455354753305299
57,455354753305299
58,455354753305299
59,455354753305299
60,455354753305299
61,455354753305299
62,455354753305299
63,455354753305299
65,455354753305299
66,455354753305299
67,455354753305299
68,455354753305299
69,455354753305299
70,455354753305299
71,455354753305299
72,455354753305299
73,455354753305299
74,455354753305299
75,455354753305299
76,455354753305299
77,455354753305299
78,455354753305299
79,455354753305299
80,455354753305299
82,455354753305299
83,455354753305299
84,455354753305299
85,455354753305299
86,455354753305299
87,455354753305299
88,455354753305299
89,455354753305299
90,455354753305299
91,455354753305299
92,455354753305299
93,455354753305299
94,455354753305299
95,455354753305299
96,455354753305299
97,455354753305299
98,455354753305299
99,455354753305299
101,455354753305299
102,455354753305299
103,455354753305299
104,455354753305299
105,455354753305299
106,455354753305299
107,455354753305299
108,455354753305299
109,455354753305299
110,455354753305299
111,455354753305299
112,455354753305299
113,455354753305299
114,455354753305299
115,455354753305299
116,455354753305299
117,455354753305299
118,455354753305299
119,455354753305299
120,455354753305299
122,455354753305299
123,455354753305299
124,455354753305299
125,455354753305299
126,455354753305299
127,455354753305299
128,455354753305299
129,455354753305299
130,455354753305299
131,455354753305299
132,455354753305299
133,455354753305299
134,455354753305299
135,455354753305299
136,455354753305299
137,455354753305299
138,455354753305299
139,455354753305299
140,455354753305299
141,455354753305299
142,455354753305299
143,455354753305299
145,455354753305299
146,455354753305299
147,455354753305299
148,455354753305299
149,455354753305299
150,455354753305299
151,455354753305299
152,455354753305299
153,455354753305299
154,455354753305299
155,455354753305299
156,455354753305299
157,455354753305299
158,455354753305299
159,455354753305299
160,455354753305299
161,455354753305299
162,455354753305299
163,455354753305299
164,455354753305299
165,455354753305299
166,455354753305299
167,455354753305299
168,455354753305299
170,455354753305299
171,455354753305299
172,455354753305299
173,455354753305299
174,455354753305299
175,455354753305299
176,455354753305299
177,455354753305299
178,455354753305299
179,455354753305299
180,455354753305299
181,455354753305299
182,455354753305299
183,455354753305299
184,455354753305299
185,455354753305299
186,455354753305299
187,455354753305299
188,455354753305299
189,455354753305299
190,455354753305299
191,455354753305299
192,455354753305299
193,455354753305299
194,455354753305299
195,455354753305299
197,455354753305299
198,455354753305299
199,455354753305299
200,455354753305299
201,455354753305299
202,455354753305299
203,455354753305299
204,455354753305299
205,455354753305299
206,455354753305299
207,455354753305299
208,455354753305299
209,455354753305299
210,455354753305299
211,455354753305299
212,455354753305299
213,455354753305299
214,455354753305299
215,455354753305299
216,455354753305299
217,455354753305299
218,455354753305299
219,455354753305299
220,455354753305299
221,455354753305299
222,455354753305299
223,455354753305299
224,455354753305299
226,455354753305299
227,455354753305299
228,455354753305299
229,455354753305299
230,455354753305299
231,455354753305299
232,455354753305299
233,455354753305299
234,455354753305299
235,455354753305299
236,455354753305299
237,455354753305299
238,455354753305299
239,455354753305299
240,455354753305299
241,455354753305299
242,455354753305299
243,455354753305299
244,455354753305299
245,455354753305299
246,455354753305299
247,455354753305299
248,455354753305299
249,455354753305299
250,455354753305299
251,455354753305299
252,455354753305299
253,455354753305299
254,455354753305299
255,455354753305299
257,455354753305299
258,455354753305299
259,455354753305299
260,455354753305299
261,455354753305299
262,455354753305299
263,455354753305299
264,455354753305299
265,455354753305299
266,455354753305299
267,455354753305299
268,455354753305299
269,455354753305299
270,455354753305299
271,455354753305299
272,455354753305299
273,455354753305299
274,455354753305299
275,455354753305299
276,455354753305299
277,455354753305299
278,455354753305299
279,455354753305299
280,455354753305299
281,455354753305299
282,455354753305299
283,455354753305299
284,455354753305299
285,455354753305299
286,455354753305299
287,455354753305299
288,455354753305299
290,455354753305299
291,455354753305299
292,455354753305299
293,455354753305299
294,455354753305299
295,455354753305299
296,455354753305299
297,455354753305299
298,455354753305299
299,455354753305299
300,455354753305299
301,455354753305299
302,455354753305299
303,455354753305299
304,455354753305299
305,455354753305299
306,455354753305299
307,455354753305299
308,455354753305299
309,455354753305299
310,455354753305299
311,455354753305299
312,455354753305299
313,455354753305299
314,455354753305299
315,455354753305299
316,455354753305299
317,455354753305299
318,455354753305299
319,455354753305299
320,455354753305299
321,455354753305299
322,455354753305299
323,455354753305299
325,455354753305299
326,455354753305299
327,455354753305299
328,455354753305299
329,455354753305299
330,455354753305299
331,455354753305299
332,455354753305299
333,455354753305299
334,455354753305299
335,455354753305299
336,455354753305299
337,455354753305299
338,455354753305299
339,455354753305299
340,455354753305299
341,455354753305299
342,455354753305299
343,455354753305299
344,455354753305299
345,455354753305299
346,455354753305299
347,455354753305299
348,455354753305299
349,455354753305299
350,455354753305299
351,455354753305299
352,455354753305299
353,455354753305299
354,455354753305299
355,455354753305299
356,455354753305299
357,455354753305299
358,455354753305299
359,455354753305299
360,455354753305299
362,455354753305299
363,455354753305299
364,455354753305299
365,455354753305299
366,455354753305299
367,455354753305299
368,455354753305299
369,455354753305299
370,455354753305299
371,455354753305299
372,455354753305299
373,455354753305299
374,455354753305299
375,455354753305299
376,455354753305299
377,455354753305299
378,455354753305299
379,455354753305299
380,455354753305299
381,455354753305299
382,455354753305299
383,455354753305299
384,455354753305299
385,455354753305299
386,455354753305299
387,455354753305299
388,455354753305299
389,455354753305299
390,455354753305299
391,455354753305299
392,455354753305299
393,455354753305299
394,455354753305299
395,455354753305299
396,455354753305299
397,455354753305299
398,455354753305299
399,455354753305299
401,455354753305299
402,455354753305299
403,455354753305299
404,455354753305299
405,455354753305299
406,455354753305299
407,455354753305299
408,455354753305299
409,455354753305299
410,455354753305299
411,455354753305299
412,455354753305299
413,455354753305299
414,455354753305299
415,455354753305299
416,455354753305299
417,455354753305299
418,455354753305299
419,455354753305299
420,455354753305299
421,455354753305299
422,455354753305299
423,455354753305299
424,455354753305299
425,455354753305299
426,455354753305299
427,455354753305299
428,455354753305299
429,455354753305299
430,455354753305299
431,455354753305299
432,455354753305299
433,455354753305299
434,455354753305299
435,455354753305299
436,455354753305299
437,455354753305299
438,455354753305299
439,455354753305299
440,455354753305299
442,455354753305299
443,455354753305299
444,455354753305299
445,455354753305299
446,455354753305299
447,455354753305299
448,455354753305299
449,455354753305299
450,455354753305299
451,455354753305299
452,455354753305299
453,455354753305299
454,455354753305299
455,455354753305299
456,455354753305299
457,455354753305299
458,455354753305299
459,455354753305299
460,455354753305299
461,455354753305299
462,455354753305299
463,455354753305299
464,455354753305299
465,455354753305299
466,455354753305299
467,455354753305299
468,455354753305299
469,455354753305299
470,455354753305299
471,455354753305299
472,455354753305299
473,455354753305299
474,455354753305299
475,455354753305299
476,455354753305299
477,455354753305299
478,455354753305299
479,455354753305299
480,455354753305299
481,455354753305299
482,455354753305299
483,455354753305299
485,455354753305299
486,455354753305299
487,455354753305299
488,455354753305299
489,455354753305299
490,455354753305299
491,455354753305299
492,455354753305299
493,455354753305299
494,455354753305299
495,455354753305299
496,455354753305299
497,455354753305299
498,455354753305299
499,455354753305299
500,455354753305299
501,455354753305299
502,455354753305299
503,455354753305299
504,455354753305299
505,455354753305299
506,455354753305299
507,455354753305299
508,455354753305299
509,455354753305299
510,455354753305299
511,455354753305299
512,455354753305299
513,455354753305299
514,455354753305299
515,455354753305299
516,455354753305299
517,455354753305299
518,455354753305299
519,455354753305299
520,455354753305299
521,455354753305299
522,455354753305299
523,455354753305299
524,455354753305299
525,455354753305299
526,455354753305299
527,455354753305299
528,455354753305299
530,455354753305299
531,455354753305299
532,455354753305299
533,455354753305299
534,455354753305299
535,455354753305299
536,455354753305299
537,455354753305299
538,455354753305299
539,455354753305299
540,455354753305299
541,455354753305299
542,455354753305299
543,455354753305299
544,455354753305299
545,455354753305299
546,455354753305299
547,455354753305299
548,455354753305299
549,455354753305299
550,455354753305299
551,455354753305299
552,455354753305299
553,455354753305299
554,455354753305299
555,455354753305299
556,455354753305299
557,455354753305299
558,455354753305299
559,455354753305299
560,455354753305299
561,455354753305299
562,455354753305299
563,455354753305299
564,455354753305299
565,455354753305299
566,455354753305299
567,455354753305299
568,455354753305299
569,455354753305299
570,455354753305299
571,455354753305299
572,455354753305299
573,455354753305299
574,455354753305299
575,455354753305299
577,455354753305299
578,455354753305299
579,455354753305299
580,455354753305299
581,455354753305299
582,455354753305299
583,455354753305299
584,455354753305299
585,455354753305299
586,455354753305299
587,455354753305299
588,455354753305299
589,455354753305299
590,455354753305299
591,455354753305299
592,455354753305299
593,455354753305299
594,455354753305299
595,455354753305299
596,455354753305299
597,455354753305299
598,455354753305299
599,455354753305299
600,455354753305299
601,455354753305299
602,455354753305299
603,455354753305299
604,455354753305299
605,455354753305299
606,455354753305299
607,455354753305299
608,455354753305299
609,455354753305299
610,455354753305299
611,455354753305299
612,455354753305299
613,455354753305299
614,455354753305299
615,455354753305299
616,455354753305299
617,455354753305299
618,455354753305299
619,455354753305299
620,455354753305299
621,455354753305299
622,455354753305299
623,455354753305299
624,455354753305299
626,455354753305299
627,455354753305299
628,455354753305299
629,455354753305299
630,455354753305299
631,455354753305299
632,455354753305299
633,455354753305299
634,455354753305299
635,455354753305299
636,455354753305299
637,455354753305299
638,455354753305299
639,455354753305299
640,455354753305299
641,455354753305299
642,455354753305299
643,455354753305299
644,455354753305299
645,455354753305299
646,455354753305299
647,455354753305299
648,455354753305299
649,455354753305299
650,455354753305299
651,455354753305299
652,455354753305299
653,455354753305299
654,455354753305299
655,455354753305299
656,455354753305299
657,455354753305299
658,455354753305299
659,455354753305299
660,455354753305299
661,455354753305299
662,455354753305299
663,455354753305299
664,455354753305299
665,455354753305299
666,455354753305299
667,455354753305299
668,455354753305299
669,455354753305299
670,455354753305299
671,455354753305299
672,455354753305299
673,455354753305299
674,455354753305299
675,455354753305299
677,455354753305299
678,455354753305299
679,455354753305299
680,455354753305299
681,455354753305299
682,455354753305299
683,455354753305299
684,455354753305299
685,455354753305299
686,455354753305299
687,455354753305299
688,455354753305299
689,455354753305299
690,455354753305299
691,455354753305299
692,455354753305299
693,455354753305299
694,455354753305299
695,455354753305299
696,455354753305299
697,455354753305299
698,455354753305299
699,455354753305299
700,455354753305299
701,455354753305299
702,455354753305299
703,455354753305299
704,455354753305299
705,455354753305299
706,455354753305299
707,455354753305299
708,455354753305299
709,455354753305299
710,455354753305299
711,455354753305299
712,455354753305299
713,455354753305299
714,455354753305299
715,455354753305299
716,455354753305299
717,455354753305299
718,455354753305299
719,455354753305299
720,455354753305299
721,455354753305299
722,455354753305299
723,455354753305299
724,455354753305299
725,455354753305299
726,455354753305299
727,455354753305299
728,455354753305299
730,455354753305299
731,455354753305299
732,455354753305299
733,455354753305299
734,455354753305299
735,455354753305299
736,455354753305299
737,455354753305299
738,455354753305299
739,455354753305299
740,455354753305299
741,455354753305299
742,455354753305299
743,455354753305299
744,455354753305299
745,455354753305299
746,455354753305299
747,455354753305299
748,455354753305299
749,455354753305299
750,455354753305299
751,455354753305299
752,455354753305299
753,455354753305299
754,455354753305299
755,455354753305299
756,455354753305299
757,455354753305299
758,455354753305299
759,455354753305299
760,455354753305299
761,455354753305299
762,455354753305299
763,455354753305299
764,455354753305299
765,455354753305299
766,455354753305299
767,455354753305299
768,455354753305299
769,455354753305299
770,455354753305299
771,455354753305299
772,455354753305299
773,455354753305299
774,455354753305299
775,455354753305299
776,455354753305299
777,455354753305299
778,455354753305299
779,455354753305299
780,455354753305299
781,455354753305299
782,455354753305299
783,455354753305299
785,455354753305299
786,455354753305299
787,455354753305299
788,455354753305299
789,455354753305299
790,455354753305299
791,455354753305299
792,455354753305299
793,455354753305299
794,455354753305299
795,455354753305299
796,455354753305299
797,455354753305299
798,455354753305299
799,455354753305299
800,455354753305299
801,455354753305299
802,455354753305299
803,455354753305299
804,455354753305299
805,455354753305299
806,455354753305299
807,455354753305299
808,455354753305299
809,455354753305299
810,455354753305299
811,455354753305299
812,455354753305299
813,455354753305299
814,455354753305299
815,455354753305299
816,455354753305299
817,455354753305299
818,455354753305299
819,455354753305299
820,455354753305299
821,455354753305299
822,455354753305299
823,455354753305299
824,455354753305299
825,455354753305299
826,455354753305299
827,455354753305299
828,455354753305299
829,455354753305299
830,455354753305299
831,455354753305299
832,455354753305299
833,455354753305299
834,455354753305299
835,455354753305299
836,455354753305299
837,455354753305299
838,455354753305299
839,455354753305299
840,455354753305299
842,455354753305299
843,455354753305299
844,455354753305299
845,455354753305299
846,455354753305299
847,455354753305299
848,455354753305299
849,455354753305299
850,455354753305299
851,455354753305299
852,455354753305299
853,455354753305299
854,455354753305299
855,455354753305299
856,455354753305299
857,455354753305299
858,455354753305299
859,455354753305299
860,455354753305299
861,455354753305299
862,455354753305299
863,455354753305299
864,455354753305299
865,455354753305299
866,455354753305299
867,455354753305299
868,455354753305299
869,455354753305299
870,455354753305299
871,455354753305299
872,455354753305299
873,455354753305299
874,455354753305299
875,455354753305299
876,455354753305299
877,455354753305299
878,455354753305299
879,455354753305299
880,455354753305299
881,455354753305299
882,455354753305299
883,455354753305299
884,455354753305299
885,455354753305299
886,455354753305299
887,455354753305299
888,455354753305299
889,455354753305299
890,455354753305299
891,455354753305299
892,455354753305299
893,455354753305299
894,455354753305299
895,455354753305299
896,455354753305299
897,455354753305299
898,455354753305299
899,455354753305299
901,455354753305299
902,455354753305299
903,455354753305299
904,455354753305299
905,455354753305299
906,455354753305299
907,455354753305299
908,455354753305299
909,455354753305299
910,455354753305299
911,455354753305299
912,455354753305299
913,455354753305299
914,455354753305299
915,455354753305299
916,455354753305299
917,455354753305299
918,455354753305299
919,455354753305299
920,455354753305299
921,455354753305299
922,455354753305299
923,455354753305299
924,455354753305299
925,455354753305299
926,455354753305299
927,455354753305299
928,455354753305299
929,455354753305299
930,455354753305299
931,455354753305299
932,455354753305299
933,455354753305299
934,455354753305299
935,455354753305299
936,455354753305299
937,455354753305299
938,455354753305299
939,455354753305299
940,455354753305299
941,455354753305299
942,455354753305299
943,455354753305299
944,455354753305299
945,455354753305299
946,455354753305299
947,455354753305299
948,455354753305299
949,455354753305299
950,455354753305299
951,455354753305299
952,455354753305299
953,455354753305299
954,455354753305299
955,455354753305299
956,455354753305299
957,455354753305299
958,455354753305299
959,455354753305299
960,455354753305299
962,455354753305299
963,455354753305299
964,455354753305299
965,455354753305299
966,455354753305299
967,455354753305299
968,455354753305299
969,455354753305299
970,455354753305299
971,455354753305299
972,455354753305299
973,455354753305299
974,455354753305299
975,455354753305299
976,455354753305299
977,455354753305299
978,455354753305299
979,455354753305299
980,455354753305299
981,455354753305299
982,455354753305299
983,455354753305299
984,455354753305299
985,455354753305299
986,455354753305299
987,455354753305299
988,455354753305299
989,455354753305299
990,455354753305299
991,455354753305299
992,455354753305299
993,455354753305299
994,455354753305299
995,455354753305299
996,455354753305299
997,455354753305299
998,455354753305299
999,455354753305299
1000,455354753305299

### Nombres triangulaires

**Exercice [043].** Un entier est **triangulaire** si et seulement s'il peut s'écrire sous la forme $\frac{n (n+1)}{2}$ avec $n$ entier positif ou nul.

| Exemple | Forme cherchée | Triangulaire |
|---:|:--:|:--:|
| $15$ | $$5\times6\div2$$ | oui |
| $16$ | non | non |

_Tâche._ Listez par ordre croissant les nombres triangulaires inférieurs ou égaux à 1000.

In [ ]:
x = 45 # le dixième nombre de la colonne
# Javascript: result[9]?.i ?? 7_531_148

In [ ]:
%%sql
-- On parcourt tous les entiers $A_i$ de la liste, et on ne garde que ceux pour lesquels il existe un entier $B_i$
-- vérifiant l'équation. Comme on connaît la borne supérieure ($1000$, qui est plus petit $45\times 46\div 2=1035$), on
-- peut (facultativement) insérer la « garde » `B.i < 45`.
SELECT i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE EXISTS
        (SELECT 1
         FROM ints B
         WHERE B.i < 45
             AND A.i = B.i * (B.i + 1) / 2 )

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Variante. Avec une auto-jointure.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1) / 2
WHERE B.i < 45
ORDER BY A.i;

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Variante. Avec une sous-requête dans le `WHERE`.
SELECT i
     , salt_043({{x}} + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i IN
        (SELECT i * (i + 1) / 2
         FROM ints
         WHERE i < 45 )

45 rows affected.

i,token
0,103209978926087
1,103209978926087
3,103209978926087
6,103209978926087
10,103209978926087
15,103209978926087
21,103209978926087
28,103209978926087
36,103209978926087
45,103209978926087
55,103209978926087
66,103209978926087
78,103209978926087
91,103209978926087
105,103209978926087
120,103209978926087
136,103209978926087
153,103209978926087
171,103209978926087
190,103209978926087
210,103209978926087
231,103209978926087
253,103209978926087
276,103209978926087
300,103209978926087
325,103209978926087
351,103209978926087
378,103209978926087
406,103209978926087
435,103209978926087
465,103209978926087
496,103209978926087
528,103209978926087
561,103209978926087
595,103209978926087
630,103209978926087
666,103209978926087
703,103209978926087
741,103209978926087
780,103209978926087
820,103209978926087
861,103209978926087
903,103209978926087
946,103209978926087
990,103209978926087

In [ ]:
assert col['i'][9] == x

In [ ]:
%%sql
-- Indication. On ne cherche pas les nombres qui vérifient l'égalité $n = \frac{n(n+1)}{2}$ mais ceux qui peuvent
-- s'écrire sous la forme de sa partie droite.
SELECT i
     , salt_043(7531148 + sum(nn(hash)) OVER ()) AS token
FROM ints
WHERE i = i * (i + 1) / 2

2 rows affected.

i,token
0,81063761713588
1,81063761713588

In [ ]:
x = 90

In [ ]:
%%sql
-- Indication. Vous avez oublié le numérateur de la formule.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1)
WHERE B.i < 45
ORDER BY A.i;

32 rows affected.

i,token
0,96800835160244
2,96800835160244
6,96800835160244
12,96800835160244
20,96800835160244
30,96800835160244
42,96800835160244
56,96800835160244
72,96800835160244
90,96800835160244
110,96800835160244
132,96800835160244
156,96800835160244
182,96800835160244
210,96800835160244
240,96800835160244
272,96800835160244
306,96800835160244
342,96800835160244
380,96800835160244
420,96800835160244
462,96800835160244
506,96800835160244
552,96800835160244
600,96800835160244
650,96800835160244
702,96800835160244
756,96800835160244
812,96800835160244
870,96800835160244
930,96800835160244
992,96800835160244

In [ ]:
assert col['i'][9] == x

In [ ]:
x = 162

In [ ]:
%%sql
-- Indication. Vous avez oublié le $+ 1$ dans la formule.
SELECT A.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * B.i / 2
WHERE B.i < 45
ORDER BY A.i

23 rows affected.

i,token
0,76118056186574
2,76118056186574
8,76118056186574
18,76118056186574
32,76118056186574
50,76118056186574
72,76118056186574
98,76118056186574
128,76118056186574
162,76118056186574
200,76118056186574
242,76118056186574
288,76118056186574
338,76118056186574
392,76118056186574
450,76118056186574
512,76118056186574
578,76118056186574
648,76118056186574
722,76118056186574
800,76118056186574
882,76118056186574
968,76118056186574

In [ ]:
assert col['i'][9] == x

In [ ]:
x = 9

In [ ]:
%%sql
-- Indication. Vous ne projetez pas la colonne `i` de la bonne table.
SELECT B.i
     , salt_043({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i = B.i * (B.i + 1) / 2
WHERE B.i < 45
ORDER BY A.i

45 rows affected.

i,token
0,103209978926115
1,103209978926115
2,103209978926115
3,103209978926115
4,103209978926115
5,103209978926115
6,103209978926115
7,103209978926115
8,103209978926115
9,103209978926115
10,103209978926115
11,103209978926115
12,103209978926115
13,103209978926115
14,103209978926115
15,103209978926115
16,103209978926115
17,103209978926115
18,103209978926115
19,103209978926115
20,103209978926115
21,103209978926115
22,103209978926115
23,103209978926115
24,103209978926115
25,103209978926115
26,103209978926115
27,103209978926115
28,103209978926115
29,103209978926115
30,103209978926115
31,103209978926115
32,103209978926115
33,103209978926115
34,103209978926115
35,103209978926115
36,103209978926115
37,103209978926115
38,103209978926115
39,103209978926115
40,103209978926115
41,103209978926115
42,103209978926115
43,103209978926115
44,103209978926115

In [ ]:
assert col['i'][9] == x

### Nombres abondants

**Exercice [023].** Un entier $n$ est **abondant** si et seulement s'il est inférieur à la somme de ses diviseurs stricts (_i.e._, distincts de $n$).

| Exemple | Diviseurs stricts | Propriété | Abondant |
|---:|:--:|:--:|:--:|
| $12$ | $${1, 2, 3, 4, 6}$$ | $$12 < 1+2+3+4+6 = 16$$ | oui |
| $16$ | $${1, 2, 4, 8}$$ | $$16 \geq 1+2+4+8 = 15$$ | non |

_Tâche._ Listez par ordre croissant les nombres abondants inférieurs ou égaux à 1000.

_Contrainte._ Utilisez une auto-jointure et un regroupement.

In [ ]:
x = 36 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i < A.i
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

246 rows affected.

i,token
12,5591408610389
18,5591408610389
20,5591408610389
24,5591408610389
30,5591408610389
36,5591408610389
40,5591408610389
42,5591408610389
48,5591408610389
54,5591408610389
56,5591408610389
60,5591408610389
66,5591408610389
70,5591408610389
72,5591408610389
78,5591408610389
80,5591408610389
84,5591408610389
88,5591408610389
90,5591408610389
96,5591408610389
100,5591408610389
102,5591408610389
104,5591408610389
108,5591408610389
112,5591408610389
114,5591408610389
120,5591408610389
126,5591408610389
132,5591408610389
138,5591408610389
140,5591408610389
144,5591408610389
150,5591408610389
156,5591408610389
160,5591408610389
162,5591408610389
168,5591408610389
174,5591408610389
176,5591408610389
180,5591408610389
186,5591408610389
192,5591408610389
196,5591408610389
198,5591408610389
200,5591408610389
204,5591408610389
208,5591408610389
210,5591408610389
216,5591408610389
220,5591408610389
222,5591408610389
224,5591408610389
228,5591408610389
234,5591408610389
240,5591408610389
246,5591408610389
252,5591408610389
258,5591408610389
260,5591408610389
264,5591408610389
270,5591408610389
272,5591408610389
276,5591408610389
280,5591408610389
282,5591408610389
288,5591408610389
294,5591408610389
300,5591408610389
304,5591408610389
306,5591408610389
308,5591408610389
312,5591408610389
318,5591408610389
320,5591408610389
324,5591408610389
330,5591408610389
336,5591408610389
340,5591408610389
342,5591408610389
348,5591408610389
350,5591408610389
352,5591408610389
354,5591408610389
360,5591408610389
364,5591408610389
366,5591408610389
368,5591408610389
372,5591408610389
378,5591408610389
380,5591408610389
384,5591408610389
390,5591408610389
392,5591408610389
396,5591408610389
400,5591408610389
402,5591408610389
408,5591408610389
414,5591408610389
416,5591408610389
420,5591408610389
426,5591408610389
432,5591408610389
438,5591408610389
440,5591408610389
444,5591408610389
448,5591408610389
450,5591408610389
456,5591408610389
460,5591408610389
462,5591408610389
464,5591408610389
468,5591408610389
474,5591408610389
476,5591408610389
480,5591408610389
486,5591408610389
490,5591408610389
492,5591408610389
498,5591408610389
500,5591408610389
504,5591408610389
510,5591408610389
516,5591408610389
520,5591408610389
522,5591408610389
528,5591408610389
532,5591408610389
534,5591408610389
540,5591408610389
544,5591408610389
546,5591408610389
550,5591408610389
552,5591408610389
558,5591408610389
560,5591408610389
564,5591408610389
570,5591408610389
572,5591408610389
576,5591408610389
580,5591408610389
582,5591408610389
588,5591408610389
594,5591408610389
600,5591408610389
606,5591408610389
608,5591408610389
612,5591408610389
616,5591408610389
618,5591408610389
620,5591408610389
624,5591408610389
630,5591408610389
636,5591408610389
640,5591408610389
642,5591408610389
644,5591408610389
648,5591408610389
650,5591408610389
654,5591408610389
660,5591408610389
666,5591408610389
672,5591408610389
678,5591408610389
680,5591408610389
684,5591408610389
690,5591408610389
696,5591408610389
700,5591408610389
702,5591408610389
704,5591408610389
708,5591408610389
714,5591408610389
720,5591408610389
726,5591408610389
728,5591408610389
732,5591408610389
736,5591408610389
738,5591408610389
740,5591408610389
744,5591408610389
748,5591408610389
750,5591408610389
756,5591408610389
760,5591408610389
762,5591408610389
768,5591408610389
770,5591408610389
774,5591408610389
780,5591408610389
784,5591408610389
786,5591408610389
792,5591408610389
798,5591408610389
800,5591408610389
804,5591408610389
810,5591408610389
812,5591408610389
816,5591408610389
820,5591408610389
822,5591408610389
828,5591408610389
832,5591408610389
834,5591408610389
836,5591408610389
840,5591408610389
846,5591408610389
852,5591408610389
858,5591408610389
860,5591408610389
864,5591408610389
868,5591408610389
870,5591408610389
876,5591408610389
880,5591408610389
882,5591408610389
888,5591408610389
894,5591408610389
896,5591408610389
900,5591408610389
906,5591408610389
910,5591408610389
912,5591408610389
918,5591408610389
920,5591408610389
924,5591408610389
928,5591408610389
930,5591408610389
936,5591408610389
940,5591408610389
942,5591408610389
945,5591408610389
948,5591408610389
952,5591408610389
954,5591408610389
960,5591408610389
966,5591408610389
968,5591408610389
972,5591408610389
978,5591408610389
980,5591408610389
984,5591408610389
990,5591408610389
992,5591408610389
996,5591408610389
1000,5591408610389

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 36

In [ ]:
%%sql
-- Indication. Sommez tous les diviseurs inférieurs à $n$, y compris 1. Le résultat est le même pour les nombres
-- de notre table, mais on peut prouver mathématiquement que cette condition supplémentaire est inutile dans le
-- cas général.
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i < A.i
AND B.i > 1
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

246 rows affected.

i,token
12,62621691563930
18,62621691563930
20,62621691563930
24,62621691563930
30,62621691563930
36,62621691563930
40,62621691563930
42,62621691563930
48,62621691563930
54,62621691563930
56,62621691563930
60,62621691563930
66,62621691563930
70,62621691563930
72,62621691563930
78,62621691563930
80,62621691563930
84,62621691563930
88,62621691563930
90,62621691563930
96,62621691563930
100,62621691563930
102,62621691563930
104,62621691563930
108,62621691563930
112,62621691563930
114,62621691563930
120,62621691563930
126,62621691563930
132,62621691563930
138,62621691563930
140,62621691563930
144,62621691563930
150,62621691563930
156,62621691563930
160,62621691563930
162,62621691563930
168,62621691563930
174,62621691563930
176,62621691563930
180,62621691563930
186,62621691563930
192,62621691563930
196,62621691563930
198,62621691563930
200,62621691563930
204,62621691563930
208,62621691563930
210,62621691563930
216,62621691563930
220,62621691563930
222,62621691563930
224,62621691563930
228,62621691563930
234,62621691563930
240,62621691563930
246,62621691563930
252,62621691563930
258,62621691563930
260,62621691563930
264,62621691563930
270,62621691563930
272,62621691563930
276,62621691563930
280,62621691563930
282,62621691563930
288,62621691563930
294,62621691563930
300,62621691563930
304,62621691563930
306,62621691563930
308,62621691563930
312,62621691563930
318,62621691563930
320,62621691563930
324,62621691563930
330,62621691563930
336,62621691563930
340,62621691563930
342,62621691563930
348,62621691563930
350,62621691563930
352,62621691563930
354,62621691563930
360,62621691563930
364,62621691563930
366,62621691563930
368,62621691563930
372,62621691563930
378,62621691563930
380,62621691563930
384,62621691563930
390,62621691563930
392,62621691563930
396,62621691563930
400,62621691563930
402,62621691563930
408,62621691563930
414,62621691563930
416,62621691563930
420,62621691563930
426,62621691563930
432,62621691563930
438,62621691563930
440,62621691563930
444,62621691563930
448,62621691563930
450,62621691563930
456,62621691563930
460,62621691563930
462,62621691563930
464,62621691563930
468,62621691563930
474,62621691563930
476,62621691563930
480,62621691563930
486,62621691563930
490,62621691563930
492,62621691563930
498,62621691563930
500,62621691563930
504,62621691563930
510,62621691563930
516,62621691563930
520,62621691563930
522,62621691563930
528,62621691563930
532,62621691563930
534,62621691563930
540,62621691563930
544,62621691563930
546,62621691563930
550,62621691563930
552,62621691563930
558,62621691563930
560,62621691563930
564,62621691563930
570,62621691563930
572,62621691563930
576,62621691563930
580,62621691563930
582,62621691563930
588,62621691563930
594,62621691563930
600,62621691563930
606,62621691563930
608,62621691563930
612,62621691563930
616,62621691563930
618,62621691563930
620,62621691563930
624,62621691563930
630,62621691563930
636,62621691563930
640,62621691563930
642,62621691563930
644,62621691563930
648,62621691563930
650,62621691563930
654,62621691563930
660,62621691563930
666,62621691563930
672,62621691563930
678,62621691563930
680,62621691563930
684,62621691563930
690,62621691563930
696,62621691563930
700,62621691563930
702,62621691563930
704,62621691563930
708,62621691563930
714,62621691563930
720,62621691563930
726,62621691563930
728,62621691563930
732,62621691563930
736,62621691563930
738,62621691563930
740,62621691563930
744,62621691563930
748,62621691563930
750,62621691563930
756,62621691563930
760,62621691563930
762,62621691563930
768,62621691563930
770,62621691563930
774,62621691563930
780,62621691563930
784,62621691563930
786,62621691563930
792,62621691563930
798,62621691563930
800,62621691563930
804,62621691563930
810,62621691563930
812,62621691563930
816,62621691563930
820,62621691563930
822,62621691563930
828,62621691563930
832,62621691563930
834,62621691563930
836,62621691563930
840,62621691563930
846,62621691563930
852,62621691563930
858,62621691563930
860,62621691563930
864,62621691563930
868,62621691563930
870,62621691563930
876,62621691563930
880,62621691563930
882,62621691563930
888,62621691563930
894,62621691563930
896,62621691563930
900,62621691563930
906,62621691563930
910,62621691563930
912,62621691563930
918,62621691563930
920,62621691563930
924,62621691563930
928,62621691563930
930,62621691563930
936,62621691563930
940,62621691563930
942,62621691563930
945,62621691563930
948,62621691563930
952,62621691563930
954,62621691563930
960,62621691563930
966,62621691563930
968,62621691563930
972,62621691563930
978,62621691563930
980,62621691563930
984,62621691563930
990,62621691563930
992,62621691563930
996,62621691563930
1000,62621691563930

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 7

In [ ]:
%%sql
-- Indication. $n$ n'est pas un diviseur strict de lui-même.
SELECT A.i
     , salt_023({{x}} + bit_xor(sum(nn(A.hash) + nn(B.hash))) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i <= A.i
AND A.i % B.i = 0
GROUP BY A.i
HAVING A.i < sum(B.i)
ORDER BY 1

999 rows affected.

i,token
2,14110344140782
3,14110344140782
4,14110344140782
5,14110344140782
6,14110344140782
7,14110344140782
8,14110344140782
9,14110344140782
10,14110344140782
11,14110344140782
12,14110344140782
13,14110344140782
14,14110344140782
15,14110344140782
16,14110344140782
17,14110344140782
18,14110344140782
19,14110344140782
20,14110344140782
21,14110344140782
22,14110344140782
23,14110344140782
24,14110344140782
25,14110344140782
26,14110344140782
27,14110344140782
28,14110344140782
29,14110344140782
30,14110344140782
31,14110344140782
32,14110344140782
33,14110344140782
34,14110344140782
35,14110344140782
36,14110344140782
37,14110344140782
38,14110344140782
39,14110344140782
40,14110344140782
41,14110344140782
42,14110344140782
43,14110344140782
44,14110344140782
45,14110344140782
46,14110344140782
47,14110344140782
48,14110344140782
49,14110344140782
50,14110344140782
51,14110344140782
52,14110344140782
53,14110344140782
54,14110344140782
55,14110344140782
56,14110344140782
57,14110344140782
58,14110344140782
59,14110344140782
60,14110344140782
61,14110344140782
62,14110344140782
63,14110344140782
64,14110344140782
65,14110344140782
66,14110344140782
67,14110344140782
68,14110344140782
69,14110344140782
70,14110344140782
71,14110344140782
72,14110344140782
73,14110344140782
74,14110344140782
75,14110344140782
76,14110344140782
77,14110344140782
78,14110344140782
79,14110344140782
80,14110344140782
81,14110344140782
82,14110344140782
83,14110344140782
84,14110344140782
85,14110344140782
86,14110344140782
87,14110344140782
88,14110344140782
89,14110344140782
90,14110344140782
91,14110344140782
92,14110344140782
93,14110344140782
94,14110344140782
95,14110344140782
96,14110344140782
97,14110344140782
98,14110344140782
99,14110344140782
100,14110344140782
101,14110344140782
102,14110344140782
103,14110344140782
104,14110344140782
105,14110344140782
106,14110344140782
107,14110344140782
108,14110344140782
109,14110344140782
110,14110344140782
111,14110344140782
112,14110344140782
113,14110344140782
114,14110344140782
115,14110344140782
116,14110344140782
117,14110344140782
118,14110344140782
119,14110344140782
120,14110344140782
121,14110344140782
122,14110344140782
123,14110344140782
124,14110344140782
125,14110344140782
126,14110344140782
127,14110344140782
128,14110344140782
129,14110344140782
130,14110344140782
131,14110344140782
132,14110344140782
133,14110344140782
134,14110344140782
135,14110344140782
136,14110344140782
137,14110344140782
138,14110344140782
139,14110344140782
140,14110344140782
141,14110344140782
142,14110344140782
143,14110344140782
144,14110344140782
145,14110344140782
146,14110344140782
147,14110344140782
148,14110344140782
149,14110344140782
150,14110344140782
151,14110344140782
152,14110344140782
153,14110344140782
154,14110344140782
155,14110344140782
156,14110344140782
157,14110344140782
158,14110344140782
159,14110344140782
160,14110344140782
161,14110344140782
162,14110344140782
163,14110344140782
164,14110344140782
165,14110344140782
166,14110344140782
167,14110344140782
168,14110344140782
169,14110344140782
170,14110344140782
171,14110344140782
172,14110344140782
173,14110344140782
174,14110344140782
175,14110344140782
176,14110344140782
177,14110344140782
178,14110344140782
179,14110344140782
180,14110344140782
181,14110344140782
182,14110344140782
183,14110344140782
184,14110344140782
185,14110344140782
186,14110344140782
187,14110344140782
188,14110344140782
189,14110344140782
190,14110344140782
191,14110344140782
192,14110344140782
193,14110344140782
194,14110344140782
195,14110344140782
196,14110344140782
197,14110344140782
198,14110344140782
199,14110344140782
200,14110344140782
201,14110344140782
202,14110344140782
203,14110344140782
204,14110344140782
205,14110344140782
206,14110344140782
207,14110344140782
208,14110344140782
209,14110344140782
210,14110344140782
211,14110344140782
212,14110344140782
213,14110344140782
214,14110344140782
215,14110344140782
216,14110344140782
217,14110344140782
218,14110344140782
219,14110344140782
220,14110344140782
221,14110344140782
222,14110344140782
223,14110344140782
224,14110344140782
225,14110344140782
226,14110344140782
227,14110344140782
228,14110344140782
229,14110344140782
230,14110344140782
231,14110344140782
232,14110344140782
233,14110344140782
234,14110344140782
235,14110344140782
236,14110344140782
237,14110344140782
238,14110344140782
239,14110344140782
240,14110344140782
241,14110344140782
242,14110344140782
243,14110344140782
244,14110344140782
245,14110344140782
246,14110344140782
247,14110344140782
248,14110344140782
249,14110344140782
250,14110344140782
251,14110344140782
252,14110344140782
253,14110344140782
254,14110344140782
255,14110344140782
256,14110344140782
257,14110344140782
258,14110344140782
259,14110344140782
260,14110344140782
261,14110344140782
262,14110344140782
263,14110344140782
264,14110344140782
265,14110344140782
266,14110344140782
267,14110344140782
268,14110344140782
269,14110344140782
270,14110344140782
271,14110344140782
272,14110344140782
273,14110344140782
274,14110344140782
275,14110344140782
276,14110344140782
277,14110344140782
278,14110344140782
279,14110344140782
280,14110344140782
281,14110344140782
282,14110344140782
283,14110344140782
284,14110344140782
285,14110344140782
286,14110344140782
287,14110344140782
288,14110344140782
289,14110344140782
290,14110344140782
291,14110344140782
292,14110344140782
293,14110344140782
294,14110344140782
295,14110344140782
296,14110344140782
297,14110344140782
298,14110344140782
299,14110344140782
300,14110344140782
301,14110344140782
302,14110344140782
303,14110344140782
304,14110344140782
305,14110344140782
306,14110344140782
307,14110344140782
308,14110344140782
309,14110344140782
310,14110344140782
311,14110344140782
312,14110344140782
313,14110344140782
314,14110344140782
315,14110344140782
316,14110344140782
317,14110344140782
318,14110344140782
319,14110344140782
320,14110344140782
321,14110344140782
322,14110344140782
323,14110344140782
324,14110344140782
325,14110344140782
326,14110344140782
327,14110344140782
328,14110344140782
329,14110344140782
330,14110344140782
331,14110344140782
332,14110344140782
333,14110344140782
334,14110344140782
335,14110344140782
336,14110344140782
337,14110344140782
338,14110344140782
339,14110344140782
340,14110344140782
341,14110344140782
342,14110344140782
343,14110344140782
344,14110344140782
345,14110344140782
346,14110344140782
347,14110344140782
348,14110344140782
349,14110344140782
350,14110344140782
351,14110344140782
352,14110344140782
353,14110344140782
354,14110344140782
355,14110344140782
356,14110344140782
357,14110344140782
358,14110344140782
359,14110344140782
360,14110344140782
361,14110344140782
362,14110344140782
363,14110344140782
364,14110344140782
365,14110344140782
366,14110344140782
367,14110344140782
368,14110344140782
369,14110344140782
370,14110344140782
371,14110344140782
372,14110344140782
373,14110344140782
374,14110344140782
375,14110344140782
376,14110344140782
377,14110344140782
378,14110344140782
379,14110344140782
380,14110344140782
381,14110344140782
382,14110344140782
383,14110344140782
384,14110344140782
385,14110344140782
386,14110344140782
387,14110344140782
388,14110344140782
389,14110344140782
390,14110344140782
391,14110344140782
392,14110344140782
393,14110344140782
394,14110344140782
395,14110344140782
396,14110344140782
397,14110344140782
398,14110344140782
399,14110344140782
400,14110344140782
401,14110344140782
402,14110344140782
403,14110344140782
404,14110344140782
405,14110344140782
406,14110344140782
407,14110344140782
408,14110344140782
409,14110344140782
410,14110344140782
411,14110344140782
412,14110344140782
413,14110344140782
414,14110344140782
415,14110344140782
416,14110344140782
417,14110344140782
418,14110344140782
419,14110344140782
420,14110344140782
421,14110344140782
422,14110344140782
423,14110344140782
424,14110344140782
425,14110344140782
426,14110344140782
427,14110344140782
428,14110344140782
429,14110344140782
430,14110344140782
431,14110344140782
432,14110344140782
433,14110344140782
434,14110344140782
435,14110344140782
436,14110344140782
437,14110344140782
438,14110344140782
439,14110344140782
440,14110344140782
441,14110344140782
442,14110344140782
443,14110344140782
444,14110344140782
445,14110344140782
446,14110344140782
447,14110344140782
448,14110344140782
449,14110344140782
450,14110344140782
451,14110344140782
452,14110344140782
453,14110344140782
454,14110344140782
455,14110344140782
456,14110344140782
457,14110344140782
458,14110344140782
459,14110344140782
460,14110344140782
461,14110344140782
462,14110344140782
463,14110344140782
464,14110344140782
465,14110344140782
466,14110344140782
467,14110344140782
468,14110344140782
469,14110344140782
470,14110344140782
471,14110344140782
472,14110344140782
473,14110344140782
474,14110344140782
475,14110344140782
476,14110344140782
477,14110344140782
478,14110344140782
479,14110344140782
480,14110344140782
481,14110344140782
482,14110344140782
483,14110344140782
484,14110344140782
485,14110344140782
486,14110344140782
487,14110344140782
488,14110344140782
489,14110344140782
490,14110344140782
491,14110344140782
492,14110344140782
493,14110344140782
494,14110344140782
495,14110344140782
496,14110344140782
497,14110344140782
498,14110344140782
499,14110344140782
500,14110344140782
501,14110344140782
502,14110344140782
503,14110344140782
504,14110344140782
505,14110344140782
506,14110344140782
507,14110344140782
508,14110344140782
509,14110344140782
510,14110344140782
511,14110344140782
512,14110344140782
513,14110344140782
514,14110344140782
515,14110344140782
516,14110344140782
517,14110344140782
518,14110344140782
519,14110344140782
520,14110344140782
521,14110344140782
522,14110344140782
523,14110344140782
524,14110344140782
525,14110344140782
526,14110344140782
527,14110344140782
528,14110344140782
529,14110344140782
530,14110344140782
531,14110344140782
532,14110344140782
533,14110344140782
534,14110344140782
535,14110344140782
536,14110344140782
537,14110344140782
538,14110344140782
539,14110344140782
540,14110344140782
541,14110344140782
542,14110344140782
543,14110344140782
544,14110344140782
545,14110344140782
546,14110344140782
547,14110344140782
548,14110344140782
549,14110344140782
550,14110344140782
551,14110344140782
552,14110344140782
553,14110344140782
554,14110344140782
555,14110344140782
556,14110344140782
557,14110344140782
558,14110344140782
559,14110344140782
560,14110344140782
561,14110344140782
562,14110344140782
563,14110344140782
564,14110344140782
565,14110344140782
566,14110344140782
567,14110344140782
568,14110344140782
569,14110344140782
570,14110344140782
571,14110344140782
572,14110344140782
573,14110344140782
574,14110344140782
575,14110344140782
576,14110344140782
577,14110344140782
578,14110344140782
579,14110344140782
580,14110344140782
581,14110344140782
582,14110344140782
583,14110344140782
584,14110344140782
585,14110344140782
586,14110344140782
587,14110344140782
588,14110344140782
589,14110344140782
590,14110344140782
591,14110344140782
592,14110344140782
593,14110344140782
594,14110344140782
595,14110344140782
596,14110344140782
597,14110344140782
598,14110344140782
599,14110344140782
600,14110344140782
601,14110344140782
602,14110344140782
603,14110344140782
604,14110344140782
605,14110344140782
606,14110344140782
607,14110344140782
608,14110344140782
609,14110344140782
610,14110344140782
611,14110344140782
612,14110344140782
613,14110344140782
614,14110344140782
615,14110344140782
616,14110344140782
617,14110344140782
618,14110344140782
619,14110344140782
620,14110344140782
621,14110344140782
622,14110344140782
623,14110344140782
624,14110344140782
625,14110344140782
626,14110344140782
627,14110344140782
628,14110344140782
629,14110344140782
630,14110344140782
631,14110344140782
632,14110344140782
633,14110344140782
634,14110344140782
635,14110344140782
636,14110344140782
637,14110344140782
638,14110344140782
639,14110344140782
640,14110344140782
641,14110344140782
642,14110344140782
643,14110344140782
644,14110344140782
645,14110344140782
646,14110344140782
647,14110344140782
648,14110344140782
649,14110344140782
650,14110344140782
651,14110344140782
652,14110344140782
653,14110344140782
654,14110344140782
655,14110344140782
656,14110344140782
657,14110344140782
658,14110344140782
659,14110344140782
660,14110344140782
661,14110344140782
662,14110344140782
663,14110344140782
664,14110344140782
665,14110344140782
666,14110344140782
667,14110344140782
668,14110344140782
669,14110344140782
670,14110344140782
671,14110344140782
672,14110344140782
673,14110344140782
674,14110344140782
675,14110344140782
676,14110344140782
677,14110344140782
678,14110344140782
679,14110344140782
680,14110344140782
681,14110344140782
682,14110344140782
683,14110344140782
684,14110344140782
685,14110344140782
686,14110344140782
687,14110344140782
688,14110344140782
689,14110344140782
690,14110344140782
691,14110344140782
692,14110344140782
693,14110344140782
694,14110344140782
695,14110344140782
696,14110344140782
697,14110344140782
698,14110344140782
699,14110344140782
700,14110344140782
701,14110344140782
702,14110344140782
703,14110344140782
704,14110344140782
705,14110344140782
706,14110344140782
707,14110344140782
708,14110344140782
709,14110344140782
710,14110344140782
711,14110344140782
712,14110344140782
713,14110344140782
714,14110344140782
715,14110344140782
716,14110344140782
717,14110344140782
718,14110344140782
719,14110344140782
720,14110344140782
721,14110344140782
722,14110344140782
723,14110344140782
724,14110344140782
725,14110344140782
726,14110344140782
727,14110344140782
728,14110344140782
729,14110344140782
730,14110344140782
731,14110344140782
732,14110344140782
733,14110344140782
734,14110344140782
735,14110344140782
736,14110344140782
737,14110344140782
738,14110344140782
739,14110344140782
740,14110344140782
741,14110344140782
742,14110344140782
743,14110344140782
744,14110344140782
745,14110344140782
746,14110344140782
747,14110344140782
748,14110344140782
749,14110344140782
750,14110344140782
751,14110344140782
752,14110344140782
753,14110344140782
754,14110344140782
755,14110344140782
756,14110344140782
757,14110344140782
758,14110344140782
759,14110344140782
760,14110344140782
761,14110344140782
762,14110344140782
763,14110344140782
764,14110344140782
765,14110344140782
766,14110344140782
767,14110344140782
768,14110344140782
769,14110344140782
770,14110344140782
771,14110344140782
772,14110344140782
773,14110344140782
774,14110344140782
775,14110344140782
776,14110344140782
777,14110344140782
778,14110344140782
779,14110344140782
780,14110344140782
781,14110344140782
782,14110344140782
783,14110344140782
784,14110344140782
785,14110344140782
786,14110344140782
787,14110344140782
788,14110344140782
789,14110344140782
790,14110344140782
791,14110344140782
792,14110344140782
793,14110344140782
794,14110344140782
795,14110344140782
796,14110344140782
797,14110344140782
798,14110344140782
799,14110344140782
800,14110344140782
801,14110344140782
802,14110344140782
803,14110344140782
804,14110344140782
805,14110344140782
806,14110344140782
807,14110344140782
808,14110344140782
809,14110344140782
810,14110344140782
811,14110344140782
812,14110344140782
813,14110344140782
814,14110344140782
815,14110344140782
816,14110344140782
817,14110344140782
818,14110344140782
819,14110344140782
820,14110344140782
821,14110344140782
822,14110344140782
823,14110344140782
824,14110344140782
825,14110344140782
826,14110344140782
827,14110344140782
828,14110344140782
829,14110344140782
830,14110344140782
831,14110344140782
832,14110344140782
833,14110344140782
834,14110344140782
835,14110344140782
836,14110344140782
837,14110344140782
838,14110344140782
839,14110344140782
840,14110344140782
841,14110344140782
842,14110344140782
843,14110344140782
844,14110344140782
845,14110344140782
846,14110344140782
847,14110344140782
848,14110344140782
849,14110344140782
850,14110344140782
851,14110344140782
852,14110344140782
853,14110344140782
854,14110344140782
855,14110344140782
856,14110344140782
857,14110344140782
858,14110344140782
859,14110344140782
860,14110344140782
861,14110344140782
862,14110344140782
863,14110344140782
864,14110344140782
865,14110344140782
866,14110344140782
867,14110344140782
868,14110344140782
869,14110344140782
870,14110344140782
871,14110344140782
872,14110344140782
873,14110344140782
874,14110344140782
875,14110344140782
876,14110344140782
877,14110344140782
878,14110344140782
879,14110344140782
880,14110344140782
881,14110344140782
882,14110344140782
883,14110344140782
884,14110344140782
885,14110344140782
886,14110344140782
887,14110344140782
888,14110344140782
889,14110344140782
890,14110344140782
891,14110344140782
892,14110344140782
893,14110344140782
894,14110344140782
895,14110344140782
896,14110344140782
897,14110344140782
898,14110344140782
899,14110344140782
900,14110344140782
901,14110344140782
902,14110344140782
903,14110344140782
904,14110344140782
905,14110344140782
906,14110344140782
907,14110344140782
908,14110344140782
909,14110344140782
910,14110344140782
911,14110344140782
912,14110344140782
913,14110344140782
914,14110344140782
915,14110344140782
916,14110344140782
917,14110344140782
918,14110344140782
919,14110344140782
920,14110344140782
921,14110344140782
922,14110344140782
923,14110344140782
924,14110344140782
925,14110344140782
926,14110344140782
927,14110344140782
928,14110344140782
929,14110344140782
930,14110344140782
931,14110344140782
932,14110344140782
933,14110344140782
934,14110344140782
935,14110344140782
936,14110344140782
937,14110344140782
938,14110344140782
939,14110344140782
940,14110344140782
941,14110344140782
942,14110344140782
943,14110344140782
944,14110344140782
945,14110344140782
946,14110344140782
947,14110344140782
948,14110344140782
949,14110344140782
950,14110344140782
951,14110344140782
952,14110344140782
953,14110344140782
954,14110344140782
955,14110344140782
956,14110344140782
957,14110344140782
958,14110344140782
959,14110344140782
960,14110344140782
961,14110344140782
962,14110344140782
963,14110344140782
964,14110344140782
965,14110344140782
966,14110344140782
967,14110344140782
968,14110344140782
969,14110344140782
970,14110344140782
971,14110344140782
972,14110344140782
973,14110344140782
974,14110344140782
975,14110344140782
976,14110344140782
977,14110344140782
978,14110344140782
979,14110344140782
980,14110344140782
981,14110344140782
982,14110344140782
983,14110344140782
984,14110344140782
985,14110344140782
986,14110344140782
987,14110344140782
988,14110344140782
989,14110344140782
990,14110344140782
991,14110344140782
992,14110344140782
993,14110344140782
994,14110344140782
995,14110344140782
996,14110344140782
997,14110344140782
998,14110344140782
999,14110344140782
1000,14110344140782

In [ ]:
assert col['i'][5] == x

**Exercice [024].** Un entier $n$ est **abondant** si et seulement s'il est inférieur à la somme de ses diviseurs stricts (_i.e._, distincts de $n$).

| Exemple | Diviseurs stricts | Propriété | Abondant |
|---:|:--:|:--:|:--:|
| $12$ | $${1, 2, 3, 4, 6}$$ | $$12 < 1+2+3+4+6 = 16$$ | oui |
| $16$ | $${1, 2, 4, 8}$$ | $$16 \geq 1+2+4+8 = 15$$ | non |

_Tâche._ Listez par ordre croissant les nombres abondants inférieurs ou égaux à 1000.

_Contrainte._ Utilisez une sous-requête corrélée, et pas de regroupement.

In [ ]:
x = 36 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT A.i
     , salt_024({{x}} + sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE A.i <
        (SELECT sum(B.i)
         FROM ints B
         WHERE B.i < A.i
             AND A.i % B.i = 0 )
ORDER BY 1

246 rows affected.

i,token
12,248960157567190
18,248960157567190
20,248960157567190
24,248960157567190
30,248960157567190
36,248960157567190
40,248960157567190
42,248960157567190
48,248960157567190
54,248960157567190
56,248960157567190
60,248960157567190
66,248960157567190
70,248960157567190
72,248960157567190
78,248960157567190
80,248960157567190
84,248960157567190
88,248960157567190
90,248960157567190
96,248960157567190
100,248960157567190
102,248960157567190
104,248960157567190
108,248960157567190
112,248960157567190
114,248960157567190
120,248960157567190
126,248960157567190
132,248960157567190
138,248960157567190
140,248960157567190
144,248960157567190
150,248960157567190
156,248960157567190
160,248960157567190
162,248960157567190
168,248960157567190
174,248960157567190
176,248960157567190
180,248960157567190
186,248960157567190
192,248960157567190
196,248960157567190
198,248960157567190
200,248960157567190
204,248960157567190
208,248960157567190
210,248960157567190
216,248960157567190
220,248960157567190
222,248960157567190
224,248960157567190
228,248960157567190
234,248960157567190
240,248960157567190
246,248960157567190
252,248960157567190
258,248960157567190
260,248960157567190
264,248960157567190
270,248960157567190
272,248960157567190
276,248960157567190
280,248960157567190
282,248960157567190
288,248960157567190
294,248960157567190
300,248960157567190
304,248960157567190
306,248960157567190
308,248960157567190
312,248960157567190
318,248960157567190
320,248960157567190
324,248960157567190
330,248960157567190
336,248960157567190
340,248960157567190
342,248960157567190
348,248960157567190
350,248960157567190
352,248960157567190
354,248960157567190
360,248960157567190
364,248960157567190
366,248960157567190
368,248960157567190
372,248960157567190
378,248960157567190
380,248960157567190
384,248960157567190
390,248960157567190
392,248960157567190
396,248960157567190
400,248960157567190
402,248960157567190
408,248960157567190
414,248960157567190
416,248960157567190
420,248960157567190
426,248960157567190
432,248960157567190
438,248960157567190
440,248960157567190
444,248960157567190
448,248960157567190
450,248960157567190
456,248960157567190
460,248960157567190
462,248960157567190
464,248960157567190
468,248960157567190
474,248960157567190
476,248960157567190
480,248960157567190
486,248960157567190
490,248960157567190
492,248960157567190
498,248960157567190
500,248960157567190
504,248960157567190
510,248960157567190
516,248960157567190
520,248960157567190
522,248960157567190
528,248960157567190
532,248960157567190
534,248960157567190
540,248960157567190
544,248960157567190
546,248960157567190
550,248960157567190
552,248960157567190
558,248960157567190
560,248960157567190
564,248960157567190
570,248960157567190
572,248960157567190
576,248960157567190
580,248960157567190
582,248960157567190
588,248960157567190
594,248960157567190
600,248960157567190
606,248960157567190
608,248960157567190
612,248960157567190
616,248960157567190
618,248960157567190
620,248960157567190
624,248960157567190
630,248960157567190
636,248960157567190
640,248960157567190
642,248960157567190
644,248960157567190
648,248960157567190
650,248960157567190
654,248960157567190
660,248960157567190
666,248960157567190
672,248960157567190
678,248960157567190
680,248960157567190
684,248960157567190
690,248960157567190
696,248960157567190
700,248960157567190
702,248960157567190
704,248960157567190
708,248960157567190
714,248960157567190
720,248960157567190
726,248960157567190
728,248960157567190
732,248960157567190
736,248960157567190
738,248960157567190
740,248960157567190
744,248960157567190
748,248960157567190
750,248960157567190
756,248960157567190
760,248960157567190
762,248960157567190
768,248960157567190
770,248960157567190
774,248960157567190
780,248960157567190
784,248960157567190
786,248960157567190
792,248960157567190
798,248960157567190
800,248960157567190
804,248960157567190
810,248960157567190
812,248960157567190
816,248960157567190
820,248960157567190
822,248960157567190
828,248960157567190
832,248960157567190
834,248960157567190
836,248960157567190
840,248960157567190
846,248960157567190
852,248960157567190
858,248960157567190
860,248960157567190
864,248960157567190
868,248960157567190
870,248960157567190
876,248960157567190
880,248960157567190
882,248960157567190
888,248960157567190
894,248960157567190
896,248960157567190
900,248960157567190
906,248960157567190
910,248960157567190
912,248960157567190
918,248960157567190
920,248960157567190
924,248960157567190
928,248960157567190
930,248960157567190
936,248960157567190
940,248960157567190
942,248960157567190
945,248960157567190
948,248960157567190
952,248960157567190
954,248960157567190
960,248960157567190
966,248960157567190
968,248960157567190
972,248960157567190
978,248960157567190
980,248960157567190
984,248960157567190
990,248960157567190
992,248960157567190
996,248960157567190
1000,248960157567190

In [ ]:
assert col['i'][5] == x

### Entiers sans facteurs carrés

**Exercice [037].** Un entier est **sans facteur carré** si et seulement si aucun des nombres de sa décomposition en facteurs premiers n'apparaît plus d'une fois.

| Exemple | Décomposition | Propriété | Sans facteur carré |
|---:|:--:|:--:|:--:|
| $30$ | $$2 \times 3 \times 5$$ | aucun facteur dupliqué | oui |
| $12$ | $$2 \times 2 \times 3$$ | $2$ apparaît plus d'une fois | non |

_Tâche._ Listez par ordre croissant les entiers sans facteurs carrés inférieurs ou égaux à 1000.

In [ ]:
%%sql
WITH squares AS
    (SELECT DISTINCT B.i * B.i AS N2
                   , hash
     FROM ints B
     WHERE B.i * B.i <= 1000
         AND B.i > 1 )
SELECT A.i
     , salt_037(bit_xor(sum(nn(A.hash) + nn(S.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN squares S ON A.i % S.n2 = 0
GROUP BY A.i
HAVING count(S.n2) = 0

608 rows affected.

i,token
1,183542481619562
2,183542481619562
3,183542481619562
5,183542481619562
6,183542481619562
7,183542481619562
10,183542481619562
11,183542481619562
13,183542481619562
14,183542481619562
15,183542481619562
17,183542481619562
19,183542481619562
21,183542481619562
22,183542481619562
23,183542481619562
26,183542481619562
29,183542481619562
30,183542481619562
31,183542481619562
33,183542481619562
34,183542481619562
35,183542481619562
37,183542481619562
38,183542481619562
39,183542481619562
41,183542481619562
42,183542481619562
43,183542481619562
46,183542481619562
47,183542481619562
51,183542481619562
53,183542481619562
55,183542481619562
57,183542481619562
58,183542481619562
59,183542481619562
61,183542481619562
62,183542481619562
65,183542481619562
66,183542481619562
67,183542481619562
69,183542481619562
70,183542481619562
71,183542481619562
73,183542481619562
74,183542481619562
77,183542481619562
78,183542481619562
79,183542481619562
82,183542481619562
83,183542481619562
85,183542481619562
86,183542481619562
87,183542481619562
89,183542481619562
91,183542481619562
93,183542481619562
94,183542481619562
95,183542481619562
97,183542481619562
101,183542481619562
102,183542481619562
103,183542481619562
105,183542481619562
106,183542481619562
107,183542481619562
109,183542481619562
110,183542481619562
111,183542481619562
113,183542481619562
114,183542481619562
115,183542481619562
118,183542481619562
119,183542481619562
122,183542481619562
123,183542481619562
127,183542481619562
129,183542481619562
130,183542481619562
131,183542481619562
133,183542481619562
134,183542481619562
137,183542481619562
138,183542481619562
139,183542481619562
141,183542481619562
142,183542481619562
143,183542481619562
145,183542481619562
146,183542481619562
149,183542481619562
151,183542481619562
154,183542481619562
155,183542481619562
157,183542481619562
158,183542481619562
159,183542481619562
161,183542481619562
163,183542481619562
165,183542481619562
166,183542481619562
167,183542481619562
170,183542481619562
173,183542481619562
174,183542481619562
177,183542481619562
178,183542481619562
179,183542481619562
181,183542481619562
182,183542481619562
183,183542481619562
185,183542481619562
186,183542481619562
187,183542481619562
190,183542481619562
191,183542481619562
193,183542481619562
194,183542481619562
195,183542481619562
197,183542481619562
199,183542481619562
201,183542481619562
202,183542481619562
203,183542481619562
205,183542481619562
206,183542481619562
209,183542481619562
210,183542481619562
211,183542481619562
213,183542481619562
214,183542481619562
215,183542481619562
217,183542481619562
218,183542481619562
219,183542481619562
221,183542481619562
222,183542481619562
223,183542481619562
226,183542481619562
227,183542481619562
229,183542481619562
230,183542481619562
231,183542481619562
233,183542481619562
235,183542481619562
237,183542481619562
238,183542481619562
239,183542481619562
241,183542481619562
246,183542481619562
247,183542481619562
249,183542481619562
251,183542481619562
253,183542481619562
254,183542481619562
255,183542481619562
257,183542481619562
258,183542481619562
259,183542481619562
262,183542481619562
263,183542481619562
265,183542481619562
266,183542481619562
267,183542481619562
269,183542481619562
271,183542481619562
273,183542481619562
274,183542481619562
277,183542481619562
278,183542481619562
281,183542481619562
282,183542481619562
283,183542481619562
285,183542481619562
286,183542481619562
287,183542481619562
290,183542481619562
291,183542481619562
293,183542481619562
295,183542481619562
298,183542481619562
299,183542481619562
301,183542481619562
302,183542481619562
303,183542481619562
305,183542481619562
307,183542481619562
309,183542481619562
310,183542481619562
311,183542481619562
313,183542481619562
314,183542481619562
317,183542481619562
318,183542481619562
319,183542481619562
321,183542481619562
322,183542481619562
323,183542481619562
326,183542481619562
327,183542481619562
329,183542481619562
330,183542481619562
331,183542481619562
334,183542481619562
335,183542481619562
337,183542481619562
339,183542481619562
341,183542481619562
345,183542481619562
346,183542481619562
347,183542481619562
349,183542481619562
353,183542481619562
354,183542481619562
355,183542481619562
357,183542481619562
358,183542481619562
359,183542481619562
362,183542481619562
365,183542481619562
366,183542481619562
367,183542481619562
370,183542481619562
371,183542481619562
373,183542481619562
374,183542481619562
377,183542481619562
379,183542481619562
381,183542481619562
382,183542481619562
383,183542481619562
385,183542481619562
386,183542481619562
389,183542481619562
390,183542481619562
391,183542481619562
393,183542481619562
394,183542481619562
395,183542481619562
397,183542481619562
398,183542481619562
399,183542481619562
401,183542481619562
402,183542481619562
403,183542481619562
406,183542481619562
407,183542481619562
409,183542481619562
410,183542481619562
411,183542481619562
413,183542481619562
415,183542481619562
417,183542481619562
418,183542481619562
419,183542481619562
421,183542481619562
422,183542481619562
426,183542481619562
427,183542481619562
429,183542481619562
430,183542481619562
431,183542481619562
433,183542481619562
434,183542481619562
435,183542481619562
437,183542481619562
438,183542481619562
439,183542481619562
442,183542481619562
443,183542481619562
445,183542481619562
446,183542481619562
447,183542481619562
449,183542481619562
451,183542481619562
453,183542481619562
454,183542481619562
455,183542481619562
457,183542481619562
458,183542481619562
461,183542481619562
462,183542481619562
463,183542481619562
465,183542481619562
466,183542481619562
467,183542481619562
469,183542481619562
470,183542481619562
471,183542481619562
473,183542481619562
474,183542481619562
478,183542481619562
479,183542481619562
481,183542481619562
482,183542481619562
483,183542481619562
485,183542481619562
487,183542481619562
489,183542481619562
491,183542481619562
493,183542481619562
494,183542481619562
497,183542481619562
498,183542481619562
499,183542481619562
501,183542481619562
502,183542481619562
503,183542481619562
505,183542481619562
506,183542481619562
509,183542481619562
510,183542481619562
511,183542481619562
514,183542481619562
515,183542481619562
517,183542481619562
518,183542481619562
519,183542481619562
521,183542481619562
523,183542481619562
526,183542481619562
527,183542481619562
530,183542481619562
533,183542481619562
534,183542481619562
535,183542481619562
537,183542481619562
538,183542481619562
541,183542481619562
542,183542481619562
543,183542481619562
545,183542481619562
546,183542481619562
547,183542481619562
551,183542481619562
553,183542481619562
554,183542481619562
555,183542481619562
557,183542481619562
559,183542481619562
561,183542481619562
562,183542481619562
563,183542481619562
565,183542481619562
566,183542481619562
569,183542481619562
570,183542481619562
571,183542481619562
573,183542481619562
574,183542481619562
577,183542481619562
579,183542481619562
581,183542481619562
582,183542481619562
583,183542481619562
586,183542481619562
587,183542481619562
589,183542481619562
590,183542481619562
591,183542481619562
593,183542481619562
595,183542481619562
597,183542481619562
598,183542481619562
599,183542481619562
601,183542481619562
602,183542481619562
606,183542481619562
607,183542481619562
609,183542481619562
610,183542481619562
611,183542481619562
613,183542481619562
614,183542481619562
615,183542481619562
617,183542481619562
618,183542481619562
619,183542481619562
622,183542481619562
623,183542481619562
626,183542481619562
627,183542481619562
629,183542481619562
631,183542481619562
633,183542481619562
634,183542481619562
635,183542481619562
638,183542481619562
641,183542481619562
642,183542481619562
643,183542481619562
645,183542481619562
646,183542481619562
647,183542481619562
649,183542481619562
651,183542481619562
653,183542481619562
654,183542481619562
655,183542481619562
658,183542481619562
659,183542481619562
661,183542481619562
662,183542481619562
663,183542481619562
665,183542481619562
667,183542481619562
669,183542481619562
670,183542481619562
671,183542481619562
673,183542481619562
674,183542481619562
677,183542481619562
678,183542481619562
679,183542481619562
681,183542481619562
682,183542481619562
683,183542481619562
685,183542481619562
687,183542481619562
689,183542481619562
690,183542481619562
691,183542481619562
694,183542481619562
695,183542481619562
697,183542481619562
698,183542481619562
699,183542481619562
701,183542481619562
703,183542481619562
705,183542481619562
706,183542481619562
707,183542481619562
709,183542481619562
710,183542481619562
713,183542481619562
714,183542481619562
715,183542481619562
717,183542481619562
718,183542481619562
719,183542481619562
721,183542481619562
723,183542481619562
727,183542481619562
730,183542481619562
731,183542481619562
733,183542481619562
734,183542481619562
737,183542481619562
739,183542481619562
741,183542481619562
742,183542481619562
743,183542481619562
745,183542481619562
746,183542481619562
749,183542481619562
751,183542481619562
753,183542481619562
754,183542481619562
755,183542481619562
757,183542481619562
758,183542481619562
759,183542481619562
761,183542481619562
762,183542481619562
763,183542481619562
766,183542481619562
767,183542481619562
769,183542481619562
770,183542481619562
771,183542481619562
773,183542481619562
777,183542481619562
778,183542481619562
779,183542481619562
781,183542481619562
782,183542481619562
785,183542481619562
786,183542481619562
787,183542481619562
789,183542481619562
790,183542481619562
791,183542481619562
793,183542481619562
794,183542481619562
795,183542481619562
797,183542481619562
798,183542481619562
799,183542481619562
802,183542481619562
803,183542481619562
805,183542481619562
806,183542481619562
807,183542481619562
809,183542481619562
811,183542481619562
813,183542481619562
814,183542481619562
815,183542481619562
817,183542481619562
818,183542481619562
821,183542481619562
822,183542481619562
823,183542481619562
826,183542481619562
827,183542481619562
829,183542481619562
830,183542481619562
831,183542481619562
834,183542481619562
835,183542481619562
838,183542481619562
839,183542481619562
842,183542481619562
843,183542481619562
849,183542481619562
851,183542481619562
853,183542481619562
854,183542481619562
857,183542481619562
858,183542481619562
859,183542481619562
861,183542481619562
862,183542481619562
863,183542481619562
865,183542481619562
866,183542481619562
869,183542481619562
870,183542481619562
871,183542481619562
874,183542481619562
877,183542481619562
878,183542481619562
879,183542481619562
881,183542481619562
883,183542481619562
885,183542481619562
886,183542481619562
887,183542481619562
889,183542481619562
890,183542481619562
893,183542481619562
894,183542481619562
895,183542481619562
897,183542481619562
898,183542481619562
899,183542481619562
901,183542481619562
902,183542481619562
903,183542481619562
905,183542481619562
906,183542481619562
907,183542481619562
910,183542481619562
911,183542481619562
913,183542481619562
914,183542481619562
915,183542481619562
917,183542481619562
919,183542481619562
921,183542481619562
922,183542481619562
923,183542481619562
926,183542481619562
929,183542481619562
930,183542481619562
933,183542481619562
934,183542481619562
935,183542481619562
937,183542481619562
938,183542481619562
939,183542481619562
941,183542481619562
942,183542481619562
943,183542481619562
946,183542481619562
947,183542481619562
949,183542481619562
951,183542481619562
953,183542481619562
955,183542481619562
957,183542481619562
958,183542481619562
959,183542481619562
962,183542481619562
965,183542481619562
966,183542481619562
967,183542481619562
969,183542481619562
970,183542481619562
971,183542481619562
973,183542481619562
974,183542481619562
977,183542481619562
978,183542481619562
979,183542481619562
982,183542481619562
983,183542481619562
985,183542481619562
986,183542481619562
987,183542481619562
989,183542481619562
991,183542481619562
993,183542481619562
994,183542481619562
995,183542481619562
997,183542481619562
998,183542481619562

### Nombres bicarrés

**Exercice [032].** Un entier $c$ est **bicarré** si et seulement s'il peut s'écrire sous la forme $a^2+b^2$ avec $a$ et $b$ entiers.

| Exemple | Forme cherchée | Bicarré |
|---:|:--:|:--:|
| $17$ | $$1^2+4^2$$ | oui |
| $15$ | aucune | non |

<figure>
  <img src="https://www.dropbox.com/scl/fi/j9dtivl6qfcrs2nkv74xq/nombre-bigarr.png?rlkey=kb58znx2v7f69wsn1sy5hhw6q&raw=1"/>
  <figcaption>Entier bicarré bigarré.</figcaption>
</figure>

_Tâche._ Listez par ordre croissant les entiers bicarrés inférieurs ou égaux à 1000.

_Contrainte._ Faites un produit cartésien de trois tables.

In [ ]:
x = 8 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
SELECT DISTINCT C.i
              , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints C
JOIN ints A ON A.i * A.i <= C.i
JOIN ints B ON A.i * A.i + B.i * B.i = C.i
ORDER BY 1

331 rows affected.

i,token
0,1230160502988882
1,1230160502988882
2,1230160502988882
4,1230160502988882
5,1230160502988882
8,1230160502988882
9,1230160502988882
10,1230160502988882
13,1230160502988882
16,1230160502988882
17,1230160502988882
18,1230160502988882
20,1230160502988882
25,1230160502988882
26,1230160502988882
29,1230160502988882
32,1230160502988882
34,1230160502988882
36,1230160502988882
37,1230160502988882
40,1230160502988882
41,1230160502988882
45,1230160502988882
49,1230160502988882
50,1230160502988882
52,1230160502988882
53,1230160502988882
58,1230160502988882
61,1230160502988882
64,1230160502988882
65,1230160502988882
68,1230160502988882
72,1230160502988882
73,1230160502988882
74,1230160502988882
80,1230160502988882
81,1230160502988882
82,1230160502988882
85,1230160502988882
89,1230160502988882
90,1230160502988882
97,1230160502988882
98,1230160502988882
100,1230160502988882
101,1230160502988882
104,1230160502988882
106,1230160502988882
109,1230160502988882
113,1230160502988882
116,1230160502988882
117,1230160502988882
121,1230160502988882
122,1230160502988882
125,1230160502988882
128,1230160502988882
130,1230160502988882
136,1230160502988882
137,1230160502988882
144,1230160502988882
145,1230160502988882
146,1230160502988882
148,1230160502988882
149,1230160502988882
153,1230160502988882
157,1230160502988882
160,1230160502988882
162,1230160502988882
164,1230160502988882
169,1230160502988882
170,1230160502988882
173,1230160502988882
178,1230160502988882
180,1230160502988882
181,1230160502988882
185,1230160502988882
193,1230160502988882
194,1230160502988882
196,1230160502988882
197,1230160502988882
200,1230160502988882
202,1230160502988882
205,1230160502988882
208,1230160502988882
212,1230160502988882
218,1230160502988882
221,1230160502988882
225,1230160502988882
226,1230160502988882
229,1230160502988882
232,1230160502988882
233,1230160502988882
234,1230160502988882
241,1230160502988882
242,1230160502988882
244,1230160502988882
245,1230160502988882
250,1230160502988882
256,1230160502988882
257,1230160502988882
260,1230160502988882
261,1230160502988882
265,1230160502988882
269,1230160502988882
272,1230160502988882
274,1230160502988882
277,1230160502988882
281,1230160502988882
288,1230160502988882
289,1230160502988882
290,1230160502988882
292,1230160502988882
293,1230160502988882
296,1230160502988882
298,1230160502988882
305,1230160502988882
306,1230160502988882
313,1230160502988882
314,1230160502988882
317,1230160502988882
320,1230160502988882
324,1230160502988882
325,1230160502988882
328,1230160502988882
333,1230160502988882
337,1230160502988882
338,1230160502988882
340,1230160502988882
346,1230160502988882
349,1230160502988882
353,1230160502988882
356,1230160502988882
360,1230160502988882
361,1230160502988882
362,1230160502988882
365,1230160502988882
369,1230160502988882
370,1230160502988882
373,1230160502988882
377,1230160502988882
386,1230160502988882
388,1230160502988882
389,1230160502988882
392,1230160502988882
394,1230160502988882
397,1230160502988882
400,1230160502988882
401,1230160502988882
404,1230160502988882
405,1230160502988882
409,1230160502988882
410,1230160502988882
416,1230160502988882
421,1230160502988882
424,1230160502988882
425,1230160502988882
433,1230160502988882
436,1230160502988882
441,1230160502988882
442,1230160502988882
445,1230160502988882
449,1230160502988882
450,1230160502988882
452,1230160502988882
457,1230160502988882
458,1230160502988882
461,1230160502988882
464,1230160502988882
466,1230160502988882
468,1230160502988882
477,1230160502988882
481,1230160502988882
482,1230160502988882
484,1230160502988882
485,1230160502988882
488,1230160502988882
490,1230160502988882
493,1230160502988882
500,1230160502988882
505,1230160502988882
509,1230160502988882
512,1230160502988882
514,1230160502988882
520,1230160502988882
521,1230160502988882
522,1230160502988882
529,1230160502988882
530,1230160502988882
533,1230160502988882
538,1230160502988882
541,1230160502988882
544,1230160502988882
545,1230160502988882
548,1230160502988882
549,1230160502988882
554,1230160502988882
557,1230160502988882
562,1230160502988882
565,1230160502988882
569,1230160502988882
576,1230160502988882
577,1230160502988882
578,1230160502988882
580,1230160502988882
584,1230160502988882
585,1230160502988882
586,1230160502988882
592,1230160502988882
593,1230160502988882
596,1230160502988882
601,1230160502988882
605,1230160502988882
610,1230160502988882
612,1230160502988882
613,1230160502988882
617,1230160502988882
625,1230160502988882
626,1230160502988882
628,1230160502988882
629,1230160502988882
634,1230160502988882
637,1230160502988882
640,1230160502988882
641,1230160502988882
648,1230160502988882
650,1230160502988882
653,1230160502988882
656,1230160502988882
657,1230160502988882
661,1230160502988882
666,1230160502988882
673,1230160502988882
674,1230160502988882
676,1230160502988882
677,1230160502988882
680,1230160502988882
685,1230160502988882
689,1230160502988882
692,1230160502988882
697,1230160502988882
698,1230160502988882
701,1230160502988882
706,1230160502988882
709,1230160502988882
712,1230160502988882
720,1230160502988882
722,1230160502988882
724,1230160502988882
725,1230160502988882
729,1230160502988882
730,1230160502988882
733,1230160502988882
738,1230160502988882
740,1230160502988882
745,1230160502988882
746,1230160502988882
754,1230160502988882
757,1230160502988882
761,1230160502988882
765,1230160502988882
769,1230160502988882
772,1230160502988882
773,1230160502988882
776,1230160502988882
778,1230160502988882
784,1230160502988882
785,1230160502988882
788,1230160502988882
793,1230160502988882
794,1230160502988882
797,1230160502988882
800,1230160502988882
801,1230160502988882
802,1230160502988882
808,1230160502988882
809,1230160502988882
810,1230160502988882
818,1230160502988882
820,1230160502988882
821,1230160502988882
829,1230160502988882
832,1230160502988882
833,1230160502988882
841,1230160502988882
842,1230160502988882
845,1230160502988882
848,1230160502988882
850,1230160502988882
853,1230160502988882
857,1230160502988882
865,1230160502988882
866,1230160502988882
872,1230160502988882
873,1230160502988882
877,1230160502988882
881,1230160502988882
882,1230160502988882
884,1230160502988882
890,1230160502988882
898,1230160502988882
900,1230160502988882
901,1230160502988882
904,1230160502988882
905,1230160502988882
909,1230160502988882
914,1230160502988882
916,1230160502988882
922,1230160502988882
925,1230160502988882
928,1230160502988882
929,1230160502988882
932,1230160502988882
936,1230160502988882
937,1230160502988882
941,1230160502988882
949,1230160502988882
953,1230160502988882
954,1230160502988882
961,1230160502988882
962,1230160502988882
964,1230160502988882
965,1230160502988882
968,1230160502988882
970,1230160502988882
976,1230160502988882
977,1230160502988882
980,1230160502988882
981,1230160502988882
985,1230160502988882
986,1230160502988882
997,1230160502988882
1000,1230160502988882

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 4

In [ ]:
%%sql
-- Indication. Supprimez les doublons.
SELECT A.i
     , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i * B.i <= A.i
JOIN ints C ON C.i * C.i <= A.i
WHERE B.i * B.i + C.i * C.i = A.i
ORDER BY 1

819 rows affected.

i,token
0,1230160502988894
1,1230160502988894
1,1230160502988894
2,1230160502988894
4,1230160502988894
4,1230160502988894
5,1230160502988894
5,1230160502988894
8,1230160502988894
9,1230160502988894
9,1230160502988894
10,1230160502988894
10,1230160502988894
13,1230160502988894
13,1230160502988894
16,1230160502988894
16,1230160502988894
17,1230160502988894
17,1230160502988894
18,1230160502988894
20,1230160502988894
20,1230160502988894
25,1230160502988894
25,1230160502988894
25,1230160502988894
25,1230160502988894
26,1230160502988894
26,1230160502988894
29,1230160502988894
29,1230160502988894
32,1230160502988894
34,1230160502988894
34,1230160502988894
36,1230160502988894
36,1230160502988894
37,1230160502988894
37,1230160502988894
40,1230160502988894
40,1230160502988894
41,1230160502988894
41,1230160502988894
45,1230160502988894
45,1230160502988894
49,1230160502988894
49,1230160502988894
50,1230160502988894
50,1230160502988894
50,1230160502988894
52,1230160502988894
52,1230160502988894
53,1230160502988894
53,1230160502988894
58,1230160502988894
58,1230160502988894
61,1230160502988894
61,1230160502988894
64,1230160502988894
64,1230160502988894
65,1230160502988894
65,1230160502988894
65,1230160502988894
65,1230160502988894
68,1230160502988894
68,1230160502988894
72,1230160502988894
73,1230160502988894
73,1230160502988894
74,1230160502988894
74,1230160502988894
80,1230160502988894
80,1230160502988894
81,1230160502988894
81,1230160502988894
82,1230160502988894
82,1230160502988894
85,1230160502988894
85,1230160502988894
85,1230160502988894
85,1230160502988894
89,1230160502988894
89,1230160502988894
90,1230160502988894
90,1230160502988894
97,1230160502988894
97,1230160502988894
98,1230160502988894
100,1230160502988894
100,1230160502988894
100,1230160502988894
100,1230160502988894
101,1230160502988894
101,1230160502988894
104,1230160502988894
104,1230160502988894
106,1230160502988894
106,1230160502988894
109,1230160502988894
109,1230160502988894
113,1230160502988894
113,1230160502988894
116,1230160502988894
116,1230160502988894
117,1230160502988894
117,1230160502988894
121,1230160502988894
121,1230160502988894
122,1230160502988894
122,1230160502988894
125,1230160502988894
125,1230160502988894
125,1230160502988894
125,1230160502988894
128,1230160502988894
130,1230160502988894
130,1230160502988894
130,1230160502988894
130,1230160502988894
136,1230160502988894
136,1230160502988894
137,1230160502988894
137,1230160502988894
144,1230160502988894
144,1230160502988894
145,1230160502988894
145,1230160502988894
145,1230160502988894
145,1230160502988894
146,1230160502988894
146,1230160502988894
148,1230160502988894
148,1230160502988894
149,1230160502988894
149,1230160502988894
153,1230160502988894
153,1230160502988894
157,1230160502988894
157,1230160502988894
160,1230160502988894
160,1230160502988894
162,1230160502988894
164,1230160502988894
164,1230160502988894
169,1230160502988894
169,1230160502988894
169,1230160502988894
169,1230160502988894
170,1230160502988894
170,1230160502988894
170,1230160502988894
170,1230160502988894
173,1230160502988894
173,1230160502988894
178,1230160502988894
178,1230160502988894
180,1230160502988894
180,1230160502988894
181,1230160502988894
181,1230160502988894
185,1230160502988894
185,1230160502988894
185,1230160502988894
185,1230160502988894
193,1230160502988894
193,1230160502988894
194,1230160502988894
194,1230160502988894
196,1230160502988894
196,1230160502988894
197,1230160502988894
197,1230160502988894
200,1230160502988894
200,1230160502988894
200,1230160502988894
202,1230160502988894
202,1230160502988894
205,1230160502988894
205,1230160502988894
205,1230160502988894
205,1230160502988894
208,1230160502988894
208,1230160502988894
212,1230160502988894
212,1230160502988894
218,1230160502988894
218,1230160502988894
221,1230160502988894
221,1230160502988894
221,1230160502988894
221,1230160502988894
225,1230160502988894
225,1230160502988894
225,1230160502988894
225,1230160502988894
226,1230160502988894
226,1230160502988894
229,1230160502988894
229,1230160502988894
232,1230160502988894
232,1230160502988894
233,1230160502988894
233,1230160502988894
234,1230160502988894
234,1230160502988894
241,1230160502988894
241,1230160502988894
242,1230160502988894
244,1230160502988894
244,1230160502988894
245,1230160502988894
245,1230160502988894
250,1230160502988894
250,1230160502988894
250,1230160502988894
250,1230160502988894
256,1230160502988894
256,1230160502988894
257,1230160502988894
257,1230160502988894
260,1230160502988894
260,1230160502988894
260,1230160502988894
260,1230160502988894
261,1230160502988894
261,1230160502988894
265,1230160502988894
265,1230160502988894
265,1230160502988894
265,1230160502988894
269,1230160502988894
269,1230160502988894
272,1230160502988894
272,1230160502988894
274,1230160502988894
274,1230160502988894
277,1230160502988894
277,1230160502988894
281,1230160502988894
281,1230160502988894
288,1230160502988894
289,1230160502988894
289,1230160502988894
289,1230160502988894
289,1230160502988894
290,1230160502988894
290,1230160502988894
290,1230160502988894
290,1230160502988894
292,1230160502988894
292,1230160502988894
293,1230160502988894
293,1230160502988894
296,1230160502988894
296,1230160502988894
298,1230160502988894
298,1230160502988894
305,1230160502988894
305,1230160502988894
305,1230160502988894
305,1230160502988894
306,1230160502988894
306,1230160502988894
313,1230160502988894
313,1230160502988894
314,1230160502988894
314,1230160502988894
317,1230160502988894
317,1230160502988894
320,1230160502988894
320,1230160502988894
324,1230160502988894
324,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
325,1230160502988894
328,1230160502988894
328,1230160502988894
333,1230160502988894
333,1230160502988894
337,1230160502988894
337,1230160502988894
338,1230160502988894
338,1230160502988894
338,1230160502988894
340,1230160502988894
340,1230160502988894
340,1230160502988894
340,1230160502988894
346,1230160502988894
346,1230160502988894
349,1230160502988894
349,1230160502988894
353,1230160502988894
353,1230160502988894
356,1230160502988894
356,1230160502988894
360,1230160502988894
360,1230160502988894
361,1230160502988894
361,1230160502988894
362,1230160502988894
362,1230160502988894
365,1230160502988894
365,1230160502988894
365,1230160502988894
365,1230160502988894
369,1230160502988894
369,1230160502988894
370,1230160502988894
370,1230160502988894
370,1230160502988894
370,1230160502988894
373,1230160502988894
373,1230160502988894
377,1230160502988894
377,1230160502988894
377,1230160502988894
377,1230160502988894
386,1230160502988894
386,1230160502988894
388,1230160502988894
388,1230160502988894
389,1230160502988894
389,1230160502988894
392,1230160502988894
394,1230160502988894
394,1230160502988894
397,1230160502988894
397,1230160502988894
400,1230160502988894
400,1230160502988894
400,1230160502988894
400,1230160502988894
401,1230160502988894
401,1230160502988894
404,1230160502988894
404,1230160502988894
405,1230160502988894
405,1230160502988894
409,1230160502988894
409,1230160502988894
410,1230160502988894
410,1230160502988894
410,1230160502988894
410,1230160502988894
416,1230160502988894
416,1230160502988894
421,1230160502988894
421,1230160502988894
424,1230160502988894
424,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
425,1230160502988894
433,1230160502988894
433,1230160502988894
436,1230160502988894
436,1230160502988894
441,1230160502988894
441,1230160502988894
442,1230160502988894
442,1230160502988894
442,1230160502988894
442,1230160502988894
445,1230160502988894
445,1230160502988894
445,1230160502988894
445,1230160502988894
449,1230160502988894
449,1230160502988894
450,1230160502988894
450,1230160502988894
450,1230160502988894
452,1230160502988894
452,1230160502988894
457,1230160502988894
457,1230160502988894
458,1230160502988894
458,1230160502988894
461,1230160502988894
461,1230160502988894
464,1230160502988894
464,1230160502988894
466,1230160502988894
466,1230160502988894
468,1230160502988894
468,1230160502988894
477,1230160502988894
477,1230160502988894
481,1230160502988894
481,1230160502988894
481,1230160502988894
481,1230160502988894
482,1230160502988894
482,1230160502988894
484,1230160502988894
484,1230160502988894
485,1230160502988894
485,1230160502988894
485,1230160502988894
485,1230160502988894
488,1230160502988894
488,1230160502988894
490,1230160502988894
490,1230160502988894
493,1230160502988894
493,1230160502988894
493,1230160502988894
493,1230160502988894
500,1230160502988894
500,1230160502988894
500,1230160502988894
500,1230160502988894
505,1230160502988894
505,1230160502988894
505,1230160502988894
505,1230160502988894
509,1230160502988894
509,1230160502988894
512,1230160502988894
514,1230160502988894
514,1230160502988894
520,1230160502988894
520,1230160502988894
520,1230160502988894
520,1230160502988894
521,1230160502988894
521,1230160502988894
522,1230160502988894
522,1230160502988894
529,1230160502988894
529,1230160502988894
530,1230160502988894
530,1230160502988894
530,1230160502988894
530,1230160502988894
533,1230160502988894
533,1230160502988894
533,1230160502988894
533,1230160502988894
538,1230160502988894
538,1230160502988894
541,1230160502988894
541,1230160502988894
544,1230160502988894
544,1230160502988894
545,1230160502988894
545,1230160502988894
545,1230160502988894
545,1230160502988894
548,1230160502988894
548,1230160502988894
549,1230160502988894
549,1230160502988894
554,1230160502988894
554,1230160502988894
557,1230160502988894
557,1230160502988894
562,1230160502988894
562,1230160502988894
565,1230160502988894
565,1230160502988894
565,1230160502988894
565,1230160502988894
569,1230160502988894
569,1230160502988894
576,1230160502988894
576,1230160502988894
577,1230160502988894
577,1230160502988894
578,1230160502988894
578,1230160502988894
578,1230160502988894
580,1230160502988894
580,1230160502988894
580,1230160502988894
580,1230160502988894
584,1230160502988894
584,1230160502988894
585,1230160502988894
585,1230160502988894
585,1230160502988894
585,1230160502988894
586,1230160502988894
586,1230160502988894
592,1230160502988894
592,1230160502988894
593,1230160502988894
593,1230160502988894
596,1230160502988894
596,1230160502988894
601,1230160502988894
601,1230160502988894
605,1230160502988894
605,1230160502988894
610,1230160502988894
610,1230160502988894
610,1230160502988894
610,1230160502988894
612,1230160502988894
612,1230160502988894
613,1230160502988894
613,1230160502988894
617,1230160502988894
617,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
625,1230160502988894
626,1230160502988894
626,1230160502988894
628,1230160502988894
628,1230160502988894
629,1230160502988894
629,1230160502988894
629,1230160502988894
629,1230160502988894
634,1230160502988894
634,1230160502988894
637,1230160502988894
637,1230160502988894
640,1230160502988894
640,1230160502988894
641,1230160502988894
641,1230160502988894
648,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
650,1230160502988894
653,1230160502988894
653,1230160502988894
656,1230160502988894
656,1230160502988894
657,1230160502988894
657,1230160502988894
661,1230160502988894
661,1230160502988894
666,1230160502988894
666,1230160502988894
673,1230160502988894
673,1230160502988894
674,1230160502988894
674,1230160502988894
676,1230160502988894
676,1230160502988894
676,1230160502988894
676,1230160502988894
677,1230160502988894
677,1230160502988894
680,1230160502988894
680,1230160502988894
680,1230160502988894
680,1230160502988894
685,1230160502988894
685,1230160502988894
685,1230160502988894
685,1230160502988894
689,1230160502988894
689,1230160502988894
689,1230160502988894
689,1230160502988894
692,1230160502988894
692,1230160502988894
697,1230160502988894
697,1230160502988894
697,1230160502988894
697,1230160502988894
698,1230160502988894
698,1230160502988894
701,1230160502988894
701,1230160502988894
706,1230160502988894
706,1230160502988894
709,1230160502988894
709,1230160502988894
712,1230160502988894
712,1230160502988894
720,1230160502988894
720,1230160502988894
722,1230160502988894
724,1230160502988894
724,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
725,1230160502988894
729,1230160502988894
729,1230160502988894
730,1230160502988894
730,1230160502988894
730,1230160502988894
730,1230160502988894
733,1230160502988894
733,1230160502988894
738,1230160502988894
738,1230160502988894
740,1230160502988894
740,1230160502988894
740,1230160502988894
740,1230160502988894
745,1230160502988894
745,1230160502988894
745,1230160502988894
745,1230160502988894
746,1230160502988894
746,1230160502988894
754,1230160502988894
754,1230160502988894
754,1230160502988894
754,1230160502988894
757,1230160502988894
757,1230160502988894
761,1230160502988894
761,1230160502988894
765,1230160502988894
765,1230160502988894
765,1230160502988894
765,1230160502988894
769,1230160502988894
769,1230160502988894
772,1230160502988894
772,1230160502988894
773,1230160502988894
773,1230160502988894
776,1230160502988894
776,1230160502988894
778,1230160502988894
778,1230160502988894
784,1230160502988894
784,1230160502988894
785,1230160502988894
785,1230160502988894
785,1230160502988894
785,1230160502988894
788,1230160502988894
788,1230160502988894
793,1230160502988894
793,1230160502988894
793,1230160502988894
793,1230160502988894
794,1230160502988894
794,1230160502988894
797,1230160502988894
797,1230160502988894
800,1230160502988894
800,1230160502988894
800,1230160502988894
801,1230160502988894
801,1230160502988894
802,1230160502988894
802,1230160502988894
808,1230160502988894
808,1230160502988894
809,1230160502988894
809,1230160502988894
810,1230160502988894
810,1230160502988894
818,1230160502988894
818,1230160502988894
820,1230160502988894
820,1230160502988894
820,1230160502988894
820,1230160502988894
821,1230160502988894
821,1230160502988894
829,1230160502988894
829,1230160502988894
832,1230160502988894
832,1230160502988894
833,1230160502988894
833,1230160502988894
841,1230160502988894
841,1230160502988894
841,1230160502988894
841,1230160502988894
842,1230160502988894
842,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
845,1230160502988894
848,1230160502988894
848,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
850,1230160502988894
853,1230160502988894
853,1230160502988894
857,1230160502988894
857,1230160502988894
865,1230160502988894
865,1230160502988894
865,1230160502988894
865,1230160502988894
866,1230160502988894
866,1230160502988894
872,1230160502988894
872,1230160502988894
873,1230160502988894
873,1230160502988894
877,1230160502988894
877,1230160502988894
881,1230160502988894
881,1230160502988894
882,1230160502988894
884,1230160502988894
884,1230160502988894
884,1230160502988894
884,1230160502988894
890,1230160502988894
890,1230160502988894
890,1230160502988894
890,1230160502988894
898,1230160502988894
898,1230160502988894
900,1230160502988894
900,1230160502988894
900,1230160502988894
900,1230160502988894
901,1230160502988894
901,1230160502988894
901,1230160502988894
901,1230160502988894
904,1230160502988894
904,1230160502988894
905,1230160502988894
905,1230160502988894
905,1230160502988894
905,1230160502988894
909,1230160502988894
909,1230160502988894
914,1230160502988894
914,1230160502988894
916,1230160502988894
916,1230160502988894
922,1230160502988894
922,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
925,1230160502988894
928,1230160502988894
928,1230160502988894
929,1230160502988894
929,1230160502988894
932,1230160502988894
932,1230160502988894
936,1230160502988894
936,1230160502988894
937,1230160502988894
937,1230160502988894
941,1230160502988894
941,1230160502988894
949,1230160502988894
949,1230160502988894
949,1230160502988894
949,1230160502988894
953,1230160502988894
953,1230160502988894
954,1230160502988894
954,1230160502988894
961,1230160502988894
961,1230160502988894
962,1230160502988894
962,1230160502988894
962,1230160502988894
962,1230160502988894
964,1230160502988894
964,1230160502988894
965,1230160502988894
965,1230160502988894
965,1230160502988894
965,1230160502988894
968,1230160502988894
970,1230160502988894
970,1230160502988894
970,1230160502988894
970,1230160502988894
976,1230160502988894
976,1230160502988894
977,1230160502988894
977,1230160502988894
980,1230160502988894
980,1230160502988894
981,1230160502988894
981,1230160502988894
985,1230160502988894
985,1230160502988894
985,1230160502988894
985,1230160502988894
986,1230160502988894
986,1230160502988894
986,1230160502988894
986,1230160502988894
997,1230160502988894
997,1230160502988894
1000,1230160502988894
1000,1230160502988894
1000,1230160502988894
1000,1230160502988894

In [ ]:
assert col['i'][5] == x

In [ ]:
x = 676

In [ ]:
%%sql
-- Indication. Triez ces nombres par ordre croissant.
SELECT DISTINCT A.i
              , salt_032({{x}} + sum(nn(A.hash) + nn(B.hash) + nn(C.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON B.i * B.i <= A.i
JOIN ints C ON C.i * C.i <= A.i
WHERE B.i * B.i + C.i * C.i = A.i

331 rows affected.

i,token
961,1230160502992190
900,1230160502992190
841,1230160502992190
784,1230160502992190
729,1230160502992190
676,1230160502992190
625,1230160502992190
576,1230160502992190
529,1230160502992190
484,1230160502992190
441,1230160502992190
400,1230160502992190
361,1230160502992190
324,1230160502992190
289,1230160502992190
256,1230160502992190
225,1230160502992190
196,1230160502992190
169,1230160502992190
144,1230160502992190
121,1230160502992190
100,1230160502992190
81,1230160502992190
64,1230160502992190
49,1230160502992190
36,1230160502992190
25,1230160502992190
16,1230160502992190
9,1230160502992190
4,1230160502992190
1,1230160502992190
0,1230160502992190
962,1230160502992190
901,1230160502992190
842,1230160502992190
785,1230160502992190
730,1230160502992190
677,1230160502992190
626,1230160502992190
577,1230160502992190
530,1230160502992190
485,1230160502992190
442,1230160502992190
401,1230160502992190
362,1230160502992190
325,1230160502992190
290,1230160502992190
257,1230160502992190
226,1230160502992190
197,1230160502992190
170,1230160502992190
145,1230160502992190
122,1230160502992190
101,1230160502992190
82,1230160502992190
65,1230160502992190
50,1230160502992190
37,1230160502992190
26,1230160502992190
17,1230160502992190
10,1230160502992190
5,1230160502992190
2,1230160502992190
965,1230160502992190
904,1230160502992190
845,1230160502992190
788,1230160502992190
733,1230160502992190
680,1230160502992190
629,1230160502992190
580,1230160502992190
533,1230160502992190
488,1230160502992190
445,1230160502992190
404,1230160502992190
365,1230160502992190
328,1230160502992190
293,1230160502992190
260,1230160502992190
229,1230160502992190
200,1230160502992190
173,1230160502992190
148,1230160502992190
125,1230160502992190
104,1230160502992190
85,1230160502992190
68,1230160502992190
53,1230160502992190
40,1230160502992190
29,1230160502992190
20,1230160502992190
13,1230160502992190
8,1230160502992190
970,1230160502992190
909,1230160502992190
850,1230160502992190
793,1230160502992190
738,1230160502992190
685,1230160502992190
634,1230160502992190
585,1230160502992190
538,1230160502992190
493,1230160502992190
450,1230160502992190
409,1230160502992190
370,1230160502992190
333,1230160502992190
298,1230160502992190
265,1230160502992190
234,1230160502992190
205,1230160502992190
178,1230160502992190
153,1230160502992190
130,1230160502992190
109,1230160502992190
90,1230160502992190
73,1230160502992190
58,1230160502992190
45,1230160502992190
34,1230160502992190
18,1230160502992190
977,1230160502992190
916,1230160502992190
857,1230160502992190
800,1230160502992190
745,1230160502992190
692,1230160502992190
641,1230160502992190
592,1230160502992190
545,1230160502992190
500,1230160502992190
457,1230160502992190
416,1230160502992190
377,1230160502992190
340,1230160502992190
305,1230160502992190
272,1230160502992190
241,1230160502992190
212,1230160502992190
185,1230160502992190
160,1230160502992190
137,1230160502992190
116,1230160502992190
97,1230160502992190
80,1230160502992190
52,1230160502992190
41,1230160502992190
32,1230160502992190
986,1230160502992190
925,1230160502992190
866,1230160502992190
809,1230160502992190
754,1230160502992190
701,1230160502992190
650,1230160502992190
601,1230160502992190
554,1230160502992190
509,1230160502992190
466,1230160502992190
425,1230160502992190
386,1230160502992190
349,1230160502992190
314,1230160502992190
281,1230160502992190
250,1230160502992190
221,1230160502992190
194,1230160502992190
146,1230160502992190
106,1230160502992190
89,1230160502992190
74,1230160502992190
61,1230160502992190
997,1230160502992190
936,1230160502992190
877,1230160502992190
820,1230160502992190
765,1230160502992190
712,1230160502992190
661,1230160502992190
612,1230160502992190
565,1230160502992190
520,1230160502992190
477,1230160502992190
436,1230160502992190
397,1230160502992190
360,1230160502992190
292,1230160502992190
261,1230160502992190
232,1230160502992190
180,1230160502992190
157,1230160502992190
136,1230160502992190
117,1230160502992190
72,1230160502992190
949,1230160502992190
890,1230160502992190
833,1230160502992190
778,1230160502992190
725,1230160502992190
674,1230160502992190
578,1230160502992190
490,1230160502992190
449,1230160502992190
410,1230160502992190
373,1230160502992190
338,1230160502992190
274,1230160502992190
245,1230160502992190
218,1230160502992190
193,1230160502992190
149,1230160502992190
113,1230160502992190
98,1230160502992190
964,1230160502992190
905,1230160502992190
848,1230160502992190
740,1230160502992190
689,1230160502992190
640,1230160502992190
593,1230160502992190
548,1230160502992190
505,1230160502992190
464,1230160502992190
388,1230160502992190
353,1230160502992190
320,1230160502992190
233,1230160502992190
208,1230160502992190
164,1230160502992190
128,1230160502992190
981,1230160502992190
922,1230160502992190
865,1230160502992190
810,1230160502992190
757,1230160502992190
706,1230160502992190
657,1230160502992190
610,1230160502992190
522,1230160502992190
481,1230160502992190
405,1230160502992190
337,1230160502992190
306,1230160502992190
277,1230160502992190
202,1230160502992190
181,1230160502992190
162,1230160502992190
1000,1230160502992190
941,1230160502992190
884,1230160502992190
829,1230160502992190
776,1230160502992190
584,1230160502992190
541,1230160502992190
461,1230160502992190
424,1230160502992190
389,1230160502992190
356,1230160502992190
296,1230160502992190
269,1230160502992190
244,1230160502992190
797,1230160502992190
746,1230160502992190
697,1230160502992190
605,1230160502992190
562,1230160502992190
521,1230160502992190
482,1230160502992190
346,1230160502992190
317,1230160502992190
242,1230160502992190
985,1230160502992190
928,1230160502992190
873,1230160502992190
769,1230160502992190
720,1230160502992190
673,1230160502992190
628,1230160502992190
544,1230160502992190
468,1230160502992190
433,1230160502992190
369,1230160502992190
313,1230160502992190
288,1230160502992190
953,1230160502992190
898,1230160502992190
794,1230160502992190
698,1230160502992190
653,1230160502992190
569,1230160502992190
458,1230160502992190
394,1230160502992190
980,1230160502992190
872,1230160502992190
821,1230160502992190
772,1230160502992190
637,1230160502992190
596,1230160502992190
557,1230160502992190
452,1230160502992190
421,1230160502992190
392,1230160502992190
954,1230160502992190
801,1230160502992190
709,1230160502992190
666,1230160502992190
586,1230160502992190
549,1230160502992190
514,1230160502992190
932,1230160502992190
881,1230160502992190
832,1230160502992190
656,1230160502992190
617,1230160502992190
512,1230160502992190
914,1230160502992190
818,1230160502992190
773,1230160502992190
613,1230160502992190
853,1230160502992190
808,1230160502992190
724,1230160502992190
648,1230160502992190
937,1230160502992190
802,1230160502992190
761,1230160502992190
722,1230160502992190
976,1230160502992190
929,1230160502992190
882,1230160502992190
968,1230160502992190

In [ ]:
assert col['i'][5] == x

**Exercice [033].** Un entier $c$ est **bicarré** si et seulement s'il peut s'écrire sous la forme $a^2+b^2$ avec $a$ et $b$ entiers.

| Exemple | Forme cherchée | Bicarré |
|---:|:--:|:--:|
| $17$ | $$1^2+4^2$$ | oui |
| $15$ | aucune | non |

_Tâche._ Listez par ordre croissant les entiers bicarrés inférieurs ou égaux à 1000.

_Contrainte._ Faites un produit cartésien de deux tables seulement.

In [ ]:
x = 8 # le 6e terme de cette suite
# Javascript: result[5]?.['i'] ?? 7_531_148

In [ ]:
%%sql
-- On fait deux « boucles », l'une sur $a$, l'autre sur $b$.
-- Plutôt que de « parcourir » tous les $c$ possibles, et éliminer ceux qui ne valent pas $a^2 + b^2$,
-- on calcule directement $c = a^2 + b^2$, et on vérifie que cette somme est bien dans la table donnée
-- (pour plus de généralité, on aurait pu écrire `A.i * A.i + B.i * B.i IN (SELECT i FROM ints)`).
-- La deuxième condition du `ON` évite les doublons par symétrie (p. ex., (3, 4) et (4, 3)).
SELECT DISTINCT A.i * A.i + B.i * B.i AS i
              , salt_033({{x}} + sum(nn(A.hash) + nn(B.hash)) OVER ()) AS token
FROM ints A
JOIN ints B ON A.i * A.i + B.i * B.i <= 1000
AND A.i <= B.i
ORDER BY 1

331 rows affected.

i,token
0,298774613720463
1,298774613720463
2,298774613720463
4,298774613720463
5,298774613720463
8,298774613720463
9,298774613720463
10,298774613720463
13,298774613720463
16,298774613720463
17,298774613720463
18,298774613720463
20,298774613720463
25,298774613720463
26,298774613720463
29,298774613720463
32,298774613720463
34,298774613720463
36,298774613720463
37,298774613720463
40,298774613720463
41,298774613720463
45,298774613720463
49,298774613720463
50,298774613720463
52,298774613720463
53,298774613720463
58,298774613720463
61,298774613720463
64,298774613720463
65,298774613720463
68,298774613720463
72,298774613720463
73,298774613720463
74,298774613720463
80,298774613720463
81,298774613720463
82,298774613720463
85,298774613720463
89,298774613720463
90,298774613720463
97,298774613720463
98,298774613720463
100,298774613720463
101,298774613720463
104,298774613720463
106,298774613720463
109,298774613720463
113,298774613720463
116,298774613720463
117,298774613720463
121,298774613720463
122,298774613720463
125,298774613720463
128,298774613720463
130,298774613720463
136,298774613720463
137,298774613720463
144,298774613720463
145,298774613720463
146,298774613720463
148,298774613720463
149,298774613720463
153,298774613720463
157,298774613720463
160,298774613720463
162,298774613720463
164,298774613720463
169,298774613720463
170,298774613720463
173,298774613720463
178,298774613720463
180,298774613720463
181,298774613720463
185,298774613720463
193,298774613720463
194,298774613720463
196,298774613720463
197,298774613720463
200,298774613720463
202,298774613720463
205,298774613720463
208,298774613720463
212,298774613720463
218,298774613720463
221,298774613720463
225,298774613720463
226,298774613720463
229,298774613720463
232,298774613720463
233,298774613720463
234,298774613720463
241,298774613720463
242,298774613720463
244,298774613720463
245,298774613720463
250,298774613720463
256,298774613720463
257,298774613720463
260,298774613720463
261,298774613720463
265,298774613720463
269,298774613720463
272,298774613720463
274,298774613720463
277,298774613720463
281,298774613720463
288,298774613720463
289,298774613720463
290,298774613720463
292,298774613720463
293,298774613720463
296,298774613720463
298,298774613720463
305,298774613720463
306,298774613720463
313,298774613720463
314,298774613720463
317,298774613720463
320,298774613720463
324,298774613720463
325,298774613720463
328,298774613720463
333,298774613720463
337,298774613720463
338,298774613720463
340,298774613720463
346,298774613720463
349,298774613720463
353,298774613720463
356,298774613720463
360,298774613720463
361,298774613720463
362,298774613720463
365,298774613720463
369,298774613720463
370,298774613720463
373,298774613720463
377,298774613720463
386,298774613720463
388,298774613720463
389,298774613720463
392,298774613720463
394,298774613720463
397,298774613720463
400,298774613720463
401,298774613720463
404,298774613720463
405,298774613720463
409,298774613720463
410,298774613720463
416,298774613720463
421,298774613720463
424,298774613720463
425,298774613720463
433,298774613720463
436,298774613720463
441,298774613720463
442,298774613720463
445,298774613720463
449,298774613720463
450,298774613720463
452,298774613720463
457,298774613720463
458,298774613720463
461,298774613720463
464,298774613720463
466,298774613720463
468,298774613720463
477,298774613720463
481,298774613720463
482,298774613720463
484,298774613720463
485,298774613720463
488,298774613720463
490,298774613720463
493,298774613720463
500,298774613720463
505,298774613720463
509,298774613720463
512,298774613720463
514,298774613720463
520,298774613720463
521,298774613720463
522,298774613720463
529,298774613720463
530,298774613720463
533,298774613720463
538,298774613720463
541,298774613720463
544,298774613720463
545,298774613720463
548,298774613720463
549,298774613720463
554,298774613720463
557,298774613720463
562,298774613720463
565,298774613720463
569,298774613720463
576,298774613720463
577,298774613720463
578,298774613720463
580,298774613720463
584,298774613720463
585,298774613720463
586,298774613720463
592,298774613720463
593,298774613720463
596,298774613720463
601,298774613720463
605,298774613720463
610,298774613720463
612,298774613720463
613,298774613720463
617,298774613720463
625,298774613720463
626,298774613720463
628,298774613720463
629,298774613720463
634,298774613720463
637,298774613720463
640,298774613720463
641,298774613720463
648,298774613720463
650,298774613720463
653,298774613720463
656,298774613720463
657,298774613720463
661,298774613720463
666,298774613720463
673,298774613720463
674,298774613720463
676,298774613720463
677,298774613720463
680,298774613720463
685,298774613720463
689,298774613720463
692,298774613720463
697,298774613720463
698,298774613720463
701,298774613720463
706,298774613720463
709,298774613720463
712,298774613720463
720,298774613720463
722,298774613720463
724,298774613720463
725,298774613720463
729,298774613720463
730,298774613720463
733,298774613720463
738,298774613720463
740,298774613720463
745,298774613720463
746,298774613720463
754,298774613720463
757,298774613720463
761,298774613720463
765,298774613720463
769,298774613720463
772,298774613720463
773,298774613720463
776,298774613720463
778,298774613720463
784,298774613720463
785,298774613720463
788,298774613720463
793,298774613720463
794,298774613720463
797,298774613720463
800,298774613720463
801,298774613720463
802,298774613720463
808,298774613720463
809,298774613720463
810,298774613720463
818,298774613720463
820,298774613720463
821,298774613720463
829,298774613720463
832,298774613720463
833,298774613720463
841,298774613720463
842,298774613720463
845,298774613720463
848,298774613720463
850,298774613720463
853,298774613720463
857,298774613720463
865,298774613720463
866,298774613720463
872,298774613720463
873,298774613720463
877,298774613720463
881,298774613720463
882,298774613720463
884,298774613720463
890,298774613720463
898,298774613720463
900,298774613720463
901,298774613720463
904,298774613720463
905,298774613720463
909,298774613720463
914,298774613720463
916,298774613720463
922,298774613720463
925,298774613720463
928,298774613720463
929,298774613720463
932,298774613720463
936,298774613720463
937,298774613720463
941,298774613720463
949,298774613720463
953,298774613720463
954,298774613720463
961,298774613720463
962,298774613720463
964,298774613720463
965,298774613720463
968,298774613720463
970,298774613720463
976,298774613720463
977,298774613720463
980,298774613720463
981,298774613720463
985,298774613720463
986,298774613720463
997,298774613720463
1000,298774613720463

In [ ]:
assert col['i'][5] == x

### Nombres premiers

**Exercice [081].** Un entier est **premier** si et seulement s'il a exactement deux diviseurs entiers (1 et lui-même).

| Exemple | Diviseurs | Propriété | Premier |
|---:|:--:|:--:|:--:|
| $13$ | $${1, 13}$$ | exactement deux diviseurs | oui |
| $12$ | $${1, 2, 3, 4, 6, 12}$$ | plus de deux diviseurs | non |
| $1$ | $${1}$$ | moins de deux diviseurs | non |

_Tâche._ Listez par ordre croissant les nombres premiers inférieurs ou égaux à 1000.

_Contrainte._ N'utilisez pas de regroupement.

In [ ]:
%%sql
SELECT i
     , salt_081(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE NOT EXISTS
        (SELECT 1
         FROM ints B
         WHERE B.i BETWEEN 2 AND A.i - 1
             AND A.i % B.i = 0 )
    AND i > 1

168 rows affected.

i,token
2,253352561534995
3,253352561534995
5,253352561534995
7,253352561534995
11,253352561534995
13,253352561534995
17,253352561534995
19,253352561534995
23,253352561534995
29,253352561534995
31,253352561534995
37,253352561534995
41,253352561534995
43,253352561534995
47,253352561534995
53,253352561534995
59,253352561534995
61,253352561534995
67,253352561534995
71,253352561534995
73,253352561534995
79,253352561534995
83,253352561534995
89,253352561534995
97,253352561534995
101,253352561534995
103,253352561534995
107,253352561534995
109,253352561534995
113,253352561534995
127,253352561534995
131,253352561534995
137,253352561534995
139,253352561534995
149,253352561534995
151,253352561534995
157,253352561534995
163,253352561534995
167,253352561534995
173,253352561534995
179,253352561534995
181,253352561534995
191,253352561534995
193,253352561534995
197,253352561534995
199,253352561534995
211,253352561534995
223,253352561534995
227,253352561534995
229,253352561534995
233,253352561534995
239,253352561534995
241,253352561534995
251,253352561534995
257,253352561534995
263,253352561534995
269,253352561534995
271,253352561534995
277,253352561534995
281,253352561534995
283,253352561534995
293,253352561534995
307,253352561534995
311,253352561534995
313,253352561534995
317,253352561534995
331,253352561534995
337,253352561534995
347,253352561534995
349,253352561534995
353,253352561534995
359,253352561534995
367,253352561534995
373,253352561534995
379,253352561534995
383,253352561534995
389,253352561534995
397,253352561534995
401,253352561534995
409,253352561534995
419,253352561534995
421,253352561534995
431,253352561534995
433,253352561534995
439,253352561534995
443,253352561534995
449,253352561534995
457,253352561534995
461,253352561534995
463,253352561534995
467,253352561534995
479,253352561534995
487,253352561534995
491,253352561534995
499,253352561534995
503,253352561534995
509,253352561534995
521,253352561534995
523,253352561534995
541,253352561534995
547,253352561534995
557,253352561534995
563,253352561534995
569,253352561534995
571,253352561534995
577,253352561534995
587,253352561534995
593,253352561534995
599,253352561534995
601,253352561534995
607,253352561534995
613,253352561534995
617,253352561534995
619,253352561534995
631,253352561534995
641,253352561534995
643,253352561534995
647,253352561534995
653,253352561534995
659,253352561534995
661,253352561534995
673,253352561534995
677,253352561534995
683,253352561534995
691,253352561534995
701,253352561534995
709,253352561534995
719,253352561534995
727,253352561534995
733,253352561534995
739,253352561534995
743,253352561534995
751,253352561534995
757,253352561534995
761,253352561534995
769,253352561534995
773,253352561534995
787,253352561534995
797,253352561534995
809,253352561534995
811,253352561534995
821,253352561534995
823,253352561534995
827,253352561534995
829,253352561534995
839,253352561534995
853,253352561534995
857,253352561534995
859,253352561534995
863,253352561534995
877,253352561534995
881,253352561534995
883,253352561534995
887,253352561534995
907,253352561534995
911,253352561534995
919,253352561534995
929,253352561534995
937,253352561534995
941,253352561534995
947,253352561534995
953,253352561534995
967,253352561534995
971,253352561534995
977,253352561534995
983,253352561534995
991,253352561534995
997,253352561534995

In [ ]:
%%sql
-- Variante. Avec une requête imbriquée dans le WHERE.
SELECT A.i
     , salt_081(sum(nn(A.hash)) OVER ()) AS token
FROM ints A
WHERE A.i > 1
    AND A.i NOT IN
        (SELECT A2.i
         FROM ints A2
         JOIN ints B ON B.i BETWEEN 2 AND sqrt(A2.i)
         AND A2.i % B.i = 0)

168 rows affected.

i,token
2,253352561534995
3,253352561534995
5,253352561534995
7,253352561534995
11,253352561534995
13,253352561534995
17,253352561534995
19,253352561534995
23,253352561534995
29,253352561534995
31,253352561534995
37,253352561534995
41,253352561534995
43,253352561534995
47,253352561534995
53,253352561534995
59,253352561534995
61,253352561534995
67,253352561534995
71,253352561534995
73,253352561534995
79,253352561534995
83,253352561534995
89,253352561534995
97,253352561534995
101,253352561534995
103,253352561534995
107,253352561534995
109,253352561534995
113,253352561534995
127,253352561534995
131,253352561534995
137,253352561534995
139,253352561534995
149,253352561534995
151,253352561534995
157,253352561534995
163,253352561534995
167,253352561534995
173,253352561534995
179,253352561534995
181,253352561534995
191,253352561534995
193,253352561534995
197,253352561534995
199,253352561534995
211,253352561534995
223,253352561534995
227,253352561534995
229,253352561534995
233,253352561534995
239,253352561534995
241,253352561534995
251,253352561534995
257,253352561534995
263,253352561534995
269,253352561534995
271,253352561534995
277,253352561534995
281,253352561534995
283,253352561534995
293,253352561534995
307,253352561534995
311,253352561534995
313,253352561534995
317,253352561534995
331,253352561534995
337,253352561534995
347,253352561534995
349,253352561534995
353,253352561534995
359,253352561534995
367,253352561534995
373,253352561534995
379,253352561534995
383,253352561534995
389,253352561534995
397,253352561534995
401,253352561534995
409,253352561534995
419,253352561534995
421,253352561534995
431,253352561534995
433,253352561534995
439,253352561534995
443,253352561534995
449,253352561534995
457,253352561534995
461,253352561534995
463,253352561534995
467,253352561534995
479,253352561534995
487,253352561534995
491,253352561534995
499,253352561534995
503,253352561534995
509,253352561534995
521,253352561534995
523,253352561534995
541,253352561534995
547,253352561534995
557,253352561534995
563,253352561534995
569,253352561534995
571,253352561534995
577,253352561534995
587,253352561534995
593,253352561534995
599,253352561534995
601,253352561534995
607,253352561534995
613,253352561534995
617,253352561534995
619,253352561534995
631,253352561534995
641,253352561534995
643,253352561534995
647,253352561534995
653,253352561534995
659,253352561534995
661,253352561534995
673,253352561534995
677,253352561534995
683,253352561534995
691,253352561534995
701,253352561534995
709,253352561534995
719,253352561534995
727,253352561534995
733,253352561534995
739,253352561534995
743,253352561534995
751,253352561534995
757,253352561534995
761,253352561534995
769,253352561534995
773,253352561534995
787,253352561534995
797,253352561534995
809,253352561534995
811,253352561534995
821,253352561534995
823,253352561534995
827,253352561534995
829,253352561534995
839,253352561534995
853,253352561534995
857,253352561534995
859,253352561534995
863,253352561534995
877,253352561534995
881,253352561534995
883,253352561534995
887,253352561534995
907,253352561534995
911,253352561534995
919,253352561534995
929,253352561534995
937,253352561534995
941,253352561534995
947,253352561534995
953,253352561534995
967,253352561534995
971,253352561534995
977,253352561534995
983,253352561534995
991,253352561534995
997,253352561534995

**Exercice [082].** Un entier est **premier** si et seulement s'il a exactement deux diviseurs entiers (1 et lui-même).

| Exemple | Diviseurs | Propriété | Premier |
|---:|:--:|:--:|:--:|
| $13$ | $${1, 13}$$ | exactement deux diviseurs | oui |
| $12$ | $${1, 2, 3, 4, 6, 12}$$ | plus de deux diviseurs | non |
| $1$ | $${1}$$ | moins de deux diviseurs | non |

_Tâche._ Listez par ordre croissant les nombres premiers inférieurs ou égaux à 1000.

_Contrainte._ Utilisez un regroupement.

In [ ]:
%%sql
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
WHERE A.i > 1
GROUP BY A.i
HAVING count(B.i) = 0

168 rows affected.

i,token
2,156364735562291
3,156364735562291
5,156364735562291
7,156364735562291
11,156364735562291
13,156364735562291
17,156364735562291
19,156364735562291
23,156364735562291
29,156364735562291
31,156364735562291
37,156364735562291
41,156364735562291
43,156364735562291
47,156364735562291
53,156364735562291
59,156364735562291
61,156364735562291
67,156364735562291
71,156364735562291
73,156364735562291
79,156364735562291
83,156364735562291
89,156364735562291
97,156364735562291
101,156364735562291
103,156364735562291
107,156364735562291
109,156364735562291
113,156364735562291
127,156364735562291
131,156364735562291
137,156364735562291
139,156364735562291
149,156364735562291
151,156364735562291
157,156364735562291
163,156364735562291
167,156364735562291
173,156364735562291
179,156364735562291
181,156364735562291
191,156364735562291
193,156364735562291
197,156364735562291
199,156364735562291
211,156364735562291
223,156364735562291
227,156364735562291
229,156364735562291
233,156364735562291
239,156364735562291
241,156364735562291
251,156364735562291
257,156364735562291
263,156364735562291
269,156364735562291
271,156364735562291
277,156364735562291
281,156364735562291
283,156364735562291
293,156364735562291
307,156364735562291
311,156364735562291
313,156364735562291
317,156364735562291
331,156364735562291
337,156364735562291
347,156364735562291
349,156364735562291
353,156364735562291
359,156364735562291
367,156364735562291
373,156364735562291
379,156364735562291
383,156364735562291
389,156364735562291
397,156364735562291
401,156364735562291
409,156364735562291
419,156364735562291
421,156364735562291
431,156364735562291
433,156364735562291
439,156364735562291
443,156364735562291
449,156364735562291
457,156364735562291
461,156364735562291
463,156364735562291
467,156364735562291
479,156364735562291
487,156364735562291
491,156364735562291
499,156364735562291
503,156364735562291
509,156364735562291
521,156364735562291
523,156364735562291
541,156364735562291
547,156364735562291
557,156364735562291
563,156364735562291
569,156364735562291
571,156364735562291
577,156364735562291
587,156364735562291
593,156364735562291
599,156364735562291
601,156364735562291
607,156364735562291
613,156364735562291
617,156364735562291
619,156364735562291
631,156364735562291
641,156364735562291
643,156364735562291
647,156364735562291
653,156364735562291
659,156364735562291
661,156364735562291
673,156364735562291
677,156364735562291
683,156364735562291
691,156364735562291
701,156364735562291
709,156364735562291
719,156364735562291
727,156364735562291
733,156364735562291
739,156364735562291
743,156364735562291
751,156364735562291
757,156364735562291
761,156364735562291
769,156364735562291
773,156364735562291
787,156364735562291
797,156364735562291
809,156364735562291
811,156364735562291
821,156364735562291
823,156364735562291
827,156364735562291
829,156364735562291
839,156364735562291
853,156364735562291
857,156364735562291
859,156364735562291
863,156364735562291
877,156364735562291
881,156364735562291
883,156364735562291
887,156364735562291
907,156364735562291
911,156364735562291
919,156364735562291
929,156364735562291
937,156364735562291
941,156364735562291
947,156364735562291
953,156364735562291
967,156364735562291
971,156364735562291
977,156364735562291
983,156364735562291
991,156364735562291
997,156364735562291

In [ ]:
%%sql
-- Indication. 0 et 1 ne sont pas premiers.
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
GROUP BY A.i
HAVING count(B.i) = 0

170 rows affected.

i,token
0,156596690231090
1,156596690231090
2,156596690231090
3,156596690231090
5,156596690231090
7,156596690231090
11,156596690231090
13,156596690231090
17,156596690231090
19,156596690231090
23,156596690231090
29,156596690231090
31,156596690231090
37,156596690231090
41,156596690231090
43,156596690231090
47,156596690231090
53,156596690231090
59,156596690231090
61,156596690231090
67,156596690231090
71,156596690231090
73,156596690231090
79,156596690231090
83,156596690231090
89,156596690231090
97,156596690231090
101,156596690231090
103,156596690231090
107,156596690231090
109,156596690231090
113,156596690231090
127,156596690231090
131,156596690231090
137,156596690231090
139,156596690231090
149,156596690231090
151,156596690231090
157,156596690231090
163,156596690231090
167,156596690231090
173,156596690231090
179,156596690231090
181,156596690231090
191,156596690231090
193,156596690231090
197,156596690231090
199,156596690231090
211,156596690231090
223,156596690231090
227,156596690231090
229,156596690231090
233,156596690231090
239,156596690231090
241,156596690231090
251,156596690231090
257,156596690231090
263,156596690231090
269,156596690231090
271,156596690231090
277,156596690231090
281,156596690231090
283,156596690231090
293,156596690231090
307,156596690231090
311,156596690231090
313,156596690231090
317,156596690231090
331,156596690231090
337,156596690231090
347,156596690231090
349,156596690231090
353,156596690231090
359,156596690231090
367,156596690231090
373,156596690231090
379,156596690231090
383,156596690231090
389,156596690231090
397,156596690231090
401,156596690231090
409,156596690231090
419,156596690231090
421,156596690231090
431,156596690231090
433,156596690231090
439,156596690231090
443,156596690231090
449,156596690231090
457,156596690231090
461,156596690231090
463,156596690231090
467,156596690231090
479,156596690231090
487,156596690231090
491,156596690231090
499,156596690231090
503,156596690231090
509,156596690231090
521,156596690231090
523,156596690231090
541,156596690231090
547,156596690231090
557,156596690231090
563,156596690231090
569,156596690231090
571,156596690231090
577,156596690231090
587,156596690231090
593,156596690231090
599,156596690231090
601,156596690231090
607,156596690231090
613,156596690231090
617,156596690231090
619,156596690231090
631,156596690231090
641,156596690231090
643,156596690231090
647,156596690231090
653,156596690231090
659,156596690231090
661,156596690231090
673,156596690231090
677,156596690231090
683,156596690231090
691,156596690231090
701,156596690231090
709,156596690231090
719,156596690231090
727,156596690231090
733,156596690231090
739,156596690231090
743,156596690231090
751,156596690231090
757,156596690231090
761,156596690231090
769,156596690231090
773,156596690231090
787,156596690231090
797,156596690231090
809,156596690231090
811,156596690231090
821,156596690231090
823,156596690231090
827,156596690231090
829,156596690231090
839,156596690231090
853,156596690231090
857,156596690231090
859,156596690231090
863,156596690231090
877,156596690231090
881,156596690231090
883,156596690231090
887,156596690231090
907,156596690231090
911,156596690231090
919,156596690231090
929,156596690231090
937,156596690231090
941,156596690231090
947,156596690231090
953,156596690231090
967,156596690231090
971,156596690231090
977,156596690231090
983,156596690231090
991,156596690231090
997,156596690231090

In [ ]:
%%sql
-- Indication. 1 n'est pas premier.
SELECT A.i
     , salt_082(bit_xor(sum(nn(A.hash))) OVER ()) AS token
FROM ints A
LEFT JOIN ints B ON B.i BETWEEN 2 AND sqrt(A.i)
AND A.i % B.i = 0
WHERE A.i != 0
GROUP BY A.i
HAVING count(B.i) = 0

169 rows affected.

i,token
1,156189361184507
2,156189361184507
3,156189361184507
5,156189361184507
7,156189361184507
11,156189361184507
13,156189361184507
17,156189361184507
19,156189361184507
23,156189361184507
29,156189361184507
31,156189361184507
37,156189361184507
41,156189361184507
43,156189361184507
47,156189361184507
53,156189361184507
59,156189361184507
61,156189361184507
67,156189361184507
71,156189361184507
73,156189361184507
79,156189361184507
83,156189361184507
89,156189361184507
97,156189361184507
101,156189361184507
103,156189361184507
107,156189361184507
109,156189361184507
113,156189361184507
127,156189361184507
131,156189361184507
137,156189361184507
139,156189361184507
149,156189361184507
151,156189361184507
157,156189361184507
163,156189361184507
167,156189361184507
173,156189361184507
179,156189361184507
181,156189361184507
191,156189361184507
193,156189361184507
197,156189361184507
199,156189361184507
211,156189361184507
223,156189361184507
227,156189361184507
229,156189361184507
233,156189361184507
239,156189361184507
241,156189361184507
251,156189361184507
257,156189361184507
263,156189361184507
269,156189361184507
271,156189361184507
277,156189361184507
281,156189361184507
283,156189361184507
293,156189361184507
307,156189361184507
311,156189361184507
313,156189361184507
317,156189361184507
331,156189361184507
337,156189361184507
347,156189361184507
349,156189361184507
353,156189361184507
359,156189361184507
367,156189361184507
373,156189361184507
379,156189361184507
383,156189361184507
389,156189361184507
397,156189361184507
401,156189361184507
409,156189361184507
419,156189361184507
421,156189361184507
431,156189361184507
433,156189361184507
439,156189361184507
443,156189361184507
449,156189361184507
457,156189361184507
461,156189361184507
463,156189361184507
467,156189361184507
479,156189361184507
487,156189361184507
491,156189361184507
499,156189361184507
503,156189361184507
509,156189361184507
521,156189361184507
523,156189361184507
541,156189361184507
547,156189361184507
557,156189361184507
563,156189361184507
569,156189361184507
571,156189361184507
577,156189361184507
587,156189361184507
593,156189361184507
599,156189361184507
601,156189361184507
607,156189361184507
613,156189361184507
617,156189361184507
619,156189361184507
631,156189361184507
641,156189361184507
643,156189361184507
647,156189361184507
653,156189361184507
659,156189361184507
661,156189361184507
673,156189361184507
677,156189361184507
683,156189361184507
691,156189361184507
701,156189361184507
709,156189361184507
719,156189361184507
727,156189361184507
733,156189361184507
739,156189361184507
743,156189361184507
751,156189361184507
757,156189361184507
761,156189361184507
769,156189361184507
773,156189361184507
787,156189361184507
797,156189361184507
809,156189361184507
811,156189361184507
821,156189361184507
823,156189361184507
827,156189361184507
829,156189361184507
839,156189361184507
853,156189361184507
857,156189361184507
859,156189361184507
863,156189361184507
877,156189361184507
881,156189361184507
883,156189361184507
887,156189361184507
907,156189361184507
911,156189361184507
919,156189361184507
929,156189361184507
937,156189361184507
941,156189361184507
947,156189361184507
953,156189361184507
967,156189361184507
971,156189361184507
977,156189361184507
983,156189361184507
991,156189361184507
997,156189361184507

In [ ]:
raise EOFError

EOFError:

In [ ]:
from markdown2 import Markdown
md = Markdown(extras=["fenced-code-blocks", "latex", "tables"])

In [ ]:
text = r"""
| Exemple | Diviseurs stricts | Propriété | Conclusion |
|---:|:--:|:--:|:--:|
| $12$ | $${1, 2, 3, 4, 6}$$ | $$12 < 1+2+3+4+6 = 16$$ | abondant |
| $16$ | $${1, 2, 4, 8}$$ | $$16 \geq 1+2+4+8 = 15$$ | non abondant |
"""

In [ ]:
md.convert(text)

'<table>\n<thead>\n<tr>\n  <th style="text-align:right;">Exemple</th>\n  <th style="text-align:center;">Diviseurs stricts</th>\n  <th style="text-align:center;">Propriété</th>\n  <th style="text-align:center;">Conclusion</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n  <td style="text-align:right;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>12</mn></mrow></math></td>\n  <td style="text-align:center;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mrow><mn>1</mn><mo>&#x0002C;</mo><mn>2</mn><mo>&#x0002C;</mo><mn>3</mn><mo>&#x0002C;</mo><mn>4</mn><mo>&#x0002C;</mo><mn>6</mn></mrow></mrow></math></td>\n  <td style="text-align:center;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mn>12</mn><mo>&#x0003C;</mo><mn>1</mn><mo>&#x0002B;</mo><mn>2</mn><mo>&#x0002B;</mo><mn>3</mn><mo>&#x0002B;</mo><mn>4</mn><mo>&#x0002B;</mo><mn>6</mn><mo>&#x0003D;</mo><mn>16</mn></mrow></math></td>\n  <td style="text-align:center;">abondant</td>\n</tr>\n<tr>\n  <td style="text-align:right;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>16</mn></mrow></math></td>\n  <td style="text-align:center;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mrow><mn>1</mn><mo>&#x0002C;</mo><mn>2</mn><mo>&#x0002C;</mo><mn>4</mn><mo>&#x0002C;</mo><mn>8</mn></mrow></mrow></math></td>\n  <td style="text-align:center;"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mn>16</mn><mo>&#x02265;</mo><mn>1</mn><mo>&#x0002B;</mo><mn>2</mn><mo>&#x0002B;</mo><mn>4</mn><mo>&#x0002B;</mo><mn>8</mn><mo>&#x0003D;</mo><mn>15</mn></mrow></math></td>\n  <td style="text-align:center;">non abondant</td>\n</tr>\n</tbody>\n</table>\n'

In [ ]:
import math

def is_perfect_square(n):
    root = int(math.isqrt(n))
    return root * root == n

def find_best_approx(limit=100000):
    best_n = None
    best_diff = float('inf')

    for n in range(1, limit + 1):
        if is_perfect_square(n):
            continue  # ignorer les carrés parfaits

        sqrt_n = math.sqrt(n)
        nearest_int = round(sqrt_n)
        diff = abs(sqrt_n - nearest_int)

        if diff < best_diff:
            best_diff = diff
            best_n = n

    return best_n, math.sqrt(best_n), best_diff

n, sqrt_n, diff = find_best_approx()
print(f"L'entier recherché est {n}")
print(f"Sa racine carrée est environ {sqrt_n:.10f}")
print(f"Écart à l'entier le plus proche : {diff:.10f}")

L'entier recherché est 99857
Sa racine carrée est environ 316.0015822745
Écart à l'entier le plus proche : 0.0015822745